부산대 BE_박수빈 3주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #109
Opened 2024-07-09 07:00 UTC by kuma4188

기존의 jdbctemplate 코드를 수정해서 jpa 코드로 바꿨습니다.
기존의 data.sql 에서 주입하던 데이터를 jpa 방식으로 주입하고 싶어서
DatabaseLoarder 이라는 파일에서 CommandLineRunner을 이용했습니다.

Q )
이런식으로 sql을 사용하지 않고 데이터를 미리 넣어주고 싶으면 
CommandLineRunner을 이용해서 하는 방식이 맞나요?
저번에 SecurityConfig에서 admin 이라는 계정을 CommandLineRunner을 이용해서 넣은적 있었는데 ,
그떄 멘토니꼐서 이렇게 하드코딩보단 yml 넣는걸 추천한다 라고 하셨던 말씀이 떠올랐습니다.
그럼 혹시 이번에도 미리 상품정보를 넣을떄도 yml을 넣어서 하는것을 추천하시나요?

2024-07-09 10:38 UTC, yoo-jaein requested changes
step1 고생하셨습니다!
질문 주신 답변은 코멘트로 달았으니 확인 부탁드립니다 :)

2024-07-09 10:38 UTC, deactivated-user commented on src/main/java/gift/config/SecurityConfig.java
> +public class SecurityConfig {
프로젝트 내에 ```SecurityConfig```가 2개가 있어요! 👀

2024-07-09 10:38 UTC, yoo-jaein commented on src/test/java/gift/test/ProductRepositoryTest.java
> +
현재 save 기능만 테스트하고 있는데 더 다양한 테스트를 추가해볼까요? (예: findById, findAll, delete 등)

2024-07-09 10:38 UTC, yoo-jaein commented on src/main/java/gift/repository/UserRepository.java
> +	Optional<SiteUser> findByusername(String username);
```findByUsername``` 이 올바른 카멜케이스 표기법입니다!

2024-07-09 10:38 UTC, yoo-jaein commented on src/test/java/gift/test/UserRepositoryTest.java
> +
save 테스트에도 다양한 케이스를 만들어 볼 수 있을 것 같아요~
이메일 유니크 제약조건에 대한 테스트, 이름 길이 제한에 대한 테스트 등

2024-07-09 10:38 UTC, yoo-jaein commented on src/test/java/gift/test/ProductRepositoryTest.java
> +        assertThat(savedProduct.getName()).isEqualTo("product1");
repository 테스트에서는 일반적으로 모든 필드를 검증합니다

2024-07-09 10:38 UTC, yoo-jaein commented on src/test/java/gift/test/WishlistRepositoryTest.java
> +
```findByUsername```에 대한 테스트가 누락되었어요!

2024-07-09 10:38 UTC, yoo-jaein commented on src/test/java/gift/test/ProductRepositoryTest.java
> +    }
저는 테스트 코드를 짤 때 Given-When-Then 구조로 작성합니다.
```java
@Test
void updateProductPrice() {
    // Given
    Product product = new Product("Test Product", 1000, "test.jpg");
    Product savedProduct = productRepository.save(product);
    Long productId = savedProduct.getId();

    // When
    savedProduct.setPrice(1500);
    productRepository.save(savedProduct);

    // Then
    Product updatedProduct = productRepository.findById(productId).orElseThrow();
    assertThat(updatedProduct.getPrice()).isEqualTo(1500);
}
```
이 구조는 테스트를 3단계로 나누기 때문에 테스트 코드의 가독성과 이해도를 높일 수 있습니다.
아직 테스트 코드 작성이 익숙하지 않으실 것 같은데, 직접 // Given ~ When ~ Then 주석을 적고 작성하시면 도움이 될 것 같아요.

2024-07-09 10:38 UTC, yoo-jaein commented on src/test/java/gift/test/UserRepositoryTest.java
> +    @Test
각 테스트 메서드에 ```@DisplayName```을 추가하면 테스트 이름과 목적을 명확히 표현할 수 있습니다.

2024-07-09 10:38 UTC, yoo-jaein commented on src/main/java/gift/config/DatabaseLoader.java
> +
초기 데이터를 넣는 방식에는 여러 방법이 있습니다.

1. CommandLineRunner 사용
장점: Java 코드로 데이터 삽입 가능
단점: 애플리케이션 코드에 데이터가 하드코딩되어 유지보수가 어려움

제가 Admin 계정을 yml에 넣는걸 추천한다고 말씀드렸던 부분은

```관리자의 계정 정보는 보호되어야 하는 중요한 정보기 때문에, 이메일 비밀번호를 하드코딩하는 것보다 yml에 넣어서 불러오게 좋을 것 같다.```

는 의미였습니다! 


2. data.sql 사용
장점: 데이터베이스 작업을 sql 파일로 명확히 분리
단점: 엔티티와 sql 스크립트 간 불일치가 발생할 수 있음

상품 정보는 yml로 분리할 필요는 없을 것 같구요.
이미 프로젝트 resources 내에 data.sql 파일이 존재하기 때문에, DatabaseLoader만 사용하거나 / data.sql만 사용하거나.. 를 선택해주시면 좋을 것 같습니다! (두 방식을 동시에 쓰는건 유지보수에 좋지 않습니다 🥲)

2024-07-09 18:42 UTC, kuma4188 commented
수정사항)
1. 각각의 테스트 코드 추가
2. sql 파일 전부 삭제
3. 중복 파일 삭제
4. 테스트 코드 작성시 given / when / then 작성

2024-07-10 04:52 UTC, yoo-jaein approved these changes
리뷰 반영된 것 확인했습니다 :)
step1 머지하겠습니다.
다음 단계 진행하실 때 추가로 남긴 코멘트 참고해주세요!

2024-07-10 04:52 UTC, yoo-jaein commented on src/test/java/gift/test/ProductRepositoryTest.java
> +    @Order(4)
단위 테스트에서 각 테스트는 실행 순서와 관계 없이 성공해야 합니다.
여기서 사용된 ```@Order```는 단위 테스트에서는 사용하지 않고, 복잡한 통합 테스트에서 시나리오를 순차적으로 테스트해야 할 때 씁니다.

2024-07-10 04:52 UTC, yoo-jaein commented on src/test/java/gift/test/ProductRepositoryTest.java
> +    private void validateProductName(String name) {
ProductRepositoryTest는 Repository 계층을 테스트하는 클래스기 때문에 데이터베이스에 명시된 제약 조건을 테스트하면 됩니다 :)
```java
// Product
    @Column(nullable = false , length = 20)
    private String name;
    @Column(nullable = false)
    private int price;
    @Column(name = "image_url", nullable = false)
    private String imageUrl;
```
여기서 name이 20 글자를 초과했을 때, imageUrl이 null일 때 등을 테스트 해야 합니다.

패턴 매칭, "카카오" 글자 검사는 서비스 계층에서 이루어지는 조건이기 때문에 ProductServiceTest 에 있는 것이 적합합니다. 

(추가로 데이터베이스의 name 컬럼은 20자 제한인데 validateProductName에서 name은 15자 제한이군요..! 통일이 필요합니다)

2024-07-10 04:52 UTC, yoo-jaein commented on src/test/java/gift/test/UserRepositoryTest.java
> +    void setUp() {
setUp 👍👍

2024-07-10 04:52 UTC, yoo-jaein commented on src/test/java/gift/test/UserRepositoryTest.java
> +@ComponentScan(basePackages = {"gift"})
```@SpringBootTest```는 이미 전체 애플리케이션을 스캔하기 때문에 ```@ComponentScan```을 하지 않아도 됩니다!

2024-07-10 04:52 UTC, yoo-jaein commented on src/test/java/gift/test/WishlistRepositoryTest.java
> +        mockMvc.perform(post("/web/wishlist/update/" + item.getId())
Repository 테스트와 컨트롤러 테스트가 혼합되어 있는데 분리되어야 합니다!
WishlistRepositoryTest에서는 WishlistRepository를 이용해 위시리스트 아이템을 저장하고 조회해보는 테스트,
(컨트롤러 테스트를 새로 만든다면) WishlistControllerTest에는 mockMvc를 이용해 담긴 상품 수량 변경, 삭제하는 테스트가 있어야 합니다.

2024-07-10 04:52 UTC, yoo-jaein commented on src/test/java/gift/test/UserRepositoryTest.java
> +        // Given
Given When Then 👍

2024-07-10 04:53 UTC, merged