경북대 BE_배규민_3주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #119
Opened 2024-07-09 09:07 UTC by GyuminBae

* 1단계 PR입니다!

2024-07-09 13:18 UTC, lsm7179 requested changes
규민님 1단계 수고하셨습니다.😁
간단한 코멘트들 있으니 확인해주세요.
이해 안가시는 부분 있으면 편하게 DM주세요~

2024-07-09 13:18 UTC, lsm7179 commented on src/main/resources/application.properties
> +spring.jpa.show-sql=true
이미 아시겠지만 spring.jpa.hibernate.ddl-auto 설정할때는 각 환경별로 조심히 사용해야합니다.
https://colabear754.tistory.com/136

2024-07-09 13:18 UTC, lsm7179 commented on src/main/java/gift/product/infrastructure/persistence/ProductEntity.java
> +    }
jpa entity를 사용하므로 setter와 프로퍼티 접근 방하기 위해 생성자는 protected로 수정해주세요.
다른 엔티티도 같이 확인해주세요.

2024-07-09 13:18 UTC, lsm7179 commented on src/main/java/gift/product/infrastructure/persistence/ProductRepositoryImpl.java
> +                .orElse(null);
null값을 전달하지 않고 Optional로 감싸서 보내볼까요?
https://dev-coco.tistory.com/178

2024-07-09 13:18 UTC, lsm7179 commented on src/main/java/gift/product/infrastructure/persistence/ProductRepositoryImpl.java
> +        return (int) jpaProductRepository.count();
size는 long인데 int로 강제형변환한 이유가 있나요?

2024-07-09 13:18 UTC, lsm7179 commented on src/main/java/gift/product/infrastructure/persistence/ProductEntity.java
> +    private Integer price;
백틱을 붙인곳과 붙이지 않는 곳이 있는데 백틱을 붙인 이유가 있나요?

2024-07-09 13:18 UTC, lsm7179 commented on src/main/java/gift/user/infrastructure/persistence/UserAccountRepositoryImpl.java
> +    private final JpaUserAccountRepository jpaUserAccountRepository;
JpaUserAccountRepository를 상속받아서 사용할 수 있는데 포함관계로 만든 이유가 있나요?

2024-07-09 13:18 UTC, lsm7179 commented on src/main/java/gift/wishes/infrastructure/persistence/WishesRepositoryImpl.java
> +    }
repository계층이 아닌 service계층에서 작업할 일인거 같은데 어떻게 생각하시나요?

2024-07-09 13:18 UTC, lsm7179 commented on src/test/java/gift/product/ProductRepositoryTests.java
> +        ProductEntity product = new ProductEntity(0L, "test", 100, "test");
id값을 jpa에서 자동생성해주므로 id없는 생성자를 만들어 보세요~

2024-07-09 13:18 UTC, lsm7179 commented on src/test/java/gift/product/ProductRepositoryTests.java
> +        ProductEntity product = new ProductEntity(0L, "test", 100, "test");
isEqualTo 를 사용해서 검증테스트를 만들어보세요~

2024-07-09 14:30 UTC, GyuminBae commented on src/main/java/gift/product/infrastructure/persistence/ProductEntity.java
> +    }
반영했습니다!

2024-07-09 14:33 UTC, GyuminBae commented on src/main/java/gift/product/infrastructure/persistence/ProductEntity.java
> +    private Integer price;
앗 실수했습니다!

2024-07-09 14:34 UTC, GyuminBae commented on src/main/java/gift/user/infrastructure/persistence/UserAccountRepositoryImpl.java
> +    private final JpaUserAccountRepository jpaUserAccountRepository;
도메인 모델과 엔티티에 사용되는 필드가 1대1 매핑이 아닐 수 있기 때문에 변경에 유연하게 대응하기 위해서 저런 방식으로 사용하고 있습니다!

2024-07-09 14:35 UTC, GyuminBae commented on src/main/java/gift/wishes/infrastructure/persistence/WishesRepositoryImpl.java
> +    }
반영하였습니다!

2024-07-09 14:41 UTC, GyuminBae commented on src/main/java/gift/product/infrastructure/persistence/ProductRepositoryImpl.java
> +        return (int) jpaProductRepository.count();
앗 이 부분도 확인해서 long 반환하도록 반영해놨습니다!

2024-07-09 14:45 UTC, GyuminBae commented on src/main/java/gift/product/infrastructure/persistence/ProductRepositoryImpl.java
> +                .orElse(null);
반영했습니다!

2024-07-09 14:47 UTC, GyuminBae commented on src/main/java/gift/product/infrastructure/persistence/ProductEntity.java
> +    }
해당 부분은 테스트 레이어에서 오류가 나는 등의 문제가 발생하기도 하고, 애초에 프로퍼티가 private으로 되어있어서 getter를 통해서만 읽을 수 있는 객체라고 생각해서 protected로 변경해야하는 이유가 잘 이해되지 않습니다!

2024-07-09 14:47 UTC, GyuminBae commented on src/test/java/gift/product/ProductRepositoryTests.java
> +        ProductEntity product = new ProductEntity(0L, "test", 100, "test");
반영하였습니다!

2024-07-10 11:17 UTC, lsm7179 approved these changes
규민님 수고하셨습니다.👍
머지하겠습니다.
몇가지 코멘트 남겼는데 이해가 안가거나 궁금한게 있으면 언제든 DM주세요~
화이팅입니다.🔥

2024-07-10 11:17 UTC, lsm7179 commented on src/main/java/gift/product/infrastructure/persistence/ProductEntity.java
> +    }
음... 사용하는 곳의 입장에서 생각해볼까요?
ProductEntity를 기본생성자를 제공해주면 사용하는곳에서 무방비하게 사용가능해집니다. set을 다 지웠지만 접근제어자까지 막는다면 좋을거 같아요.
특히 다음 단계에서 연관관계맵핑을 작업하게 될때 하위 객체로 기본생성자로 생성못하게 막는것에도 도움되겠네요.
이펙티브 자바 접근제어는 최소화 하자 읽어보시면 좋을거 같네요.
https://jjingho.tistory.com/58

2024-07-10 11:17 UTC, lsm7179 commented on src/main/java/gift/product/infrastructure/persistence/ProductEntity.java
> +    private String name;
여기는 아직 백틱이 붙어 있습니다😅

2024-07-10 11:17 UTC, lsm7179 commented on src/main/java/gift/product/infrastructure/persistence/ProductRepositoryImpl.java
> +    }
get으로 꺼내지 말고 ProductEntity에서 아래처럼 해보세요.
어떤게 더 객체지향적일까요?
엔티티에서 도메인으로 변환하는 역할은 엔티티의 역할이며 get으로 꺼내며 작업하지 않아도 됩니다.
```
 public Product toProduct() {
        return new Product(
                id, name, price, imageUrl
        );
    }
```

2024-07-10 11:18 UTC, merged