부산대 BE_박혜연 3주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #127
Opened 2024-07-09 10:57 UTC by hyyyh0x

![image](https://github.com/kakao-tech-campus-2nd-step2/spring-gift-jpa/assets/141637975/f31a49bb-8afe-4c30-9d9e-956da6134c87)
추가를 할 때 중복 이름이 있으면 이런 페이지가 뜨고, 업데이트를 할 때는 
![Untitled](https://prod-files-secure.s3.us-west-2.amazonaws.com/3ef8dbd9-414c-4cf5-813d-32ecb943cc67/e17d71a6-c36a-48e4-a58e-901579520325/Untitled.png)
이렇게 뜨는데 똑같은 코드를 작성했는데 왜 다르게 뜨는건지 잘 모르겠습니다.

`@PostMapping("/add")
    public String postProduct(@ModelAttribute @Valid ProductDTO product, BindingResult result, Model model){
        if(productService.existsByName(product.getName())){
            result.addError(new FieldError("productDTO", "name", "존재하는 이름입니다."));
        }
        if(result.hasErrors()){
            return "add";
        }
        productService.addProduct(product);
        model.addAttribute("productDTO",product);
        return "redirect:/api/products";
    }

    @PostMapping("/update/{id}")
    public String putProduct(@PathVariable("id") Long id,  @ModelAttribute @Valid ProductDTO product, BindingResult result)
        throws NotFoundException {
        if(productService.existsByName(product.getName())){
            result.addError(new FieldError("productDTO", "name", "존재하는 이름입니다."));
        }
        if(result.hasErrors()){
            return "update";
        }
        product = new ProductDTO(id,product.getName(),product.getPrice(),product.getImageUrl());
        productService.updateProduct(product);
        return "redirect:/api/products";
    }`
    
-----
저번 주차에서 에러가 너무 많이 나서 이유를 찾으려 로깅을 꼼꼼하게 했는데, 하고 나니 코드가 조금 지저분한 느낌이 듭니다. 로깅은 필요할 때만 쓰고 없애는 것이 좋은 것인가요? 아니면 로깅은 많이 하면 할 수록 좋은 건가요? 실무에서는 로깅이 어떻게 쓰이는지 궁금합니다.
-----
assertThat(actual.getId()).isNotNull();
테스트 코드에 이걸 넣으면 이 뒤로는 실행이 안됩니다. unreachable이라고 뜨는데 이유를 모르겠습니다. 라이브코딩 실습 때도 사용하시는 걸 보았고 다른 학생들이 사용하는 것도 보입니다. 제 코드에서 안되는 이유는 뭘까요?
-----
다른 분들의 코멘트를 여러가지 봤는데, setter을 사용하지 않는 것이 좋다고 하시는 분들이 많이 계셔서 저도 setter을 없애버렸습니다. 그리고 저번 리뷰에서 DTO가 필요하다고 하셨는데 UserDTO가 없어 추가했습니다.

2024-07-09 13:19 UTC, yoo-jaein requested changes
step1 고생하셨습니다! :)
리뷰 코멘트 확인 부탁드려요.

상품 추가 / 수정 쪽은 로직 버그를 먼저 고쳐주시면 확인해보겠습니다!

### 질문 1
저번 주차에서 에러가 너무 많이 나서 이유를 찾으려 로깅을 꼼꼼하게 했는데, 하고 나니 코드가 조금 지저분한 느낌이 듭니다. 로깅은 필요할 때만 쓰고 없애는 것이 좋은 것인가요? 아니면 로깅은 많이 하면 할 수록 좋은 건가요? 실무에서는 로깅이 어떻게 쓰이는지 궁금합니다.

### 답변 1
에러가 많이 나서 문제 지점을 찾으려는 경우 로깅을 꼼꼼히 하고 디버깅을 하는 것은 좋은 방향입니다 👍 (꼭 디버깅도 같이..!)

실무에서 로그는 꼭 필요한 곳에만 남기고 (심각한 오류, 중요한 비즈니스 이벤트, 개발자가 디버깅하기 위한 상세 정보 등...) 일반적인 비즈니스 로직 과정에서는 잘 남기지 않습니다. 그리고 개발/테스트 환경에서는 DEBUG 레벨까지 로그를 출력하고 프로덕션 환경에서는 보통 DEBUG 레벨은 출력하지 않습니다.

로깅은 많이 한다고해서 무조건 좋은 것은 아닙니다. 너무 많으면 애플리케이션 성능에 영향이 가기도 하고, 불필요한 정보가 많이 쌓여서 실제로 중요한 정보를 찾지 못할 수도 있습니다.

### 질문 2
assertThat(actual.getId()).isNotNull();
테스트 코드에 이걸 넣으면 이 뒤로는 실행이 안됩니다. unreachable이라고 뜨는데 이유를 모르겠습니다. 라이브코딩 실습 때도 사용하시는 걸 보았고 다른 학생들이 사용하는 것도 보입니다. 제 코드에서 안되는 이유는 뭘까요?

### 답변 2
이건 어느 테스트 클래스일까요?

2024-07-09 13:19 UTC, deactivated-user commented on src/test/java/gift/WishListRepositoryTest.java
> +        WishList actual = wishListRepository.save(wishList);
저는 테스트 코드를 짤 때 Given-When-Then 구조로 작성하는데요.
구조 사이 사이에 줄을 띄워주면 보기 깔끔해집니다!
```java
@Test
@DisplayName("상품 가격 업데이트 테스트")
void updateProductPrice() {
    // Given
    Product product = new Product("Test Product", 1000, "test.jpg");
    Product savedProduct = productRepository.save(product);
    Long productId = savedProduct.getId();

    // When
    savedProduct.setPrice(1500);
    productRepository.save(savedProduct);

    // Then
    Product updatedProduct = productRepository.findById(productId).orElseThrow();
    assertThat(updatedProduct.getPrice()).isEqualTo(1500);
}
```
이 구조는 테스트를 3단계로 나누기 때문에 테스트 코드의 가독성과 이해도를 높일 수 있습니다.
아직 테스트 코드 작성이 익숙하지 않으실 것 같은데, 직접 // Given ~ When ~ Then 주석을 적고 작성하시면 도움이 될 것 같아요.

2024-07-09 13:19 UTC, deactivated-user commented on src/main/java/gift/wishlist/WishListService.java
인텔리제이에서 현재 파일의 코드 포맷을 정리하는 단축키를 써보세요!
- 윈도우:  Ctrl + Alt + L
- 맥 : Option + Command + L

혹은 저장 시 자동으로 포맷을 정리해주는 설정도 있습니다.
- IntelliJ IDEA > Preferences > Tools > Actions on Save에서 "Reformat code" 옵션을 체크하면 파일 저장 시 자동으로 코드 포맷이 정리됩니다.

2024-07-09 13:19 UTC, deactivated-user commented on src/test/java/gift/ProductRepositoryTest.java
> +        productRepository.deleteById(product.getId());
deleteById 테스트에서 삭제 전에 먼저 저장 작업이 필요합니다.

2024-07-09 13:19 UTC, deactivated-user commented on src/test/java/gift/ProductRepositoryTest.java
> +
findAll에 대한 테스트가 누락되어 있습니다!

2024-07-09 13:19 UTC, deactivated-user commented on src/test/java/gift/UserRepositoryTest.java
> +    }
정상 케이스에 대한 테스트 코드를 잘 작성해주셨네요!
예외 케이스에 대한 테스트 코드도 작성해볼 수 있을까요?

2024-07-09 13:19 UTC, deactivated-user commented on src/test/java/gift/WishListRepositoryTest.java
> +    @Test
각 테스트 메서드에 ```@DisplayName```을 추가하면 테스트 이름과 목적을 명확히 표현할 수 있습니다.

2024-07-09 13:19 UTC, deactivated-user commented on src/main/java/gift/wishlist/WishList.java
>      private int num;
최소값 검사를 넣는 것도 좋겠네요~

2024-07-09 13:19 UTC, deactivated-user commented on src/main/java/gift/product/ProductService.java
> +        if(productRepository.existsByName(product.getName())){
이름 중복 체크 로직이 잘못되었습니다.
productDTO로 사용자가 요청한 이름이 db에 이미 존재하는지 체크해야 합니다!

2024-07-09 13:19 UTC, deactivated-user commented on src/main/java/gift/product/ProductController.java
> +        throws NotFoundException {
컨트롤러에서는 비즈니스 로직을 가급적 처리하지 않는 것이 좋습니다.
서비스 레이어로 옮겨볼까요?

2024-07-09 13:19 UTC, deactivated-user commented on src/main/java/gift/product/ProductController.java
> +        if(productService.existsByName(product.getName())){
여기도 서비스 레이어로 이동하는 것이 더 적합할 것 같습니다

2024-07-09 13:19 UTC, yoo-jaein commented on src/main/java/gift/wishlist/WishListService.java
> +            return wishListRepository.findAll().stream()
모든 예외를 Excpeiont으로 감싸고 있네요. 이는 구체적인 예외 처리를 어렵게 만들 수 있습니다.
가능하면 try-catch (Exception)은 사용하지 않기로 해요.

그리고 일반적으로 전체 조회 메서드의 경우 데이터가 없음을 빈 리스트로 표현하는 경우가 더 많습니다 😀

2024-07-09 13:19 UTC, yoo-jaein commented on src/main/java/gift/wishlist/WishListService.java
> +            NotFoundException::new);
Optional은 불필요합니다!
```java
WishList wishList = wishListRepository.findByEmailAndProductId(email, productId)
            .orElseThrow(() -> new NotFoundException());
```
repository가 반환하는 값을 그대로 받는 것이 좋습니다.

2024-07-09 13:19 UTC, yoo-jaein commented on src/main/java/gift/wishlist/WishListService.java
> +    public Boolean existsByEmailAndProduct_id(String email, long productId){
카멜케이스에 맞게 메서드 이름 변경이 필요합니다!

2024-07-09 13:19 UTC, yoo-jaein commented on src/main/java/gift/wishlist/WishListService.java
> +        if(!existsByEmailAndProduct_id(email, productId)){
추가로 Optional은 비싼 객체이기 때문에 주의해서 꼭 필요한 곳에만 사용해야 합니다.
- https://dev-coco.tistory.com/178
- https://homoefficio.github.io/2019/10/03/Java-Optional-%EB%B0%94%EB%A5%B4%EA%B2%8C-%EC%93%B0%EA%B8%B0/

2024-07-09 13:19 UTC, yoo-jaein commented on src/test/java/gift/UserRepositoryTest.java
> +        assertThat(actual).isEqualTo(true);
이 테스트 메서드는 2개로 분리하는 것이 좋을 것 같습니다.
하나의 메서드당 하나의 테스트를 만들어보아요.

2024-07-09 19:24 UTC, hyyyh0x commented
상품 추가 / 수정 쪽 질문 했던 것은 해결했습니다!
@ModelAttribute 관련해서 setter가 설정되어 있지 않아서 인 것 같습니다. setter 없이 하는 방법도 찾아봤는데, 기본 생성자가 없어야 한다고 되어 있더라고요.
@GetMapping("/add")
    public String showPostProduct(Model model){
        model.addAttribute("productDTO", new ProductDTO());
        return "add";
    }
 이 부분에서 기본생성자를 사용하고 있고, 없애려고 하니 오류가 계속 떠서 그냥 setter를 사용하기로 했습니다.
 처음 질문드렸던, 오류 메시지가 다른 방법으로 뜨는 것은 해결했습니다!

 _assertThat(actual.getId()).isNotNull();
테스트 코드에 이걸 넣으면 이 뒤로는 실행이 안됩니다. unreachable이라고 뜨는데 이유를 모르겠습니다. 라이브코딩 실습 때도 사용하시는 걸 보았고 다른 학생들이 사용하는 것도 보입니다. 제 코드에서 안되는 이유는 뭘까요?_
이 질문에서 말하는 테스트 코드는 ProductRepositoryTest 입니다!
"전체 상품 찾기 테스트" 에 이 줄을 추가하면 뒤 코드가 실행되지 않습니다.
assertThat(actual.getFirst().getId()).isNotNull();

하지만 
assertThat(actual.get(1).getId()).isNotNull();
이건 됩니다...

상품추가테스트에서도
assertThat(actual.getId()).isNotNull(); 를 추가하면 안됩니다.
상품삭제테스트에서도 assertThat(actual).isNull(); 가 안됩니다.
안된다는 것은 The call to 'isNotNull' always fails with an exception 이라고 뜨며 뒤 코드가 모드 회색으로 바뀌며 Unreachable code 라고 나옵니다. 특별한 이유가 있을까요?

2024-07-10 05:17 UTC, yoo-jaein approved these changes
리뷰 반영된 것 확인했습니다!
step1 머지하겠습니다.

질문 주신 부분은 코멘트로 답변 달았으니 확인 부탁드려요.
혹시 문제가 계속 발생하거나 잘 이해가 되지 않는다면 편하게 메시지 주시면 됩니다 :)

2024-07-10 05:17 UTC, yoo-jaein commented on src/main/java/gift/product/Product.java
> +    private long id;
id의 필드 타입이 ```long```으로 선언되었기 때문에 ```assertThat(actual.getId()).isNotNull();```과 같은 null 체크가 정상적으로 되지 않았던 것 같습니다 👀
(```long```은 null 값을 가질 수 없고 항상 기본값 0을 가지는 반면, ```Long```은 null 값을 가질 수 있습니다.)

JPA에서 일반적으로 엔티티의 id 필드는 ```Long```으로 가져가는데요. 그 이유는 데이터베이스에 저장되기 전 엔티티의 id가 null일 수 있기 때문입니다. 

(데이터베이스에 id 컬럼을 auto_increment로 지정했기 때문에, 실제 데이터베이스에 저장되기 전까지 애플리케이션에 있는 Product 엔티티의 id 값은 비어있겠죠?)

```private Long id```로 변경한 다음 테스트 코드를 수정해볼까요?

2024-07-10 05:17 UTC, yoo-jaein commented on src/test/java/gift/ProductRepositoryTest.java
> +        product = new Product(3000,"이춘식","example.jpg");
두번째 테스트 데이터라는 의미를 담아 구체적으로 변수를 지정해 주는 것이 좋습니다!
```java
Product product2 = new Product(3000,"이춘식","example.jpg");
```

2024-07-10 05:17 UTC, yoo-jaein commented on src/test/java/gift/WishListRepositoryTest.java
> +        assertThat(actual).isNotPresent();
👍

2024-07-10 05:17 UTC, yoo-jaein commented on src/test/java/gift/ProductRepositoryTest.java
> +        //Then
```assertThat(actual).hasSize(2);``` 리스트 크기 검증도 추가하면 좋겠습니다.

2024-07-10 05:17 UTC, yoo-jaein commented on src/test/java/gift/UserRepositoryTest.java
> +    void notExistsByEmail(){
부정 테스트도 테스트하고 있어 좋습니다! 다만 정상 케이스와 DisplayName이 같은데 이를 구분하면 좋을 것 같습니다.
예: "존재하지 않는 이메일로 회원을 찾으면 false 리턴"

2024-07-10 05:17 UTC, yoo-jaein commented on src/test/java/gift/WishListRepositoryTest.java
> +        //Then
여기도 리스트 크기 검증을 추가하면 좋겠습니다.

2024-07-10 05:18 UTC, merged