강원대 BE_오승환 3주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #134
Opened 2024-07-09 11:29 UTC by humpose

안녕하세요. 코치님
저번에 권고해주신 사항 1, 3번은 해결하였습니다.
그러나 2번 사항에 대해 여쭤볼 것이 있습니다. 
현재 제 코드에서 타임리프가 모델 객체의 속성을 폼 필드에 바인딩하거나 폼 필드의 값을 모델 객체의 속성에 바인딩할 때 사용되는 상태입니다. 이러한 상황에서 setter를 꼭 삭제해야하는 이유가 뭔지, 무엇으로 대체해야 할지 여쭤보고 싶습니다.

또한 현재 제 코드가 로그인 화면에서 토큰을 발급하여 저장하고, 위시리스트 메인 화면에서 상품 추가 화면으로 이동할 때도 제대로 스토리지에서 토큰이 전달되는 것처럼 보입니다. 그런데 상품을 추가하려고 할 때만 어째서 토큰이 발급되지 않는 건지 알 수 있을까요? 정확히는 add_product_to_wishlist.html의 script가 작동하지 않는 상태입니다.

마지막으로, setter에 관한 부분을 너무나 늦게 말씀드린 점 죄송합니다. 다른 문제를 먼저 수정하느라 인지하고 있었음에도 말씀 드릴 겨를이 없었습니다. 이번만 용서해주시면 감사하겠습니다.

조언해주시면 열심히 수정해보도록 하겠습니다. 감사합니다

2024-07-09 13:05 UTC, pci2676 commented
> 그러나 2번 사항에 대해 여쭤볼 것이 있습니다.
> 현재 제 코드에서 타임리프가 모델 객체의 속성을 폼 필드에 바인딩하거나 폼 필드의 값을 모델 객체의 속성에 바인딩할 때 사용되는 상태입니다. 이러한 상황에서 setter를 꼭 삭제해야하는 이유가 뭔지, 무엇으로 대체해야 할지 여쭤보고 싶습니다.

제가 말씀드린 부분은 서로 다른 객체를 사용하기를 바란 리뷰였습니다.

하나의 객체를 이용해서 요청/응답에도 사용하고 데이터를 저장하는 모델로도 사용한다면 이는 SRP를 위반하게됩니다.

2024-07-09 13:37 UTC, pci2676 commented
> 또한 현재 제 코드가 로그인 화면에서 토큰을 발급하여 저장하고, 위시리스트 메인 화면에서 상품 추가 화면으로 이동할 때도 제대로 스토리지에서 토큰이 전달되는 것처럼 보입니다. 그런데 상품을 추가하려고 할 때만 어째서 토큰이 발급되지 않는 건지 알 수 있을까요? 정확히는 add_product_to_wishlist.html의 script가 작동하지 않는 상태입니다.

프론트는 리뷰의 범위가 아니긴 한데요..

`document.body.innerHTML = html;` 

로 작성해주신 부분을

```javascript
document.open();
document.write(html);
document.close();
```

로 변경하면 동작할것 같네요.

2024-07-09 13:38 UTC, pci2676 commented
> 마지막으로, setter에 관한 부분을 너무나 늦게 말씀드린 점 죄송합니다. 다른 문제를 먼저 수정하느라 인지하고 있었음에도 말씀 드릴 겨를이 없었습니다. 이번만 용서해주시면 감사하겠습니다.

엇 제가 용서하고 말고 할게 있나요. 😓 

승환님이 제출하시는대로 저는 리뷰를 할 뿐입니다.

그 과정에서 저는 가능한 승환님이 좋은 코드를 작성할 수 있도록 리뷰를 남기는 것 일뿐이지요.

2024-07-09 14:30 UTC, pci2676 requested changes
질문에 대한 답변과 리뷰를 남겨두었으니 반드시 개선해주세요.

2024-07-09 14:30 UTC, pci2676 commented on src/main/java/gift/controller/UserController.java
> +    }
`@Autowired`가 필요한가요?

spring bean 주입방식에 대해 알아내신다음 저에게 한번 공유해주시는 연습을 해보시면 좋을것 같네요.

2024-07-09 14:30 UTC, pci2676 commented on src/main/java/gift/controller/UserController.java
> +    public ResponseEntity<Map<String, Object>> login(@ModelAttribute User user) {
코멘트로 남겨둔 부분을 참고하여 개선해주세요.

2024-07-09 14:30 UTC, pci2676 commented on src/main/java/gift/controller/WishListController.java
> +        }
controller에서는 비즈니스 흐름이 나타나지 않도록 해주세요.

service 레이어로 옮겨주시면 좋을것 같네요.

2024-07-09 14:30 UTC, pci2676 commented on src/main/java/gift/jwt/JwtInterceptor.java
> -        if (authorizationHeader.isValid()) {
엇 이 부분은 왜 롤백되었나요? 

AuthorizationHeader를 잘 활용해주셨던것 같아요

2024-07-09 14:30 UTC, pci2676 commented on src/main/java/gift/repository/WishListRepository.java
> +    WishList findByUser(User user);
WishList가 없을수도 있지 않을까요? Optional을 활용해주세요.

2024-07-09 14:30 UTC, pci2676 commented on src/main/java/gift/model/WishList.java
> +    @ManyToOne
ManyToOne을 활용하셨는데 fetch 속성에 대해 알고계신가요?

2024-07-09 14:30 UTC, pci2676 commented on src/main/java/gift/service/ProductService.java
> +        return productRepository.findById(id).orElse(null);
꼭 null을 반환해야하나요? 그렇다면 Optional을 활용해주세요.

2024-07-09 14:30 UTC, pci2676 commented on src/main/java/gift/service/ProductService.java
> +        productRepository.save(product);
id를 입력받고 사용하지 않는것 같네요

2024-07-09 14:30 UTC, pci2676 commented on src/main/java/gift/service/UserService.java
> +    private final String secretKey = "Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=";
이 부분도 롤백 될 필요가 없어보이네요.

2024-07-09 14:30 UTC, pci2676 commented on src/main/java/gift/service/WishListService.java
> +            wishList.setProducts(new ArrayList<>());
이러한 부분들이 setter를 사용하지 말기를 바라는 부분인데요.

아래 동영상을 참고하시면 좋을것 같습니다.

https://www.youtube.com/watch?v=3etKkkna-f0&ab_channel=%EC%9A%B0%EC%95%84%ED%95%9C%ED%85%8C%ED%81%AC

2024-07-10 06:18 UTC, humpose commented
제가 찾아본 바로는 
spring bean 주입 방식에는 크게 4가지로 필드 주입, 생성자 주입, 세터 주입, 메소드 주입이 있었습니다. 
필드 주입의 특징은 코드가 간결하고, 필드에 직접 주입되어 간단하지만 코드가 스프링에 의존적이게 된다는 단점 때문에 UNIT테스트가 어렵다는 특징이 있습니다.
생성자 주입은 불변성을 보장하며, 모든 의존성이 생성자 호출 시점에 주입되므로 객체가 불완전한 상태로 존재하지 않습니다. 또한 생성자가 하나뿐이라면 @Autowired를 생략할 수 있다는 특징이 있습니다.
세터 주입은 필드 값을 변경하는 Setter를 통해서 의존 관계를 주입하는 방법으로 주입받는 객체가 변경될 가능성이 있는 경우에 사용한다는 특징이 있습니다.
메소드 주입은 한 번에 여러 필드를 주입받을 수 있다는 점이 특징이지만, 여러 필드를 받을 것이라면 차라리 생성자 주입을 사용하는 것이 좋기 때문에 잘 사용하지 않습니다.

객체의 불변성 확보
테스트 코드의 작성
순환 참조 에러 방지
등의 이유로 생성자 객체를 쓰는 것을 권장하고 있는 것 같습니다.

제 코드를 돌아보니, 생성자가 하나뿐인 생성자의 @Autowired를 생략하는 방향으로 리펙토링 할 수 있을 것 같습니다.
저번에 공부했을 때는 @Autowired를 생략할 수 있는 부분을 제대로 인지하지 못 했던 것 같습니다. 어떠한 개념에 대해 검색하고 찾아볼 때 그 개념이 가지고 있는 작은 기능까지 정확히 공부해야 제대로 사용할 수 있음을 느꼈습니다.

@ManyToOne의 fetch 속성에 대해 공부해 보았습니다.
FetchType.LAZY(지연 로딩)와 FetchType.EAGER(즉시 로딩)이 있었습니다.
지연 로딩은 연관된 엔티티를 실제로 사용할 때 로드하고, 즉시 로딩은 연관된 엔티티를 즉시 로드한다는 특징이 있습니다.
지연 로딩은 초기 로딩 시, 메모리 사용을 줄일 수 있습니다.
즉시 로딩은 코드가 더 단순해지며 연관된 엔티티를 바로 사용할 수 있으나, 연관된 엔티티가 많을 경우 초기 로딩 시 메모리 사용이 증가할 수 있다는 단점이 있습니다.

현재까지는 아무런 속성을 지정하지 않아 기본 설정인 즉시 로딩으로 설정되었습니다.
제가 생각하기에, 제 코드에서 지연 로딩을 사용하고 필요할 때만 연관된 엔티티를 로드하는 것이 더 유연하고 효율적이라고 생각합니다.

2024-07-10 07:44 UTC, pci2676 commented
> 런 속성을 지정하지 않아 기본 설정인 즉시 로딩으로 설정되었

크 깔끔하게 정리해주셨네요 👍

2024-07-10 07:50 UTC, pci2676 approved these changes
리뷰 반영을 깔끔하게 잘 해주셨네요 👍 

다음 단계를 진행하면서 이번단계에 남겨진 리뷰를 참고하여 개선해주세요.

2024-07-10 07:50 UTC, pci2676 commented on src/main/java/gift/model/WishList.java
> +    private final List<Product> products = new ArrayList<>();
https://edu.nextstep.camp/s/dGx30MLc/ls/AoOcpVXR

요구사항을 보았을때 wish list가 아닌 wish에 대한 jpa entity가 도출되어야 할 것 같아보이네요!

2024-07-10 07:50 UTC, pci2676 commented on src/main/java/gift/model/WishList.java
> +        user = new User();
jpa entity 특성상 기본 생성자가 필요한데요.

꼭 모든 필드를 final을 이용한 불변으로 표현하실 필요는 없습니다~

final 없이 가변적인 필드로 선언하고 기본생성자는 빈 body를 갖게 해주시는게 더 일반적인 구현방법이니 참고해주세요~!

2024-07-10 07:50 UTC, pci2676 commented on src/main/java/gift/model/WishList.java
> +    @ManyToOne(fetch = FetchType.LAZY)
👍

2024-07-10 07:50 UTC, pci2676 commented on src/main/java/gift/model/Product.java
> +    }
여기도 동일합니다. 😄

2024-07-10 07:50 UTC, pci2676 commented on src/main/java/gift/dto/ProductDTO.java
> +public class ProductDTO implements Serializable {
dto 분리 👍 

Serializable은 왜 사용하셨을까요?

2024-07-10 07:50 UTC, merged