경북대 BE_신성민 3주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #136
Opened 2024-07-09 12:08 UTC by anaconda77

안녕하세요 경북대 BE 신성민 학생입니다. 3주차 과제 step1 제출드립니다.

## 과제 수행 중에 궁금했던 점

2024-07-09 13:35 UTC, lsm7179 commented
> 안녕하세요 경북대 BE 신성민 학생입니다. 3주차 과제 step1 제출드립니다.
> 
> ## 과제 수행 중에 느낀 점
> 이번 과제에서 ControllerTest를 수행할때 실제 Service/Repository 객체를 받아왔는데, 트랜잭션 적용이 생각대로 되지않아서 찾아보니 트랜잭션을 주관하는 스레드와 컨트롤러 메서드를 호출하는 스레드가 달라 그렇다는 얘기를 듣게 되었습니다. 실제 DB를 거쳐 데이터에 접근하다보니 중복 저장 문제 등이 생겨 테스트를 수행하기 까다로웠습니다.
> 
> 대충 예외를 처리한 후 곰곰히 생각해보니, Controller에 대한 테스트를 수행할때는 하위 계층(Service,Repository)을 테스트 스텁 혹은 Mock 객체로 만들어서 실제 DB 접근 없이도 Controller의 기능을 검증할 수 있게 테스트를 설계하는게 적절한 방향이라는 생각이 들었습니다.
> 
> 실제 DB에 접근하여 데이터 검증 혹은 비즈니스 로직 자체에 대한 검증은 Service/Repository 각각에 대한 테스트로 가능하므로, Controller에 대한 테스트는 최대한 외부 효과를 배제하고 그 자체의 기능에만 집중할 필요가 있다는 생각이 들었습니다..!

좋은 고민과 접근이네요.
controller의 테스트도 단위테스트 slice하거나 통합테스트, 인수테스트 등등을 할수있습니다.
각각의 장단점을 알고 사용하면 좋을거 같아요.
특히 Mock으로 테스트 하지 않고 end to end 테스트도 경험해보시면 좋을거 같아요.
저같은 경우 실무에서 testcontainer와 springboottest 를 활용하여 end to end 테스트를 했었습니다.
어떤 장단점이 있는지 알면 좋을거 같네요.

2024-07-09 13:56 UTC, lsm7179 requested changes
성민님 1단계 수고하셨습니다.😁
간단한 코멘트들 있으니 확인해주세요.
이해 안가시는 부분 있으면 편하게 DM주세요~

2024-07-09 13:56 UTC, lsm7179 commented on src/main/java/gift/model/Member.java
> +    @Column(nullable = false)
👍

2024-07-09 13:56 UTC, lsm7179 commented on src/main/java/gift/model/Member.java
>      public Member() {
jpa entity를 사용하므로 setter와 프로퍼티 접근 방하기 위해 생성자는 protected로 수정해주세요.
다른 엔티티도 같이 확인해주세요.

2024-07-09 13:56 UTC, lsm7179 commented on src/main/java/gift/model/Product.java
> +
도메인객체에 set은 지워주세요.
다른 도메인객체도 같이 해볼까요?

2024-07-09 13:56 UTC, lsm7179 commented on src/main/java/gift/service/MemberService.java
> +@Transactional
저는 클래스단위로 @transactional(readOnly = true) 붙이고 cud하는 메서드만 @transactional를 붙입니다.
@transactional(readOnly = true) 를 붙여보세요.(다른 서비스계층도 같이 붙여보세요.)

왜 @transactional(readOnly = true) 를 클래스에 붙이는게 @transactional 보다 좋을까요?🤔

2024-07-09 13:56 UTC, lsm7179 commented on src/main/java/gift/service/MemberService.java
> +            throw new MemberException("중복된 이메일의 회원이 이미 존재합니다.");
MemberException 클래스명이 모호하네요. 중복된이메일일 경우 에러 클래스명으로 수정하는게 어떨까요?
예를 들어 `DuplicateEmailException`

2024-07-09 13:56 UTC, lsm7179 commented on src/main/java/gift/service/MemberService.java
> +            .orElseThrow(() -> new LoginErrorException("아이디 또는 비밀번호가 일치하지 않습니다."));
orElseThrow 좋습니다.

2024-07-09 13:56 UTC, lsm7179 commented on src/main/java/gift/service/ProductService.java
> +        productRepository.save(product);
jpa를 사용한 update시 save를 사용하지 않고 해보세요.
https://winterroom.tistory.com/161

2024-07-09 13:56 UTC, lsm7179 commented on src/main/java/gift/service/ProductService.java
> +                );
변수로 받은 name, price, imageUrl을 영속성컨텍스트 엔티티 product에 넣지 않아서 수정이 안될거 같아요.

2024-07-09 13:56 UTC, lsm7179 commented on src/test/java/gift/controller/ProductApiControllerTest.java
> +
@SpringBootTest 까지 진행해주셨군요.💯👍

2024-07-09 15:48 UTC, anaconda77 commented on src/main/java/gift/service/MemberService.java
> +@Transactional
성능과 연관이 있을 것 같은데..찾아보니 해당 옵션이 영속성 컨텍스트에서 변경 감지(dirty checking)를 수행하지 않게 하여서 작업의 수가 월등히 줄어들 것 같습니다!

2024-07-09 15:58 UTC, anaconda77 commented on src/main/java/gift/service/ProductService.java
> +        productRepository.save(product);
위에서 setter 메소드를 모두 지워주라고 하셨는데, setter가 없으면 변경 감지 기능을 활용할 수 없지 않나요?

2024-07-10 11:25 UTC, lsm7179 commented on src/main/java/gift/model/Product.java
> +    protected Product() {
기본생성자가 위에 있어야될거같네요~
생성자 위치를 수정해볼까요?

2024-07-10 11:25 UTC, lsm7179 commented on src/main/java/gift/service/MemberService.java
> +@Transactional
readOnly = true 속성도 같이 붙여주면 더 좋을거 같네요.😁

2024-07-10 11:25 UTC, lsm7179 commented on src/main/java/gift/service/MemberService.java
> +            throw new DuplicateEmailException("중복된 이메일의 회원이 이미 존재합니다.");
DuplicateEmailException는 이미 의미를 가지고 있는거 같아요.
DuplicateEmailException에서 "중복된 이메일의 회원이 이미 존재합니다."을 상수로 만들어 부모객체에게 던져볼까요?

2024-07-10 11:25 UTC, lsm7179 commented on src/main/java/gift/service/ProductService.java
> +        productRepository.save(product);
네 update메소드를 만들어서 사용해주시면 됩니다.
그게 객체지향코드의 핵심이에요.
모든 프로퍼티의 접근을 제어하는것이죠.
update에서는 도메인 검증도 진행할수있어요. 
이를테면 "이름 null이면 안되고 가격이 0이상이어야한다." 이런거요.

2024-07-10 11:27 UTC, lsm7179 approved these changes
성민님 수고하셨습니다.👍
머지하겠습니다.
몇가지 코멘트 남겼는데 이해가 안가거나 궁금한게 있으면 언제든 DM주세요~
화이팅입니다.🔥

2024-07-10 11:27 UTC, lsm7179 commented on src/main/java/gift/model/Product.java
> +        this.imageUrl = newImageUrl;
👍
각 필드별 검증도 있으면 좋겠네요~

2024-07-10 11:27 UTC, merged