충남대 BE_박서현 3주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #137
Opened 2024-07-09 12:48 UTC by sseooh

2024-07-09 14:45 UTC, jjongwa requested changes
1단계 미션 수고하셨습니다 👍 

아직 지난 리뷰 내용이 완전히 반영되진 않은 것 같아요.!
- Controller에서 사용하지 않는 필드 / 메서드 제거 & ResponseType 와일드카드 변경
- 서비스의 생성자에서 `@Autowired` 제거 & 사용하지 않는 메서드 제거

추가로, 1단계 요구사항인 `@DataJpaTest를 사용하여 학습 테스트`가 존재하지 않네요!
해당 조건 완료되면 다시 리뷰 요청 부탁드려요~!

2024-07-09 14:45 UTC, jjongwa commented on src/main/java/gift/domain/Member.java
>      public Member() {}
외부에서 사용되지 않는 메서드는 제거하거나 private로 바꾸는게 좋겠네요!

2024-07-09 14:45 UTC, jjongwa commented on src/main/java/gift/domain/Member.java
> +@Table(name = "member")
만약 해당 라인을 지우면 Member 테이블의 이름은 어떻게 정의될까요?

2024-07-09 14:45 UTC, jjongwa commented on src/main/java/gift/repository/MemberRepository.java
> +}
JpaRepository 사용 좋습니다 👍

2024-07-11 00:43 UTC, sseooh commented on src/main/java/gift/domain/Member.java
> +@Table(name = "member")
클래스 이름 그대로 Member로 정의됩니다!

2024-07-11 14:20 UTC, jjongwa commented on src/main/java/gift/domain/Member.java
> +@Table(name = "member")
네 맞습니다! `@Table` 을 통해 이름을 적지 않더라도 테이블 이름은 클래스를 따라가기 때문에 꼭 클래스 위에 해당 어노테이션을 추가하지 않아도 됩니다! (필드에 있는 `@Colum`의 name도 마찬가지입니다!)

한가지 특징이 있다면 Camel Case를 Snake Case로 자동으로 변환해 적용되기 때문에
(ex. ProductStat -> product_stat)

클래스의 이름과 실제 테이블의 이름의 형식 차이가 나타난다는 점을 기억하고 있으면 좋을 것 같습니다~!

2024-07-11 14:29 UTC, jjongwa approved these changes
1단계 고생 많으셨어요! 3주차도 얼마 안남았네요..! 다음 단계도 파이팅입니다!! 🦾🦾

2024-07-11 14:29 UTC, jjongwa commented on src/test/java/gift/MemberRepositoryTest.java
> +}
1. 테스트 클래스와 메서드에는 접근제어자를 쓰지 않아도 됩니다!
2. `@Rollback` 을 false로 두는 것 보단 각 메서드 or 클래스마다 새롭게 생성된 데이터는 지워주는게 좋습니다! 지금은 테스트가 많이 없어서 괜찮지만 규모가 커지고 테스트의 수도 많아지면 다른 메서드의 결과값에 영향을 줄 수도 있어요!
3. 각 테스트마다 `@DisplayName`을 통해 설명을 적어놓으면 좋을 것 같아요~!
4. `isGreaterThan(0)`은 `isPositive()`로 대체할 수 있을 것 같네요.!
5. testSaveMember에서 해당 멤버가 제대로 db에 저장되어 id를 할당받았음을 나타내고 싶다면 isNotNull()도 괜찮을 것 같습니다!

2024-07-11 14:30 UTC, merged