충남대 BE_배민수 3주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #138
Opened 2024-07-09 12:50 UTC by minsu-cnu

1단계 과제 수행하여 PR 올립니다.

리뷰 맡아주시느라 항상 고생이 많으십니다. 감사합니다!

2024-07-09 14:34 UTC, jjongwa requested changes
1단계 수고하셨어요~! 
테스트가 아주 야무지네요!! 👍👍

JPA 관련 본격적인 리뷰를 남기기 전에 전체적으로 변경해야 할 부분이 있어 보여 우선 이렇게 RC 드립니다.!

현재 repository 패키지에서 SpringDataJpa로 시작하는 Repository가 있긴 한데 사용하지 않고
각각의 Repository 인터페이스를 만든 뒤 entityManager를 통해 이를 구현하는 구현체 클래스를 사용하고 있는데,

JpaRepository를 extends 하고 있는 SpringDataJpaOOORepository를 사용하는 방식으로 리팩토링이 필요할 것 같습니다.! (커밋이 모두 담기지 않았을 수도 있겠네요..! 다시 한 번 확인 부탁드려요~!)

2024-07-09 14:34 UTC, jjongwa commented on src/main/java/gift/product/model/Member.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
GeneratedValue의 strategy는 어떤게 있나요?
각각의 특징은 무엇인가요?

2024-07-09 14:34 UTC, jjongwa commented on src/main/java/gift/product/service/AuthService.java
>  public class AuthService {
`@Transactional` 을 클래스 위에 붙이는 것과 메서드 위에 붙이는 것은 어떤 차이가 있을까요?

만약 둘 다 붙어있다면 어떤게 우선순위를 가질까요?
( + Transactional의 readOnly 옵션에 대해 알고 있나요?)

2024-07-09 14:34 UTC, jjongwa commented on src/test/java/gift/AuthRepositoryTest.java
> +class AuthRepositoryTest {
이것도 알쓸신잡이긴 한데..ㅋㅋ
`@SuppressWarnings("NonAsciiCharacters")`을 붙이면 한글 이름 메서드에 경고 밑줄이 생기지 않습니다..ㅎ

```
@DataJpaTest
@SuppressWarnings("NonAsciiCharacters")
class AuthRepositoryTest {
```

2024-07-09 14:34 UTC, jjongwa commented on src/main/java/gift/product/model/Wish.java
> +
현재 Product와 Wish, Member는 각각 어떤 관계를 이루고 있나요?

각각의 Entity들이 서로 연관관계를 가질 필요는 없을까요?

2024-07-09 14:34 UTC, jjongwa commented on src/main/java/gift/product/repository/ProductRepository.java
> +    public void deleteById(Long id);
아래에 생성해 놓은 SpringDataJpaProductRepository를 사용하면 해당 메서드를 정의할 필요도 없어지게 됩니다.!

+추가로 인터페이스에는 접근제어자를 붙일 필요가 없습니다!

2024-07-10 03:42 UTC, minsu-cnu commented on src/main/java/gift/product/model/Member.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
GeneratedValue의 strategy를 통해 기본키 생성 전략을 지정할 수 있는데, 다음과 같은 전략들이 있습니다.

AUTO : 하이버네이트가 DB 벤더에 적합한 기본키 생성 전략을 자동으로 지정해줍니다. 복잡한 알고리즘으로 되어있고, 버전마다 어떤 전략을 선택할 지 달라질 수 있으므로, 개발자 입장에서 예측 가능성이 조금 떨어져서 잘 선호되진 않는 듯 합니다. 다만 이식성이 높다는 장점이 있는 것 같습니다.

IDENTITY : 기본키 생성을 DB에 위임합니다. MySQL의 auto_increment와 같은 작업을 합니다.

다만 보통의 경우 커밋 시점에 영속성 컨텍스트의 쓰기 지연 SQL 저장소에 모아놓은 쿼리를 DB에 한꺼번에 보내서 성능 상 이점을 보는데, IDENTITY 전략을 사용하는 경우에는 INSERT를 실행하기 전에는 객체의 ID 값을 알 방법이 없으므로, persist()로 객체를 영속화하는 시점에 INSERT 쿼리를 곧바로 실행함으로써 ID 값을 가져와서 캐시에서 관리합니다. 이 때문에 성능에 영향을 미칠 수 있는 듯 합니다.

SEQUENCE : DB 시퀀스를 사용하여 기본키 값을 생성하는 방식입니다. 시퀀스를 지원하는 데이터베이스에서 사용되며, allocationSize등의 설정을 통해, 한 번에 사용할 시퀀스 덩어리 사이즈를 정해서 성능 상 최적화를 할 수 있다고 합니다.

TABLE : 키 생성 전용 테이블을 만들어서 시퀀스와 비슷한 기능을 흉내내는 전략입니다. 모든 데이터베이스에 적용이 가능한 장점이 있지만 성능이 아쉬워서 잘 쓰이지는 않는 듯 합니다.

2024-07-10 03:43 UTC, minsu-cnu commented on src/main/java/gift/product/service/AuthService.java
>  public class AuthService {
클래스에 지정하면 클래스 내의 모든 메소드에 적용이 되고, 특정 메소드에 지정하면 그 메소드에만 적용이 되는 것으로 알고 있습니다. 만약 둘 다 붙어있다면 메소드쪽의 우선순위가 더 높습니다. 따라서 공통적인 트랜잭션 규칙을 클래스에 걸고, 좀 더 구체적이고 특별한 규칙을 메소드에 추가로 걸어주는게 가능합니다.

그리고 readOnly 옵션명을 보고 어느정도 유추할 수는 있었지만 사용해본적이 없어서 따로 찾아보았는데, 저 옵션을 지정한 트랜잭션 내에서는 DML 중 조회만 가능하고 나머지 쓰기 작업이 불가능하다고 합니다.

2024-07-10 03:43 UTC, minsu-cnu commented on src/test/java/gift/AuthRepositoryTest.java
> +class AuthRepositoryTest {
앗 꿀팁 감사합니다! 바로 적용했습니다ㅎㅎ

2024-07-10 03:43 UTC, minsu-cnu commented on src/main/java/gift/product/model/Wish.java
> +
제 생각에는 Wish 테이블이 갖고 있는 member_id 필드와 product_id 필드를 통해 Wish가 Member와 Product를 참조하고 있는 관계라고 생각합니다. 다만 현재 Wish 테이블의 해당 두 필드에 FK 제약 조건을 걸어두지 않았기 때문에, 참조 무결성과 원활한 참조를 위해 해당 연관관계 매핑이 필요하다고 생각합니다.

연관관계 매핑은 목요일 특강에서 배우는 내용이라서 특강 이후 step2에서 적용할 계획입니다!

2024-07-10 03:44 UTC, minsu-cnu commented on src/main/java/gift/product/repository/ProductRepository.java
> +    public void deleteById(Long id);
맨 위에서 주신 레포지토리 리팩토링 관련 리뷰가 이해가 어려운 부분이 일부 있어서 코멘트 남깁니다..!

앞서 기존의 제 구현 방식을 먼저 구체적으로 설명드리자면, 처음에 순수 JPA 구현체 클래스를 쓰도록 먼저 리팩토링했었고, 이후에 스프링 데이터 JPA 인터페이스를 쓰도록 리팩토링하였습니다. 따라서 PR 드린 시점에서는 순수 JPA 구현체는 쓰지 않고 있지만 이걸 삭제해야할지 남겨야할지 애매해서 일단 남겨두었습니다.

따라서 PR 드린 시점에는 JpaRepository를 상속받은 SpringDataJpa~Repository 인터페이스를 빈에 등록하여 사용 중입니다. 혹시 몰라서 순수 Jpa 구현체 클래스를 지워도보고 SpringDataJpa~Repository 인터페이스를 주석 처리도 해보면서 해당 흐름이 잘 이루어졌다는 것을 확인도 해보았습니다. 그래서 SpringDataJpa~Repository를 사용하지 않고 구현체 클래스를 사용 중이다 라는 말씀이 아직 이해가 가지 않습니다. 혹시 제가 잘 이해하지 못하고 있는 부분이 있다면 알려주시면 감사드리겠습니다!

한편, ~Repository 인터페이스를 남겨두고 이를 SpringDataJpa~Repository 인터페이스에 상속시켜 따로 스프링 데이터 JPA 인터페이스를 남겨둔 판단의 근거는 확장성입니다. 만약 추후 순수 JPA 구현체 클래스를 쓴다던지 상황이 바뀌게 된다면, 레포지토리 빈 등록을 관리하는 Configuration 코드에서 갈아끼워주기만 하면 돼서 편리하기 때문입니다.

다만 현재 상황에서는 순수 Jpa 구현체 클래스는 사용할 일이 없기도 하고, 멘토님이 말씀해 주신 리뷰의 의도가 사용하지 않는 구현체는 삭제하고, 굳이 SpringDataJpa~Repository를 따로 만들지 말고 바로 ~Repository 인터페이스에 JpaRepositry를 상속시켜서 써라. 일 것이라고 가정을 하고 반영하여 리팩토링하였습니다.

그리고 인터페이스 내의 추상 메소드에 붙인 public 접근 제어자를 리뷰 반영하여 제거하였습니다!

2024-07-10 13:30 UTC, jjongwa commented on src/main/java/gift/product/model/Member.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
정리 잘 해주셨어요!
대부분의 경우 IDENTITY를 쓰지만 간혹가다 이렇게 다른 종류의 전략을 사용하는 경우도 있으니 머리에 넣어두면 좋습니다~!

2024-07-10 13:35 UTC, jjongwa commented on src/main/java/gift/product/service/AuthService.java
>  public class AuthService {
맞습니다! 민수님이 설명해주신 내용을 바탕으로 현재 AuthService에 적용해 본다면,
`@Transactional`은 register 메서드 위에만 붙어 있어도 충분할 것 같네요!
아니면 클래스에 `@Transactional`은 유지하고 저장이 아닌 나머지 메서드는 readOnly 옵션을 걸어주는 방식,
클래스에 readOnly를 걸어두고 register에 다시 `@Transactional`을 선언하는 방식 등
다양하게 구성할 수 있을 것 같습니다~!

2024-07-10 13:50 UTC, jjongwa commented on src/main/java/gift/product/repository/ProductRepository.java
> +    public void deleteById(Long id);
아아 SpringDataJpaRepo에 Repository 인터페이스가 extends 되어 있었군요..! 제가 잘못 봤네요..

민수님이 말씀하신 확장성 부분도 충분히 일리 있습니다!
구현체 부분을 각각 다른 패키지로 나눠 분리해 놓는다면 구분하기 편할 것 같네요~! (물론 제대로 확인 못한 제 잘못입니다..ㅎㅎ)

2024-07-10 13:51 UTC, jjongwa approved these changes
1단계는 충분한 것 같아 이만 머지하겠습니다!
2단계 3단계도 쭉쭉 달려보시죠~!

구현체 빈 등록에 관한 부분은 제가 잘못 봤었네요..! 😭  코멘트 남겨놨습니다ㅎㅎ

2024-07-10 13:51 UTC, merged

2024-07-10 13:59 UTC, minsu-cnu commented on src/main/java/gift/product/repository/ProductRepository.java
> +    public void deleteById(Long id);
아녜요 제 코드가 좀 지저분해서 가독성이 많이 떨어지는 것 같습니다ㅎㅎ.. 항상 좋은 리뷰 남겨주셔서 감사합니다!