경북대 BE_석혜원_3주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #142
Opened 2024-07-09 13:29 UTC by hyeywon

### 궁금한 점
1. 테스트를 작성하며 새로 생성자를 만들기도 했는데,
1.1. 기존의 생성자가 적절하지 못했던 건지
1.2. 테스트 작성이 잘못된 건지
이에 대해 궁금합니다.
2. `findAll()`과 같은 리스트를 반환하는 메서드를 테스트할 때, `isEqualTo()`, `contains()` 모두 시도하였지만 실패 원인을 이해하지 못해 관련 메서드에 대한 테스트는 작성하지 못한 상태입니다. `contains()`를 이용하는 것은 적절하지 않은 방법일까요?

테스트 작성에 익숙하지 않아 제대로 작성했는지에 대해 의문입니다!

2024-07-09 14:14 UTC, lsm7179 commented
> ### 궁금한 점
> 1. 테스트를 작성하며 새로 생성자를 만들기도 했는데,
>    1.1. 기존의 생성자가 적절하지 못했던 건지
>    1.2. 테스트 작성이 잘못된 건지
>    이에 대해 궁금합니다.
> 2. `findAll()`과 같은 리스트를 반환하는 메서드를 테스트할 때, `isEqualTo()`, `contains()` 모두 시도하였지만 실패 원인을 이해하지 못해 관련 메서드에 대한 테스트는 작성하지 못한 상태입니다. `contains()`를 이용하는 것은 적절하지 않은 방법일까요?
> 
> 테스트 작성에 익숙하지 않아 제대로 작성했는지에 대해 의문입니다!

1. 생성자에 대한 답변은 코멘트로 작성하였습니다. "request를 도메인객체가 알게 해주지 마세요."
   1.1 생성자는 매개변수가 많아도 괜찮습니다.
   1.2 테스트는 잘 작성해주셨습니다.👍
2. findAll 테스트 했던 예시를 보여주시면 좋을거 같아요.
    제 생각엔 contains에서 도메인 객체끼리 비교하다가 깨졌을거 같단 생각이 드는데 
   그럴땐 도메인객체의 "equals hashcode 재정의 해보세요" https://tecoble.techcourse.co.kr/post/2020-07-29-equals-and-hashCode/

2024-07-09 14:14 UTC, lsm7179 requested changes
혜원님 1단계 수고하셨습니다.😁
간단한 코멘트들 있으니 확인해주세요.
이해 안가시는 부분 있으면 편하게 DM주세요~

2024-07-09 14:14 UTC, lsm7179 commented on src/main/java/gift/api/member/Member.java
> +import jakarta.validation.constraints.NotNull;
해당 어노테이션과 jpa notnull 설정은 다릅니다.
jpa notnull으로 진행해주세요~

2024-07-09 14:14 UTC, lsm7179 commented on src/main/java/gift/api/member/Member.java
> +    }
👍
왜 protected로 생성자를 만들었나요?

2024-07-09 14:14 UTC, lsm7179 commented on src/main/java/gift/api/member/Member.java
> +    }
도메인객체는 request, response를 알고 있으면 안됩니다.
request 수정이 되면 도메인 객체가 오염 될 수 있습니다.
반대로는 가능합니다.(request, response는 도메인객체를 알아도 됩니다.)

2024-07-09 14:14 UTC, lsm7179 commented on src/main/java/gift/api/member/MemberDao.java
>  public class MemberDao {
dao계층이 jpa를 쓰니 필요없을거 같네요~
서비스 계층에서 MemberRepository를 불러볼까요?

2024-07-09 14:14 UTC, lsm7179 commented on src/main/java/gift/api/wishlist/WishDao.java
> +    }
jpa를 사용한 update시 save를 사용하지 않고 해보세요.
https://winterroom.tistory.com/161

2024-07-09 14:14 UTC, lsm7179 commented on src/test/java/gift/api/member/MemberRepositoryTest.java
> +@DataJpaTest
👍

2024-07-10 13:02 UTC, hyeywon commented on src/main/java/gift/api/member/Member.java
> +    }
강의를 참고하여 protected로 설정하였는데, 사실 protected를 사용하는 이유에 대해 궁금했습니다! public이 아닌 protected를 사용하는 경우는 단지 접근을 보다 제한적으로 허용하기 위함인가요?

2024-07-10 20:13 UTC, lsm7179 approved these changes
혜원님 수고하셨습니다.👍
머지하겠습니다.
몇가지 코멘트 남겼는데 이해가 안가거나 궁금한게 있으면 언제든 DM주세요~
화이팅입니다.🔥

2024-07-10 20:13 UTC, lsm7179 commented on src/main/java/gift/api/member/Member.java
> +    }
제한적으로 허용하기 위해서가 맞습니다.
기본생성자를 public으로 열어두면 무분별하게 사용하니 protected로 막는거죠.

2024-07-10 20:13 UTC, lsm7179 commented on src/main/java/gift/api/member/MemberService.java
> +public class MemberService {
👍

2024-07-10 20:13 UTC, lsm7179 commented on src/main/java/gift/api/wishlist/WishService.java
> +        wish.setQuantity(wishRequest.quantity());
set을 쓰지않고 메서드를 만들어서 해보세요.
메서드에 도메인 검증도 추가하면 좋을거 같네요. "위시리스트의 수량은 0보다 커야된다"

2024-07-10 20:13 UTC, merged