충남대 BE_윤정훈 3주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #144
Opened 2024-07-09 13:36 UTC by yunjunghun0116

## 1단계 과제 수행 과정
1. README.md 작성
2. 일반 클래스로 만들어진 도메인 계층의 클래스를 엔티티 클래스로 작성
3. JdbcTemplate 기반으로 작성된 레포지토리 계층을 JPA 레포지토리로 전환 작업
4. 여러가지 시나리오에 대해서 테스트코드 작성

## 과제 수행시 고민한 부분
1. Service계층에서 다른 Service계층 의존이 필요한 경우 의존을 해도 괜찮은지?
WishProductService 계층에서 Product 객체가 필요하기에 레포지토리를 통해 findById를 수행하고, 리턴타입이 Optional이라 예외에 대한 처리를 해주어야 합니다.
하지만 이 코드가 ProductService, WishProductService, ProductOptionService 에서 전부 같은 형태로 사용됩니다(중복)
그래서 저는 이부분을 ProductService 내부에 public 메서드로 findById(Long id) 로 메서드를 만들었습니다.
하지만 find 로직 하나때문에 다른 Service계층을 참조하게 되면 추후 로직이 추가됨에 따라 순환참조 와 같은 문제점이 발생할 수도 있다고 생각해서 Reader클래스를 만들어 오직 조회로직을 수행하고, 예외에 대한 처리만을 하는 컴포넌트를 만들지, 혹은 지금과 같이 Service계층을 의존하되 최대한 순환참조가 발생하지 않도록 코드를 작성하는게 옳을지 모르겠습니다.
이 부분에 대해 멘토님은 어떻게 생각하시나요?

2. Product와 WishProduct 가 서로 연관관계를 맺고 있는데 WishProduct에서
```
public void addProduct(Product product){
 product.getWishes().add(this);
 this.product = product;
}
```
와 같이 서로간의 관계 설정을 맡고있고, WishProductService의 saveWishProduct 메서드에서는
```
private WishProduct saveWishProductWithWishProductRequest(Product product, Member member, Integer count){
var wishProduct = new WishProduct(count);
wishProduct.addProduct(product);
wishProduct.addMember(member);
var savedProduct = wishProductRepository.save(wishProduct);
return savedProduct;
}
```
를 수행하는데, 양방향 연관관계에 대해 객체를 생성하여 저장하는 과정에 대해서 아직 이해가 조금 부족한것 같아 이부분에 대해서 로직을 한번 더 자세히 확인 부탁드립니다!

2024-07-10 17:54 UTC, asebn1 requested changes
정훈님 안녕하세요~
이번에 처음 JPA를 적용해주셨는데 많이 고민하신 흔적이 보이네요 👍 
고민하면 좋을 부분을 코멘트 드렸습니다. 

---

> 멘토님은 위와 같은 경우 1번 선택지와 2번 선택지, 혹은 다른 선택지를 통해 어떤식으로 중복코드와 의존성을 해결하실지 궁금합니다.

말씀 주신 1번 같은 경우는 헬퍼를 통해 독립적으로 사용할 수 있는데 이게 장점이자 단점이 아닐까 싶어요. 팀 프로젝트라면 헷갈릴만한 포인트가 될 수 있지 않을까 싶습니다
`Optional<Member> findById(Long id);` 한 줄 추가되는 거라 개인적으로 큰 부담으로 느껴지진 않았습니다. 제안주신 2번도 팀 내 합의가 된다면 코드중복을 줄여주어 나쁘지 않다고 봐요.
다만 리팩토링이 될 수 있다는 점을 기억해주세요!! (물론 지금은 많이 고민해보고 시도해보는게 좋습니다)

2024-07-10 17:54 UTC, asebn1 commented on src/main/java/gift/dto/ProductOptionResponse.java
>      }
`ProductResponse`를 반환하는게 좋은지 다시 고민해봅시다!
만약 `ProductResponse`의 필드값 변경이 있다면 `ProductOptionResponse`에도 영향이 있을 것 같네요

2024-07-10 17:54 UTC, asebn1 commented on src/main/java/gift/model/Member.java
> +    private List<WishProduct> wishes = new ArrayList<>();
cascade를 ALL로 설정해주었네요
다른 설정값엔 무엇이있을까요? ALL을 적용해야할까요?

2024-07-10 17:54 UTC, asebn1 commented on src/main/java/gift/model/Product.java
> +    private List<WishProduct> wishes = new ArrayList<>();
product가 가지는 옵션들로 `List<ProductOption>`가 있는게 직관적으로 이해가 가네요
- `wishes`를 product에서 관리해야할까요?
- 네이밍은 productOptions은 어떨까요?

2024-07-10 17:54 UTC, asebn1 commented on src/main/java/gift/model/WishProduct.java
> +    @Column(name = "count")
`Product`와 `Member`의 다대다 관계를 위해 중간 테이블로 `WishProduct`를 만들어주셨군요~ 두 속성도 `@NotNull`이 들어가면 좋을 것 같아요

2024-07-10 17:54 UTC, asebn1 commented on src/main/java/gift/repository/BaseRepository.java
> +}
지금 구조도 괜찮다고 생각합니다~
다만 추가로 생각해볼 내용이 있습니다

1. 하나로 묶은 에러얼럿이 `존재하지 않는 리소스에 대한 접근입니다`인데, 어느 엔티티에서 발생한 에러인지 추적하기 어려울 것 같아요
2. 조회 시 반환값에서 Optional 반환을 맞추어주세요. Member의 경우 `Optional<Member> findByEmail(String email);`로 사용하고있네요
3. `.orElseThrow(() -> new NotFoundElementException("존재하지 않는 리소스에 대한 접근입니다."));`의 에러처리는 서비스/레포지토리 중 어디에서 하는게 좋다고 생각하시나요?
4. 서비스가 계속 커지는 상태에서 항상 모든 레포지토리가 `findByIdOrThrow`를 사용한다는 보장을 할 수 있을까요?

2024-07-10 17:54 UTC, asebn1 commented on src/main/java/gift/service/MemberService.java
> +@Transactional
`@Transactional`을 사용해주셨네요 👍 
어떤 장점이 있을까요?

2024-07-10 17:54 UTC, asebn1 commented on src/main/java/gift/service/ProductOptionService.java
>      }
`@Transactional`에서 `readOnly`를 고민해볼까요? 
적용하면 왜 성능이 향상될까요?

2024-07-11 06:34 UTC, yunjunghun0116 commented on src/main/java/gift/model/Member.java
> +    private List<WishProduct> wishes = new ArrayList<>();
다른 설정값에는
CascadeType.PERSIST, MERGE, REMOVE, DETACH, REFRESH가 있습니다.

위 속성값은 모두 영속성과 관련이 있고, 영속성(컨텍스트) 는 DB에 존재하는 데이터를 객체형태로 관리하는 저장소입니다.
+ PERSIST 는 A와 연관되어있는 엔티티 B, C가 있고, A에 대해서 save를 수행하게 되면 B, C도 함께 save되어 영속 상태가 되도록 하는것
+ MERGE 는 연관된 엔티티가 함께 merge(update) 되도록 하는것
+ REMOVE 는 연관된 엔티티가 함께 삭제되도록 하는것이며, 이 경우 고아객체가 생길 수 있기에 orphanremoval 를 통해 발생한 고아객체에 대한 처리까지 수행할 수 있음
+ DETACH 는 영속성 컨텍스트에서 관리를 하지 않겠다고 선언하는것이며, 연관된 엔티티 모두 관리를 하지 않게되는것
+ REFRESH 는 영속성 컨텍스트에서 DB에 접근해 다시 불러오는 작업을 연관된 엔티티 모두 수행하는것

또한 find, update 등의 작업을 service계층에서 하나의 트랜잭션으로 묶어 작업을 수행하기 때문에 ALL을 적용하지 않고, PERSIST를 통해 연관된 엔티티에 대해서 함께 영속 상태가 될 수 있도록 하여 적절한 CascadeType을 적용할 수 있겠네요!

그리고, DETACH는 오히려 JPA를 사용하는 입장에서 EntityManager의 관리 범위 밖으로 넘어가는 것이기에 위험할수 있다고 생각했습니다!

그렇기에 저는 PERSIST, MERGE, REMOVE 를 통해 연관된 객체에 있어 추가, 수정, 삭제에 관해서만 영속성 관리를 하도록 
`{CascadeType.PERSIST,CascadeType.MERGE,CascadeType.REMOVE}` 로 필요한 설정만을 해주었습니다.

2024-07-11 14:11 UTC, yunjunghun0116 commented on src/main/java/gift/dto/ProductOptionResponse.java
>      }
ProductResponse를 반환하는 상황과 사용되는 상황에 대해서 다시 한번 고민해보았습니다.

우선 제 생각은 WishProduct, ProductOption 에서는 상품의 모든 정보가 필요하지 않을 수 있다. 예를 들면 상품의 상세 설명, 상품에 대한 이미지 등 모든 정보가 필요하지 않을 수 있다.

하지만 Product에 대한 조회를 수행하는 이용자에게는 모든 정보가 필요할 수 있다. -> ProductResponse는 그 자체로 필요하다.

그러면 WishProduct, ProductOption 과 같은 엔티티에서 필요로 하는 상품의 "기본 정보" 혹은 상품의 "필수 정보", 예를 들면 상품의 이름과 가격, 로직을 수행하는데 필요한 ID 정도가 될 수 있다고 생각했습니다.
그렇기에 상품의 기본 정보만을 담는 `ProductBasicInformation` 이라는 DTO를 담고, 이는 WishProduct, ProductOption 과 같이 상품의 기본정보만을 필요로 하는 ResponseDTO 에 기존 ProductResponse 대신 ProductBasicInformation 을 담아줌으로써 클라이언트에게는 오직 "클라이언트가 필요로 하는 정보" 만을 제공할 수 있도록 DTO를 추가하였습니다.

위 과정을 통해 Product와 ProductResponse의 필드값이 변경되는 경우가 있다 하더라도 기본정보가 변경되지 않는한 WishProductResponse, ProductOptionResponse 에는 영향이 없도록 하여 객체간 영향도도 기존보다 낮게 개선하였습니다.

2024-07-11 14:25 UTC, yunjunghun0116 commented on src/main/java/gift/model/Product.java
> +    private List<WishProduct> wishes = new ArrayList<>();
wishes는 Product에서는 관리할 필요 없습니다!
이유는 논리적 연관관계가 현재는 발생하지 않고, 그로 인해 역방향(Product -> WishProduct) 조회 역시 로직상 발생하지 않기 때문입니다.
그래서 논리적 연관관계가 발생하는 wishes는 Member와 양방향 연관관계를 맺고, wishes는 Member에서만 관리하도록 하였습니다.

productOptions가 조금 더 직관적인 것 같아 네이밍은 변경하였습니다!

2024-07-11 14:28 UTC, yunjunghun0116 commented on src/main/java/gift/model/WishProduct.java
> +    @Column(name = "count")
기존에는 count만을 갖고 연관관계를 맺어주는 add 함수를 통해 만들어 주었는데 현재 로직상, 그리고 논리상 WishProduct는 "누가(Member)", "무엇을(Product)" 에 대한 정보는 수정되지 않을것이라 판단하고 이 부분은 생성자에서 product와 member를 받도록 하였고 두 속성에 대해 `@NotNull` 어노테이션을 붙여주어 서비스, DB 모두 null값에 대한 제약을 걸어주었습니다!

2024-07-11 14:44 UTC, yunjunghun0116 commented on src/main/java/gift/repository/BaseRepository.java
> +}
멘토님 말씀처럼 위 코드로 개발을 하게 될 경우 `어느 상황에서`, `어떤 엔티티가` 예외가 발생했는지에 대해서 추적하기 어려울 것 같습니다.
그래서 저는 기존코드가 오히려 하이리스크 로우리턴 코드가 될 수 있다고 생각하였습니다.
또한 서비스계층에서 같은 findById 로직을 수행하는것처럼 보일 수 있지만 `에러얼럿이 달라질 수 있고, 결국 중복 코드가 아니라 다른 코드다!` 라는 판단을 하고 이 부분은 서비스계층에서 필요한 경우 findById를 수행하도록 하였습니다.

또한 4번 질문처럼 findByIdOrThrow가 모든 레포지토리에서 사용한다고 보장할 수 없습니다. 그럴 경우 오히려 불필요한 상속 구조가 만들어진 것이기에 이 부분도 서비스계층에서 필요한 경우 findById를 수행하도록 하여 개선하였습니다.

2번 질문에 대해서 Optional<엔티티>로 반환하도록 하여 존재하지 않는 객체에 대해서도 Optional.empty()를 반환하도록 하여 존재하지 않는 객체에 대해 명시적으로 처리해주기 위해서 MemberRepository의 findByEmail, WishProductRepository의 findbyProductAndMember 등을 모두 Optional로 반환하도록 하였습니다.

3번 질문에 대해서는 너무 명확하게도, 에러 처리는 서비스 계층에서 하는게 좋다고 생각합니다.
그 이유는 id를 통해 DB에 접근했을때 응답이 존재하지 않더라도, Repository 계층에서는 정상적으로 동작한것이고, Service계층에서 로직상 발생한 에러이기 때문입니다!

2024-07-11 15:37 UTC, yunjunghun0116 commented on src/main/java/gift/service/MemberService.java
> +@Transactional
우선, 트랜잭션은 하나의 메서드 내에서 다양한 Repository에 접근하여 조작하는 과정을 `하나의 논리적 단위` 로 묶어주는 역할을 합니다.
또한 영속성 컨텍스트와 생명주기를 동일시하기에 이미 조회한 정보를 다시 조회하는 경우 영속성 컨텍스트 내부의 `1차 캐시` 에서 꺼내오기에 속도가 빠를 수 있습니다.
그리고 전체 로직중 일부의 로직만 잘못된 경우에 필요한 경우 하나의 프로세스의 원자성을 보장하기 위해 기존 상태로 되돌아가야 하는 기능이 필요할 수 있는데 이러한 경우 트랜잭션의 롤백을 사용해 돌아갈 수 있습니다.

이처럼 하나의 메소드 처리 과정(프로세스) 의 원자성을 보장할 수 있고 영속성 컨텍스트와 결합되어 성능 향상도 기대할수 있다는 장점이 있습니다.

2024-07-11 15:47 UTC, yunjunghun0116 commented on src/main/java/gift/service/ProductOptionService.java
>      }
트랜잭션은 데이터베이스의 상태를 일관성 있게 유지하기 위해서 데이터베이스에 존재하는 데이터에 접근할 때 다른 트랜잭션은 접근하여 조작할 수 없도록 락을 걸게 됩니다.

하지만 ReadOnly는 잠금을 설정하지 않아 다른 트랜잭션들과의 동시성 충돌 가능성이 줄어듭니다.
또한 엔티티의 변경 감지를 위해 메모리상에 스냅샷을 만들지 않아도 되기에 성능 상 이점이 있습니다.
또한 명시적으로 Insert, Update, Delete 가 진행되지 않는다는 것을 알릴 수 있어 가독성이 향상될 수 있습니다.

2024-07-12 09:55 UTC, yunjunghun0116 commented on src/main/java/gift/model/Member.java
> +    private List<WishProduct> wishes = new ArrayList<>();
추가로 로직 복잡도를 개선할 수 있다고 생각하여 우선 다대일 단방향 관계로 설정하여 연관관계를 맺어 주고, 현재는 반대방향으로 탐색하는 기능이 필요로 하지 않기에 ManyToOne만을 사용했습니다.

로직 복잡도에 대한 생각
1. 자식 엔티티를 추가할 경우 부모 엔티티도 조회하여 추가해주는 작업을 수행해야합니다.
2. 자식 엔티티를 삭제할 경우 부모 엔티티를 조회하여 `member.getWishes.remove(this)` 로직도 수행하여 연관관계를 끊어준 후에 삭제를 해야합니다.
와 같은 이유에서 이 부분을 다대일 단방향 관계로 설정하더라도 필요한 경우 자식Repository에서 findAllByProductId 등을 통해 필요한 데이터를 가져올 수 있다고 생각했습니다.

이 경우 부모 객체를 삭제 시 외래키 제약조건에 위배되어 삭제를 할 수 없게 되는데, 이를 해결하기 위해 repository에서 외래키를 바탕으로 삭제하는 deleteWishProductsByMemberId, ProductId 와 같은 메서드를 생성하여 해결했습니다.

2024-07-12 17:56 UTC, asebn1 approved these changes
2단계도 잘 마무리해주셨네요!
고생하셨습니다 👏
2단계는 이만 머지할게요~
3단계도 화이팅!!

2024-07-12 17:56 UTC, merged