강원대 BE_오승규 3주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #145
Opened 2024-07-09 13:53 UTC by 5win

안녕하세요 제이님!
step1 마치고 PR드립니다.

JPA를 아직 이해하지 못한 것 같아 딱히 질문드릴 사항은 없는 거 같아요...
코드는 JPA를 사용하는 DAO를 따로 작성한 뒤에 서비스 계층의 코드를 변경해주었고, JPA를 사용하는 과정에서 Product가 원래 record였으나 class를 사용해야하는 것 같아 변경하였습니다.
그리고 원래는 ManyToOne, OneToMany를 사용하려 했으나 잘 안되는 바람에 `@Query`를 통해 위시리스트를 가져오도록 했습니다.

정말 이해하고 작성한게 많지 않은 것 같아서 JPA 사용의 잘못된 부분, 불필요한 부분 또는 개선할 점을 중점으로 피드백 주시면  감사하겠습니다!

2024-07-10 01:54 UTC, jaymarystella requested changes
안녕하세요 승환님.
1단계 고생많으셨어요.
처음 해본다고하셨는데 잘 해주셨습니다. 피드백 남겨드린부분 위주로 학습해보시면 좋을거같아요

2024-07-10 01:54 UTC, jaymarystella commented on README.md
> +POST /api/members/register
꼼꼼하게 잘 수정해주셨네요!

2024-07-10 01:54 UTC, jaymarystella commented on src/main/java/gift/repository/WishlistJpaDao.java
> +    Optional<Wishlist> findByWishlist(@Param("wish") Wishlist wish);
> JPA를 아직 이해하지 못한 것 같아 딱히 질문드릴 사항은 없는 거 같아요...

처음해보시면 당연히 어렵다고생각합니다.
지금 제가 말씀드리는것보다 조금만 찾아보시면 이 클래스는 전부 개선이 될거같아요. 다른 모든 메서드들도 Query를 사용하지 않고 작성이 가능하니 한번 수정해보셔요.
잘안되면 말씀주시구요.

2024-07-10 01:54 UTC, jaymarystella commented on src/main/java/gift/repository/WishlistJpaDao.java
> +    void deleteByWishlist(@Param("wish") Wishlist wishlist);
이런 애노테이션이 필요한지 어떤역할을 하는지도 찾아보시면 좋을것같습니다. (위에말씀드린것처럼 학습하시면 해결이 될듯합니다)

2024-07-10 01:54 UTC, jaymarystella commented on src/test/java/gift/repository/WishlistJpaDaoTest.java
> +    @DisplayName("위시리스트에 상품 추가 테스트")
displayName까지 꼼꼼하게 잘 작성해주셨네요!

2024-07-10 01:54 UTC, jaymarystella commented on src/test/java/gift/repository/WishlistJpaDaoTest.java
> +//            wishlistJpaDao.findByEmailAndProductId("sgoh", 1L).get();
불필요한 주석은 삭제 부탁드려요

2024-07-10 01:54 UTC, jaymarystella commented on src/main/java/gift/dto/Wishlist.java
> +    }
기본생성자가 왜 필요할까요?

2024-07-10 01:54 UTC, jaymarystella commented on src/main/java/gift/dto/Wishlist.java
> +    private String email;
여기는 column애노테이션이 없네요

2024-07-10 06:19 UTC, 5win commented on src/main/java/gift/repository/WishlistJpaDao.java
> +    Optional<Wishlist> findByWishlist(@Param("wish") Wishlist wish);
> > JPA를 아직 이해하지 못한 것 같아 딱히 질문드릴 사항은 없는 거 같아요...
> 
> 처음해보시면 당연히 어렵다고생각합니다. 지금 제가 말씀드리는것보다 조금만 찾아보시면 이 클래스는 전부 개선이 될거같아요. 다른 모든 메서드들도 Query를 사용하지 않고 작성이 가능하니 한번 수정해보셔요. 잘안되면 말씀주시구요.

이렇게 메서드 이름으로 쿼리를 생성하는 방식으로는 Wishlist 객체를 전달하여 사용할 수 없는 것 같아서 객체 대신 email, productId를 직접 넘겨주도록 바꿔보았습니다.
원래 이 방식으로 했었다가 Wishlist 객체를 DTO로 활용하자는 생각에 객체로 넘기고  `@Query` 를 사용하도록 했었습니다.

메서드 이름으로 쿼리를 생성하는 방식으로는 객체를 넘길 수 없는게 맞다면,
DTO 대신 이렇게 값들을 넘겨주고 쿼리부분 코드를 간결하게 가는 것이 나을까요? 아니면 DTO로 넘겨서 서비스 쪽을 간결하게 하고 쿼리 부분을 상대적으로 복잡하게 하는 것이 나을까요?

그리고 위시리스트를 가져오는 join이 필요한 쿼리는 잘 모르겠어서 수정하지 못했습니다..

2024-07-10 06:27 UTC, 5win commented on src/main/java/gift/repository/WishlistJpaDao.java
> +    void deleteByWishlist(@Param("wish") Wishlist wishlist);
> 이런 애노테이션이 필요한지 어떤역할을 하는지도 찾아보시면 좋을것같습니다. (위에말씀드린것처럼 학습하시면 해결이 될듯합니다)

어제 이부분 때문에 오류가 발하여 디버깅하면서 살짝 찾아보긴 했는데
`@Transactional` 은 Dirty checking을 통해 변경사항을 적용하는 부분에서 사용되는 것으로 이해했는데 이것 말고도 기능이 많더라고요.. 좀 더 자세히 알아봐야 할 것 같습니다.
`@Modifying` 도 마찬가지로 영속성 컨텍스트와 관련있는 것 같은데 아직 잘 이해가 안돼서 공부해보겠습니다 :(

2024-07-10 06:51 UTC, 5win commented on src/main/java/gift/dto/Wishlist.java
> +    }
> 기본생성자가 왜 필요할까요?

Java Reflection과 관련이 있다고 들었습니다.
객체에 대한 인스턴화를 컴파일 타임이 아닌 런타임에 수행하며 접근할 수 있게 해주는 API라고 하는데
reflection이 객체를 생성할 때 기본 생성자를 사용하기 때문인 것 같습니다.
JPA가 쿼리로 조회해 온 데이터를 reflection을 생성하기 때문에 필요한 것 같습니다.

p.s.
2주차 때 말씀해주셨던 아래 리뷰에서도 저는 MockMvc를 사용하는 과정에서 발생하는 줄 알았는데
`@RequestBody` 를 통해 객체에 바인딩할 때도 reflection을 사용하기 때문에 기본 생성자가 필요하더라고요.
Product는 record를 썼어서 몰랐는데, record는 기본 생성자를 컴파일러가 자동으로 생성해주기 때문에 운좋게?도 바로 바인딩이 가능했지만, Member는 클래스로 선언하였기 때문에 바인딩되지 않았던 것 같네요.

https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/pull/372#discussion_r1668739049

2024-07-10 06:52 UTC, 5win commented on src/main/java/gift/dto/Wishlist.java
> +    private String email;
> 여기는 column애노테이션이 없네요

반영하여 추가적으로 애노테이션 달아주었습니다!

2024-07-12 02:01 UTC, jaymarystella commented on src/main/java/gift/repository/WishlistJpaDao.java
> +    Optional<Wishlist> findByWishlist(@Param("wish") Wishlist wish);
음 파라미터를 각각 넘기시면 될거같은데요, 다음스텝에서 한번 수정시도해보시면 될거같습니다.

2024-07-12 02:02 UTC, jaymarystella commented on src/main/java/gift/repository/WishlistJpaDao.java
> +    void deleteByWishlist(@Param("wish") Wishlist wishlist);
넵 지금 꼭 안하셔도되니 필요할때 붙여보시면 될거같아요.

2024-07-12 02:02 UTC, jaymarystella approved these changes
안녕하세요 승규님.
리뷰 반영하느라 고생많으셨습니다. 다음 단계 진행 해주시면 될거같아요.

2024-07-12 02:02 UTC, merged