충남대 BE_정현서 3주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #153
Opened 2024-07-09 15:03 UTC by hynseoj

2024-07-09 15:13 UTC, ksy90101 requested changes
고생많으셨습니다~
테스트코드까지 짱짱이네요!
간단한 피드백남겼으니 한번 확인해주세요~

2024-07-09 15:13 UTC, ksy90101 commented on src/main/java/gift/domain/product/controller/ProductRestController.java
> +        product.setImageUrl(productDto.imageUrl());
setter를 사용하기 보단 update라는 메서드를 만들어서 행위로 변경해보면 어떨까요?

2024-07-09 15:13 UTC, ksy90101 commented on src/main/java/gift/domain/product/entity/Product.java
>      private String imageUrl;
image url의 글자수를 고민해보신적이 있을까요?
지금은 제약조건으로 몇글자까지 되어있을까요!?
default값이있겟죠!?

2024-07-09 15:13 UTC, ksy90101 commented on src/main/java/gift/domain/user/entity/User.java
> +    @Enumerated(value = EnumType.STRING)
👍

2024-07-09 15:13 UTC, ksy90101 commented on src/main/java/gift/domain/wishlist/dao/WishlistJpaRepository.java
> +    List<WishItem> findAllByUser_id(Long userId);
```suggestion
    List<WishItem> findAllByUserId(Long userId);
```
메서드명은 카멜케이스여야 합니다.

2024-07-09 15:13 UTC, ksy90101 commented on src/main/java/gift/domain/wishlist/entity/WishItem.java
> +)
👍

2024-07-09 15:13 UTC, ksy90101 commented on src/main/java/gift/domain/wishlist/entity/WishItem.java
>      Product product;
해당 부분은 2단계 미션입니다.
한번 일단 id로 해보면 어떨까요?
비교해보고 어떤 이점이 있고 어떤게 좋은지 서로 써보면 좋겠거든요~

2024-07-09 15:13 UTC, ksy90101 commented on src/test/java/gift/domain/product/controller/ProductRestControllerTest.java
> +        given(productJpaRepository.save(any(Product.class))).willReturn(product);
컨트롤러 테스트를 단위테스트로 하고 싶으신거 같은데
그렇다면 Service를 mocking해야하지 않을까요?

2024-07-10 01:05 UTC, hynseoj commented on src/main/java/gift/domain/product/controller/ProductRestController.java
> +        product.setImageUrl(productDto.imageUrl());
네! 그렇게 수정해보겠습니다.

2024-07-10 01:09 UTC, hynseoj commented on src/main/java/gift/domain/product/entity/Product.java
>      private String imageUrl;
네 default값이 255자라고 알고 있습니다. DB schema에서 설정한 글자수와 같아 별도로 명시하지 않았습니다.

2024-07-10 01:26 UTC, hynseoj commented on src/main/java/gift/domain/wishlist/dao/WishlistJpaRepository.java
> +    List<WishItem> findAllByUser_id(Long userId);
JPA의 외래키 조회 메서드를 사용하려고 했는데 findAllByUserId 방식이 잘 동작하지 않아 저렇게 작성했습니다.
그런데 찾아보니 JPA의 외래키 조회 방식이 불필요한 조인을 발생시킨다고 하여 JPQL을 사용하는 방식으로 수정해보려고 합니다. 메서드 이름도 변경하겠습니다!

2024-07-10 01:30 UTC, hynseoj commented on src/main/java/gift/domain/wishlist/entity/WishItem.java
>      Product product;
아하 다음 단계 내용을 확인을 못하고 진행했습니다. 수정하겠습니다!

2024-07-10 01:31 UTC, hynseoj commented on src/test/java/gift/domain/product/controller/ProductRestControllerTest.java
> +        given(productJpaRepository.save(any(Product.class))).willReturn(product);
맞습니다. 상품 도메인은 지금 1주차에 진행했던 구조 그대로라 Service 없이 바로 Controller와 DAO가 연결되는 형태였습니다. Service 계층 만들고 테스트 코드도 변경하겠습니다!

2024-07-10 07:45 UTC, ksy90101 commented on src/main/java/gift/domain/product/entity/Product.java
>      private String imageUrl;
url이 255자면 충분하겟죠?
(정책적인 부분에 고민해보라는 이야기였어요!)

2024-07-10 07:48 UTC, ksy90101 approved these changes
고생하셨습니다~
테스트 코드까지 잘. 작성해주셨네요!
이미 선행학습하셔서 ㅎㅎ 2단계는 금방 하시겠네요..!!
1주차, 2주차 선택미션도 시간나실떄 한번 해보셔도 좋을거 같습니다!
(당연히 필수 미션이 더 먼저이긴 합니다~)
홧팅입니다!

2024-07-10 07:48 UTC, merged