경북대 BE_우현서_3주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #167
Opened 2024-07-09 16:44 UTC by wndlthsk

안녕하세요 멘토님!

jpa로 변경 후 실행했을 때 잘 실행되다가 갑자기 data.sql의 쿼리문에서 계속 오류가 발생하였습니다. h2-console로 같은 쿼리문을 실행했을 때 오류 없이 잘 돼서 해결 방법을 찾다가 결국 data.sql과 schema.sql을 삭제하고 제출하려했는데, 로컬에서 브랜치 변경해야했어서 변경 후 다시 실행하니 잘 돌아갑니다 ..! 인텔리제이의 문제였던 걸까요,..ㅜ

2024-07-10 15:06 UTC, leaf-upper requested changes
안녕하세요 현서님 1단계 코드 잘 작성해주셨네요~
계속해서 코드가 발전해나가는게 보입니다.
Controller에서 Repository로 바로 접근하는 코드가 몇개 보이는데요~
Service 코드도 작성해뒀으니, Service를 통해서 접근해보는건 어떨까요?
요 부분만 검토부탁드려요!
고생하셨습니다~ 👍

2024-07-10 15:06 UTC, leaf-upper commented on src/main/java/gift/config/WebConfig.java
> +            .excludePathPatterns("/login", "/register","/admin/products", "/admin/products/**", "/members", "/members/*");
* 한개와 ** 두개의 차이는 뭘까요?
members path에는 * 한개로 충분할까요?

2024-07-10 15:06 UTC, leaf-upper commented on src/main/java/gift/controller/WishController.java
> +        ProductRepository productRepository, MemberRepository memberRepository) {
Repository를 Controller에서 직접 사용해도 좋고, 큰 문제는 없지만
되도록이면 계층간 분리를 위해서, Service 객체를 만들고 이를 통해서 Repository에 접근 및 사용하는것도 좋아보여요.

2024-07-10 15:12 UTC, leaf-upper commented
jpa로 변경 후 실행했을 때 잘 실행되다가 갑자기 data.sql의 쿼리문에서 계속 오류가 발생하였습니다. h2-console로 같은 쿼리문을 실행했을 때 오류 없이 잘 돼서 해결 방법을 찾다가 결국 data.sql과 schema.sql을 삭제하고 제출하려했는데, 로컬에서 브랜치 변경해야했어서 변경 후 다시 실행하니 잘 돌아갑니다 ..! 인텔리제이의 문제였던 걸까요,..ㅜ

-> 이 오류는 어떤 오류였을까요? 쿼리 Syntax 오류였을까요? 좀더 오류에 대한 상황을 알려주시면 어떤 문제였을지 생각해볼 수 있을것 같아요!

테스트 코드 작성을 잊어서 마지막에 추가하였습니다!
member의 이메일, 비밀번호 일치 여부에 대한 로그인 실패와 
성공에 대한 테스트도 RepositoryTest에서 진행해도 되는지 헷갈립니다..!

-> DataJpaTest는 JPA와 관련된 설정들만 스프링에서 사용할수 있게해주는 애너테이션이에요
이메일, 비밀번호 일치 여부는 좀더 비즈니스로직인만큼 DataJpaTest로 테스트해보이기엔 적합해보이진 않네요 ㅠ
다만 작성해주신코드는 MemberRepositoryTest에 대해 DataJpaTest가 아니라 SpringBootTest 애너테이션을 사용해주셔서 
문제는 없어 보여요. 다만 이름이 헷갈릴 수 있으니 MemberServiceTest 혹은 MemberIntegrationTest와 같은 이름도 좋을것 같아요~

2024-07-11 06:00 UTC, wndlthsk commented on src/main/java/gift/config/WebConfig.java
> +            .excludePathPatterns("/login", "/register","/admin/products", "/admin/products/**", "/members", "/members/*");
@leaf-upper **는 모든 하위 경로를 의미합니다. member path는 현재는 members/login, members/register 가 끝이라 한개로 충분하다고 판단하였습니다!

2024-07-11 13:04 UTC, leaf-upper approved these changes
👍  고생하셨습니다
2단계 진행 부탁드릴게요~!

2024-07-11 13:04 UTC, merged