전남대 BE_김보민_3주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #170
Opened 2024-07-09 17:29 UTC by KBM05haruin30

# 1단계
### 코드 작성하면서 어려웠던 점
Repository를 JPA로 구현할 때 기본적으로 제공해주는 메소드 외의 만들었던 메소드의 기능을 구현하는 것이 헷갈려 찾아보고 했습니다. 모든 메소드를 자동으로 만들어주는 줄 알았지만 필요에 의하면 커스텀 메소드를 따로 만들어야 한다는 것을 알게 되었습니다.
Repository에 대한 테스트 코드 구현이 어려웠습니다. 모든 RepositoryTest 코드에 Repository를 주입시킬 때 생성자 주입으로 작성했습니다. 그랬더니 코드가 실행이 되지 않았고 @Autowired를 사용해 주입을 하니 코드가 실행되었습니다. 왜 이렇게 실행되는지 궁금합니다.
WishlistRepositoryTest 같은 경우 application.properties에`spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect`을 추가하면 에러가 발생하는 것을 확인할 수 있었다. 하지만 위의 코드를 지우면 ProductRepositoryTest, UserRepositoryTest가 되지 않는 것을 확인할 수 있었다.
해결 방법으로는 WishlistRepositoryTest의 @DataJpaTest위에 `@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)`을 추가해주면 된다고 찾아서 해결했습니다. 왜 이렇게 되는지 궁금합니다.

### 중점적으로 봐주셨으면 하는 점
JPA를 처음 사용하다 보니 코드들이 잘 짜여졌는지 봐주셨으면 합니다. 추가로 `spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect`을 사용할 때 WishlistRepositoryTest는 안되고 ProductRepositoryTest와 UserRepositoryTest는 되는지 잘 모르겠습니다. 
WishlistService.java를 보시면 마지막의 removeWishlist메서드에 @Transactional을 붙였습니다. 이걸 붙이지 않으면 실행이 되지 않던데 왜 그런지 궁금합니다. 찾아보니 JpaRepository의 실제 구현체인 SimpleJpaRepositor를 보면 save와 delete관련 로직에는 트랜잭션이 붙어 있어 실제 구현체에서 제공하는 save, delete 메서드가 아니라면 트랜잭션을 붙여주어야 한다고 합니다. 왜 트랜잭션을 붙여야 하는 건지 궁금합니다.

2024-07-11 16:57 UTC, Hongdonggeon requested changes
안녕하세요 보민님! 
미션 구현하시느라 수고 많으셨습니다! 
일단 1차적으로 코드에 대해 코멘트들 드렸고요! 
오늘 시간이 늦어서.. 질문 주신거랑 내일 리뷰 더 드릴게요 
화이팅입니다!

2024-07-11 16:57 UTC, Hongdonggeon commented on src/main/java/gift/controller/ProductController.java
> +        return productRepository.findById(id).orElse(null);
repository 계층과 Controller 계층 사이에 Service 계층을 만들어줘볼까요? 
repository 메서드를 호출해서, 존재하지 않으면 null을 반환하던 예외를 던지던 이런 로직은 컨트롤러 계층보다 서비스 계층이 잘 어울린다고 생각해요
이 패턴을 레이어드 아키텍처 패턴이라고 하는데 한번 학습해보면 좋을 것 같아요

2024-07-11 16:57 UTC, Hongdonggeon commented on src/main/java/gift/annotation/LoginMember.java
> +public @interface LoginMember {
전체적으로 User -> Member로 변경한 이유가 뭘까요?

2024-07-11 16:57 UTC, Hongdonggeon commented on src/main/java/gift/model/Member.java
> +@Table(name = "member")
아 user라는 db 예약어가 있기 때문에 member로 변경했나보네요
지금은 코드양이 많지 않아서 전체적으로 변경할 수 있었는데, 코드양이 너무 많았더라도 전체적으로 변경하셨을까요? 그런 상황에선 어떻게 하셨을 것 같아요?

2024-07-11 16:57 UTC, Hongdonggeon commented on src/main/java/gift/model/Member.java
> +    @NotBlank(message = "이름을 입력하세요.")
엔티티에서는 이런 어노테이션을 사용하는것보다 순수 로직으로 검증하는게 더 좋다고 생각해요

2024-07-11 16:57 UTC, Hongdonggeon commented on src/main/java/gift/model/Member.java
> +    @NotBlank(message = "이름을 입력하세요.")
이유도 한번 찾아보면 좋을 것 같아요

2024-07-11 16:57 UTC, Hongdonggeon commented on src/test/java/gift/repository/MemberRepositoryTest.java
> +    public MemberRepositoryTest(MemberRepository memberRepository) {
생성자 주입을 사용하셨는데 `@Autowired` 선언을 해야하나요?

2024-07-11 16:57 UTC, Hongdonggeon commented on src/main/java/gift/model/Member.java
> +    }
setId 메서드를 선언해둬서 실수로 호출해서 id 가 변경될 수도 있을 것 같은데요. 이 메서드를 선언한 이유가 궁금합니다

2024-07-11 16:57 UTC, Hongdonggeon commented on src/main/java/gift/model/Member.java
> +    }
다른 필드들도요

2024-07-11 16:57 UTC, Hongdonggeon commented on src/main/java/gift/model/Member.java
> +    }
기본 생성자 접근 지정자를 protected로 변경한 이유가 뭘까요?

2024-07-11 16:57 UTC, Hongdonggeon commented on src/main/java/gift/model/Member.java
> +            '}';
현재 엔티티에서 view의 역할까지 해주고 있는 것 같은데요. 
보여주어야 하는 형식이 변경된다면 엔티티까지 변경되어야 할 것 같은데요
뷰의 변경 영향이 엔티티까지 미치지 않게 끊어내볼까요

2024-07-11 16:57 UTC, Hongdonggeon commented on src/main/java/gift/model/Product.java
> +public class Product {
여기 엔티티도 Member와 동일한 코멘트입니다 
- set 메서드
- 어노테이션 검증 
- toString
같이 고민해봐주세요

2024-07-11 16:57 UTC, Hongdonggeon commented on src/main/java/gift/model/Wishlist.java
> +@Table(name = "wish")
테이블 이름을 wish로만 한 이유가 뭘까요?

2024-07-11 16:57 UTC, Hongdonggeon commented on src/main/java/gift/model/Wishlist.java
> +    private String memberEmail;
컬럼 이름을 member_id라고 한 이유가 뭘까요?

2024-07-11 16:57 UTC, Hongdonggeon commented on src/main/java/gift/service/WishlistService.java
>      }
이곳에만 `@Transactional`을 선언한 이유가 뭘까요? 
트랜잭션이란 개념은 정말 중요한데요! 한번 제대로 학습해보는게 좋을 것 같습니다

2024-07-11 16:57 UTC, Hongdonggeon commented on src/test/java/gift/repository/ProductRepositoryTest.java
> +    }
정상 케이스 말고 예외 발생하는 케이스에 대해서도 테스트코드 작성해주는게 좋을 것 같아요

2024-07-11 16:57 UTC, Hongdonggeon commented on src/test/java/gift/repository/WishlistRepositoryTest.java
> +@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
이 옵션을 추가한 이유가 뭘까요?

2024-07-11 16:57 UTC, Hongdonggeon commented on src/test/java/gift/repository/WishlistRepositoryTest.java
> +        wishlistRepository.save(wishlist);
항상 테스트하기 위해 저장하고 있는데 `@BeforeEach`를 이용해봐도 좋을 것 같아요

2024-07-11 22:41 UTC, KBM05haruin30 commented on src/main/java/gift/model/Member.java
> +@Table(name = "member")
db예약어로 user가 있기 때문에 아마 user가 아닌 users와 같이 예약어는 피하되 의미는 전달될 수 있도록 했을 것 같습니다!

2024-07-11 22:57 UTC, KBM05haruin30 commented on src/main/java/gift/model/Wishlist.java
> +@Table(name = "wish")
과제의 기능 요구 사항에 테이블 이름이 wish여서 wish로 작성했습니다. 하지만 제가 작성한 코드와 일관성 있게 보이려면 wishlist로 바꾸는 것이 좋다고 생각이 들어 wishlist로 현재 변경하였습니다. 추가로 scehma,sql의 내용도 수정하였습니다!

2024-07-11 23:01 UTC, KBM05haruin30 commented on src/main/java/gift/model/Wishlist.java
> +    private String memberEmail;
이것도 위의 답변과 마찬가지로 과제의 기능 요구 사항을 비슷하게 하려다가 이름을 이렇게 설정했습니다. 하지만 id가 아닌 email을 사용하므로 컬럼 이름을 member_email로 설정하는 것이 더 바람직해 보입니다. 추가로 schema.sql의 내용도 함께 수정하였습니다!

2024-07-11 23:10 UTC, KBM05haruin30 commented on src/main/java/gift/model/Member.java
> +    }
일반 클래스로 변경하면서 습관적으로 인텔리제이의 generate 기능을 이용하여 setter와 getter를 함께 만들었습니다. 멘토님 말씀처럼 setter를 선언해두면 실수로 변경될 수 있기도 하고 사용하지 않으므로 지우는게 맞는 것 같습니다!

2024-07-11 23:10 UTC, KBM05haruin30 commented on src/main/java/gift/model/Member.java
> +    }
Member, Product, Wishlist의 setter를 삭제했습니다!

2024-07-11 23:13 UTC, KBM05haruin30 commented on src/main/java/gift/model/Member.java
> +    }
public으로 선언되면 외부에서 의도치 않게 호출되어 생성될 가능성이 있으므로 protected로 하였습니다!

2024-07-11 23:17 UTC, KBM05haruin30 commented on src/main/java/gift/model/Member.java
> +            '}';
넵! record 클래스에서 일반 클래스로 변경하게 되면서 setter/getter와 toString을 사용했습니다. toString을 지워줌으로써 끊어낼 수 있다고 생각합니다!

2024-07-11 23:35 UTC, KBM05haruin30 commented on src/test/java/gift/repository/WishlistRepositoryTest.java
> +@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
```
spring.datasource.url=jdbc:h2:mem:test;MODE=MYSQL;DB_CLOSE_DELAY=-1
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
```

현재 제가 application.properties에 추가한 내용입니다. 
검색해서 찾아보니 추가한 코드는 h2 데이터베이스를 인메모리에서 동작하는 MySQL 모드로 설정하는 것이고 dialect 설정을 통해 SQL 구문도 MySQL 구문으로 생성되도록 하는 것입니다. 이렇게 하면 SQL은 MySQL 구문으로 생성되지만 테스트 데이터베이스는 설정한 데이터소스가 아닌 테스트 데이터 환경으로 교체되어 SQL구문을 정상적으로 실행시킬 수 없어 테이블이 정상적으로 생성되지 않습니다. 이 문제를 해결하기 위해 `dialect.MySQLDialect`를 `dialect.H2Dialect`로 변경하거나 `@AutoConfigureTestDatabase 설정을 replace.ANY에서 replace.NONE으로 수정하면 해결이 가능하다고 하여 사용했습니다!

2024-07-11 23:35 UTC, KBM05haruin30 commented on src/test/java/gift/repository/WishlistRepositoryTest.java
> +@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
추가한 이유는 과제에 있어서 사용했었습니다!

2024-07-12 00:01 UTC, KBM05haruin30 commented on src/test/java/gift/repository/WishlistRepositoryTest.java
> +        wishlistRepository.save(wishlist);
넵! 알겠습니다!

2024-07-12 00:04 UTC, KBM05haruin30 commented on src/test/java/gift/repository/WishlistRepositoryTest.java
> +        wishlistRepository.save(wishlist);
WishlistRepositoryTest뿐만 아니라 MemberRepositoryTest, ProductRespotiroyTest에도 @BeforeEach를 사용해 보았습니다!

2024-07-12 00:37 UTC, KBM05haruin30 commented on src/test/java/gift/repository/ProductRepositoryTest.java
> +    }
넵! 알겠습니다! ProductRepositoryTest와 MemberRepositoryTest에 예외 발생하는 케이스에 대해서도 테스트 코드를 작성했습니다!

2024-07-12 00:41 UTC, KBM05haruin30 commented on src/test/java/gift/repository/ProductRepositoryTest.java
> +    }
예외 발생하는 케이스에 대한 테스트 코드는 @BeforeEach를 통해 작성하면 코드가 많이 길어지게 될 것 같아 사용하지 않았습니다. 코드가 길어지더라도 @BeforeEach에 작성하는 게 맞는지 궁금합니다.

2024-07-12 01:16 UTC, KBM05haruin30 commented on src/test/java/gift/repository/MemberRepositoryTest.java
> +    public MemberRepositoryTest(MemberRepository memberRepository) {
```
org.junit.jupiter.api.extension.ParameterResolutionException: No ParameterResolver registered for parameter [gift.repository.MemberRepository memberRepository] in constructor [public gift.repository.MemberRepositoryTest(gift.repository.MemberRepository)].
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```
@Autowired를 제거하면 다음과 같은 에러가 발생합니다. 이와 관련해서 검색을 해보면 테스트 코드에서는 Spring 컨테이너가 아니라 JUnit5의 Jupiter가 의존성 주입을 담당하는데 테스트 코드에서 @Autowired가 생략되어 있다면 Jupiter가 객체를 탐색하지 못해 발생하는 에러라고 합니다. 그래서 선언을 해주었습니다.

2024-07-12 01:29 UTC, KBM05haruin30 commented on src/main/java/gift/controller/ProductController.java
> +        return productRepository.findById(id).orElse(null);
넵! 알겠습니다!

2024-07-12 01:59 UTC, KBM05haruin30 commented on src/main/java/gift/model/Member.java
> +    @NotBlank(message = "이름을 입력하세요.")
넵 알겠습니다!

2024-07-12 02:33 UTC, KBM05haruin30 commented on src/main/java/gift/model/Member.java
> +    @NotBlank(message = "이름을 입력하세요.")
순수 로직으로 검증하면 복잡하고 다양한 검증 로직을 구현할 수 있고 데이터 모델과 비즈니스 로직을 명확히 분리할 수 있다는 장점이 있고 어노테이션보다 단위 테스트가 더 쉽다는 장점도 있다는 것을 알게 되었습니다!

2024-07-12 02:36 UTC, KBM05haruin30 commented on src/test/java/gift/repository/ProductRepositoryTest.java
> +    }
어노테이션 검증에서 순수 로직 검증으로 변경하면서 ConstraintViolationException 대신 IllegalArgumentException을 사용하도록 변경하였습니다.

2024-07-12 02:44 UTC, KBM05haruin30 commented on src/main/java/gift/service/WishlistService.java
>      }
트랜잭션은 데이터베이스의 상태를 일관되게 유지하고 데이터 무결성을 보장하기 위해 사용하는 논리적 작업 단위입니다. 트랜잭션 ACID라는 4가지 주요 특성을 가집니다.
1. Atomicity(원자성)
- 트랜잭션의 모든 작업이 모두 성공하거나 모두 실패하는 것을 보장합니다. 트랜잭션 중 일부 작업이 실패하면 전체 트랜잭션은 롤백됩니다.
2. Consistency(일관성)
- 트랜잭션이 완료되면 데이터베이스는 항상 일관된 상태를 유지해야 합니다
3. Isolation(고립성)
- 트랜잭션이 실행되는 동안 다른 트랜잭션이 접근하지 못하도록 보장합니다.
4. Durability(내구성)
- 트랜잭션이 성공적으로 완료되면 그 결과가 영구적으로 데이터베이스에 저장됩니다. 시스템이 고장 나더라도 트랜잭션의 결과는 보존됩니다.

@Transactional 어노테이션은 메서드 또는 클래스에 적용하여 트랜잭션 범위를 지정합니다. @Transactional이 적용된 메서드가 호출될 때 트랜잭션이 시작되고, 메서드가 정상적으로 완료되면 트랜잭션이 커밋되지만 예외가 발생하면 트랜잭션은 롤백됩니다.

2024-07-12 02:46 UTC, KBM05haruin30 commented on src/main/java/gift/service/WishlistService.java
>      }
`@Transactional`을 사용한 이유는 데이터베이스의 상태를 안전하게 유지하기 위해서입니다.

2024-07-12 02:49 UTC, KBM05haruin30 commented on src/main/java/gift/service/WishlistService.java
>      }
처음에는 삭제가 안되어서 검색으로 단순히 삭제하기 위해서는  `@Transactional`을 사용해야 된다는 것을 알게 되었습니다. 다시 트랜잭션에 대해 학습해보니 데이터베이스의 일관성을 유지하기 위해 필요한 모든 메서드에 적용하 수 있다는 것을 알게 되었습니다. removeWishlist뿐만 아니라 addWishlist에도 적용할 수 있다는 것을 알 수 있었습니다.

2024-07-12 02:51 UTC, KBM05haruin30 commented on src/main/java/gift/service/WishlistService.java
>      }
추가로 WishlistService뿐만 아니라 MemberService, ProductService에도 `@Transactional`을 추가해주었습니다!

2024-07-13 15:28 UTC, Hongdonggeon approved these changes
보민님 리뷰 반영하시느라 수고많으셨습니다
아직 더 수정해야될 부분들이 보이네요 
코멘트 남겨놓았으니까 반영해주세요 
일단 1단계는 머지할게요! 수고하셨습니다!

2024-07-13 15:28 UTC, Hongdonggeon commented on src/main/java/gift/model/Member.java
> +    }
private으로 해도되지 않나요?

2024-07-13 15:28 UTC, Hongdonggeon commented on src/main/java/gift/model/Member.java
> +    }
메서드를 분리하는게 좋지 않을까요? 
검증할게 많아지면 한 메서드에서 너무 많이 검증을 해야할 것 같은데요

2024-07-13 15:28 UTC, Hongdonggeon commented on src/main/java/gift/model/Member.java
> +@Table(name = "member")
정답은 없으니 다양한 방법에 대해 생각해보세요~

2024-07-13 15:28 UTC, Hongdonggeon commented on src/main/java/gift/service/WishlistService.java
>      }
조회 쿼리에는 `@Transactional` 을 붙이지 않아도 될까요 
readOnly 옵션에 대해서도 학습해보시면 좋을 것 같아요

2024-07-13 15:28 UTC, Hongdonggeon commented on src/test/java/gift/repository/MemberRepositoryTest.java
> +    public MemberRepositoryTest(MemberRepository memberRepository) {
그렇다면 생성자는 제거해주어도 되지 않나요?

2024-07-13 15:28 UTC, Hongdonggeon commented on src/test/java/gift/repository/ProductRepositoryTest.java
> +    }
`@beforeEach` 가 오히려 반복되는 코드를 줄여주지 않나요? 오히려 코드가 더 짧아질 것 같아요

2024-07-13 15:28 UTC, merged