경북대 BE_장우석 3주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #172
Opened 2024-07-09 18:02 UTC by us4c0d3

step0 merge 되기 전부터 작업을 시작하여 충돌된 부분 merge commit이 있습니다.

## 1단계 적용점
* 2주차 코드 리뷰로 남겨주신 점을 최대한 적용했습니다.
    * 다만 CQS부분은 Repository에서 Dto를 반환하는 등 개발했던 Repository 구조 자체에 문제가 있던 Wish 모듈만 수정했습니다.
    * 추후 다른 모듈도 CQS를 적용하도록 하겠습니다.
    * 아직 jjwt에 대한 이해가 부족해 적용하지 못했습니다.
* builder 패턴을 적용했습니다.
    * 코드의 가독성과 적용 필드가 일정하지 않는 경우를 고려하여 Entity에 Builder 패턴을 적용하였습니다.
    * 특히, JPA에서 Entity의 경우 특성상 가변 객체를 활용하기 때문에 record 객체에서 class 객체로 바꾸며 Builder패턴을 사용했습니다.
    
---

## 질문점
* 대부분은 활용 및 익숙해짐의 문제라고 생각해 JPA 자체에 대한 질문점은 아직까지는 크게 없습니다.
* 테스트에 관한 질문이 몇 가지 있습니다.
    * controller의 기능, service의 기능, repository의 기능 등 기능을 단위로 나눠 단위 테스트로 진행해야함이 중요하다고 알고있습니다.
    * controller 테스트의 경우 라이브 강의 시간에 다뤘던 `@SpringBootTest`를 이용하면 되는 것 같습니다
    * 그러나 service 테스트와 repository 테스트는 어떤 방식으로 진행하면 좋을지 모르겠습니다.
    * 그 이유는 DB 데이터 때문인데 service와 repository는 결론적으로 db의 데이터에 접근한 결과에 대해 테스트 합니다.
    * 이 때, 테스트를 위한 데이터는 어떤 식으로 하는지 궁금합니다.
    * 또한 각 객체의 단위 테스트를 진행하려면 각 클래스간의 연결을 끊어줄 필요가 있다고 생각되는데, controller, service, repository 간 어떻게 분리되어 단위테스트가 진행되는지 궁금합니다.

2024-07-10 17:51 UTC, sang5c requested changes
요구사항을 만족하지 못해 request change를 드려요!  
```
@DataJpaTest를 사용하여 학습 테스트를 해 본다.
```

다른 리뷰에 대해서는 2단계에서 수정 진행하시고, 테스트를 작성해주세요.  

요구사항이 만족되지 않고, 질문이 목표를 벗어낫기에 따로 답변을 드리지 않습니다.  
요구사항을 모두 만족하신 다음 고민해보시면 어떨까요?

2024-07-10 17:51 UTC, sang5c commented on src/main/java/gift/entity/Wish.java
> +    protected Wish() {}
해당 클래스가 다음 컨벤션을 만족하는지 확인해주세요.
https://www.oracle.com/java/technologies/javase/codeconventions-fileorganization.html#1852

2024-07-10 17:51 UTC, sang5c commented on src/main/java/gift/entity/Wish.java
> +@Table(name = "wishes")
엔티티 이름과 테이블 이름을 다르게 가져가는 이유가 있을까요?

2024-07-10 17:51 UTC, sang5c commented on src/main/java/gift/entity/Product.java
> +    private String name;
요구사항을 만족하지 못했어요!
```
    name      varchar(15)  not null,
```

2024-07-10 17:51 UTC, sang5c commented on src/main/java/gift/service/UserService.java
> +        if(user.isPresent()) {
정렬 🥲

2024-07-10 17:51 UTC, sang5c commented on src/main/java/gift/service/UserService.java
>          }
이렇게도 표현 가능해요
```java
        userRepository.findByEmail(request.email())
                .ifPresent(user -> {
                    throw new UserAlreadyExistException("이미 존재하는 Email입니다.");
                });
```

2024-07-10 17:51 UTC, sang5c commented on src/main/java/gift/service/ProductService.java
> +        return productRepository.findById(id).get();
Optional.get()은 NPE가 발생할 수 있어요. orElseThrow()를 고려해주세요.

2024-07-10 17:51 UTC, sang5c commented on src/main/java/gift/service/ProductService.java
> +            .collect(Collectors.toList());
```suggestion
            .toList();
```

2024-07-10 17:51 UTC, sang5c commented on src/main/java/gift/entity/Product.java
> +    public static class Builder {
이 빌더는 어떤 장점을 주고 어떤 단점을 주는가, 꼭 필요한가? 를 고민해보면 좋겠네요.

2024-07-10 17:51 UTC, sang5c commented on src/main/java/gift/service/WishService.java
> +            wish.setQuantity(request.quantity());
`위시의 수량을 변경한다` 는 set보다는 change가 더 잘어울린다고 생각해요.

2024-07-10 17:51 UTC, sang5c commented on src/main/java/gift/service/WishService.java
> +        if (wish.getQuantity() <= 0) {
get으로 꺼내서 값을 확인하기보다, wish에게 역할을 위임해보면 어떨까요?
```suggestion
        if (wish.isQuantityZero()) {
```
`규칙 9: getter/setter/프로퍼티를 쓰지 않는다.`

2024-07-10 17:51 UTC, sang5c commented on src/main/java/gift/util/mapper/ProductMapper.java
> +        product.setImageUrl(request.imageUrl());
product의 이름, 가격, 이미지를 변경한다는 의미의 메서드를 만들면 어떨까요?
`규칙 9: getter/setter/프로퍼티를 쓰지 않는다.`

2024-07-10 17:51 UTC, sang5c commented on src/main/java/gift/config/WebConfig.java
> +    }
어떤 이유로 빈으로 직접 등록하고 있나요?  
빈으로 직접 등록하는 것과 `@Component`로 등록하는 것은 어떤 차이가 있을까요?

2024-07-10 17:53 UTC, sang5c commented
PR을 올리신 후에 추가 수정을 진행하는 방식은 지양해주세요.

2024-07-10 18:23 UTC, us4c0d3 commented
혼란을 주어 죄송합니다! 그렇다면 PR을 올린 이후에 코드리뷰를 기다리며 개발을 지속할 때는 브랜치를 추가하여 rebase 형식으로 맞추면 되는걸까요?

2024-07-10 18:40 UTC, sang5c commented
맞습니다.  
PR을 올리기 전에 스스로 리뷰를 한 번 해보셔도 좋을 것 같아요~  
- [ ] 컨벤션을 지켰는가?
- [ ] 객체지향 생활체조를 지켰는가?
- [ ] 요구사항을 모두 만족했는가?

2024-07-11 05:35 UTC, us4c0d3 reviewed
지적해주신 부분 빠르게 적용하고 현재 테스트 작성중입니다.

2024-07-11 05:35 UTC, us4c0d3 commented on src/main/java/gift/entity/Wish.java
> +@Table(name = "wishes")
엔티티의 객체 하나로 생각해 단수형, 테이블 이름은 복수형으로 했습니다.

2024-07-11 05:35 UTC, us4c0d3 commented on src/main/java/gift/entity/Wish.java
> +    protected Wish() {}
컨벤션 상으로 instance 변수 -> 생성자 -> 메서드 순으로 작성하도록 되어있습니다.

그러나 이 경우 Builder 패턴의 형태가 정해져 있고, 인자가 없는 생성자도 Jpa에서 요구되지만 실질적으론 사용하지 않습니다. 그렇기 때문에 컨벤션에서 어느정도 벗어나더라도 이 두 가지를 뒤쪽에 두어 코드 가독성을 높였습니다.

이러한 자의적인 판단으로 코드 가독성이 높아지는 방향을 생각하였는데, 그래도 자바 컨벤션에 맞추는 것이 좋을까요?

2024-07-11 05:35 UTC, us4c0d3 commented on src/main/java/gift/config/WebConfig.java
> +    }
`@Component`와 `@Bean`의 차이에 대해 확실히 알지 못해 혼용해서 잘못 사용한 것 같습니다. 그래서 이에 관해 조금 찾아봤습니다.

@Component의 경우 스프링이 시작될 때 Component Scan을 통해 컴포넌트를 확인한 후 스프링 객체에 자동으로 빈으로 등록합니다. 이 때, Component는 클래스 레벨에 선언됩니다.

@Bean은 메서드 레벨에 선언되어 개발자가 수동으로 빈에 등록할 때 사용됩니다. 주로 외부 라이브러리를 사용하기 위해 의존성 주입이 필요할 때 사용됩니다.


|`@Component`|`@Bean`|
|-----------------|---------|
|클래스에 사용|메서드에 사용|
|개발자가 제어할 수 있는 내부 클래스에 사용|사용자가 제어할 수 없는 외부 라이브러리 사용 시 사용|

2024-07-11 05:35 UTC, us4c0d3 commented on src/main/java/gift/entity/Product.java
> +    private String name;
수정하겠습니다!

2024-07-11 05:35 UTC, us4c0d3 commented on src/main/java/gift/entity/Product.java
> +    public static class Builder {
wish에서 코드 가독성적인 측면에서 필요하다고 생각되어 처음 빌더 패턴을 적용했었습니다. 그러나 Product나 User의 경우 이러한 부분들을 각각의 mapper에 위임하고 있기 때문에 service에서만 본다면 굳이 필요 없을 것 같습니다.
특히, 빌더 패턴의 경우 객체를 생성할 때 Builder 객체를 함께 생성해야돼서 성능 오버헤드가 발생할 수 있습니다. 따라서 꼭 필요로 하지 않는 부분에서는 사용하지 않는 것이 좋을 것 같습니다.

2024-07-11 05:35 UTC, us4c0d3 commented on src/main/java/gift/service/WishService.java
> +        if (wish.getQuantity() <= 0) {
필드 정보 검증 로직은 엔티티 내에서 만들어보겠습니다!

2024-07-11 05:35 UTC, us4c0d3 commented on src/main/java/gift/util/mapper/ProductMapper.java
> +        product.setImageUrl(request.imageUrl());
상황에 맞게 메서드 명을 바꾸겠습니다.

2024-07-11 12:02 UTC, us4c0d3 commented
요구사항을 혼돈하여 DataJpaTest 학습 테스트를 누락한 점 죄송합니다! 

현재 각 Repository 별 테스트 추가 완료했는데 리팩토링 과정에서 Service 코드에 대한 input/output이나 메서드 이름 등 변경점이 많아 테스트가 정상 작동하지 않는 문제가 있어 `@Disabled`해둔 상태입니다.

DataJpaTest 코드 작성에서 id를 통한 접근 테스트를 제어하기 위해 매 테스트마다 auto_incremental을 초기화하는 방식을 사용했습니다. 그러나 이 때, h2의 문법과 MySQL의 문법의 충돌이 발생해서 application.properties의 MySQL dialect설정을 없앴더니 해결 됐습니다. 더미 데이터 삽입을 위해 직접 save해주는 방식을 사용했는데 다른 방법이 있는지 궁금합니다.

추가로, 멘토님의 코멘트에 답글로 남기긴 했는데 Entity에서 No Args Constructor는 개발자가 사용하지는 않지만 Jpa에서 요구하는 생성자입니다. 그렇기 때문에 코드 가독성을 위하여 가장 아래로 밀었습니다. 코딩 컨벤션이란 여러 사람이 협업에서 코드 일관성을 유지하기 위해 지키는 룰이라고 생각하면 컨벤션을 지키는 것이 맞지만 코드 가독성도 어느정도 신경 쓸 필요가 있다고 생각합니다. 가독성이 떨어지더라도 코드 일관성을 유지하기 위해 컨벤션은 무조건 지켜주는게 맞을까요?

2024-07-11 12:49 UTC, sang5c approved these changes
1단계 머지합니다! 리뷰 남겼으니 확인해주세요~

> 가독성 해친다고 느끼는 컨벤션도 지켜야 하는가?  

컨벤션에 대해 협의하고 맨 밑으로 내리기로 했다면 상관없습니다만, 
우린 `구글 가이드`를 따르기로 했고, 추가로 자바의 컨벤션이 필드 다음에 위치하도록 하니 지켜보면 어떨까요?  
https://google.github.io/styleguide/javaguide.html#s3.4.2-ordering-class-contents  

`컨벤션을 지키는 이유`에서 생각하면 좋을 것 같습니다.  
각자가 각자의 방식으로 작성/읽음으로 인해 발생하는 불협화음을 줄이기 위해 컨벤션을 만들고 지키기 위해 노력합니다.  
내가 편한방식으로 바꾸는게 아니라 우리가 편한 방식으로 바꿔야 합니다.  

`우산의 위치는 신발장 앞이다` 라는 규칙을 모두가 지키고 있다면 우산을 찾을 때 `당연히` 신발장 앞을 보게됩니다.  


> sql 실행하는 다른 방법

이 글을 참고하시면 좋을 것 같네요
https://docs.spring.io/spring-framework/reference/testing/testcontext-framework/executing-sql.html

2024-07-11 12:49 UTC, sang5c commented on src/main/java/gift/entity/Product.java
> +    public String name() {
혹시 오해가 있을까봐 남깁니다.
getter를 제거하라는 의미는 단순히 prefix를 떼라는 의미보다는 객체에서 값을 꺼내 작업하는대신, 객체가 직접 작업하고 결과를 돌려주는 방식으로 유도하기 위함입니다.  
데이터를 단순 조회하는 메서드를 getter라 호칭하고, getName() 형태로 무조건 작성해야 하는 것은 아니지만 일반적으로 getName()으로 사용합니다.

2024-07-11 12:49 UTC, sang5c commented on src/main/java/gift/entity/Product.java
> +    private String name;
아직 지켜지지 않았네요!
출력되는 DDL은 다음과 같습니다.
```SQL
    create table products (
        price integer not null,
        id bigint generated by default as identity,
        image_url varchar(255),
        name varchar(255) not null,
        primary key (id)
    )
```

2024-07-11 12:49 UTC, sang5c commented on src/test/java/gift/repository/ProductRepositoryTest.java
> +        insertion();
@BeforEach에 given절에 포함되는 코드를 넣는게 맞을까? 생각해보시면 좋을 것 같아요.  
진짜 공통이 아니면 테스트 가독성을 해친다고 생각합니다.

2024-07-11 12:49 UTC, sang5c commented on src/test/java/gift/repository/ProductRepositoryTest.java
> +        assertThat(products.size()).isEqualTo(5);
예를 들어 이 코드가 마지막에 있었고, given절이 좀 더 복잡했다면 테스트 클래스의 맨 위로 올라와 BeforeEach를 확인하고 다시 내려가는걸 반복해야 해요.  
이후에 이어지는 다른 테스트에서 동일하게 given절이 숨어있다고 느꼈습니다.

2024-07-11 12:49 UTC, sang5c commented on src/test/java/gift/repository/ProductRepositoryTest.java
> +        final Product actual = productRepository.findById(1L).get();
final을 붙인다면 모두 붙이고 아니라면 모두 안붙이는게 일관성이 있어 읽기 수월합니다.

2024-07-11 12:49 UTC, sang5c commented on src/test/java/gift/controller/ProductControllerTest.java
> +import static org.assertj.core.api.AssertionsForClassTypes.assertThat;
이곳에서만 다른 assertThat을 사용하고 있어요!

2024-07-11 12:49 UTC, merged

2024-07-11 12:56 UTC, sang5c commented
혹시 컨벤션 정의를 못봤다면 강의 자료를 천천히 다시 읽어봐주세요 :)  
<img width="690" alt="image" src="https://github.com/kakao-tech-campus-2nd-step2/spring-gift-jpa/assets/28697758/b6d1dd93-074f-44f1-9418-cb830fb68e20">

2024-07-11 14:12 UTC, us4c0d3 commented on src/main/java/gift/entity/Product.java
> +    private String name;
노트북 - PC 환경 바꿔가며 작업하다가 커밋 기록이 날아갔던 것 같습니다 😢