전남대 BE_박민규 3주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #176
Opened 2024-07-09 19:12 UTC by ps9319

2024-07-10 02:33 UTC, dc-choi requested changes
안녕하세요! step1 과제를 하시느라 정말 고생하셨습니다!

테스트 코드에 대한 부분을 첨언해드리자면 실패 케이스에 대해서도 테스트 코드를 작성하시면 더 좋은 테스트가 될 수 있을 것이라고 생각합니다!

자세한 내용은 하단 코멘트에 적어두었어요~! 확인 부탁드려요~!

2024-07-10 02:33 UTC, dc-choi commented on build.gradle
> +    implementation"org.springframework.boot:spring-boot-starter-data-jpa"
jpa 패키지안에 jdbc가 포함되어 있어요~!

`implementation 'org.springframework.boot:spring-boot-starter-jdbc'` 이 부분 제거하시는게 좋아요

2024-07-10 02:33 UTC, dc-choi commented on src/main/java/gift/domain/Product.java
> +    @NotNull
`validation`을 사용하기 보단 `@Column`을 사용하시는건 어떨까요?

2024-07-10 02:33 UTC, dc-choi commented on src/main/java/gift/domain/User.java
> +@Table(name = "user_table")
`user_table`이라는 네이밍을 사용하신 이유가 있으실까요?

2024-07-10 02:33 UTC, dc-choi commented on src/main/java/gift/domain/User.java
> +    @NotNull
마찬가지로 `validation`을 사용하기 보단 `@Column`을 사용하시는건 어떨까요?

2024-07-10 02:33 UTC, dc-choi commented on src/main/java/gift/domain/Wish.java
> +    @NotNull
마찬가지로 `validation`을 사용하기 보단 `@Column`을 사용하시는건 어떨까요?

2024-07-10 02:33 UTC, dc-choi commented on src/test/java/gift/repository/JpaProductRepositoryTest.java
> +@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
`@AutoConfigureTestDatabase`는 무엇인지 설명해주실 수 있나요?

2024-07-10 02:33 UTC, dc-choi commented on src/test/java/gift/repository/JpaProductRepositoryTest.java
> +        Product product = new Product("사과", 12000, "www.naver.com");
given 부분이 중복되는 것으로 보입니다~!

`@BeforeEach`에 대해서 알아보시고 테스트 데이터를 만드는 로직의 중복을 줄여보는건 어떨까요?

2024-07-10 02:33 UTC, dc-choi commented on src/test/java/gift/repository/JpaProductRepositoryTest.java
> +        Product findProduct = jpaProductRepository.findById(insertProductId).get();
이 부분은 when에 해당하는 영역 같아요! 확인 부탁드려요!

2024-07-10 02:33 UTC, dc-choi commented on src/test/java/gift/repository/JpaUserRepositoryTest.java
> +        User user = new User("www.naver.com", "1234", "일반");
마찬가지로 given 부분이 중복되는 것으로 보입니다~!

`@BeforeEach`에 대해서 알아보시고 테스트 데이터를 만드는 로직의 중복을 줄여보는건 어떨까요?

2024-07-11 01:03 UTC, ps9319 commented on build.gradle
> +    implementation"org.springframework.boot:spring-boot-starter-data-jpa"
넵 제거했습니다

2024-07-11 01:09 UTC, ps9319 commented on src/main/java/gift/domain/User.java
> +@Table(name = "user_table")
H2 데이터베이스에서 user가 예약어로 되어있어서 자동으로 테이블 생성할 때 오류가 생겨서 user_table이라고 지정해줬습니다.

2024-07-11 02:16 UTC, ps9319 commented on src/main/java/gift/domain/User.java
> +    @NotNull
validation보다 @Column을 사용하라고 여쭤보시는 이유가 궁금합니다!

제가 공부했을 때는 implementation 'org.springframework.boot:spring-boot-starter-validation'가 있고, @Column(nullable = false)일 때에는 jpa Entity 값에 null 값이 들어왔을 때에는 예외 처리를 하지 못하고 db에 insert될 때 예외가 터지는 걸로 알고 있는데, NotNull을 사용해서 jpa Entity 값에 null값 자체가 못 들어오게 하는게 더 좋은 방법이라고 생각해서 NotNull을 사용했습니다.

혹시 dto에서 이미 검증을 하고 있으니 entity에서는 Column을 사용하는게 나은 방법일까요?

2024-07-11 02:17 UTC, ps9319 commented on src/main/java/gift/domain/Product.java
> +    @NotNull
https://github.com/kakao-tech-campus-2nd-step2/spring-gift-jpa/pull/176#discussion_r1673302700
여기에 질문 남겼습니다!

2024-07-11 02:17 UTC, ps9319 commented on src/main/java/gift/domain/Wish.java
> +    @NotNull
https://github.com/kakao-tech-campus-2nd-step2/spring-gift-jpa/pull/176#discussion_r1673302700
여기에 질문 남겼습니다!

2024-07-11 04:15 UTC, ps9319 commented on src/test/java/gift/repository/JpaProductRepositoryTest.java
> +@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
`spring.datasource.url=jdbc:h2:mem:test;MODE=MYSQL;DB_CLOSE_DELAY=-1
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect`
이 설정을 했더니 
DataJpaTest를 사용할 때 윗부분이 적용되지 않고, h2 db로 테스트가 되더라구요. 저 설정을 해주지 않았더니 쿼리 생성 오류가 발생해서 원래 테스트할때에도 properties가 적용되게 했습니다

2024-07-11 04:15 UTC, ps9319 commented on src/test/java/gift/repository/JpaProductRepositoryTest.java
> +        Product product = new Product("사과", 12000, "www.naver.com");
넵 적용해보겠습니다. 감사합니다!

2024-07-11 04:16 UTC, ps9319 commented on src/test/java/gift/repository/JpaUserRepositoryTest.java
> +        User user = new User("www.naver.com", "1234", "일반");
넵 적용해보겠습니다. 감사합니다!

2024-07-11 04:27 UTC, ps9319 commented on src/test/java/gift/repository/JpaProductRepositoryTest.java
> +        Product findProduct = jpaProductRepository.findById(insertProductId).get();
바꿨습니다!

2024-07-11 04:30 UTC, ps9319 reviewed
실패 테스트는 커스텀 예외를 만들고 그 예외가 터지는지 확인해야할것 같아서 step2때 해보겠습니다...!!

2024-07-11 05:45 UTC, dc-choi commented on src/main/java/gift/domain/User.java
> +    @NotNull
> 혹시 dto에서 이미 검증을 하고 있으니 entity에서는 Column을 사용하는게 나은 방법일까요?

정확히는 DTO에서 이미 데이터 자체에 대한 유효성 검사를 진행해서 그렇습니다.

그리고 `Entity`의 역할에 대해서 생각을 해보았을 때 이 안에서 유효성 검사가 일어나면 하나의 객체에서 너무 많은 일이 일어난다고 생각하기도 합니다!

저는 데이터 유효성 자체의 검사는 `Controller`에서 전부 처리가 되어야 하고 도메인 로직에서의 예외는 따로 예외를 처리할 수 있는 객체를 만들어서 처리합니다!

2024-07-11 05:49 UTC, dc-choi requested changes
안녕하세요 민규님! 리뷰 요청 확인하였습니다~!

피드백 주신대로 잘 수정해주셨고 질문 주셨던건 그 밑에 답변으로 코멘트하였어요~!

확인 부탁드려요~!

2024-07-11 06:05 UTC, ps9319 commented on src/main/java/gift/domain/User.java
> +    @NotNull
아하 바로 이해가 갔습니다!! 수정했습니다.

2024-07-11 08:08 UTC, dc-choi requested changes
안녕하세요 민규님~! `@Size` 부분만 처리되면 승인하도록 하겠습니다!

2024-07-11 08:08 UTC, dc-choi commented on src/main/java/gift/domain/Product.java
>      @Size(max = 15)
아직 `validation` 부분이 남아있네요! 확인 부탁드려요!!

2024-07-11 08:27 UTC, ps9319 commented on src/main/java/gift/domain/Product.java
>      @Size(max = 15)
앗! Size도 있었네요 제거했습니다!

2024-07-11 09:09 UTC, dc-choi requested changes
민규님~! SIze를 수정하면서 누락된 부분이 있는거 같아요~!

다시 확인 부탁드려요~!

2024-07-11 09:09 UTC, dc-choi commented on src/main/java/gift/domain/Product.java
> +    @Column(nullable = false)
요구사항대로 상품이름의 길이에 대한 제한이 있었으면 좋겠습니다!

2024-07-11 11:11 UTC, ps9319 commented on src/main/java/gift/domain/Product.java
> +    @Column(nullable = false)
읗어어어어어엏 죄송합니다

2024-07-12 01:21 UTC, dc-choi approved these changes
민규님~! step1 과제 진행하시느라 고생하셨습니다!

다음 과제 진행해주시면 될 거 같습니다!

2024-07-12 01:21 UTC, merged