충남대 BE_이택 3주차 과제 (Step1)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #179
Opened 2024-07-10 05:15 UTC by LeeTaek2T

![image](https://github.com/kakao-tech-campus-2nd-step2/spring-gift-jpa/assets/137752192/df0ac8a3-8b7d-473a-b719-ed9bc2fb5b8c)
이 부분에서 리뷰를 jwtService에서도 메시지를 던져 valid를 체크하는것처럼 matchInfo()와 같이 메서드로 처리하는게 어떠시냐고 말씀해주셨습니다.
먼저 @Valid와 같이 로그인관련 어노테이션이 있나 찾아봤는데, 해당되는 어노테이션을 찾지 못했습니다. 그래서 가독성을 위해 UserService안에 단순히 matchInfo라는 메서드를 만들면 좋겠다라고 하시는 건가?라는 생각이 들었습니다. 

멘토님이 해당 리뷰를 남겨주신 이유가 오직 가독성만을 위한 것인가요?

*아직 해당 리뷰는 코드에 반영하지 않았습니다..!

2024-07-10 05:32 UTC, ksy90101 commented
객체지향에서 메시지를 던져라. 하는 것처럼
https://soongjamm.tistory.com/133

실제 user라는 객체에 메시지를 던져서 체크하라는 의미였어요.

즉, user라는 곳에 해당 로직을 체크하는 메서드를 만들라는 의미입니다!

https://jheloper.github.io/2020/02/object-oriented-facts-and-misunderstandings-01/

위 글을 한번 읽어보시면 좋을거 같아요~

2024-07-10 07:52 UTC, ksy90101 requested changes
고생하셨습니다!
간단한 피드백을 남겼으니 확인해주세요~
언제든 질문이 있다면 DM주세요!

2024-07-10 07:52 UTC, ksy90101 commented on src/main/java/gift/Controller/ProductAdminController.java
> +    Optional<ProductDto> productDTO = productService.getProductById(id);
Optional이니 orElasThrow를 메서드 체이닝을써서 에러 처리를 해보면 어떨까요?

2024-07-10 07:52 UTC, ksy90101 commented on src/main/java/gift/DTO/ProductDto.java
> +@Table(name = "PRODUCT_DTO")
어... 테이블 이름에 DTO가 들어가는게 맞나요?
DTO와 엔티티는 별개라고 생각이 드는데요.
Entity에 대응되는 객체와
DTO로 대응되는 객체가 따로 있어야 할거 같아요,

2024-07-10 07:52 UTC, ksy90101 commented on src/main/java/gift/Repository/ProductDao.java
> +  void deleteById(Long Id);
이부분은 이미 JpaRepository에 정의되어 있는데 따로 또 정의하신 이유가 있나요?

2024-07-10 07:52 UTC, ksy90101 commented on src/test/java/gift/ProductDtoControllerTest.java
> +  @DirtiesContext
이건 왜 추가가 되었나요?

2024-07-10 08:33 UTC, LeeTaek2T commented on src/main/java/gift/Controller/ProductAdminController.java
> +    Optional<ProductDto> productDTO = productService.getProductById(id);
네! 해보겠습니다

2024-07-10 09:36 UTC, LeeTaek2T commented on src/main/java/gift/Repository/ProductDao.java
> +  void deleteById(Long Id);
jpa는 이렇게 정의를 해야 사용가능한 줄 알았습니다..
상속받았으니 할 필요가 없었는데 말이죠....
수정하겠습니다!

2024-07-10 10:29 UTC, LeeTaek2T commented on src/test/java/gift/ProductDtoControllerTest.java
> +  @DirtiesContext
@DirtiesContext를 이용하면 독립적으로 테스트를 할 수 있다고 들었습니다.
각 테스트에 사용된 product가 데이터로 남아있어 그 다음 테스트에 영향을 주어 이를 방지하기 위해 사용하였습니다.

2024-07-11 00:31 UTC, ksy90101 approved these changes
Optional 처리를 잘 해보시면 좋을거 같아요.
아직 단계가 좀 남아 있기 때문에 이건 리뷰를 남기고 머지할게요~
2단계는 간단하니 2단계에서 같이 적용해주세요!
궁금한게 있다면 언제든 DM주세요!

2024-07-11 00:31 UTC, ksy90101 commented on src/main/java/gift/DTO/ProductDto.java
>    @Size(min = 1, max = 15, message = "가능한 글자 수는 1~15입니다.")
이전에 NotNull, NotEmpty, NotBlank가 있었던거 같은데...

혹시 이러한 validate도 필요하지 않을까요?

2024-07-11 00:31 UTC, ksy90101 commented on src/main/java/gift/DTO/ProductEntity.java
> +@Table()
```suggestion
@Table
```

2024-07-11 00:31 UTC, ksy90101 commented on src/main/java/gift/DTO/ProductEntity.java
> +  })
entity에 validate를 이렇게 쓰는게 맞을까요!?
혹시 이게 동작하나요?

2024-07-11 00:31 UTC, ksy90101 commented on src/main/java/gift/DTO/UserDto.java
> +  }
entity와 DTO둘다 있는데
이게 둘다 있을 이유가 있을까요?

2024-07-11 00:31 UTC, ksy90101 commented on src/main/java/gift/Repository/ProductDao.java
> +  void deleteById(Long Id);
이건 정의내릴 필요가 없어요~
지우는게 좋을거 같습니다~

2024-07-11 00:31 UTC, ksy90101 commented on src/main/java/gift/Service/JwtService.java
> +  public JwtToken createAccessToken(Optional<UserEntity> userDto) {
Optional을 쓰는게 아니라 이걸 가져오는 곳에서 UserEntity를 처리합니다.

https://dev-coco.tistory.com/178

이글을 한번 읽어보세요.

2024-07-11 00:31 UTC, ksy90101 commented on src/main/java/gift/Service/ProductService.java
> +  public List<ProductEntity> getAllProducts() {
Entity는 도메인과 테이블을 매핑하기 때문에 Entity라고 명시적으로 쓰지 않습니다.

즉, Product라고 쓰고, DTO는 ProductDto, ProductRequest, ProductResponse 이런식으로 씁니다~

2024-07-11 00:31 UTC, ksy90101 commented on src/main/java/gift/Service/ProductService.java
> +    Optional<ProductEntity> existingProductDto = productDao.findById(id);
Optional은 Service에서 마무리 해주세요.

2024-07-11 00:31 UTC, ksy90101 commented on src/main/java/gift/Repository/ProductDao.java
> +public interface ProductDao extends JpaRepository<ProductEntity, Long> {
Dao라는 이름보다 Repository라는 이름이 어울릴거 같아요.

2024-07-11 00:31 UTC, merged

2024-07-11 05:30 UTC, LeeTaek2T commented on src/main/java/gift/DTO/ProductDto.java
>    @Size(min = 1, max = 15, message = "가능한 글자 수는 1~15입니다.")
필요한 것 같습니다
반영하겠습니다!

2024-07-11 05:35 UTC, LeeTaek2T commented on src/main/java/gift/DTO/ProductEntity.java
> +  })
제가 Entity를 계층 간 이동할 때에도 사용하여 제대로 동작은 하였습니다.
jpa를 이용하여 객체를 받을 때는 entity, 계층 간 이동을 할 때는 dto를 사용하여 다시 구현해보겠습니다.

그리고 eneity의 해당 validate들은 맞지 않는 것 같습니다. 이 부분도 수정하겠습니다!

2024-07-11 09:04 UTC, LeeTaek2T commented on src/main/java/gift/DTO/UserDto.java
> +  }
Dto와 entity의 개념이 모호할 때 두 곳에서 모두 쓰고 지우지 않았습니다..
현재는 entity에만 두었습니다. (Dto는 setter,getter까지만 있어야 된다고 생각하기 때문입니다)

2024-07-11 09:05 UTC, LeeTaek2T commented on src/main/java/gift/Repository/ProductDao.java
> +  void deleteById(Long Id);
네! 알겠습니다

2024-07-11 09:22 UTC, LeeTaek2T commented on src/main/java/gift/Service/JwtService.java
> +  public JwtToken createAccessToken(Optional<UserEntity> userDto) {
오....네! 알겠습니다!!

2024-07-11 09:34 UTC, LeeTaek2T commented on src/main/java/gift/Service/ProductService.java
> +  public List<ProductEntity> getAllProducts() {
네!! 알겠습니다
반영하겠습니다

2024-07-11 09:53 UTC, LeeTaek2T commented on src/main/java/gift/Service/ProductService.java
> +    Optional<ProductEntity> existingProductDto = productDao.findById(id);
네! 알겠습니다

2024-07-11 09:55 UTC, LeeTaek2T commented on src/main/java/gift/Repository/ProductDao.java
> +public interface ProductDao extends JpaRepository<ProductEntity, Long> {
네! 알겠습니다