부산대 BE 원윤서 3주차 과제 (Step2)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #184
Opened 2024-07-10 06:11 UTC by yoonsu0325

step2 연관 관계 매핑 구현했습니다!

2024-07-10 07:14 UTC, yoo-jaein requested changes
step2 고생하셨습니다!
리뷰 코멘트 확인 부탁드려요~

2024-07-10 07:14 UTC, deactivated-user commented on src/main/java/gift/wishList/WishListController.java
> +        if (count.count == 0) {
컨트롤러에 비즈니스 로직이 너무 많이 들어있습니다.
서비스 계층으로 분리해주세요~

2024-07-10 07:14 UTC, deactivated-user commented on src/main/java/gift/wishList/WishListController.java
> +    public ResponseEntity<?> addWishes(@LoginUser User user, @RequestBody WishListDTO wishListDTO) {
```<?>``` 와일드카드 타입을 사용하는 것은 좋은 방법이 아닙니다.
```<?>```는 모든 타입을 허용하기 때문에 컴파일 시점에 타입 검사를 제대로 할 수 없고, 반환 타입이 명확하지 않아 코드 가독성을 해칩니다.
WishListDTO와 같은 구체적인 타입을 사용하도록 코드를 수정해주세요!

2024-07-10 07:14 UTC, deactivated-user commented on src/main/java/gift/wishList/WishList.java
> +public class WishList implements Serializable {
Serializable을 구현한 이유가 있을까요?

2024-07-10 07:14 UTC, deactivated-user commented on src/main/java/gift/wishList/WishListController.java
> +    public ResponseEntity<?> getWishesByUserID(@LoginUser User user) {
```@RestController```가 사용된 컨트롤러 클래스의 메서드들의 반환값은 자동으로 ResponseBody로 처리됩니다.
상태 코드나 헤더를 수정하는 등 세밀한 설정이 필요하지 않다면 ResponseEntity<...>를 사용할 필요가 없습니다.

2024-07-10 07:14 UTC, yoo-jaein commented on src/main/java/gift/product/Product.java
> +    @OneToMany(cascade = CascadeType.ALL,
cascade & orphanRemoval 👍

2024-07-10 07:14 UTC, yoo-jaein commented on src/main/java/gift/product/Product.java
> +        wishList.setProduct(this);
setProduct 👍

2024-07-10 07:14 UTC, yoo-jaein commented on src/main/java/gift/product/Product.java
>      Long id;
객체의 캡슐화를 위해 엔티티 객체들의 필드를 private으로 설정해주세요~
필드를 private으로 바꾸고 getters / setters를 적절히 제공해서 접근해야 합니다.

2024-07-10 07:14 UTC, yoo-jaein commented on src/main/java/gift/user/User.java
> +    public void removeWishLists() {
removeWishList 메서드를 재사용해서 더 깔끔한 코드로 리팩터링할 수 있을 것 같아요!

2024-07-10 15:59 UTC, yoonsu0325 commented on src/main/java/gift/wishList/WishList.java
> +public class WishList implements Serializable {
앗 계절 수업에서 배운 내용보고 그냥 생각없이 넣은 것 같습니다... 지금 필요하지 않은 것 같아서 삭제했습니당

2024-07-11 03:18 UTC, yoo-jaein approved these changes
step2 머지하겠습니다! :)

2024-07-11 03:18 UTC, merged