부산대 BE_박수빈 3주차 과제 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #193
Opened 2024-07-10 07:45 UTC by kuma4188

1. wishlist에서 product와 user 객체를 바로 받도록 수정했습니다.
2.  wishlistRepository에서 user 이라는 객체를 바로 받기 때문에 
findByUsername 을 사용할수없게 되었습니다.  그래서 user 객체의 username을 find 해야하기 때문에
findByUserUsername 으로 변경 했습니다.
3. 그 이후로 영향을 받은 모든 코드들을 수정했습니다.
- WishlistServiceImpl 
- WishlistRepository
- WishlistControllerTest
- WIshlistRepositoryTest

2024-07-10 17:01 UTC, kuma4188 commented
rebase를 이용해서 squash를 해보았습니다. drop을 시도해봤는데 커밋때 수정한 코드도 같이 삭제되는것 같아서 표기했습니다.
squash로 앞선 커밋을 합치고 강제 push를 했습니다.
git이 처음이라  많이 미흡하네요 ㅜㅜ 열심히 공부해보겠습니다!

2024-07-11 03:50 UTC, yoo-jaein requested changes
step2 고생하셨습니다!
몇 가지 코멘트 확인 부탁드립니다 :)

2024-07-11 03:50 UTC, yoo-jaein commented on src/test/java/gift/test/ProductRepositoryTest.java
> +    @BeforeEach
setUp 👍

2024-07-11 03:50 UTC, yoo-jaein commented on src/test/java/gift/test/ProductRepositoryTest.java
> +    @DisplayName("상품 이름이 NULL 일때")
테스트 이름은 보통 "조건 + 결과" 포맷으로 작성합니다
- "~~일 때 ~~ 예외 발생"
- "~~일 때 ~~리턴" 
- "~~일 때 성공"

2024-07-11 03:50 UTC, yoo-jaein commented on src/test/java/gift/test/ProductServiceTest.java
> +@TestMethodOrder(OrderAnnotation.class)
이건 어떤 설정인가요?

2024-07-11 03:50 UTC, yoo-jaein commented on src/test/java/gift/test/WishlistControllerTest.java
> +public class WishlistControllerTest {
컨트롤러 테스트 👍

2024-07-11 03:50 UTC, yoo-jaein commented on src/main/java/gift/model/Wishlist.java
> +    private SiteUser user;
단방향 연관관계로 설정해주셨군요! 코드가 깔끔합니다

2024-07-11 03:50 UTC, yoo-jaein commented on src/test/java/gift/test/ProductServiceTest.java
> +    private void validateProductName(String name) {
컨트롤러 단에 있는 규칙 3가지 메서드를 복사해서 가져오셨네요!
만약 컨트롤러의 규칙 로직이 바뀐다면 테스트 코드의 내용과 달라질 수 있습니다.

테스트하기 쉽도록 컨트롤러단에 있는 validateProductName을 별도의 validator 클래스로 옮기고, 테스트 코드에서 해당 클래스를 가져와서 테스트해볼 수 있을 것 같습니다.

2024-07-11 03:50 UTC, yoo-jaein commented on src/test/java/gift/test/WishlistRepositoryTest.java
>      @DisplayName("담긴 상품 수량 변경")
여기도 repository 테스트와 controller 테스트가 섞여있네요!

2024-07-11 05:31 UTC, kuma4188 commented
수정사항)
1. 테스트 이름 (조건 + 결과) 형식으로 변경
2.  validator 패키지 생성후 , ProductNameValidator 클래스 생성
3.  repository 클래스에서 컨트롤 테스트 제거후  (findByUserUsername) 테스트로 변경

2024-07-11 09:01 UTC, yoo-jaein approved these changes
리뷰 반영된 것 확인했습니다.
step2 머지하겠습니다! :)

2024-07-11 09:01 UTC, yoo-jaein commented on src/test/java/gift/validator/ProductNameValidator.java
> +public class ProductNameValidator {
Validator 👍

2024-07-11 09:01 UTC, merged