부산대 BE_박혜연 3주차 과제 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #198
Opened 2024-07-10 10:25 UTC by hyyyh0x

2024-07-10 12:03 UTC, yoo-jaein requested changes
step2 고생하셨습니다!
리뷰 코멘트 확인 부탁드려요~

2024-07-10 12:03 UTC, deactivated-user commented on src/main/java/gift/wishlist/WishList.java
> +    @ManyToOne(fetch = FetchType.LAZY)
LAZY 👍

2024-07-10 12:03 UTC, deactivated-user commented on src/main/java/gift/user/User.java
> +
양방향 관계에서 부모와 자식 간 데이터 일관성과 무결성을 유지하는 것이 중요합니다.
부모 엔티티 (Product, User) 에서 자식 엔티티 (WishList)를 추가 & 제거하는 메서드를 만들어주세요!

```java
// Product와 UserInfo 생성
Product product = new Product("Laptop", 1500L, "laptop.jpg");
User userInfo = new User("user@example.com", "123123");

// Wish 생성 및 추가
WishList wishList = new WishList(product, userInfo, 1L);

// Product와 User에 Wish 추가
product.addWishList(wishList); 
userInfo.addWishList(wishList);

// 저장
productRepository.save(product);
userRepository.save(userInfo);

// Wish 제거
product.removeWish(wishList);
userInfo.removeWish(wishList);
```
만들어야 할 메서드들
- Product.addWishList(), removeWishList()
- User.addWishList(), removeWishList()

2024-07-10 12:03 UTC, deactivated-user commented on src/main/java/gift/user/User.java
> +    @OneToMany(mappedBy = "user")
필요에 따라 cascade, orphanRemoval 속성을 추가하여 영속성 전이(엔티티의 상태 변화를 연관된 엔티티에도 함께 적용하는 것) 설정해볼 수 있습니다!
- https://willseungh0.tistory.com/67 참고

2024-07-10 12:03 UTC, deactivated-user commented on src/main/java/gift/user/User.java
> +    private List<WishList> wishes;
NPE를 방지하기 위해 초기화해주는 것이 좋습니다!
```java
private List<WishList> wishes = new ArrayList<>();
```

2024-07-11 03:32 UTC, yoo-jaein requested changes
추가 코멘트 확인 부탁드립니다!!
내용이 잘 이해가 안되시면 메시지 부탁드려요

2024-07-11 03:32 UTC, yoo-jaein commented on src/main/java/gift/user/User.java
> +    public void removeWishList(){this.wishes = null;}
메서드 잘 만들어주셨습니다! 한 가지 보충할 코드가 있어 알려드릴게요
```java
    public void addWishList(List<WishList> wishes) {
        this.wishes = wishes;
        wishes.forEach(wish -> wish.setUser(this)); // 파라미터로 들어온 wishes에도 User를 세팅해주어야 합니다.
    }

    public void removeWishList() {
        this.wishes = null;
    }
```

위 코드처럼 Product에도 수정이 필요한지 체크해주세요!

그리고 위시리스트를 추가하는 비즈니스 로직에서 product와 user에 각각 addWishList를 호출해주어야 합니다. (제거할 때에는 removeWishList()) 그래야 양방향 연관관계의 데이터 일관성과 무결성이 지켜집니다.

### 예시
```java
// 위시리스트를 추가하는 과정에....
user.addWishList(wishList);
product.addWishList(wishList);
wishListRepository.save(wishList);
```

2024-07-11 04:49 UTC, hyyyh0x commented on src/main/java/gift/user/User.java
> +    public void removeWishList(){this.wishes = null;}
피드백 해주신 내용을 이해한 것 같습니다 피드백 감사합니다. 
멘토님이 피드백 해주신 내용을 추가하기 전에도 실행은 잘 되었는데, 양방향 연관관계의 데이터 일관성과 무결성이 지켜지지 않으면 어떤 문제가 생길 수 있나요?

2024-07-11 05:05 UTC, hyyyh0x commented on src/main/java/gift/user/User.java
> +    private List<WishList> wishes;
NPE가 NullPointerException이란 것을 검색을 통해 알게 되었습니다. 그런데 new ArrayList<>();로 초기화 시켜주는 것이 왜 NPE를 방지 하는 것인지 이해가 잘 가지 않습니다. 객체가 생성이 되면서 빈 값이 들어가는 것이 아닌가요?

2024-07-11 08:50 UTC, yoo-jaein commented on src/main/java/gift/user/User.java
> +    public void removeWishList(){this.wishes = null;}
한쪽에서만 관계를 설정하고 다른 쪽에서는 설정하지 않으면 데이터베이스와 애플리케이션 사이에 데이터가 일치하지 않을 수도 있습니다.

예를 들어, User는 WishList를 가지고 있지만 WishList는 해당 User를 참조하지 않는 상황이 생길 수 있습니다. 그러면 서비스 코드에서 비즈니스 로직이 예상대로 동작하지 않을 수 있습니다.

2024-07-11 08:57 UTC, yoo-jaein commented on src/main/java/gift/user/User.java
> +    private List<WishList> wishes;
```wishes;``` 로 객체를 선언만 했을 때 wishes는 ```null```로 초기화됩니다.
```wishes = new ArrayList<>();``` 로 객체를 초기화했을 때 wishes는 ```비어있는 리스트(ArrayList)```를 참조합니다. 

NPE는 null 객체의 메서드를 호출하거나, null 객체에 접근하려 할 때 발생하는데요. 디버깅과 예측이 까다롭기 때문에 가능하면 발생하지 않도록 대비해야하는 예외입니다. 
- https://goddaehee.tistory.com/126 
- https://upcurvewave.tistory.com/644 

```java
// 초기화하지 않은 경우
private List<WishList> wishes;

public void addWish(WishList wish) {
    wishes.add(wish);  // NPE 발생! wishes가 null인데 null의 add를 호출하기 때문
}
```

```java
// 초기화한 경우
private List<WishList> wishes = new ArrayList<>();

public void addWish(WishList wish) {
    wishes.add(wish);  // 정상 작동. wishes가 빈 ArrayList 객체를 참조하고 있음. ArrayList의 add를 정상적으로 호출함
}
```

2024-07-11 08:58 UTC, yoo-jaein approved these changes
step2 머지하겠습니다!
추가 질문에 대한 답변은 코멘트로 달았습니다.

2024-07-11 08:58 UTC, merged