전남대 BE_지연우 3주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #199
Opened 2024-07-10 10:48 UTC by speciling

자꾸 새롭게 공부할 내용들이 생기고 과제 진행하느라 시간에 쫒겨서 피드백 해주신 내용들을 빠르게 반영하지 못하고 있습니다.
늦더라도 천천히 하나씩 수정할 수 있도록 노력하겠습니다.

2024-07-10 15:52 UTC, seungy0 requested changes
연우님 안녕하세요~
우선 지금 실행이 안되는 상태입니다.
실행되는 상태로 고쳐주시면 리뷰 진행하겠습니다.
도움이 필요하면 알려주세요!

2024-07-11 01:24 UTC, speciling commented
confilct를 해결하다가 실수로 삭제했던 과거 Repository 파일들이 다시 살아나서 실행이 안되고 있었네요.
해당 파일들 다시 삭제해서 해결했습니다.

2024-07-14 08:31 UTC, seungy0 approved these changes
연우님 안녕하세요~
이번주도 고생하셨습니다.

몇가지 코멘트 남겼으니 참고해주세요.
스프링의 핵심원리 중 하나인 IoC/DI를 활용하지 못하고 있는 부분이 있습니다. 해당 부분은 꼭 고치셨으면 좋겠습니다.

2024-07-14 08:31 UTC, seungy0 commented on src/main/java/gift/doamin/admin/controller/AdminController.java
> +    JpaProductRepository productRepository;
이런 부분은 조금 아쉽네요. interface는 그대로 두는게 좋았을 것 같습니다.

2024-07-14 08:31 UTC, seungy0 commented on src/main/java/gift/doamin/wishlist/entity/Wish.java
> +    @JoinColumn(nullable = false)
```suggestion
    @ManyToOne(optional = false)
```
이렇게 변경해도 동일할 것 같네요.

2024-07-14 08:31 UTC, seungy0 commented on src/main/java/gift/doamin/wishlist/service/WishListService.java
> +    private final JpaProductRepository jpaProductRepository;
더 좋은 방법 없을까요?
wishReposiry 이외에는 필요한지 잘 모르겠습니다.

2024-07-14 08:31 UTC, seungy0 commented on src/main/java/gift/doamin/wishlist/service/WishListService.java
> +    private final JpaProductRepository jpaProductRepository;
```suggestion
    private final WishListRepository wishListRepository;
```
최대한 이 상태를 유지하시면 좋겠습니다.
일단 JpaWishListRepository에 `@Repository`를 넣으시면 됩니다.
interface를 사용하는 이유입니다. SOLID 중 DIP를 사용한거죠.

2024-07-14 08:31 UTC, seungy0 commented on src/main/java/gift/doamin/user/entity/User.java
>  public class User {
가입 시점, 업데이트 시점, 누구에 의해 업데이트 됐는지 등이 있으면 좋겠네요.

2024-07-14 08:31 UTC, seungy0 commented on src/main/java/gift/doamin/product/entity/Product.java
>  public class Product {
가입 시점, 업데이트 시점, 누구에 의해 업데이트 됐는지 등이 있으면 좋겠네요.

2024-07-14 08:31 UTC, merged

2024-07-15 06:27 UTC, speciling commented on src/main/java/gift/doamin/wishlist/entity/Wish.java
> +    @JoinColumn(nullable = false)
감사합니다. 수정했습니다

2024-07-15 06:32 UTC, speciling commented on src/main/java/gift/doamin/admin/controller/AdminController.java
> +    JpaProductRepository productRepository;
jpa로 쉽게 변경하려고 기존 인터페이스를 수정하기보단 삭제해버리니 DIP를 지키지 못하게 되어버렸네요.
SOLID에 대한 이해가 부족했던 것 같습니다. SOLID 개념을 다시 공부하고 앞으로는 지킬 수 있도록 하겠습니다.

2024-07-15 06:54 UTC, speciling commented on src/main/java/gift/doamin/wishlist/service/WishListService.java
> +    private final JpaProductRepository jpaProductRepository;
우선 실수로 두 개나 만들어버린 productRepository중 한 개는 삭제했습니다.
JpaWishListRepository를 제외한 다른 repository를 제거하려면 repository 대신 각각의  Service를 의존하거나 연관관계를 끊고 이전처럼 pk값만 저장하는 방법밖에는 생각나지 않는데 혹시 다른 방법이 있을까요?

2024-07-15 08:33 UTC, speciling commented on src/main/java/gift/doamin/user/entity/User.java
>  public class User {
JPA Auditing 기능을 적용해서 추가했습니다