전남대 BE_모아림 3주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #204
Opened 2024-07-10 13:03 UTC by ariimo

2024-07-10 13:12 UTC, ariimo commented
안녕하세요 멘토님! 
이번 step1 과제는 테스트코드 작성이 개인적으로 정말 힘들었습니다..ㅠㅠ
사실 목표는 MemberController와 WishController의 E2E테스트 진행이었으나, MemberController만 성공하고 WishController는 오류 해결이 안 되는 상태입니다. 

 WishController 안의 각각의 Test에 대해서는 '테스트 통과'가 되나 이상하게 전체 WishControllerTest()를 실행하면 오류가 발생합니다. 개인적인 생각으로는 운영체제 시간에 배웠던 '멀티스레딩'으로 인한 경쟁상태가 아닐까 싶은데 해결 방법을 못 찾겠습니다. 음.. 혹시 mock객체에 대해서 학습하면... 오류를 해결할 수 있을까요..?
 
 아쉬운 마음에 WishRepositoryTest를 추가하며 PR을 날립니다.. 
 항상 상세한 코드 리뷰 감사드립니다:) 이번 주도 잘 부탁드리겠습니다!!

2024-07-11 05:41 UTC, dc-choi requested changes
안녕하세요 아림님!

자세한 내용은 코멘트에 남겨두었습니다! 확인 부탁드립니다~!

추가적으로 첨언을 하자면 각각의 테스트는 다른 테스트에 종속적이면 안됩니다. 그리고 실패 케이스에 대해서도 테스트를 작성하시면 더 훌륭한 테스트 코드를 작성하실 수 있을거라 생각합니다.

코멘트에 대한 답변도 같이 남겨드리도록 하겠습니다!

> WishController 안의 각각의 Test에 대해서는 '테스트 통과'가 되나 이상하게 전체 WishControllerTest()를 실행하면 오류가 발생합니다. 개인적인 생각으로는 운영체제 시간에 배웠던 '멀티스레딩'으로 인한 경쟁상태가 아닐까 싶은데 해결 방법을 못 찾겠습니다. 음.. 혹시 mock객체에 대해서 학습하면... 오류를 해결할 수 있을까요..?

멀티스레딩이라고 생각하신 이유가 있을까요? 어떤 근거로 그렇게 생각하셨는지 궁금합니다!

2024-07-11 05:41 UTC, dc-choi commented on src/main/java/gift/domain/Product.java
> +    @Column(nullable = false)
요구사항에 맞게 길이 조정을 해주시면 감사하겠습니다!

2024-07-11 05:41 UTC, dc-choi commented on src/main/java/gift/repositories/WishRepository.java
> +    @Query("SELECT w FROM Wish w WHERE w.memberId = :memberId")
JPQL을 특별히 사용하신 이유가 있으실까요?

2024-07-11 05:41 UTC, dc-choi commented on src/main/java/gift/services/WishService.java
> +    @Transactional
`@Transactional`이 사용되는 이유가 있을까요?

2024-07-11 05:41 UTC, dc-choi commented on src/main/java/gift/domain/Member.java
> +    public void setEmail(String email) {
특별히 setter를 사용하시는 이유가 있을까요?

2024-07-11 07:23 UTC, ariimo commented on src/main/java/gift/domain/Product.java
> +    @Column(nullable = false)
넵 수정완료했습니다!

2024-07-11 07:25 UTC, ariimo commented on src/main/java/gift/repositories/WishRepository.java
> +    @Query("SELECT w FROM Wish w WHERE w.memberId = :memberId")
JPA에 ID가 아닌 특정 칼럼을 기준으로 Wish 를 찾는 메서드가 없는 줄 알고 선택했던 방법입니다. 멘토님의 리뷰를 보고 다시 좀 찾아보니 있더군요...하하 이 부분도 수정했습니다!

2024-07-11 07:29 UTC, ariimo commented on src/main/java/gift/services/WishService.java
> +    @Transactional
음.. Wishlist E2E 테스트를 진행하며 계속 전체 테스트가 통과되지 않는 문제가 발생했습니다. 이때 이런 저런 해결 방법을 찾으며 발견했던 부분입니다. 서비스 계층에 @Transactional을 사용하면 서비스 로직에 문제가 발생했을때 관련 부분을 모두 롤백할 수 있다는 것을 알게되었고 '혹시나' 하는 마음에 시도해봤던 부분 중 하나입니다.

2024-07-11 07:43 UTC, ariimo commented on src/main/java/gift/domain/Member.java
> +    public void setEmail(String email) {
이전에 ProductControllerTest 를 실행할 때 필요해서 넣어뒀던 부분입니다. 다시 보니 수정된 Test 에서는 사용하지 않아 지웠습니다:)

2024-07-11 08:17 UTC, ariimo commented
> 멀티스레딩이라고 생각하신 이유가 있을까요? 어떤 근거로 그렇게 생각하셨는지 궁금합니다!

음.. 우선 각 Test메소드를 따로 실행했을 때는 전무 테스트가 통과되었고 문제는 전체 실행을 할 때 발생하였습니다. 그럼 각 테스트간의 충돌이 있었다는 거고 이를 @Transactional 과 @Order를 통해 테스트 실행 순서를 지정하면 해결될 것이라고 생각했었습니다. 하지만, 오류가 해결되지 않았고 자연스럽게 내부적으로 문제가 있는 게 아닌가... 라는 .... 아주 지극히 개인적인 결론에 도달하게 되었습니다...

2024-07-11 09:03 UTC, dc-choi commented on src/main/java/gift/services/WishService.java
> +    @Transactional
직접 찾아본 것은 훌륭합니다. 하지만 이 부분은 다음주에 학습하는 영역이라 아직은 안하셔도 될 것으로 보입니다!

2024-07-11 09:07 UTC, dc-choi requested changes
> 음.. 우선 각 Test메소드를 따로 실행했을 때는 테스트가 전부 통과되었고 문제는 전체 실행을 할 때 발생하였습니다. 그럼 각 테스트간의 충돌이 있었다는 거고 이를 @transactional 과 @order를 통해 테스트 실행 순서를 지정하면 해결될 것이라고 생각했었습니다. 하지만, 오류가 해결되지 않았고 자연스럽게 내부적으로 문제가 있는 게 아닌가... 라는 .... 아주 지극히 개인적인 결론에 도달하게 되었습니다...

테스트 코드를 확인하였습니다. 제 생각에는 멀티스레딩 문제에서 발생한게 아니라 테스트가 서로 종속적이여서 문제가 발생한걸로 보입니다.

현재 테스트가 DB를 바라보고 데이터 베이스의 PK는 auto_increment를 통해 계속 PK가 달라지는 상황입니다.

현재 코드 상에서는 PK를 일일히 입력하는 것으로 보이는데, 일일히 입력하지 마시고 `@BeforeEach`를 사용해서 필요한 데이터를 가져오는 것을 추천드립니다.

그래야 생각하시는 문제가 해결될 것으로 보입니다.

> 실패 케이스에 대한 테스트 작성은 step2와 함께 진행해도 될까요??

네 그렇게 해주세요!

2024-07-11 12:55 UTC, ariimo commented on src/main/java/gift/services/WishService.java
> +    @Transactional
본의 아니게 예습을 했군요!! 하하! 우선 지우도록 하겠습니다.

2024-07-11 17:33 UTC, ariimo commented
Test간의 종속성을 없애기 위해 각 Test마다 따로 Member와 Product를 추가하여 WishControllerTest 오류를 해결했습니다. 음.. 근데 문제는 service계층에서 @Transactional이 적용되어야만, deleteWishTest가 진행됩니다... 
제가 JPA를 다루는 게 처음이라서, 솔직히 말씀드리면 '왜 service 계층에서 @Transactional이 있어야만 하는지'에 대한 정확한 원인을 아직 파악하지 못했습니다. 이 부분은 이후 과제를 수행하며 차근차근 찾아나가도록 하겠습니다. (마감 시간이 얼마 남지 않아, 이번 주 과제 수행이 우선인 것 같습니다ㅠㅠ)

2024-07-12 01:34 UTC, dc-choi approved these changes
> Test간의 종속성을 없애기 위해 각 Test마다 따로 Member와 Product를 추가하여 WishControllerTest 오류를 해결했습니다. 음.. 근데 문제는 service계층에서 `@transactional`이 적용되어야만, deleteWishTest가 진행됩니다... 제가 JPA를 다루는 게 처음이라서, 솔직히 말씀드리면 '왜 service 계층에서 `@transactional`이 있어야만 하는지'에 대한 정확한 원인을 아직 파악하지 못했습니다. 이 부분은 이후 과제를 수행하며 차근차근 찾아나가도록 하겠습니다. (마감 시간이 얼마 남지 않아, 이번 주 과제 수행이 우선인 것 같습니다ㅠㅠ)

동의합니다. 다행히 요구사항은 어느정도 충족하는 것으로 보아 이 부분은 넘어가도 될 것으로 보입니다.

다음주에 배우는걸 미리 예습하신걸로 생각하시죠~! `@transactional` 부분은 넘어가도록 하겠습니다!

2024-07-12 01:34 UTC, merged