경북대 BE_김민주 3주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #207
Opened 2024-07-10 14:37 UTC by minju26

2024-07-12 12:41 UTC, gongdongho12 requested changes
레포지토리를 쓰기 시작했으면 전부 한꺼번에 바꿔주셔야 해요
엔티티를 사용하는 객체를 JDBC에서 그대로 쓰고 있는 상황이라서요
이부분 통일하고 다시 업데이트 부탁드립니다

나머지는 잘 반영해주셨어요 👍🏼

2024-07-12 12:41 UTC, gongdongho12 commented on src/main/java/gift/constant/Path.java
> +    public static final String MANAGE_PRODUCT = "/api/manage/products";
path와 page는 구분해주는거 어떨까요?

2024-07-12 12:41 UTC, gongdongho12 commented on src/main/java/gift/domain/Wish.java
> +    private Product product;
나중에 직접 데이터 접근해야 조회되는 lazy 사용 👍🏼

2024-07-12 12:41 UTC, gongdongho12 commented on src/main/java/gift/repository/jdbcTemplate/AuthRepository.java
> +    }
DB 접근을 두가지 사용하고 있는데요, JPA를 사용중이시면 옮겨주는게 좋은 방향입니다!

2024-07-12 12:41 UTC, gongdongho12 commented on src/main/java/gift/domain/Product.java
> +public class Product {
이미 엔티티로 DAO로 접근하는데 JDBC로 조회하고 있는 상황이에요
이 PR에서 JPA로 통일시켜서 업데이트 부탁드립니다

2024-07-12 12:41 UTC, gongdongho12 commented on src/main/resources/db/schema.sql
> +)
JPA 엔티티 선언시 스키마 자동생성을 이용해보면 어떨까요?

2024-07-13 06:49 UTC, minju26 commented
> 레포지토리를 쓰기 시작했으면 전부 한꺼번에 바꿔주셔야 해요 엔티티를 사용하는 객체를 JDBC에서 그대로 쓰고 있는 상황이라서요 이부분 통일하고 다시 업데이트 부탁드립니다
> 
> 나머지는 잘 반영해주셨어요 👍🏼

 JPA로 리팩토링 하면서, JDBC 코드(메서드)를 사용하진 않지만 삭제를 해야하나.. 고민하다가 그대로 두었습니다. 깔끔하게 정리하도록 하겠습니다! 😊

2024-07-13 06:49 UTC, minju26 commented on src/main/resources/db/schema.sql
> +)
넵 알겠습니다!

2024-07-13 06:50 UTC, minju26 commented on src/main/java/gift/constant/Path.java
> +    public static final String MANAGE_PRODUCT = "/api/manage/products";
네! 구분하도록 하겠습니다 :)

2024-07-14 16:03 UTC, gongdongho12 approved these changes
고생하셨습니다

2024-07-14 16:03 UTC, merged