경북대 BE_심규민 3주차 과제 (3단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #238
Opened 2024-07-11 07:10 UTC by sim-mer

- 상품, 위시리스트 조회 API에 페이지네이션을 적용하였습니다.
- JPA, 페이지네이션 적용으로 인해 테스트코드를 수정하였습니다.
- JpaRepository 테스트 코드를 작성하였습니다.

2024-07-11 13:29 UTC, leaf-upper requested changes
안녕하세요 규민님 벌써 3단계네요~
몇가지 코멘트를 남겨드렸는데 이부분만 작업해주시면 바로 어프로브 드리겠습니다
고생하셨습니다 👍

2024-07-11 13:29 UTC, leaf-upper commented on src/main/java/gift/member/business/service/WishlistService.java
> +        PageRequest pageRequest = PageRequest.of(page, 20);
size도 Controller에서 전달받는건 어떨까요? 다만, size의 최대 개수에 대해서는 validation을 하는식으로요~

2024-07-11 13:29 UTC, leaf-upper commented on src/main/java/gift/member/business/service/WishlistService.java
> +        PageRequest pageRequest = PageRequest.of(page, 20);
paging은 정렬순서가 굉장히 중요한데요~ 정렬 방식 또한 Controller에서 전달받을 수 있을것 같아요
또한 정렬 기준을 만들어야할것 같은데 현재 위시리스트에 관련 정보를 넣어보는건 어떨까요?
ex) 생성시각, 변경 시각

2024-07-11 13:29 UTC, leaf-upper commented on src/main/java/gift/member/business/service/WishlistService.java
> +        PageRequest pageRequest = PageRequest.of(page, 20);
또한 정렬을 할때 데이터베이스 인덱스에 대해서도 같이 알아보시면 좋을것 같습니다

2024-07-12 13:33 UTC, sim-mer commented on src/main/java/gift/member/business/service/WishlistService.java
> +        PageRequest pageRequest = PageRequest.of(page, 20);
BaseTimeEntity와 Jpa Auditing으로 생성, 수정시간 관리하도록 추가하였고 default 정렬로 생각한 수정 시간에 index를 추가하였습니다! 그리고 @PageableDefault 메서드로 컨트롤러에서 직접 여러 파라미터로 Pageable 객체를 입력받도록 변경하였고 size의 경우엔 validation을 설정했습니다!

2024-07-12 13:56 UTC, sim-mer commented
### 궁금한 점
- Jpa는 기본적으로 non-clustered index를 사용한다던데 그럼 실제로 clustered index를 사용하는 경우는 직접 db에 접근해서 인덱스를 설정하나요?
- clustered index는 정렬되었기에 검색 작업에는 성능상 이점이 있지만 삽입, 삭제에는 많은 시간이 소요된다는데 주로 어떤 데이터에 사용하는 지 궁금합니다!

2024-07-13 15:28 UTC, leaf-upper approved these changes
코드는 너무 잘작성해주셔서 어프로브 드릴게요!
고생하셨습니다!
질문에 대해서는 답변드릴게요~

Jpa는 기본적으로 non-clustered index를 사용한다던데 그럼 실제로 clustered index를 사용하는 경우는 직접 db에 접근해서 인덱스를 설정하나요?
clustered index는 정렬되었기에 검색 작업에는 성능상 이점이 있지만 삽입, 삭제에는 많은 시간이 소요된다는데 주로 어떤 데이터에 사용하는 지 궁금합니다!

---

음 제가 생각하고 있는 클러스터링 인덱스와 논 클러스터링 인덱스는 사실 JPA와 관련이 없는 부분인것 같아요. (혹시 관련해서 참조하신 사이트나 자료가 있으면 공유 부탁드립니다 ㅎㅎ..)

간단하게 말해서 인덱스는 데이터베이스에서 쓰기성능을 포기하고, 읽기성능을 향상시키기 위해서 사용해요~ 그렇기 때문에 당연하게도 인덱스는 DB에서 직접 생성하게 됩니다. 저는 아직 JPA에서 인덱스를 생성하는 경우는 보지 못했어요 (DDL 매핑으로 생성할수도 있겠지만, 이렇게 사용하시는분은 아직까지는 보진 못한것 같아요)  인덱스는 중요하기도하고, 사용에 주의를 해야하기 때문입니다.

그렇다면 클러스터링 인덱스랑 논클러스터링 인덱스 이야기가 왜 나왔을지 궁금해요~ 클러스터링 인덱스는, MySQL InnoDB Engine에서 사용하는데요, 쉽게 말하면 PK 인덱스입니다. PK를 기준으로 실제 데이터가 파일시스템에서 정렬되어 저장되게 되어요~ 그렇기 때문에 PK를 기준으로 데이터를 읽으면 굉장히 빠르게 데이터를 읽으실 수 있습니다. 그렇다면 사용자가 PK를 쓰지않는경우는 어떻게될까요? -> 이경우 내부적으로 PK를 생성해서 사용합니다. PK를 사용하지 않아도 내부적으로 차지하는 데이터의 크기는 비슷하기때문에 PK를 대부분의 경우 그냥 사용하시는게 좋은것 같아요~
논클러스터링 인덱스는 보통 세컨더리 인덱스라고 불려요. 이건 소위말하는 사용자가 생성하는 인덱스이구요, 예를들어 상품을 이름순으로 정렬하고 싶다면, 이름에 대해 인덱스를 거는거에요
세컨더리를 기준으로 데이터를 정렬하지만 세컨더리 인덱스 B-Tree의 리프노드에는 실제 데이터가 있는게 아니라, PK가 있다고 생각해주시면 좋을것 같아요.
그래서 세컨더리 인덱스는 조회할때 사실
세컨더리 인덱스 -> 클러스터링 인덱스 -> 실제 데이터 
이렇게 데이터가 조회되게 됩니다. 

---

위 사항의 지식을 기반으로 답변드리자면,
클러스터링 인덱스든 논클러스터링인덱스든 결국 쓰기 성능에 대해 어느정도 성능 저하를 감수하고 읽기 성능을 키우는데 사용됩니다.
클러스터링 인덱스는 무조건 생성되기 때문에 어떤 데이터는 사실 크게 중요하지 않습니다.
더 궁금하신것 있으시면 질문부탁드려요~ 고생하셨습니다 👍

2024-07-13 15:29 UTC, merged