경북대 BE_이지호_3주차 과제(2단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #248
Opened 2024-07-11 09:24 UTC by GitJIHO

**코드 작성하면서 어려웠던 점**
---

- 2단계 자체는 생각보다 JPA에서 처리해주는 부분들이 많아서 크게 어렵지 않았습니다.
- 1단계 pr 코멘트 남겨주신것 기반으로 step2에 수정사항을 commit 하였는데, repository와 service단에서 Optional을 사용하는것이 익숙치 않아 제대로 작성한지 헷갈렸습니다. 또한 Optional을 사용했을 때 오는 장점이 와닿지 않았는데 혹시 관련 자료나 설명이 듣고 싶습니다..!!

**코드 리뷰 시, 멘토님이 중점적으로 리뷰해주셨으면 하는 부분**
---

- 연관관계 매핑을 한 후 수정한 repository와 service부분의 코드가 잘 수정되었는지 궁금합니다.
- ProductRequest DTO를 추가하였는데, 혹시 ProductResponse DTO도 필요할까요? 필드항목이 같아 일단은 Product entity가 그 역할을 대신하도록 구성하였습니다.

2024-07-11 14:39 UTC, sang5c requested changes
작성하신 코드를 병합하는 과정에서 일부 코드가 제대로 반영되지 않은걸로 보여 Request Change를 드려요!  

지금은 일단 작동하도록 고쳐주시고, 다음 단계부터는 링크를 참고하셔서 rebase를 해보시면 좋을 것 같아요.
https://youtu.be/b72mDco4g78  

> Optional 장점?

데이터베이스를 통해 데이터를 조회했는데 null인 경우, Optional을 사용함으로써 객체가 null이 될 수 있음을 알린다고 생각하시면 됩니다. findByXxx() 메서드를 통해 반환되는 값이 항상 있다고 볼 수 없어요.
```
// 저장하지 않고 조회
Wish wish = wishRepository.findByNumber(1);
wish.getNumber() // NPE 발생
```

> 연관관계 매핑을 한 후 수정한 repository와 service부분의 코드가 잘 수정되었는지 궁금합니다.

리뷰 남겼으니 확인해주시고, 일부 코드가 누락된 것 같아 다시 요청해주세요!

> ProductRequest DTO를 추가하였는데, 혹시 ProductResponse DTO도 필요할까요? 필드항목이 같아 일단은 Product entity가 그 역할을 대신하도록 구성하였습니다.

entity를 반환하게 되면 entity의 변화(이름 변경, 컬럼 추가 등)에 response가 영향받습니다.  
반대로 response에만 필요한 값이 있을 때 entity에 추가하게되면 entity가 관련 없는 값을 가져야 합니다.  
이를 DTO하나를 둠으로써 예방한다고 생각하시면 됩니다.

---

혹시 저번 PR에서 해결되지 않은 질문이 있으면 이곳에 다시 남겨주세요!

2024-07-11 14:39 UTC, sang5c commented on src/main/java/gift/entity/Product.java
>      private String name;
size가 제거되면 요구사항을 만족할 수 없게돼요. 
```
    name      varchar(15)  not null,
```

2024-07-11 14:39 UTC, sang5c commented on src/main/java/gift/entity/Product.java
> +    private List<Wish> wishes;
NPE를 방지하기 위해 생성까지 해주는 편입니다.
```suggestion
    private List<Wish> wishes = new ArrayList();
```

2024-07-11 14:39 UTC, sang5c commented on src/main/java/gift/entity/Wish.java
> +    @JoinColumn(name = "productId")
`@JoinColumn`의 name은 데이터베이스에서 사용되는 열의 이름을 그대로 사용하는 편이에요.

2024-07-11 14:39 UTC, sang5c commented on src/test/java/gift/repository/WishRepositoryTest.java
> +        Wish updatedWish = wishRepository.findByUserIdAndId(user.getId(), savedWish.getId()).orElse(null);
null을 반환한 다음 null인지 확인하는 방식은 좋지 않다고 생각합니다.  
```
        assertThat(wish)
                .isPresent()
                .hasValueSatisfying(wish ->
                        assertThat(wish.getNumber()).isEqualTo(30)
                );
```

이렇게도 작성해볼 수 있겠네요.

2024-07-11 14:39 UTC, sang5c commented on src/test/java/gift/repository/WishRepositoryTest.java
> +        List<Wish> wishes = wishRepository.findByUserId(user.getId()).orElse(null);
요기도 null 반환은 좋지 못하다고 생각해요~

2024-07-11 14:39 UTC, sang5c commented on src/main/java/gift/repository/WishRepository.java
> +    Optional<List<Wish>> findByUserId(Long userId);
List를 반환하는 경우 null을 반환하지 않아요. Optional로 감싸지 않고 사용합니다.
```suggestion
    List<Wish> findByUserId(Long userId);
```

2024-07-11 14:39 UTC, sang5c commented on src/main/java/gift/entity/Wish.java
> +    @JoinColumn(name = "productId")
추가로, 외래키 이름도 설정해보면 어떨까요?

2024-07-11 14:39 UTC, sang5c commented on src/main/java/gift/entity/Wish.java
>      public Wish() {
public으로 열려있네요!

2024-07-11 16:54 UTC, GitJIHO commented on src/main/java/gift/entity/Wish.java
>      public Wish() {
엇 무슨 의미인지 잘 모르겠습니다 기본 생성자가 private로 닫혀 있어야 한다는 뜻인가요?!

2024-07-11 16:55 UTC, GitJIHO commented on src/main/java/gift/entity/Product.java
>      private String name;
pattern은 ProductRequest에 추가했는데 맞을까요?

2024-07-11 17:01 UTC, GitJIHO commented on src/main/java/gift/entity/Wish.java
> +    @JoinColumn(name = "productId")
Hibernate: 
    alter table if exists wishes 
       add constraint FKef34opvvpteniel93u4hikth3 
       foreign key (product_id) 
       references products
Hibernate: 
    alter table if exists wishes 
       add constraint FKh4fwumji30i8f8lt9gnhqxjy7 
       foreign key (user_id) 
       references users

현재 로그가 이렇게 뜨는데 그럼 JoinColumn을 통해 외래키까지 설정해준게 아닌가요??

2024-07-11 17:08 UTC, GitJIHO commented
머지되기 전에 다음 단계를 진행하기 위해 새 브렌치를 만들고 아직 머지 전이기 때문에 upstream을 통해 리베이스 하는 것이 아닌 로컬 이전 브렌치를 pull하여 진행하였는데, 이전 브렌치의 커밋 기록들을 정리하기 위해 
`git rebase -i HEAD~{커밋 개수}`
을 하여 명시적으로 첫번째 커밋을 제외하고 squash로 압축해주었는데 혹시 그게 문제일까요? ㅠ
아니면 충돌을 수동으로 잡는 과정에서 제가 빠트린걸까요

2024-07-11 17:10 UTC, GitJIHO commented
> 저번 pr 질문입니다!

WishRepositoryTest의 
```
 @Test
    @DisplayName("updateWishNumber JPQL 테스트")
    void updateWishNumber() {
        Wish wish = new Wish(user, product1, 10);
        Wish savedWish = wishRepository.save(wish);
        wishRepository.updateWishNumber(user.getId(), savedWish.getId(), 30);
        entityManager.flush();
        entityManager.clear();

        Wish updatedWish = wishRepository.findByUserIdAndId(user.getId(), savedWish.getId()).orElse(null);

        assertThat(updatedWish.getNumber()).isEqualTo(30);
    }
```

해당 테스트 코드를 작성했을 때의 목적은 위시리스트에서의 number변화를 JPA가 제대로 감지하는지를 test하고자 하는 목적이 아닌,
wishRepository의 updateWishNumber jpql를 검증하는 의도였습니다.

updateWishNumber는 영속성 콘텍스트에 등록된 객체의 필드값을 변경하는것이 아닌 Modifying을 통해 직접 db를 다루는 메서드로 설계되었기 때문에 테스트코드 내에서 dirty checker에 걸리지 않을 것으로 생각됩니다.

그러면 setter를 통해 영속성 콘텍스트에 등록된 값을 명시적으로 변경해야할 것 같은데 이는 검증 원하는 jpql을 테스트하는것이 아니라 적용하지 않았습니다!

혹시 해당 jpql을 통해 영속성 콘텍스트 내의 값을 변경하여 dirty checking을 이용할 수 있게 하는 방법이 있을까요?

2024-07-13 17:49 UTC, sang5c approved these changes
테스트가 실패하고 있으니 확인해주세요!  
나머지 리뷰는 3단계에서 이어서 진행하겠습니다 :)  

> rebase 관련

스쿼시를 직접 하셔서 문제가 되는 것 같네요.  
리베이스는 머지가 되고 나서 remote githijo 브랜치를 대상으로 수행하시면 됩니다.  
머지 과정에서 squash merge를 사용하고 있어 커밋 로그가 하나로 정리되니, 이후에 진행하시면 문제 없으실거에요.

> WishRepository 관련

질문주신 내용은 미션의 범위를 벗어나서 따로 답변드리지 않습니다 :)  
이번 미션에서는 UPDATE 쿼리를 직접 작성하는 대신 객체의 상태를 변화시키고 이로 인해 자동으로 실행되는 쿼리문이 어떻게 실행되는지 확인하는 방향으로 진행하길 유도하는 리뷰였습니다.

2024-07-13 17:49 UTC, sang5c commented on src/main/java/gift/entity/Product.java
>      private String name;
요구사항을 다시 천천히 읽어보시고, 
1. 작성하신 코드로 인한 결과물이 로그로 어떻게 출력되는지
2. 출력되는 DDL이 요구사항과 일치하는지 확인해주세요

2024-07-13 17:49 UTC, sang5c commented on src/main/java/gift/entity/Wish.java
>      public Wish() {
1. 이 생성자는 왜 필요한가
2. 접근제어자는 어떻게 설정하는 것이 좋은가

단계로 접근해보면 좋겠네요.  
https://www.inflearn.com/questions/594179/%EC%83%9D%EC%84%B1%EC%9E%90-%EC%97%90%EB%9F%AC-%EB%B0%9C%EC%83%9D%ED%95%A9%EB%8B%88%EB%8B%A4

2024-07-13 17:49 UTC, sang5c commented on src/main/java/gift/entity/Wish.java
> +    @JoinColumn(name = "productId")
외래키 `이름`을 바꿔보는게 어떤가에 대한 댓글이었습니다. 필수는 아니고 시도해보시면 좋을 것 같아 남긴 리뷰입니다.

2024-07-13 17:50 UTC, merged

2024-07-13 17:57 UTC, sang5c commented
수정됐는데 제쪽에서 풀을 제대로 안받았네요! 리뷰를 조금 수정할게요 잠시만 기다려주세요.

2024-07-13 17:59 UTC, sang5c commented
고생하셨습니다👍  
3단계에서 나머지 리뷰 진행할게요~