전남대 BE_안원모_3주차 과제(0,1단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #251
Opened 2024-07-11 11:46 UTC by Wonmoan

### 2주차 과제 step3의 코멘트 부분을 수정해서 반영했습니다. 

###  테스트에서 미흡한 부분이 있으면 피드백 주시면 감사하겠습니다!

### 질문
아래와 같이 wish 를 조회하면 상품 정보들이 뜨는데 member에 관한 정보도 반환 되야할지 여쭤봅니다.
![image](https://github.com/kakao-tech-campus-2nd-step2/spring-gift-jpa/assets/102709424/29ea383e-4914-414f-8297-19694f9ea1e2)

감사합니다.

2024-07-11 11:54 UTC, Wonmoan reviewed
추가로 layered architecture 패키지 구조 반영해서 코드 정리하였습니다.

2024-07-11 11:54 UTC, Wonmoan commented on src/main/java/gift/controller/MemberController.java
> +    }
Q.else 사용을 지양하는 방식으로 해당 로직을 리팩토링 해보도록 하죠.

RE : 조건 검사를 별도의 메서드로 분리해서 코드 리팩토링 하였습니다.

2024-07-11 11:54 UTC, Wonmoan commented on src/main/java/gift/exception/GlobalExceptionHandler.java
> +    }
`RuntimeException` 사용 시 발생할 수 있는 단점을 보완하기 위해 
클라이언트 에게 전송하는 예외 메시지는 추상화하는 방향으로 전달하고 
내부적으로 로그를 남겨 개발자에게는 상세한 정보를 확인 할 수 있도록, 코드 리펙토링 하였습니다.

2024-07-11 11:54 UTC, Wonmoan commented on src/main/java/gift/service/JwtService.java
> +    }
`java.util.Base64.getDecoder().decode(secretKey)`와 `Keys.hmacShaKeyFor(keyBytes)`를 Base64 디코딩하여 관리하는 최신 방식을 사용하여 키를 생성했습니다.

2024-07-11 11:54 UTC, Wonmoan commented on src/main/java/gift/service/JwtService.java
> +    }
기존의  `.signWith(key, SignatureAlgorithm.HS256)` 에서`.signWith(SigningKey())`으로 서명 알고리즘 변경하여 적용했습니다.

2024-07-11 11:54 UTC, Wonmoan commented on src/main/java/gift/exception/GlobalExceptionHandler.java
> +        return ResponseEntity.badRequest().body(error);
`ResponseEntity`가 사용되는 곳을 `ResponseEntity.badRequest()`활용해서 방법을 통일했습니다.

2024-07-11 11:54 UTC, Wonmoan commented on src/main/java/gift/controller/WishController.java
> +    }
예외 처리 메서드는 ResponseEntity.badRequest() 활용하여 통일 했고,
문제가 생겼을 때의 응답을 만드는건 GlobalExceptionHandler 에서 하도록 wishController 클래스도 수정해 반영했습니다.

2024-07-12 10:20 UTC, pkeugine requested changes
안녕하세요 원모님,
미션 잘 진행해주시고 있습니다.
일단 change request 로 두고, 리뷰 확인한 뒤에 다음 스텝으로 넘어가보아요.
각 코멘트에 **모두** 답변 달아주세요!

2024-07-12 10:20 UTC, pkeugine commented on src/main/java/gift/config/DataLoader.java
> +    public void run(String... args) throws Exception {
사용하지 않는 throws 는 제거해주세요.

2024-07-12 10:20 UTC, pkeugine commented on src/main/java/gift/config/DataLoader.java
> +    }
data.sql 과 해당 방식을 함께 사용하게 된 이유가 궁금해요.

2024-07-12 10:20 UTC, pkeugine commented on src/main/java/gift/controller/MemberController.java
> +            logger.debug("Register - Generated Token: " + response.get("token"));
```suggestion
            logger.debug("Register - Generated Token: {}", response.get("token"));
```

이런 방식을 사용해볼 수도 있어요.
다른 곳들도 확인해주세요.

2024-07-12 10:20 UTC, pkeugine commented on src/main/java/gift/controller/MemberController.java
> +        }
예외를 잡아서 다시 runtime exception 으로 바꿔주시는 이유가 궁금합니다.

2024-07-12 10:20 UTC, pkeugine commented on README.md
> +- 테이블에서는 외래 키를 사용
단계별로 하나의 PR 을 올려주셔야 합니다.
절차를 따라주세요.

2024-07-12 10:20 UTC, pkeugine commented on src/main/java/gift/controller/MemberController.java
> +        Optional<Member> foundMemberOpt = memberService.getMemberByEmail(member.getEmail());
줄임말은 사용하지 말아주세요.

2024-07-12 10:20 UTC, pkeugine commented on src/main/java/gift/controller/MemberController.java
> +    }
Optional 의 `orElseThrow` 도 활용해보면 좋겠네요.

2024-07-12 10:20 UTC, pkeugine commented on src/main/java/gift/util/LoginMemberArgumentResolver.java
> +    }
`@Autowired` 관련 리뷰가 이전엔 없었나요...?
과거 리뷰 중 어떤 걸 남겼고... 어떤게 반영되었는지 이젠 확인하기가 너무 힘드네요.

예전에 남겨놨군요...
https://github.com/kakao-tech-campus-2nd-step2/spring-gift-product/pull/183#discussion_r1659674666
한 번 확인해주세요.

2024-07-12 10:20 UTC, pkeugine commented on src/main/java/gift/util/LoginMemberArgumentResolver.java
> +    public Object resolveArgument(MethodParameter parameter, ModelAndViewContainer mavContainer, NativeWebRequest webRequest, WebDataBinderFactory binderFactory) throws Exception {
줄바꿈을 활용해볼 수 있을 것 같고,
불필요한 throws 는 제거하면 좋을 것 같아요.

2024-07-12 10:20 UTC, pkeugine commented on src/main/java/gift/controller/ProductWebController.java
> +    public String editProduct(@RequestParam Long id, @RequestParam String name, @RequestParam BigDecimal price, @RequestParam String imageUrl) {
path 에 id 가 있는데 request param 으로 한 번 더 받을 필요는 없을 것 같아요.

2024-07-12 10:20 UTC, pkeugine commented on src/main/java/gift/controller/WishController.java
> +        }
member 가 null 인 상태로 들어와서 controller 쪽에서 예외를 던지기보단,
아예 resolver 자체에서 예외를 던져보는건 어떨까요?
이는 어떤 차이가 있을지도 답변 남겨주세요.

2024-07-12 10:20 UTC, pkeugine commented on src/main/java/gift/domain/Member.java
> +    }
JPA, 검증 등... Member 가 너무 많은 기능을 담당하는 것 같은데,
dto 를 따로 하나 만들어보는 것이 좋을 것 같네요.
다른 도메인들도 마찬가지구요!

2024-07-12 10:20 UTC, pkeugine commented on src/main/java/gift/exception/GlobalExceptionHandler.java
> +    }
`Exception` 도 있네요!

2024-07-12 10:20 UTC, pkeugine commented on src/main/java/gift/service/JwtService.java
> +    }
사용하지 않는 메서드는 제거해주세요.

2024-07-12 10:20 UTC, pkeugine commented on src/main/java/gift/service/JwtUtil.java
> +            logger.error("Error parsing token", e);
전반적으로 로깅을 해주고 계시네요!
로깅은 꽤나 비싼 작업인데요, 한 번 로깅해주시는 것들을 잘 확인해보고,
정말 필요한 것들만 해보는건 어떨까요?

2024-07-12 10:20 UTC, pkeugine commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=update
해당 설정은 무엇을 하며, `update` 로 둔 이유는 무엇인가요?

2024-07-12 10:20 UTC, pkeugine commented on src/test/java/gift/WishRepositoryTest.java
> +        Product product = productRepository.save(new Product.ProductBuilder().name("Product1").price(BigDecimal.valueOf(10.00)).imageUrl("http://example.com/product1.jpg").description("Description fo
줄바꿈해주세요.
밑에 있는 메서드도...!

2024-07-12 10:20 UTC, pkeugine commented on src/test/java/gift/MemberRepositoryTest.java
> +class MemberRepositoryTest {
Repository 테스트를 작성하시게 된 이유가 궁금해요.
테스트는 여러 종류가 있으니까요.

2024-07-12 10:20 UTC, pkeugine commented on src/main/java/gift/domain/Wish.java
> +    @JoinColumn(name = "member_id", nullable = false)
`FetchType.LAZY` 로 설정하신 이유가 궁금합니다.

2024-07-12 10:20 UTC, pkeugine commented on src/main/java/gift/domain/Product.java
> +    private List<Wish> wishes;
해당 필드를 두신 이유가 궁금하네요!
각 설정에 대해서도 한 번 설명해주시죠!!

2024-07-13 07:40 UTC, Wonmoan commented on src/main/java/gift/controller/MemberController.java
> +    }
```
private Member getValidMember(Member member) {
        Member foundMember = memberService.getMemberByEmail(member.getEmail())
                .orElseThrow(() -> new IllegalArgumentException("Invalid email or password"));

        if (!isPasswordValid(foundMember, member.getPassword())) {
            throw new IllegalArgumentException("Invalid email or password");
        }

        return foundMember;
    }
```
`getValidMember` 메서드에 `orElseThrow`를 사용하여 예외를 던지도록 반영해 보았습니다.

2024-07-13 07:50 UTC, Wonmoan commented on src/main/java/gift/config/DataLoader.java
> +    public void run(String... args) throws Exception {
다음 step에 반영했습니다.

2024-07-13 07:55 UTC, Wonmoan commented on src/main/java/gift/config/DataLoader.java
> +    }
음 .. 다음 step인 step3 에서 페이지네이션 작성하여 확인할 때  편의성을 위해 작성하였습니다. 
data.sql에는 현재 product2 까지 2개의 상품으로 초기 데이터가  작성 되어 있는데, 
이 경우,  상품 여러개를 추가하여 페이지네이션 작동을 확인 할 때 data.sql파일을 업데이트를 계속해서 해줘야 할 것 같아 해당 방식을 사용하였습니다.

2024-07-13 08:03 UTC, Wonmoan commented on src/main/java/gift/controller/MemberController.java
> +            logger.debug("Register - Generated Token: " + response.get("token"));
반영했습니다. 
불필요한 문자열 결합 연산을 피하여 성능을 향상 시킬 수 있는 법을 확인했습니다.

2024-07-13 08:27 UTC, Wonmoan commented on src/main/java/gift/controller/MemberController.java
> +        }
음.. `exception`을 잡아서 다시 `RuntimeException`으로 예외를 잡아서 다시 던지면서
예외 메시지를 추가하거나 로깅을 통해 디버깅 정보를 더 자세하게 나타내보려 했습니다. 
변경하는 편이 코드 가독성에 더 도움이 된다면 변경하겠습니다.

2024-07-13 08:32 UTC, Wonmoan commented on src/main/java/gift/controller/MemberController.java
> +        Optional<Member> foundMemberOpt = memberService.getMemberByEmail(member.getEmail());
`Optional` 의 `orElseThrow` 피드백 반영하면서  해당 사항 수정했습니다.

2024-07-13 08:35 UTC, Wonmoan commented on src/main/java/gift/util/LoginMemberArgumentResolver.java
> +    }
확인했습니다. 전체적으로 코드 다시 한번 확인해서 수정했습니다.

2024-07-13 08:39 UTC, Wonmoan commented on src/main/java/gift/util/LoginMemberArgumentResolver.java
> +    public Object resolveArgument(MethodParameter parameter, ModelAndViewContainer mavContainer, NativeWebRequest webRequest, WebDataBinderFactory binderFactory) throws Exception {
다음 step에 반영했습니다.

2024-07-13 08:46 UTC, Wonmoan commented on src/main/java/gift/controller/ProductWebController.java
> +    public String editProduct(@RequestParam Long id, @RequestParam String name, @RequestParam BigDecimal price, @RequestParam String imageUrl) {
`@PathVariable`으로 변경했습니다. 
```
public String editProduct(@PathVariable Long id,
 @RequestParam String name, @RequestParam BigDecimal price,
 @RequestParam String imageUrl)
```

2024-07-13 09:31 UTC, Wonmoan commented on src/main/java/gift/controller/WishController.java
> +        }
컨트롤러에서 예외를 던지게 되면 각 컨트롤러 메서드(`getWishes`,`addWish`,`removeWish`)에서
member가 null인지 확인하고 예외를 던져야 함으로 중복이 발생 합니다.

resolver에서 `member`가 `null` 에서 예외를 던지도록 처리하면 중복된 null 체크를 제거 할 수 있을 것 같습니다. 

LoginMemberArgumentResolver 에서 `member`가 `null`인 경우 예외를 던지도록 수정하였고 
WishController에서 `member`가 `null`인지 확인하는 부분을 제거했습니다. 
예)
```
 if (authorizationHeader == null) {
            logger.warn("Authorization header is missing");
            throw new IllegalArgumentException("Authorization header is missing"); 
        }
if (!authorizationHeader.startsWith("Bearer ")) {
    logger.warn("Authorization header is invalid");
    throw new IllegalArgumentException("Authorization header is invalid"); 
} ...

```

2024-07-13 09:56 UTC, Wonmoan commented on src/main/java/gift/domain/Member.java
> +    }
각 도메인은 jpa 데이터베이스 매핑을 담당하고,
DTO 생성하여 데이터 전송과 검증을 할 수 있도록 분리하였습니다.
해당 내용 변경하여 다음 step에 적용하였습니다.

2024-07-13 09:57 UTC, Wonmoan commented on src/main/java/gift/domain/Member.java
> +    }
```
package gift.domain;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import java.util.List;

@Entity
@Table(name = "member", uniqueConstraints = {@UniqueConstraint(columnNames = "email")})
public class Member {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false, unique = true)
    private String email;

    @Column(nullable = false)
    private String password;

    @JsonIgnore
    @OneToMany(mappedBy = "member", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<Wish> wishes;

    protected Member() {
    }

    private Member(MemberBuilder builder) {
        this.id = builder.id;
        this.email = builder.email;
        this.password = builder.password;
        this.wishes = builder.wishes;
    }

    public Long getId() {
        return id;
    }

    public String getEmail() {
        return email;
    }

    public String getPassword() {
        return password;
    }

    public static class MemberBuilder {
        private Long id;
        private String email;
        private String password;
        private List<Wish> wishes;

        public MemberBuilder id(Long id) {
            this.id = id;
            return this;
        }

        public MemberBuilder email(String email) {
            this.email = email;
            return this;
        }

        public MemberBuilder password(String password) {
            this.password = password;
            return this;
        }

        public MemberBuilder wishes(List<Wish> wishes) {
            this.wishes = wishes;
            return this;
        }

        public Member build() {
            return new Member(this);
        }
    }
}

```
```
package gift.dto;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;

public class MemberDTO {

    @Email(message = "유효한 이메일을 입력해주세요.")
    @NotBlank(message = "이메일은 필수 입력 항목입니다.")
    private String email;

    @NotBlank(message = "비밀번호는 필수 입력 항목입니다.")
    private String password;

    public MemberDTO() {
    }

    public MemberDTO(String email, String password) {
        this.email = email;
        this.password = password;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
}
```

2024-07-13 10:11 UTC, Wonmoan commented on src/main/java/gift/service/JwtService.java
> +    }
반영했습니다.

2024-07-13 10:36 UTC, Wonmoan commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=update
원래는 spring.jpa.hibernate.ddl-auto=none으로 해서 data.sql ,schema.sql의 값들로 작업했었지만
step3 페이지네이션을 확인하면서 많은 수의 상품들이 등록되다 보니 update로 바꾸어  동적으로 스키마 업데이트를 하다보니 update로 수정했습니다.

2024-07-13 10:36 UTC, Wonmoan commented on src/test/java/gift/WishRepositoryTest.java
> +        Product product = productRepository.save(new Product.ProductBuilder().name("Product1").price(BigDecimal.valueOf(10.00)).imageUrl("http://example.com/product1.jpg").description("Description fo
수정했습니다.

2024-07-13 10:39 UTC, Wonmoan commented on src/test/java/gift/MemberRepositoryTest.java
> +class MemberRepositoryTest {
음 .. 
데이터베이스와의 상호작용이 잘 되고 있는지 , 데이터가 올바르게 저장되고 검색되는지 확인을 먼저 하는 것이 
선물하기 기능을 구현할때 우선적으로 확인이 되어야 한다고 생각해서 repository 테스트를 먼저 작성하게 되었습니다.

2024-07-13 10:42 UTC, Wonmoan commented on src/main/java/gift/domain/Wish.java
> +    @JoinColumn(name = "member_id", nullable = false)
`FetchType.LAZY`를 사용하면 해당 연관된 엔티티가 필요할 때 로드 됨으로 
이렇게 하면 초기 로딩 시 불필요한 데이터 로드를 방지하여 필요한 시점에만 로드 함으로써
좀 더 나은 성능을 보일 것 이라 생각했습니다.

2024-07-13 10:48 UTC, Wonmoan commented on src/main/java/gift/domain/Product.java
> +    private List<Wish> wishes;
1. `@OneToMany(mappedBy = "product")` : Product 엔티티와 Wish 엔티티 간의 일대다 관계 의미 `mappedBy` 'wish'엔티티가 엔티티가 외래 키를 가지고 있음을 의미 
2. `cascade = CascadeType.ALL` :  관련된 엔티티들을 쉽게 관리하기 위해 사용 `Product` 엔티티에 대한  변경 사항이 `Wish` 엔티티에  반영되도록 하기 위해
3. `orphanRemoval = true` : `Product` 엔티티에서 `Wish` 엔티티가 제거될 때, 데이터베이스에서도 해당 `Wish` 엔티티가 삭제되도록 하기 위해

Product와 Wish의 관계를 한꺼번에 관리하고 데이터베이스 무결성 보장을 위해 작성하였습니다.

2024-07-13 13:47 UTC, Wonmoan commented on src/main/java/gift/service/JwtUtil.java
> +            logger.error("Error parsing token", e);
음 .. 정말 필요한 로깅이 무엇인지 구분이 잘 되지 않는 것 같습니다 ㅜ;; 
일단은 오류 및 예외 로깅과 등록하거나 로그인했을 때 로그를 남기는 것은 유지를 해보았습니다.
JWT 토큰이 생성되는 것은 디버깅 목적으로 유용할 수 있지만, 필수적인 것 같지 않아 토큰 생성과 같은 디버깅용 로깅은 삭제하는 방향으로 다음 step에 적용해 보았습니다.

2024-07-13 14:00 UTC, Wonmoan commented on src/main/java/gift/config/DataLoader.java
> +                .price(BigDecimal.valueOf(10.00 * i))
사용하지 않는 throws 는 제거하였습니다.

2024-07-13 14:00 UTC, Wonmoan commented on src/main/java/gift/controller/MemberController.java
> +        }
Optional 의 orElseThrow 피드백 반영하면서 줄임말은 사용도 없앴습니다.

2024-07-13 14:00 UTC, Wonmoan commented on src/main/java/gift/util/LoginMemberArgumentResolver.java
> +        String authorizationHeader = webRequest.getHeader("Authorization");
줄바꿈과 불필요한 throws 제거했습니다.

2024-07-13 14:00 UTC, Wonmoan commented on src/main/java/gift/controller/ProductWebController.java
> +        @RequestParam BigDecimal price, @RequestParam String imageUrl) {
중복된 request param사용 `@PathVariable`으로 수정했습니다.

2024-07-13 14:00 UTC, Wonmoan commented on src/main/java/gift/util/LoginMemberArgumentResolver.java
> +
member 가 null 인 경우
 resolver 자체에서 예외를 던지도록 수정했습니다.

2024-07-13 14:00 UTC, Wonmoan commented on src/main/java/gift/dto/MemberDTO.java
> +
각각의 도메인 기능을 분리해 DTO를 생성하였고 도메인은 jpa 데이터베이스 매핑 
DTO는 데이터 전송과 검증 하도록 분리하였습니다.

2024-07-13 14:00 UTC, Wonmoan commented on src/main/java/gift/service/JwtUtil.java
> +        }
오류 및 예외 로깅, 등록하거나 로그인했을때 의 로깅은 유지하고
디버깅용 로깅은 삭제하는 방향으로 적용해보았습니다.

2024-07-14 13:28 UTC, pkeugine commented on src/main/java/gift/config/DataLoader.java
> +    public void run(String... args) throws Exception {
리뷰가 달린다면 최대한 해당 PR 에 반영하길 바랍니다.

2024-07-14 13:29 UTC, pkeugine commented on src/main/java/gift/config/DataLoader.java
> +    }
하나의 방식으로 통일하는게 좋을 것 같네요.

2024-07-14 13:31 UTC, pkeugine commented on src/main/java/gift/controller/MemberController.java
> +        }
이 방식을 적용하는 경우도 있긴하지만, 지금은 말해주신
* `의미있는` 예외 메시지를 추가
* 로깅

둘 다 하지 않는 상황인 것 같아요. 가독성도 그렇지만, 불필요한 것 같다는 생각이 가장 크게 들어서
저는 변경하면 좋을 것 같네요!

2024-07-14 13:34 UTC, pkeugine commented on src/main/java/gift/util/LoginMemberArgumentResolver.java
> +    public Object resolveArgument(MethodParameter parameter, ModelAndViewContainer mavContainer, NativeWebRequest webRequest, WebDataBinderFactory binderFactory) throws Exception {
앞서 코멘트에 남겼던 것처럼,
미리 작업을 했다고 하더라도 PR 에 리뷰가 달리면 그 PR 안에서 반영되거나 의견이 달리면 좋겠습니다.

2024-07-14 13:38 UTC, pkeugine commented on src/test/java/gift/MemberRepositoryTest.java
> +class MemberRepositoryTest {
그렇군요!

2024-07-14 13:39 UTC, pkeugine commented on src/main/java/gift/domain/Wish.java
> +    @JoinColumn(name = "member_id", nullable = false)
자주 사용하는 정보라면 오히려 매번 여러번 불러와서 비효율적이기도 합니다.
현재 원모님 서비스에서는 어떤가요?
(틀렸다고 말하는거 아닙니다!)

2024-07-14 13:48 UTC, pkeugine approved these changes
안녕하세요 원모님
리뷰 반영 + 반영 사항 표시해주시느라 정말 고생 많이하셨네요.
대박입니다 👍 

이 PR 은 일단 머지하도록 할게요.
추가로 남긴 댓글은 시간나면 한 번 확인해주세요!

2024-07-14 13:48 UTC, merged

2024-07-15 05:26 UTC, Wonmoan commented on src/main/java/gift/config/DataLoader.java
> +    }
음..  위시 리스트 구현방법에 대해 질문 드리고 다음 step에 반영 하겠습니다. 
```
 @Override
    public void run(String... args) throws Exception {
        for (int i = 3; i <= 10; i++) {
            Product product = new Product.ProductBuilder()
                .name("Product" + i)
                .price(BigDecimal.valueOf(10.00 * i))
                .imageUrl("http://example.com/product" + i)
                .description("Description for Product" + i)
                .build();
            productRepository.save(product);
        }
    }
```
현재 구현된 방법은 상품에 대한 구체적인 정보가 단순히 인덱스만 증가하는 형태입니다. 
하지만 실제 상품의 경우는 이름도 다 다르고 imageurl, description같은 경우에도 인덱싱뿐만 아니라 설명하는 내용이 다를텐데 이런 요구사항을 어떻게 반영해야 할까요?

기존의 방법으로 data.sql에 상품의 구성요소들을 등록하는 방법으로 통일하는 편이  좋을까요? 
아니면,  JSON, CSV와 같은 상품 정보를 담은 외부 파일에서 데이터를 읽어와서 초기화 하는 방법으로 통일하는 편이 좋을가요?

2024-07-15 05:44 UTC, Wonmoan commented on src/main/java/gift/controller/MemberController.java
> +        }
```
@PostMapping("/register")
    public ResponseEntity<Map<String, String>> register(@Valid @RequestBody MemberDTO memberDTO) {
        Member member = memberDTO.toEntity();
        Member savedMember = memberService.createMember(member);
        Map<String, String> response = new HashMap<>();
        response.put("token", jwtService.generateToken(savedMember));
        return ResponseEntity.ok(response);
    }
```
GlobalExceptionHandler 에서 에외처리 할 수 있도록 
기존의 예외를 다시 던지는 코드 수정했습니다.

2024-07-15 05:52 UTC, Wonmoan commented on src/main/java/gift/domain/Wish.java
> +    @JoinColumn(name = "member_id", nullable = false)
음 .. 필요할 때마다 데이터 로드하는 방식이 더 나을 거라고 생각했는데, 
현재 서비스에선 wish 엔티가 작업될 때 member ,product 정보가 항상 포함 되어 함께 사용 되는 것 같다고 생각이 드네요 
`FetchType.LAZY` 에서 `FetchType.EAGER` 로 변경하겠습니다.

2024-07-16 06:53 UTC, Wonmoan commented on src/main/java/gift/config/DataLoader.java
> +    }
4주차 step1과제를 좀 진행 해보면서 
위와 같은 초기데이터 설정은 페이지네이션 작동이 잘 되는지 확인할 때
여러 상품이 잘 등록,조회가 될수 있나? 테스트할 때  사용되기 좋은 방식이지 실제로 초기 데이터를 등록 할 때는 좋은 방법이 아닌 것 같다라고 생각이 듭니다.

제가 이해한 4주차 step1은 상품등록에 있어 카테고리의 범주가 한정 되어있다고 생각했습니다. 
(교환권, 상품권, 뷰티, 패션, 식품, 리빙/도서, 레저/스포츠, 아티스트/캐릭터, 유아동/반려, 디지털/가전, 카카오프렌즈, 트렌드 선물, 백화점)
저 로직으로 여러 상품을 만들어 잘 작동 되는 지 확인하는 용으로 사용하고 
앞으로 진행할 프로젝트에서는 data.sql 방식을 사용할까 합니다.