강원대 BE_이강욱_3주차 과제(3단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #255
Opened 2024-07-11 12:18 UTC by kanguk01

## 저번 피드백에서 JoinColumn의 fetch를 물어보셔서 그에 대해 알아보았습니다

### Fetch

연관된 엔티티를 언제 로딩할지 설정하는 속성이다. 기본값은 `FetchType.EAGER` 이며, 외에도 `LAZY` 속성이 있다.

</aside>

- `FetchType.EAGER` : **즉시 로딩**, 엔티티가 로드될 때 연관된 모든 엔티티를 즉시 로드한다. (기본값)
    
    ```java
    @ManyToOne(fetch = FetchType.EAGER) // 생략 가능
    private User user;
    ```
    
    `Wish` 엔티티가 로드될 때 `User` 엔티티도 즉시 로드된다는 의미 
    
- `FetchType.LAZY` : **지연 로딩**, 연관된 엔티티가 실제로 사용될 때까지 로드를 지연한다. 성능 최적화를 위해 사용하는 경우가 일반적임
    
    ```java
    @ManyToOne(fetch = FetchType.LAZY)
    private User user;
    ```
    
    `Wish` 엔티티가 로드될 때 `User` 엔티티는 로드되지 않고, `user` 필드에 접근할 때 로드
    

### 왜 LAZY 사용?

- **성능 최적화**
    - 실제로 필요한 시점에만 데이터를 로드하므로, 불필요한 DB 쿼리를 줄일 수 있다.
    - 필요한 데이터만 로드하므로, 전송되는 데이터의 양을 최소화할 수 있고, 메모리를 효율적으로 사용할 수 있다.
    - 필요한 데이터만 로드하므로 빠르게 응답할 수 있다. 결국 전체적인 성능 최적화를 위함임.

### 주의점

- **N + 1 문제** : 하나의 쿼리로 부모 엔티티를 로드한 후, 부모 엔티티에 대해 연관된 자식 엔티티를 로드하기 위해 추가적인 쿼리가 실행되는 문제
- `LazyInitializationException` : 지연 로딩은 실제 엔티티가 필요할 때 초기화되는 **프록시 객체**를 사용하여 연관된 엔티티를 대체하는데, 잘못된 사용으로 영속성 컨텍스트 밖에서 지연 로딩된 엔티티에 접근하려고 할 때 발생하는 `LazyInitializationException` 을 일으킬 수 있다.

그리고 직접 코드에도 적용하여 수정했습니다..! 괜찮은가요?!

---

## 페이지네이션

`PagingAndSortingRepository` 을 extends 받는 방법도 있고 

```java
public interface WishRepository extends JpaRepository<Wish, Long> {
    Page<Wish> findByUser(User user, Pageable pageable);
}
```

이렇게 구현하는 법이 있던데 뭘 사용하든 상관 없을까요? 

이번 주차는 전체적으로 개념은 어렵지만 코드를 작성할때는 그렇게 큰 어려움은 없었는데, 제가 혹시 잘못한 부분이 있어서 그런가 걱정이 되네요..ㅎㅎ 
전체적으로 한번 쓱 봐주시면 감사하겠습니다..!

늘 좋은 피드백 주셔서 감사하고 고생 많으십니다 멘토님!! 😄

2024-07-12 01:28 UTC, pci2676 requested changes
기반코드가 탄탄하게 작성되어있어서 요구사항 구현도 쉽게 하신것 같습니다. 😄 

아주 조금 개선해볼만한 부분에 리뷰를 남겨두었으니 확인부탁드리겠습니다.

2024-07-12 01:28 UTC, pci2676 commented on src/main/java/gift/entity/Wish.java
> +    @JoinColumn(name = "user_id", nullable = false, foreignKey = @ForeignKey(name = "fk_wish_user"))
Column 애너테이션에도 여기처럼 columnDefinition을 이용해서 컬럼에 대한 상세 설명을 추가해주시면 좋을것 같습니다.

2024-07-12 01:28 UTC, pci2676 commented on src/main/java/gift/repository/WishRepository.java
> +    Page<Wish> findByUser(User user, Pageable pageable);
이렇게 사용하셔도 됩니다~

페이징은 특정 기능에서 유용할 수 있으나 데이터의 양이 많아지면 성능적이슈가 발생할 수 있는데요

아래 글을 참고해보시면 좋을것 같습니다. (지금 개선할 필요는 없으니 이런게 있구나~ 참고만해주세요~)

https://jojoldu.tistory.com/528

2024-07-12 01:28 UTC, pci2676 commented on src/main/java/gift/controller/ProductController.java
> +    public ResponseEntity<Page<ProductResponseDto>> getAllProducts(@RequestParam(defaultValue = "0") int page, @RequestParam(defaultValue = "10") int size) {
외부에 응답을 할때는 page객체를 그대로 노출하는것 보다 별도의 객체로 노출하는것도 좋습니다.

spring data가 web레이어까지 넘어오게 되어서요~!

2024-07-12 01:28 UTC, pci2676 commented on src/test/java/gift/service/ProductServiceTest.java
> +    }
하나의 테스트에 여러개의 단언문이 있는것은 지양해주시는게 좋습니다.

컨텍스트를 이어서 테스트를 하고 싶으시다면 Junit의 DynamicTest를 활용해보시면 좋을것 같습니다

2024-07-12 01:28 UTC, pci2676 commented on src/test/java/gift/service/ProductServiceTest.java
> +    public void 상품_목록_페이지네이션() {
이 부분말고 다른 부분도 함께 챙겨봐주시면 좋을것 같은데요.

테스트 이름에는 테스트가 나타내고자 하는 바가 명확히 나타나는 것이 좋습니다~!

가령 exception이 발생하는 테스트라면

'~를 하면 예외가 발생한다'라고 명시적으로 적어주는것이 되겠네요

2024-07-12 05:06 UTC, kanguk01 commented on src/main/java/gift/entity/Wish.java
> +    @JoinColumn(name = "user_id", nullable = false, foreignKey = @ForeignKey(name = "fk_wish_user"))
오 바로 적용해보도록 하겠습니다!!

2024-07-12 05:10 UTC, kanguk01 commented on src/main/java/gift/repository/WishRepository.java
> +    Page<Wish> findByUser(User user, Pageable pageable);
위 내용 추후에 학습해보도록 하겠습니다!! 감사합니다 😄

2024-07-12 05:11 UTC, kanguk01 commented on src/main/java/gift/controller/ProductController.java
> +    public ResponseEntity<Page<ProductResponseDto>> getAllProducts(@RequestParam(defaultValue = "0") int page, @RequestParam(defaultValue = "10") int size) {
생각 못한 부분입니다!! 수정해보도록 하겠습니다

2024-07-12 05:15 UTC, kanguk01 commented on src/test/java/gift/service/ProductServiceTest.java
> +    }
헉 한번 다듬어보겠습니다!

2024-07-12 05:16 UTC, kanguk01 commented on src/test/java/gift/service/ProductServiceTest.java
> +    public void 상품_목록_페이지네이션() {
더 디테일하게 적어야하는군요..! 전체적으로 반영해보겠습니다!

2024-07-12 06:58 UTC, kanguk01 commented
피드백 사항 반영해보았습니다!

2024-07-12 16:42 UTC, pci2676 requested changes
조금만 고쳐보셨으면 하는 부분이 있어 리뷰를 남겨두었으니 확인부탁드리겠습니다~!

2024-07-12 16:42 UTC, pci2676 commented on src/main/java/gift/controller/ProductViewController.java
> +                                 @RequestParam(defaultValue = "10") int size) {
클라이언트가 이 API를 통해 무지막지한 크기의 page와 size로 요청을 한다면 문제가 발생할 수 있을것 같네요~! 🤔

2024-07-12 16:42 UTC, pci2676 commented on src/main/java/gift/dto/ProductPageResponseDto.java
> +public class ProductPageResponseDto {
👍

2024-07-12 16:42 UTC, pci2676 commented on src/main/java/gift/entity/Product.java
> +    @Column(name = "image_url", nullable = false, columnDefinition = "VARCHAR(255) NOT NULL COMMENT 'Product Image URL'")
👍

2024-07-12 16:42 UTC, pci2676 commented on src/test/java/gift/controller/ProductControllerTest.java
> +@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
💯

2024-07-12 16:42 UTC, pci2676 commented on src/test/java/gift/service/ProductServiceTest.java
> +        }
테스트에서는 반복문, 분기문 등의 로직이 들어가지 않는것이 좋습니다.

테스트는 읽기 쉬워야 하는데 위와 같은 로직은 테스트 코드를 읽다가 잠시 멈추게하는 요소가 되기 때문입니다.

조금 불편하더라도 명시적으로 필요한 개수(최소)의 데이터를 생성해주시는 것을 권장드립니다. :)

2024-07-12 16:42 UTC, pci2676 commented on src/test/java/gift/service/ProductServiceTest.java
> +    }
이렇게도 표현할 수 있습니다~!

반환타입을 Collection에서 Stream으로 변경해주면 됩니다~!

```suggestion
        return Stream.of(
                DynamicTest.dynamicTest("첫번째 페이지 조회", () -> {
                    ProductPageResponseDto page1 = productService.getAllProducts(0, 10);
                    assertNotNull(page1);
                    assertEquals(10, page1.getProducts().size());
                    assertEquals(0, page1.getCurrentPage());
                    assertEquals(3, page1.getTotalPages());
                }),
                DynamicTest.dynamicTest("두번째 페이지 조회", () -> {
                    ProductPageResponseDto page2 = productService.getAllProducts(1, 10);
                    assertNotNull(page2);
                    assertEquals(10, page2.getProducts().size());
                    assertEquals(1, page2.getCurrentPage());
                }),
                DynamicTest.dynamicTest("세번째 페이지 조회", () -> {
                    ProductPageResponseDto page3 = productService.getAllProducts(2, 10);
                    assertNotNull(page3);
                    assertEquals(5, page3.getProducts().size());
                    assertEquals(2, page3.getCurrentPage());
                })
        );
```

2024-07-14 14:51 UTC, kanguk01 commented on src/main/java/gift/controller/ProductViewController.java
> +                                 @RequestParam(defaultValue = "10") int size) {
```java

int maxPage = 1000;
int maxSize = 100;

if (page > maxPage) {
    page = maxPage;
}

if (size > maxSize) {
    size = maxSize;
}
```

그냥 이렇게 값 제한을 두면 될까요..?

2024-07-14 15:27 UTC, pci2676 commented on src/main/java/gift/controller/ProductViewController.java
> +                                 @RequestParam(defaultValue = "10") int size) {
그렇게 해도 되고 Max와 같은 validation 애너테이션을 활용하는것도 방법이 되지 않을까요?

2024-07-14 15:29 UTC, pci2676 approved these changes
일요일을 기점으로 마무리를 지어야 해서 merge하겠습니다~

코드도 깔끔하게 작성해주셔서 사실 리뷰로 남겨둔 부분은 조금만 확인해보시면 어떻게 할지 다 아시리라 생각이 되네요~

고생하셨습니다.

2024-07-14 15:29 UTC, merged

2024-07-15 05:55 UTC, kanguk01 commented on src/test/java/gift/service/ProductServiceTest.java
> +        }
한 페이지의 데이터 수를 줄이고 모든 데이터를 명시적으로 생성하겠습니다!

2024-07-15 05:56 UTC, kanguk01 commented on src/test/java/gift/service/ProductServiceTest.java
> +    }
오 가독성이 훨씬 좋은것같습니다!! 감사합니다!!