전남대 BE_서영우 3주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #256
Opened 2024-07-11 13:01 UTC by westzeroright

멘토님 이번주 리뷰도 잘 부탁드립니다!

이번 과제에서 JPA로 리팩토링하면서 서비스 계층에 대해 고민하는 시간을 가졌습니다. 서비스 계층이 필요한 이유에 대해 생각해보고, 그러면 컨트롤러랑 서비스 계층 역할 분리에 대해서 고민해보았습니다. 결론적으로 컨트롤러에서 수행할 비즈니스 로직을 서비스 계층에서 검증을 포함하여 구현하였습니다.그래서 이번 리뷰에서는 서비스 계층에 대해 리뷰를 받고 싶습니다:)

아래는 저번 PR에서 언급하신 부분에 대한 학습입니다!

&nbsp;중복 코드는 좋지 않다는 고정관념이 있어서 최대한 공통적으로 묶는 게 효율적으로 좋다고 생각했습니다. 그러나 테스트 같은 경우에는 메서드 단위로 실행하는 경우가 있는데 Fixture을 Setup으로 통합해 놓은 코드에서는 실행하고자 하는 메서드 내부에서 테스트에 대한 모든 내용을 파악하기 어려운 점이 있을 수 있다고 깨달았습니다.

&nbsp;먼저 E2E 테스트를 했을 때, 테스트가 통과되면 애플리케이션이 제대로 동작함을 보장할 수 있는 장점이 있을 것 같습니다. 다만, 특정 계층만 테스트가 필요한 상황에서 사용하면 무겁고, 시간이 오래 걸리고, 디버깅도 어려울 것 같습니다.
&nbsp;슬라이스 테스트는 E2E 테스트의 단점을 보완하지만 E2E 테스트의 장점을 못 가져가고 외부 라이브러리, 데이터베이스 등을 연결하는 과정에서 발생하는 에러를 검증할 수 없는 단점이 있을 것 같습니다.
&nbsp;둘의 장단점으로부터 trade-off 관계같다고 느껴졌습니다. 이 둘을 모두 실행하면 꼼꼼하게 테스트할 수 있겠지만 너무 무거워지고 비용이 많이 들 것 같아 상황에 맞게 장단점을 고려하여 적용하면 좋을 것 같다고 생각합니다:)

2024-07-12 10:34 UTC, pkeugine requested changes
안녕하세요 영우님,
잘 만들어주셨습니다.
그리고 테스트에 대한 내용도 정말 좋았어요 👍 
그런데 지금 코드에 문제가 있어서 실행이.. 안되니
해당 문제를 해결해주시면 좋을 것 같습니다.

그리고 리뷰 남겨보았으니 반영 + 댓글 남겨주세요!
파이팅입니다 🔥 🔥 🔥

2024-07-12 10:34 UTC, pkeugine commented on src/main/java/gift/member/MemberController.java
>      public ResponseEntity<?> registerMember(@RequestBody Member member) throws AlreadyExistMember {
`?` 를 controller 전체적으로 제거해보아요!

2024-07-12 10:34 UTC, pkeugine commented on src/main/java/gift/member/MemberRepository.java
> +    Member findByEmail(String email);
`findByEmail` 도 Optional 로 감싸볼 수 있을 것 같아요!

2024-07-12 10:34 UTC, pkeugine commented on src/main/java/gift/member/MemberService.java
> +        return memberRepository.findByEmail(userEmail);
사용하지 않는 메서드는 제거해주세요.

2024-07-12 10:34 UTC, pkeugine commented on src/main/java/gift/member/Member.java
>      private String name;
PR 날리기 전에 코드 확인, 컴파일 확인, 그리고 테스트 실행을 해보시면 좋을 것 같아요.
현제 코드에 오류가 있네요.
그래서 애플리케이션 실행도 불가능해요.

2024-07-12 10:34 UTC, pkeugine commented on src/main/java/gift/member/MemberService.java
> +            throw new AlreadyExistMember("이미 회원정보가 존재합니다");
예외가 Exception 이 아닌 RuntimeException 을 상속받도록 해보는건 어떨까요?
어떤 차이가 있을지도 알아보아요.

2024-07-12 10:34 UTC, pkeugine commented on src/test/java/gift/wishlist/WishlistRepositoryTest.java
> +@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
해당 어노테이션은 어떤 역할을 하나요?

2024-07-12 10:34 UTC, pkeugine commented on src/test/java/gift/wishlist/WishlistRepositoryTest.java
> +class WishlistRepositoryTest {
테스트에 대해 굉장히 좋은 내용을 남겨주셨네요!!! 👍 👍 👍 👍 
그렇다면 영우님이 Repository Test 를 만들어주신 이유가 궁금해요.

2024-07-12 10:34 UTC, pkeugine commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=create
해당 설정을 `create` 로 해주신 이유가 궁금합니다!

2024-07-12 10:34 UTC, pkeugine commented on src/main/java/gift/product/ProductService.java
> +            Product pd = product.get();
줄임말은 지양해주세요!

2024-07-12 10:34 UTC, pkeugine commented on src/main/java/gift/product/ProductService.java
> +            pd.update(productRequestDto.name(), productRequestDto.price(), productRequestDto.url());
Optional 을 사용한다면 if 문도 없앨 수 있을 것 같아요!

2024-07-12 10:34 UTC, pkeugine commented on src/main/java/gift/product/ProductController.java
> +        return productService.postProduct(product);
어떤 경우에는 controller 에서 도메인을 만들어 service 로 보내고,
어떤 경우엔 dto 상태로 넘겨주네요!
통일해보죠!

통일 할 때 그 방식을 선택하신 이유도 알려주세요.

2024-07-12 14:23 UTC, westzeroright commented on src/main/java/gift/member/MemberService.java
> +        return memberRepository.findByEmail(userEmail);
`LoginMemberArgumentResolver`에서 사용하고 있습니다!

2024-07-12 14:34 UTC, westzeroright commented on src/main/java/gift/member/MemberService.java
> +            throw new AlreadyExistMember("이미 회원정보가 존재합니다");
Exception은 반드시 예외 처리를 해야하면 그렇지 않을시 컴파일 오류가 발생합니다. 다만, RuntimeException은 발생 가능성에 대해 예측이 불가능하고 필수적이지 않아 생략이 가능한 점이 있습니다.

2024-07-12 14:59 UTC, westzeroright commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=create
저는 운영 서버가 아니고 제가 변경한 사항이 반영됐는지 확인하기 위해서 create 옵션을 두었습니다! 만약 create가 아니라면, 잘못 설정한 테이블 및 값들에 대해서 불편함을 겪을 수 있을 것 같습니다.

다만, 라이브 강의에서 강사님께서 현업에서 create 옵션을 사용하면 무지막지한 손실을 초래할 수 있다고 말씀하신 것이 상기되는데 다른 옵션을 사용해야 할까요?

2024-07-12 15:03 UTC, westzeroright commented on src/test/java/gift/wishlist/WishlistRepositoryTest.java
> +@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
테스트용 DB를 사용하기 위해 해당 어노테이션으로 properties가 적용되게 하였습니다

2024-07-12 15:08 UTC, westzeroright commented on src/test/java/gift/wishlist/WishlistRepositoryTest.java
> +class WishlistRepositoryTest {
JPA를 사용하면서 API로 추상화가 많이 되어 있다고 느꼈습니다. 기존에 쿼리문을 직접 작성하여 접근하던 것을 JPA가 대신하도록 리팩토링 되었는데 이에 대해 올바르게 작동하는지 테스트가 필요하다고 생각하였습니다.

2024-07-12 15:57 UTC, westzeroright commented on src/main/java/gift/product/ProductController.java
> +        return productService.postProduct(product);
요청과 응답을 주고 받는 부분에 대하여 DTO를 사용하도록 수정해보았습니다!

DTO는 불변성을 특징으로 record로 설정을 하는데 

도메인으로 주고받으면 DTO로 변환하는 과정이 없어 코드가 간결해보일 수는 있지만 record로 설정하는 불변성을 특징으로 가지는 DTO가 데이터를 주고 받는 역할에 있어서 더 적합하다고 생각하여 DTO를 선택하였습니다!

2024-07-13 03:28 UTC, pkeugine commented on src/test/java/gift/wishlist/WishlistRepositoryTest.java
> +class WishlistRepositoryTest {
그렇군요!
리팩토링이 잘 되었는지 확인해보는 테스트 좋네요.
저는 개인적으로 테스트를 더 만들어본다면 e2e 테스트를 만들어 볼 것 같긴해요.

2024-07-13 03:29 UTC, pkeugine commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=create
네 실제 프로덕션 환경에서는 create 를 잘 사용하진 않아요!
지금은 말해주신 이유로 create 로 둬도 괜찮다고는 생각합니다 👍

2024-07-13 03:31 UTC, pkeugine commented on src/main/java/gift/product/ProductController.java
> +        return productService.postProduct(product);
사실 DTO 를 만들 때 record 를 사용하지 않아도 만들 수 있어요.
오히려 처음부터 record 로 만들면, 그 특징을 제대로 이해하지 못하고 넘어갈 수 있다고 생각하는 1인입니다. ㅋㅋㅋ
그런데 도메인은 불변 객체가 될 수 없는걸까요? 🤔

2024-07-13 03:31 UTC, pkeugine commented
<img width="876" alt="Screenshot 2024-07-13 at 12 31 42 PM" src="https://github.com/user-attachments/assets/36609636-3650-4635-aae0-7743b5b14576">

앞으로 커밋 메시지는 의미있는 내용을 담아주세요!

2024-07-13 03:32 UTC, pkeugine commented on src/test/java/gift/wishlist/WishlistRepositoryTest.java
> +@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
그렇군요!

2024-07-13 03:33 UTC, pkeugine commented
<img width="876" alt="Screenshot 2024-07-13 at 12 32 42 PM" src="https://github.com/user-attachments/assets/14074ed4-213c-4680-a64f-181c7f29c791">

이런 커밋들을 방지하기 위해 시도할 수 있는 방법이 뭐가 있을까요?

2024-07-13 03:34 UTC, pkeugine approved these changes
안녕하세요 영우님,
우선 시간이 꽤나 촉박하니 해당 스텝은 머지하도록 할게요.
제가 git 관련 코멘트 남긴 부분 한 번 봐주시고,
추가 질문도 있으니 확인해주세요!
고생하셨습니다 👍

2024-07-13 03:34 UTC, merged

2024-07-13 07:28 UTC, westzeroright commented
> <img alt="Screenshot 2024-07-13 at 12 32 42 PM" width="876" src="https://private-user-images.githubusercontent.com/48251668/348446777-14074ed4-213c-4680-a64f-181c7f29c791.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NTU5NjIsIm5iZiI6MTcyMDg1NTY2MiwicGF0aCI6Ii80ODI1MTY2OC8zNDg0NDY3NzctMTQwNzRlZDQtMjEzYy00NjgwLWE2NGYtMTgxYzdmMjljNzkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEzVDA3Mjc0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwM2VhZWNiMzYzMWJkY2E3YWIzN2I0ZTFlYmNlZjA1NzcxZGUyYWJiNGQwNTVhYWU1OGZiMTIwZDNiZmZkNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZQu_0YemXS0Tz77ujHYfXk8eH0rjhRXxuzYxgvXNiX4">
> 이런 커밋들을 방지하기 위해 시도할 수 있는 방법이 뭐가 있을까요?

이전 커밋으로 되돌리는 reset이나 revert가 있을 것 같습니다..!