강원대 BE_이세진 3주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #257
Opened 2024-07-11 13:09 UTC by ez23re

멘토님 늦어져서 죄송합니다. 
계속되는 테스트 실패로 늦어졌습니다. 테스트 뭐가 문젠지 모르겠습니다. 인텔리제이 디버깅 기능을 사용하는데 하나 수정하면 하나가 또 오류가 납니다. 계속 수정하겠습니다.

아래는 0단계 피드백 수정 사항입니다. 
- 시큐리티 의존성 삭제
- setter 말고 생성자 생성
- 들여쓰기 오류 수정
- connection 삭제
- 불필요한 의존성 주입 삭제
- 시크릿 키 하드코딩 수정

2024-07-12 01:33 UTC, pci2676 requested changes
컴파일이 깨지고 있는것 같습니다.

확인후 다시 제출해주세요.

2024-07-12 01:33 UTC, pci2676 commented on src/main/java/gift/admin/AdminController.java
> +        model.addAttribute("product", product); // 모델에 상품 추가
외부에서 데이터를 받거나 내보낼때는 dto를 사용해보시면 좋을것 같습니다.

2024-07-12 01:33 UTC, pci2676 commented on src/main/java/gift/member/model/Member.java
> +    @Column(nullable = false, unique = true)
Column에 columnDefinition을 이용해서 조금 더 명확한 컬럼 설명을 적어주시면 좋을것 같습니다.

2024-07-12 01:33 UTC, pci2676 commented on src/main/java/gift/member/model/Member.java
> +    }
데이터 영속성 모델과 dto를 구분하신다면 이러한 setter는 데이터 영속성 모델에서 제거할 수 있습니다. 😄

2024-07-12 01:33 UTC, pci2676 commented on src/main/java/gift/member/repository/MemberRepository.java
> +    }
이렇게 작성하신 이유가 있나요?

2024-07-12 01:33 UTC, pci2676 commented on src/main/java/gift/member/repository/MemberRepository.java
> +    String PASSWORD = "";
반드시 필요한 정보인가요?

2024-07-15 08:39 UTC, pci2676 approved these changes
리뷰를 확인해주시고 참고하여 3단계를 진행해주세요

2024-07-15 08:39 UTC, pci2676 commented on src/main/java/gift/member/model/Member.java
> +    }
setter와 다를바가 없는 메서드같습니다.

메서드 내에서 validation을 해주어야 할 것 같습니다.

그리고 메서드 네이밍으로 with을 사용하신 이유가 있나요? 참고하신 컨벤션이 있을까요?

자바에서는 메서드에 동사를 사용하는 컨벤션이 있습니다.

2024-07-15 08:39 UTC, pci2676 commented on src/main/java/gift/member/model/Member.java
> +    public Member() {
기본 생성자를 public으로 한 이유가 있을까요?

2024-07-15 08:39 UTC, pci2676 commented on src/main/java/gift/member/model/Member.java
> +    @OneToMany(mappedBy = "member", cascade = CascadeType.ALL, orphanRemoval = true)
OneToMany로 설정해야하는 이유가 있을까요?

2024-07-15 08:39 UTC, pci2676 commented on src/main/java/gift/product/model/Product.java
> +    private String imgUrl;
컬럼에 대한 설명이 없는것 같습니다.

2024-07-15 08:39 UTC, pci2676 commented on src/main/java/gift/product/model/Product.java
> +    }
업데이트 메서드를 사용하지 않는것 같습니다.

2024-07-15 08:39 UTC, pci2676 commented on src/main/java/gift/product/service/ProductService.java
> +    @Autowired
autowired가 반드시 필요한가요?

2024-07-15 08:39 UTC, pci2676 commented on src/main/java/gift/product/service/ProductService.java
> +    private final JdbcTemplate jdbcTemplate;
repository를 사용하는 코드로 service를 변경해야할것 같아보입니다.

2024-07-15 08:39 UTC, pci2676 commented on src/main/java/gift/wishlist/model/WishList.java
> +    @ManyToMany
manyToMany 관계로 설정해야하는 요구사항이 맞나요?

2024-07-15 08:39 UTC, pci2676 commented on src/main/java/gift/wishlist/model/WishList.java
> +    @ManyToOne
fetch 옵션에 대해 알고 사용하셨나요?

2024-07-15 08:39 UTC, pci2676 commented on src/main/java/gift/wishlist/model/WishList.java
> +    @Id
id의 발번을 uuid로 한 이유가 있나요?

2024-07-15 08:39 UTC, pci2676 commented on src/main/java/gift/product/model/ProductName.java
> +    @Pattern(regexp = "^[\\w\\s()\\[\\]+\\-&/]*$", message = "상품명에 잘못된 문자가 있습니다.")
ProductName을 사용해주세요.

2024-07-15 08:39 UTC, pci2676 commented on src/test/java/gift/member/repository/MemberRepositoryTest.java
> +//package gift.member.repository;
테스트 코드가 전부 주석처리되어있네요?

테스트 코드를 다시 활성화 시켜주시면 좋을것 같습니다.

2024-07-15 08:39 UTC, pci2676 commented on src/main/java/gift/member/controller/MemberController.java
> +    public Member getMemberById(@PathVariable Long id) {
이렇게 하면 id에 올바른 값이 맵핑이 되나요?

2024-07-15 08:39 UTC, pci2676 commented on src/main/java/gift/member/model/Member.java
> +    @Column(nullable = false, columnDefinition = "BINARY(16)")
BINARY로 설정하신 이유가 있나요?

2024-07-15 09:00 UTC, ez23re commented on src/main/java/gift/member/model/Member.java
> +    }
메소드명 동사로 시작 규칙에 맞게 수정하겠습니다

2024-07-15 09:01 UTC, ez23re commented on src/main/java/gift/member/model/Member.java
> +    public Member() {
다른 클래스에서 참조할 때 인텔리제이 빠른 수정(빨간 전구) 으로 자동 생성했습니다. 다시 보니 불필요한 부분 같아서 제거하겠습니다.

2024-07-15 09:03 UTC, ez23re commented on src/main/java/gift/member/model/Member.java
> +    @OneToMany(mappedBy = "member", cascade = CascadeType.ALL, orphanRemoval = true)
앗 @원투원, 회원 한 명당 하나의 위시리스트만 연관되도록 수정하겠습니다.

2024-07-15 09:06 UTC, ez23re commented on src/main/java/gift/member/model/Member.java
> +    @Column(nullable = false, columnDefinition = "BINARY(16)")
UUID 찾을 수 없다는 오류가 계속 떠서 [https://jehuipark.github.io/java/my-sql-binary-reference](url) 이 블로그에에“UUID 에는 16 바이트가 필요합니다”
“UUID 를 저장할 땐 VARCHAR 대신 BINARY(16) 컬럼을 이용하세요”
를 보고 VARCHAR 에서 바이너리로 수정했는데 솔직히 잘 모르겠습니다. 좀 더 공부해서 추가하겠습니다.

2024-07-15 09:08 UTC, ez23re commented on src/main/java/gift/product/model/Product.java
> +    private String imgUrl;
수정하겠습니다.

2024-07-15 09:11 UTC, ez23re commented on src/main/java/gift/product/service/ProductService.java
> +    @Autowired
앗 생성자가 하나 뿐이라 필요없을 것 같습니다. 수정하겠습니다.

2024-07-15 09:21 UTC, ez23re commented on src/main/java/gift/wishlist/model/WishList.java
> +    @ManyToOne
아니요 숙지하고 사용해보겠습니다.

2024-07-15 09:29 UTC, ez23re commented on src/main/java/gift/member/controller/MemberController.java
> +    public Member getMemberById(@PathVariable Long id) {
네이밍 수정과정에서 member_id 로 바꾸는 것을 빼먹은 것 같습니다. 수정하겠습니다.

2025-04-20 08:16 UTC, closed without merging