경북대 BE_안재민 3주차 과제 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #258
Opened 2024-07-11 13:28 UTC by dkswoals

늘 좋은 리뷰 감사드립니다! (컨설팅도 감사드립니다😊)
## 중점적으로 리뷰 받고 싶은 부분, 궁금한 점
- 통합 테스트를 위해 SpringBootTest에서 RANDOM_PORT 혹은 DEFINED_PORT 사용 시 테스트 메서드와 비즈니스 로직 메서드가 다른 쓰레드에서 동작하여 트랜젝션이 제대로 적용되지 않는 이슈가 있었습니다.. 
99d0cb1

(일단 deleteAll로 DB 데이터를 지워주며 진행하였지만 id에 대해서는 완벽하게 격리가 되지 않았습니다)

멘토님은 통합 테스트 시 어떠한 방식으로 테스트 메서드들을 격리하시는지 궁금합니다!

2024-07-11 13:47 UTC, leaf-upper requested changes
안녕하세요 재민님~
몇가지 코멘트 남겨드렸는데 확인 부탁드릴게요:)
고생많으셨습니다! ~ 👍 👍

2024-07-11 13:47 UTC, leaf-upper commented on src/main/java/gift/controller/ItemController.java
> +        return HttpStatus.CREATED;
HttpStatus을 응답으로 주기보다는, JSON 데이터를 기반으로 하여 응답해주시는건 어떨까요?

2024-07-11 13:47 UTC, leaf-upper commented on src/main/java/gift/controller/ItemController.java
> +    public HttpStatus updateItem(@PathVariable Long id, @Valid @RequestBody ItemForm form,
이부분도 위와 같습니다~

2024-07-11 13:47 UTC, leaf-upper commented on src/main/java/gift/controller/ItemController.java
> +        return HttpStatus.OK;
이부분도 위와 같습니다.

2024-07-11 13:47 UTC, leaf-upper commented on src/main/java/gift/controller/WishListController.java
> +        @RequestAttribute("userId") Long userId) {
추가 삭제에 대해서도 void응답보다는 생성된 Entity의 ID 혹은 삭제된 Entity의 ID 라도 리턴할 수 있도록 코드를 작성해주시면 좋을것 같아요~

2024-07-11 13:47 UTC, leaf-upper commented on src/main/java/gift/model/item/Item.java
> +    private List<WishItem> wishes;
Item과 WishItem의 생명주기를 맞춰놓으신것 같아요.
이 코드에 대해서 설명부탁드려도 될까요?

2024-07-11 13:47 UTC, leaf-upper commented on src/main/java/gift/model/user/User.java
> +    private List<WishItem> wishItemList;
이 코드에 대해서도 설명부탁드려도 될까요?

2024-07-11 13:47 UTC, leaf-upper commented on src/main/java/gift/service/ItemService.java
> +@Transactional
1. read만하는곳에서는 Transactional(readOnly=true)를 사용해주시는것도 좋을것 같아요.

2024-07-11 13:48 UTC, leaf-upper commented
- 통합 테스트를 위해 SpringBootTest에서 RANDOM_PORT 혹은 DEFINED_PORT 사용 시 테스트 메서드와 비즈니스 로직 메서드가 다른 쓰레드에서 동작하여 트랜젝션이 제대로 적용되지 않는 이슈가 있었습니다..

이 질문은 테스트코드에 트랜잭션을 붙여서, 테스트가 끝난후에 롤백이 되도록 의도하였는데 이 부분이 제대로 동작하지 않았다는 의미이실까요?

2024-07-12 05:31 UTC, dkswoals commented on src/main/java/gift/controller/ItemController.java
> +        return HttpStatus.CREATED;
반영하였습니다!

2024-07-12 05:31 UTC, dkswoals commented on src/main/java/gift/controller/WishListController.java
> +        @RequestAttribute("userId") Long userId) {
전체 반영하였습니다!

2024-07-12 05:31 UTC, dkswoals commented on src/main/java/gift/service/ItemService.java
> +@Transactional
반영하였습니다!

2024-07-12 07:26 UTC, dkswoals commented on src/main/java/gift/model/item/Item.java
> +    private List<WishItem> wishes;
해당 코드는 item과 wish 엔티티 연관관계를 매핑하기 위한 코드로 다 대 일 양방향으로 매핑되어 있습니다 (단방향 + 단방향)
fk의 주인로 wish를 지정하여 wish에서는 fk를 관리 가능하게 하였고 item에서는 mappedBy를 통해 단순 조회만 가능하도록 설정하였습니다.
이때 영속성 전이를 위해 item에 cascade 옵션을 설정하여 item엔티티의 영속성 상태 변화가 연관된 wish 엔티티에도 적용되도록 하였습니다! (예를 들어 item이 삭제 될 시 해당 item을 참조하는 wish 또한 제거 되도록)

2024-07-12 07:26 UTC, dkswoals commented on src/main/java/gift/model/user/User.java
> +    private List<WishItem> wishItemList;
item 엔티티와 동일합니다!

2024-07-12 07:28 UTC, dkswoals commented
피드백 반영 후 리뷰 요청 드립니다!

2024-07-13 10:30 UTC, leaf-upper approved these changes
안녕하시요 재민님~ 2단계 구현 고생 많으셨습니다~! 다음단계 진행 부탁드립니다!

2024-07-13 10:30 UTC, merged