충남대 BE_배민수 3주차 과제 (2단계 ~ 3단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #267
Opened 2024-07-11 14:47 UTC by minsu-cnu

시간 상 2단계, 3단계를 하나의 PR로 보내드리는 점 양해 말씀 드립니다..!

이번 2단계, 3단계 과정을 수행하면서 다음과 같은 궁금증이 생겨 질문을 드리고 싶습니다.

<br/>

1. 연관 관계 매핑을 적용하다보니 WishService에서 ProductService와 AuthRepository를 의존하고 있는데, 이런 식으로 다른 종류의 레포지토리나 서비스를 막 여러개 의존해도 괜찮은건지 궁금합니다!

2. 과제 2단계에서 요구하는 사항인 연관 관계 매핑이 필요한 이유(요구하는 이유)는 참조 무결성을 위해서인지, (삭제 cascade 등을 위해서인지) 아니면 클라이언트에게 Wish 엔티티를 응답할 때 이제는 외래키값이 아닌 Product와 Member 그 자체를 응답하게 바뀌었는데, 이걸 위한 것인지가 궁금합니다.

3. Wish 영속성 객체를 findById 등을 통해 찾아와 변수에 저장해두고, 직후에 해당 Wish 객체 내의 필드에 담고 있는 Product 객체에 대해, 해당 product의 ID 값을 통해 ProductRepository의 save를 통해 name을 수정하면, 변수에 담아뒀던 Wish 객체의 필드에 담겨있는 Product 객체에 변경 감지 원리가 적용이 되는건지 궁금합니다.

4. 코드 상에서 엔티티 객체 간의 참조 관계가 있는지를 기준으로 단방향으로 할지 양방향으로 할지 판단하는 것 같은데, 이 부분이 감이 잘 안 잡힙니다..! Member와 Wish 엔티티 간의 관계를 단방향으로 할지 양방향으로 할지 고민이 됐었는데, Member 객체가 Wish 객체를 참조할 일이 있을 때 양방향으로 설계를 해야할 것 같은데, 어떤 상황에서 Wish 객체를 참조할 일이 있는건지 잘 모르겠습니다.

5. 다대일 단방향 관계에서 부모 엔티티가 제거되었을 때 자식을 연쇄적으로 지우는 방법을 찾아보니 두가지가 있었습니다.

    우선은 wish와 product를 다대일 양방향 관계로 설계하였는데, 연쇄적인 제거를 위해서는 product 쪽에 cascade를 걸기 위해 양방향 관계로 설계를 바꾸거나, 단방향을 그대로 유지하고 wish쪽에 @OnDelete를 쓰는 방법이 있다고 합니다. 당장 보기에는 단방향을 유지할 수 있는 @OnDelete만 쓰면 되는 것 아닌가싶기도 한데... 실무에서는 어떤 방법을 어떤 상황에 쓰는지 궁금합니다.

2024-07-13 14:25 UTC, jjongwa requested changes
2~3단계까지 아주 잘 구현해 주셨어요! 일정이 있어 리뷰가 조금 늦었습니다 😭 

질문에 대한 제 의견을 하나씩 적어보자면..

> 연관 관계 매핑을 적용하다보니 WishService에서 ProductService와 AuthRepository를 의존하고 있는데, 이런 식으로 다른 종류의 레포지토리나 서비스를 막 여러개 의존해도 별 문제 없을지 궁금합니다!

사실 이 부분도 사용자가 잘 인지하고 작성한다면 로직 상으로 큰 문제는 없습니다! (이번 미션에서도 이렇게 구성하면 작동을 안한다던가 하는 그런 문제는 없었듯이요..!)

하지만 지금과 같이 같은 계층끼리 서로 의존성을 가지는 상황이 점점 많아지고, 프로젝트의 규모도 커진다면 전체적인 구조 파악이 힘들어질 수 있습니다.!

이를 방지하기 위해선 최대한 Service는 Repo만 가지고 있게 하고, 필요한 로직이 있으면 중복을 감안하더라도 해당 서비스에서 다시 구현해 주는게 좋다고 생각합니다.!

> 과제 2단계에서 요구하는 사항인 연관 관계 매핑이 필요한 이유(요구하는 이유)는 참조 무결성을 위해서인지, (삭제 cascade 등을 위해서인지) 아니면 클라이언트에게 Wish 엔티티를 응답할 때 이제는 외래키값이 아닌 Product와 Member 그 자체를 응답하게 바뀌었는데, 이걸 위한 것인지가 궁금합니다. (덕분에 관리자 위시리스트 페이지에서 외래키로 API 요청을 통해 상품 정보를 받아올 필요 없이 바로 상품을 보여줄 수 있게 되었습니다.)

일단 이번 과제에서 요구하는 점은 `JPA`라는 걸 왜 쓰는지 짚고 넘어가기 위해서라고 생각해요! JPA의 장점은 `쿼리 없이 쉽게 db 접근 로직을 구현할 수 있다`도 있지만, 가장 중요한 점은 **데이터를 객체 중심으로 바라볼 수 있다**는 점입니다!

예를 들어, 만약 해당 선물하기 서비스에 db라는 개념이 들어가지 않았다면, 사용자가 찜한 상품을 나타내는 Wish라는 객체에 Product가 있는게 자연스럽게 느껴지겠죠? 하지만 db가 들어오고 테이블 구조를 생각하게 되면서, Wish에는 Product의 id가 들어가는 방식으로 코드도 짜여지게 됩니다. 
이러한 테이블 중심의 설계를 최대한 객체 중심으로 바라볼 수 있게 도와주는게 JPA고, 그 중 핵심적인 요소가 이러한 연관관계 매핑이기 때문에, 이러한 기능을 충분히 사용해 보며 익히는게 중요한 것 같아요~!

> Wish 영속성 객체를 findById 등을 통해 찾아와 변수에 저장해두고, 직후에 해당 Wish 객체 내의 필드에 담고 있는 Product 객체에 대해, 해당 product의 ID 값을 통해 ProductRepository의 save를 통해 name을 수정하면, 변수에 담아뒀던 Wish 객체의 필드에 담겨있는 Product 객체에 변경 감지 원리가 적용이 되는건지 궁금합니다.

네, 해당 Wish와 함께 Product도 영속성 컨텍스트에 올라오게 되고, 각 객체를 구분하는 기준은 해당 엔티티의 id이기 때문에 해당 id로 조회하는 객체는 이미 영속성 컨텍스트에 올라와 있는 객체를 가리키게 됩니다! 
해당 부분에 대해서 심도있게 공부해 보면 JPA를 훨씬 더 잘 이해할 수 있을 거예요!

> 코드 상에서 엔티티 객체 간의 참조 관계가 있는지를 기준으로 단방향으로 할지 양방향으로 할지 판단하는 것 같은데, 이 부분이 감이 잘 안 잡힙니다..!

이 부분도 저는 직접 경험해 보는게 가장 이해하기 빠를 거라고 생각해요! 양방향 참조를 어떨 떄 해야하는지 고민하는 건 아주 좋습니다! 각 상황마다 선택이 달라질 수도 있을 것 같아요~!
아 무조건 양방향 참조를 해야하는 건 아닙니다~

> 다대일 단방향 관계에서 부모 엔티티가 제거되었을 때 자식을 연쇄적으로 지우는 방법을 찾아보니 두가지가 있었습니다.

우선은 wish와 product를 다대일 단방향 관계로 설계하였는데, 연쇄적인 제거를 위해서는 product 쪽에 cascade를 걸기 위해 양방향으로 설계를 바꾸거나, 단방향을 그대로 유지하고 wish쪽에 @OnDelete를 쓰는 방법이 있다고 합니다.

당장 보기에는 단방향을 유지할 수 있는 @OnDelete만 쓰면 되는 것 아닌가싶기도 한데... 실무에서는 어떤 방법을 어떤 상황에 쓰는지 궁금합니다.

이 부분에 대한 대답도 바로 위의 답과 같습니다! 상황마다 다르기 때문에 직접 경험해 보면서 자신이 생각했을 때 가장 올바를 방법을 정하고, 그러한 과정 속에서 기준을 세우게 될 것 같아요!

음 제가 있는 곳에선 양방향은 최대한 자제하는 편이기도 하고, 사실 연관관계도 많이 쓰진 않습니다.!ㅋㅋ

이번엔 고칠 건 딱히 없어 보여서 간단한 질문과 팁만 남겼고, 다음 리뷰땐 바로 머지할 예정입니다~!

2024-07-13 14:25 UTC, jjongwa commented on src/main/java/gift/product/model/Wish.java
> +    private final Product product;
onDeleteAction의 설정에는 어떤게 있나요?
각각은 어떤 특징을 가지고 있고, 현재의 상황에서는 왜 CASCADE를 사용하게 되었나요?

2024-07-13 14:25 UTC, jjongwa commented on src/main/java/gift/product/service/WishService.java
> +
optional에는 `orElseThrow`와 `orElseGet` 이 존재하는데, 각각 가져온 객체가 empty상태일 때 예외를 바로 던지거나, 디폴트 값을 넣어줄 때 사용합니다!

여기서는 orElseThrow를 사용해 이렇게 리팩토링 할 수도 있곘네요!

```suggestion
private Member getMember(LoginMember loginMember) {
        return authRepository.findById(loginMember.id())
                .orElseThrow(() -> new NoSuchElementException("회원 정보가 존재하지 않습니다."));
    }
```

2024-07-13 14:25 UTC, jjongwa commented on src/test/java/gift/repository/WishRepositoryTest.java
> +
ㅎㅎ 테스트까지 깔끔하게 잘 작성해 주셔서 리뷰할게 별로 없네요..!
자잘한 팁으로 하나 더 나갑니다..ㅎㅎ
`@DisplayNameGeneration`게 있는데, 이를 통해 메서드의 이름 표기 스타일을 변경시킬 수 있어요!

예를 들어, 
`@DisplayNameGeneration(DisplayNameGenerator.ReplaceUnderscores.class)`
이렇게 사용하면 

기존에는 이렇게 표시되던 테스트 이름이
![image](https://github.com/user-attachments/assets/e1451b84-9007-4fa1-a5b8-e1c884a6f068)


이렇게 밑줄 없이 조금 더 깔끔해집니다.!
![image](https://github.com/user-attachments/assets/afc404ac-120c-4a49-a4ed-b888ec18a9cc)


그래서 저는 한글 이름 메서드를 사용할 때 다음 두 어노테이션을 붙이는 편이에요~
```
@DataJpaTest
@DisplayNameGeneration(DisplayNameGenerator.ReplaceUnderscores.class)
@SuppressWarnings("NonAsciiCharacters")
class WishRepositoryTest {
```

2024-07-13 14:25 UTC, jjongwa commented on src/test/java/gift/repository/WishRepositoryTest.java
> +
DatapaTest와 SpringBootTest의 차이점은 무엇일까요?

현재 테스트 코드에는 테스트에서 사용된 데이터를 삭제하거나 초기화 하는 코드가 없는데 다른 테스트와의 충돌은 없을까요?

2024-07-13 14:25 UTC, jjongwa commented on src/test/java/gift/service/ProductServiceTest.java
> +class ProductServiceTest {
새롭게 만든 서비스 테스트와 기존에 존재하던 리포지터리 테스트가 검증하는 부분이 비슷한 것 같아요!

서비스 계층에서 진행하는 예외 처리 부분에 대한 테스트를 추가해 보는건 어떨까요?

2024-07-14 05:28 UTC, minsu-cnu commented on src/main/java/gift/product/model/Wish.java
> +    private final Product product;
onDeleteAction의 설정에는 다음과 같은 설정들이 있습니다.

1. NO_ACTION : 부모가 제거될 때 이를 참조하고 있는 자식에 대해 아무런 행동도 하지 않습니다. 이 경우, 참조 무결성 제약 조건을 체크할 때 자식이 여전히 제거되었던 부모를 참조하고 있는 경우 트랜잭션에서 오류를 발생시킨다고 합니다.

2. CASCADE : 부모가 제거될 때, 이를 참조하고 있던 자식도 같이 제거시킨다고 합니다. 이는 DB 단에서 on delete cascade 제약조건을 건 것과 동일하며 JPA 상에서는 단 한 개의 delete 쿼리가 생성된다고 합니다.

3. RESTRICT : 부모를 제거하려고 시도할 때 이를 참조하고 있는 자식이 있다면 삭제를 막고 에러를 발생시킵니다. 이를 통해 참조 무결성을 잘 유지할 수 있습니다.

4. SET_NULL : 부모를 제거할 때, DB 상에서 이를 참조하고 있는 자식이 갖고 있던 외래키를 null로 바꿔주는 설정입니다. 코드 상에서도 자식 객체가 갖고 있던 부모 객체 필드를 null로 바꿔주는 듯 합니다.

5. SET_DEFAULT : SET_NULL과 유사한데, null 값 대신 기본 값으로 바꿔주는 동작을 합니다. 다만 이는 JPA나 하이버네이트에서 직접적으로 지원하지 않는 기능이라고 합니다. 따라서 DB 스키마에서 기본값을 잘 설정해두거나, 코드 상에서 직접 구현할 필요가 있을 듯 합니다.


현재 상황에서 제가 원한 것은 상품을 삭제할 때, 이 상품에 해당하는 위시리스트 항목을 같이 제거시켜주는 것이었으므로 CASCADE 옵션을 사용하게 되었습니다.

2024-07-14 05:28 UTC, minsu-cnu commented on src/main/java/gift/product/service/WishService.java
> +
꿀팁 감사합니다! 바로 적용하겠습니다.

2024-07-14 05:28 UTC, minsu-cnu commented on src/test/java/gift/repository/WishRepositoryTest.java
> +
알려주신 내용 적용하니 훨씬 보기 편해졌습니다. 감사합니다!

2024-07-14 05:28 UTC, minsu-cnu commented on src/test/java/gift/repository/WishRepositoryTest.java
> +
SpringBootTest는 프로젝트 내에 모든 빈을 로드시키고, DataJpaTest는 JPA 관련 빈(엔티티 매니저, JPA 레포지토리 등)만 로드시켜서, JPA 레포지토리만을 테스트하는 경우에는 DataJpaTest를 사용하여 테스트 속도 상 이득을 볼 수 있습니다.

또한 DataJpaTest 어노테이션을 추적해서 들어가보면 내부에 Transactional 어노테이션이 기본적으로 선언되어 있습니다.
이를 통해 테스트 클래스 내의 테스트 인스턴스마다 종료 시 롤백을 시키기때문에, 테스트 간의 충돌이 발생하지 않는 것이라고 생각합니다.

그리고 테스트 클래스 간의 충돌 또한 막기 위해, spring.jpa.hibernate.ddl-auto=create-drop를 설정해주었습니다.

2024-07-14 05:29 UTC, minsu-cnu commented on src/test/java/gift/service/ProductServiceTest.java
> +class ProductServiceTest {
리뷰 반영하여 예외 처리 부분에 대한 테스트를 서비스 테스트에 추가해보았습니다!

2024-07-15 14:00 UTC, jjongwa commented on src/test/java/gift/repository/WishRepositoryTest.java
> +
> 또한 DataJpaTest 어노테이션을 추적해서 들어가보면 내부에 Transactional 어노테이션이 기본적으로 선언되어 있습니다.

아주 좋습니다~! ㅎㅎ 이렇게 자주 사용하는 어노테이션이 어떤 설정을 상속하고 있는지 확인하는 습관을 가지면 좋아요~!

2024-07-15 14:01 UTC, jjongwa commented on src/main/java/gift/product/model/Wish.java
> +    private final Product product;
잘 정리해 주셨어요! 💯

2024-07-15 14:02 UTC, jjongwa approved these changes
수고하셨어요! 4주차도 달려봅시다 🚗 🚗

2024-07-15 14:02 UTC, merged