부산대 BE_강수민 3주차 과제 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #278
Opened 2024-07-11 19:35 UTC by wvssm

Product-Wish, Member-Wish 각각 양방향 One to Many로 연관 관계를 맺은 뒤, 테스트 코드를 작성했습니다 :D 

## 리뷰받고 싶은 내용
1. 추가적으로 더 테스트해보면 좋을 것 같은 기능이 있는지 궁금합니다.
2. 현재 저는 Lazy Fetch를 쿼리가 나가는지 직접 보는 것을 통해서 테스트를 진행했는데, 이것 말고 다른 테스트 방법이 있는지 궁금합니다.

바쁜 시간 와중에도 정성스럽게 리뷰 남겨주셔서, 항상 감사드립니다.❤️

2024-07-12 08:09 UTC, jadie0319 reviewed
3단계 진행 중이셔서 머지는 안할게요~
피드백 확인해주시고 3단계 완료 하시면 리뷰요청 눌러주세요!

2024-07-12 08:09 UTC, jadie0319 commented on src/main/java/gift/domain/Member.java
>  @Table(name="member")
schema.sql 에 있는 테이블명과 일치시켜주는게 좋아요~ Product, Wish 도 동일 합니다.

2024-07-12 08:09 UTC, jadie0319 commented on src/main/java/gift/domain/Member.java
> +    }
이 두 메서드는 도메인 로직과는 거리가 머니 코드 제일 아래에 위치시키면 어떨까요?

2024-07-12 08:09 UTC, jadie0319 commented on src/main/java/gift/controller/WishRestController.java
ProductRestController 의 RequestMapping url 과 통일시켜주는게 좋을 것 같아요.
/wishes 앞에 api 를 붙여주거나 product 측에서 api 를 제거해주면 될 것 같아요
member 도 동일하게 적용되는 피드백 입니다~

2024-07-12 08:09 UTC, jadie0319 commented on src/test/java/gift/repository/ProductRepositoryTest.java
> +        expectedProduct = new Product(expectedName, expectedPrice, expectedImageUrl);
사실 제가 의도했던 코드 중복을 줄이는 방법은 
```java
  product1 = createProduct("아메리카노", 4500, "americano");
...
  private Product createProduct(String name, Integer price, String url) {
    return new Product(name, price, url);
  }
```
이렇게 new Product 를 한곳에서만 사용하는 코드를 의도하긴 했습니다 ㅎ
또는 test fixture 객체 생성하는 것도 하나의 방법입니다. :)

BeforeEach 사용도 좋았지만 DataJpaTest 에서 필요한지는 좀 고민해봐야겠네요 ㅎ

2024-07-12 08:09 UTC, jadie0319 commented on src/test/java/gift/repository/WishRepositoryTest.java
>      private EntityManager entityManager;
Product, Wish, Member 공통 피드백 입니다.

현재 방식의 entityManager 를  사용하여 영속성을 직접 제어하고 테스트하려는 도메인의 Repository만 주입하는 방식과
MemberRepository, ProductRepository 를 사용하여 entityManager 를 통해 영속성을 직접 제어하지 않아도 되는 방식이 있어요.(EntityManager 삭제)
수민님은 어떤 코드가 더 좋아보이시나요?

2024-07-12 08:09 UTC, jadie0319 commented on src/main/java/gift/service/WishService.java
> +    public List<WishResponseDto> getMemberWishesByMemberId(Long memberId){
호출하면 아래와 같은 에러가 나옵니다~ 원인이 뭘까요?
spring.jpa.open-in-view 라는 옵션과 엔티티를 컨트롤러로 반환했을 때 어떤일이 생기는지 
찾아보시면 될거에요!

![image](https://github.com/user-attachments/assets/3ac108f8-ca31-4931-9686-27ae9cfaac7d)

2024-07-12 08:09 UTC, jadie0319 commented on src/main/java/gift/service/WishService.java
> +        member.addWish(newWish);
35,36 Line 의 코드는 비즈니스 로직과는 무관한 것 같아요.
35,36 Line 의 연관관계 편의 메서드를 Wish 를 생성하는 로직에 넣으면 어떨까요?
그러면 서비스단 로직이 더 깔끔해 질것 같아요!

```suggestion
        Wish newWish = Wish.of(member,product,wishRequestDto.getQuantity());
```

2024-07-12 08:09 UTC, jadie0319 commented on src/main/java/gift/service/WishService.java
> +        wish.getProduct().removeWish(wish);
이 두 메서드를 추가하신 이유가 뭘까요? 없어도 되지 않을까요?? 
필요하시다면 wish.getMember() 나 wish.getProduct() 로 조회 후 remove 하지 말고
wish 에 위임하는건 어떨까요?

객체지향 생활 체조 원칙을 참고해 보시면 도움이 될거에요~
- 규칙 4: 한 줄에 점을 하나만 찍는다.
- "Tell, Don't Ask" 라는 객체지향 문구가 있어요!

2024-07-12 08:20 UTC, jadie0319 commented on src/test/java/gift/domain/MemberTest.java
> +class MemberTest {
도메인 로직도 테스트해주셨네요 👍

2024-07-12 08:27 UTC, jadie0319 commented
안녕하세요 수민님! 
3단계 미션 중이셔서 머지는 안했습니다 :)
2단계 피드백 드리다가 퇴근 후 더 자세히 봐야 할 것 같아서 일단 중간 피드백 먼저 남깁니다 ㅎ
질문해 주신것 답변 간단하게 드릴게요 ㅎ

- 추가적으로 더 테스트해보면 좋을 것 같은 기능이 있는지 궁금합니다.

현재 DataJpaTest 에서는 더 구현해야할 대상이 안보이네요. 테스트 꼼꼼하게 잘 작성해주셨습니다!
도메인 로직 테스트는 도메인 로직이 좀 더 풍부해지면 다뤄보기로 해요 ㅎ 일단은 E2E 테스트나 서비스 로직 통합테스트 해보시면 어떨까요? 모든 기능을 다 테스트 해보시면 좋겠지만 우선순위로 해보실건 WishService 를 우선으로 테스트 해주시면 좋을 것 같아요~ 

- 현재 저는 Lazy Fetch를 쿼리가 나가는지 직접 확인하여 테스트 했는데, 이것 말고 다른 테스트 방법이 있는지 궁금합니다.

쿼리를 직접 확인하시는 것만 해도 정말 좋은 습관입니다 🙂 JPA 를 사용하지만 실제로 쿼리가 어떻게 실행됐는지 확인 안(or못) 하는 경우도 정말 많거든요.

 인텔리제이 디버깅 모드를 통해서 확인하는 방법도 있습니다! LAZY 로딩된 객체의 모습이 조금 다르다는 것을 눈으로 확인하실 수 있을거에요!

2024-07-13 09:26 UTC, jadie0319 requested changes
3주차 미션하시느라 고생하셨어요!
이번 주차에 배운 JPA 학습 테스트 작성 좋습니다 💯 
이번 미션에 대한 피드백 남겨놨으니 확인 부탁드려요! 그리고 질문 주신건 코멘트로 작성해놓겠습니다!

2024-07-13 09:26 UTC, jadie0319 commented on src/main/java/gift/controller/ProductRestController.java
> +    public ResponseEntity<List<ProductResponseDto>> getPagedProducts(@PageableDefault(size = 5, sort = "id", direction = Sort.Direction.DESC) Pageable pageable){
`@PageableDefault` 사용 좋습니다! 👍

2024-07-13 09:26 UTC, jadie0319 commented on src/test/java/gift/domain/ProductTest.java
> +class ProductTest {
이전 미션에서 상품 이름에 카카오 문자열과 특수기호에 대한 제약사항이 있었어요.
그 제약사항을 DTO -> Product 도메인의 제약사항으로 옮기면 도메인 객체 테스트 코드도 짤 수 있을 것 같아요~

2024-07-13 09:26 UTC, jadie0319 commented on src/test/java/gift/repository/ProductRepositoryTest.java
ProductRespository 에서 findById 메서드를 사용중인 곳을 찾아보면 아래와 같이 사용하고 있는 곳이 나와요
![image](https://github.com/user-attachments/assets/a8b0f76c-ca09-4955-82e4-77f88cfbdb03)

만약 테스트 코드가 더 늘어나면 사용하고 있는 메서드가 엄청 많이 나올 것 같아요.
사용하고 있는 곳이 많아지면 코드를 찾기 어려워지고 변경하기 어려운 코드가 돼요. 

그리고 해당 메서드가 실제 비즈니스 로직에서 사용하는 곳이 한눈에 들어와야 하는데
테스트 코드에서 사용하는 목록 때문에 한눈에 안들어오는 문제도 있어요.

테스트코드에서 사용하는 findById 메서드의 중복을 줄여볼까요?
ProductRepositoryHelper 라는 테스트 도우미 클래스를 만들수도 있을 것 같고 메서드를 분리할 수도 있을것 같아요 :)

2024-07-13 09:40 UTC, jadie0319 commented on src/main/java/gift/service/WishService.java
>          wishRepository.save(updatedWish);
```suggestion
existingWish.updateQuantity(request.getQuantity());
```
위와 같이 한줄의 코드로 해결할 수도 있었을 것 같은데 Wish 객체를 만들고 save한 이유가 있을까요?

2024-07-13 16:22 UTC, jadie0319 commented on src/main/java/gift/service/ProductService.java
> +                .toList();
Paging 처리 요청에 대한 응답으로 어떤 데이터가 포함되어야 할까요?
응답값으로 받은 Page 인터페이스가 제공하는 메서드를 확인하시면서 고민해보면 좋을 것 같아요!

2024-07-14 22:11 UTC, merged

2024-07-15 01:06 UTC, wvssm commented on src/main/java/gift/domain/Member.java
>  @Table(name="member")
테이블명이 복수 명사가 되도록 통일하겠습니다! 👍

2024-07-15 01:39 UTC, wvssm commented on src/main/java/gift/domain/Member.java
> +    }
로직과 관련없기 때문에 아래로 이동하는 것이 맞다고 생각합니다!
수정하도록 하겠습니다 :) 
메서드의 기능에 따라 위치도 앞으로 고려하겠습니다!

2024-07-15 01:41 UTC, wvssm commented on src/main/java/gift/controller/WishRestController.java
wishes앞에 api를 붙여 api path를 통일시키겠습니다!

2024-07-15 02:22 UTC, wvssm commented on src/test/java/gift/repository/ProductRepositoryTest.java
> +        expectedProduct = new Product(expectedName, expectedPrice, expectedImageUrl);
createProduct 함수를 사용하면 객체 생성로직을 한 곳에서 관리할 수 있어서 좋다고 생각합니다!

BeforeEach 대신에 Builder 패턴을 사용하여 생성자가 변경되더라도 필요 부분만 수정할 수 있도록 수정하겠습니다!

2024-07-15 04:13 UTC, wvssm commented on src/test/java/gift/repository/WishRepositoryTest.java
>      private EntityManager entityManager;
상황에 따라 다르다고 생각합니다!
단순한 CRUD 작업을 테스트하는 경우에는 레포지토리만 사용하는 것이 좋은 것 같습니다.

하지만 LAZY fetch 같이 특정 상황의 쿼리가 날아가게 하기 위해 영속성 컨텍스트를 관리해야 하는 경우에는 Entity manager를 사용하는 게 좋을 것 같습니다!

2024-07-15 05:31 UTC, wvssm commented on src/main/java/gift/service/WishService.java
> +    public List<WishResponseDto> getMemberWishesByMemberId(Long memberId){
현재 Wish와 Product, Wish와 Member가 양방향 관계를 이루고 있는 상태에서 @RestController를 사용해 JSON으로 직열화하면, 순환 참조로 인해 위와 같은 현상이 발생합니다!

저는 Product, Member Entity를 직접 사용하지 않고 DTO로 대체하는 방식으로 일단 변경하였습니다.

2024-07-15 14:33 UTC, wvssm commented on src/main/java/gift/service/WishService.java
> +        member.addWish(newWish);
Wish를 생성하는 로직에 추가하도록 수정하겠습니다!

2024-07-15 14:40 UTC, wvssm commented on src/main/java/gift/service/WishService.java
> +        wish.getProduct().removeWish(wish);
wish 객체가 삭제될 때, 이와 관련된 member, product에서도 관계를 끊기 위해서(일관성을 유지 하기 위해서) 해당 두 메서드를 사용했습니다!

데이터베이스에서는 wish가 삭제되면, 자동으로  외래키 관계가 정리되어서 필수적이라고 생각하진 않습니다!

하지만 메모리 내에서 객체 간의 관계를 일관되게 유지하기 위해서 사용했습니다!

2024-07-15 14:48 UTC, wvssm commented on src/main/java/gift/service/WishService.java
>          wishRepository.save(updatedWish);
제가 최근에 JPA를 배워서  엔티티의 속성을 변경하기만 하면, 별도로 save 메서드를 호출하지 않아도 트랜잭션이 끝날 때 변경 사항이 자동으로 데이터베이스에 반영된다는 사실을 오늘 제대로 알았습니다!
아래와 같이 수정하겠습니다!

2024-07-15 14:48 UTC, wvssm commented on src/test/java/gift/domain/ProductTest.java
> +class ProductTest {
다음에 Product 도메인 테스트 코드 작성할 때 참고하겠습니다!

2024-07-15 16:11 UTC, wvssm commented on src/main/java/gift/service/ProductService.java
> +                .toList();
반환값을 List<ProductResponseDto> 하는 대신 Page<ProdcutResponseDto>로 변경하여 
총 페이지 수, 총 element 개수, page 크기, content 등을 반환하게 변경했습니다!

![image](https://github.com/user-attachments/assets/3a70b5db-3563-4212-aa89-374e903e304a)

2024-07-15 16:38 UTC, wvssm commented on src/test/java/gift/repository/ProductRepositoryTest.java
ProductRepositoryHelper라는 클래스를 만들어 메서드 분리를 하여 
test에서 findById 사용 횟수를 줄여보겠습니다!