충남대 BE_이택 3주차 과제 step2
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #282
Opened 2024-07-11 20:31 UTC by LeeTaek2T

아직 step2단계를 모두 구현하지 못했습니다.
현재, 양방향 관계를 모두 맺고, wishListService에 이를 적용하려 하는데 감이 잡히지가 않습니다...
제가 생각하는 것은 product와 member를 db에 저장하고, db에 저장되어 있는 member와 product 내용을 WishListController로 요청 보내면, 해당 member와 product가 wishlist테이블에 저장이 되는 것을 생각하였습니다.
하지만, addProductToWishList에 getId()를 한 경우 null이므로 안된다는 오류가 계속 뜹니다.
member와 product는 post요청을 통해 미리 저장을 한 상태인데도 오류가 뜹니다...

어떤 식으로 가야할지 조금의 도움을 주실 수 있을까요?

2024-07-12 00:17 UTC, ksy90101 requested changes
고생하셨습니다~

2024-07-12 00:17 UTC, ksy90101 commented on src/main/java/gift/DTO/Member.java
> +  public boolean matchLoginInfo(MemberDto memberDtoByEmail) {
```suggestion
  }

  public boolean matchLoginInfo(MemberDto memberDtoByEmail) {
```

개행을 잘 관리해주세요.

2024-07-12 00:17 UTC, ksy90101 commented on src/main/java/gift/DTO/Product.java
> +  @Column(nullable = false)
```suggestion
  private Long id;

  @Column(nullable = false, unique = true)
  private String name;
  
  @Column(nullable = false)
```

2024-07-12 00:17 UTC, ksy90101 commented on src/main/java/gift/DTO/Product.java
> +  private String imageUrl;
여기도 nullable을 명시해주면 어떨까요?

2024-07-12 00:17 UTC, ksy90101 commented on src/main/java/gift/Repository/WishListRepository.java
> +  List<WishList> findByProductId(Long productId);
이렇게 되었을떄 Member나 Product를 조회할때 N+1문제가 발생합니다.
N+1가 뭔지 찾아보시고 한번 해결해보면 어떨까요?

2024-07-12 05:14 UTC, LeeTaek2T commented on src/main/java/gift/DTO/Member.java
> +  public boolean matchLoginInfo(MemberDto memberDtoByEmail) {
네! 알겠습니다.

2024-07-12 05:18 UTC, LeeTaek2T commented on src/main/java/gift/DTO/Product.java
> +  private String imageUrl;
좋은 것 같습니다!

2024-07-12 06:35 UTC, LeeTaek2T commented on src/main/java/gift/Repository/WishListRepository.java
> +  List<WishList> findByProductId(Long productId);
이런 문제가 있는지 몰랐습니다
알려주셔서 감사합니다!

2024-07-12 06:40 UTC, LeeTaek2T commented
Optional은 service에서 모두 해결하는게 좋다고 하셨습니다. 그런데 @LonginUser같은 경우 Optional로 인자를 받도록 설정이 되어있습니다. 이 경우에도 다른 방법을 찾아 Controller에서는 Optional을 사용하지 않는 것이 좋을까요?

2024-07-12 07:02 UTC, ksy90101 commented
LoginUser에서 optional이 아니라 실제 객체를 리턴시키면 되지 않을까요?
Optional을 쓰신 이유가 궁금해요.

2024-07-12 07:05 UTC, ksy90101 requested changes
좀더 수정해보시죠~
https://dev-coco.tistory.com/178
한번 이글을 읽어보시고 옵셔널 사용법을 알아보시면 어떨까요!?
Optional은 잘못쓰면 좀 코드가 애매해져서, 한번 공부해보시면 좋을거 같아요~

2024-07-12 07:05 UTC, ksy90101 commented on src/main/java/gift/Repository/WishListRepository.java
> +  List<WishList> findByMemberId(Long memberId);
실제 메서드와 쿼리가 다르지 않나요?

이렇게 되면 전체 WishList가 나올거 같은데요~

2024-07-12 07:05 UTC, ksy90101 commented on src/main/java/gift/Controller/ProductController.java
>      }
이 로직이 필요할까요? updateProduct에서 예외처리를 했으니 이제 동작하지 않을거 같아요~

2024-07-12 07:05 UTC, ksy90101 commented on src/main/java/gift/Service/ProductService.java
> +    Optional<Product> productOptional = productRepository.findById(id);
get을 쓰지 말고 orElseThrow를 써서 예외를 처리하는게 좋습니다.

2024-07-12 08:03 UTC, LeeTaek2T commented on src/main/java/gift/Controller/ProductController.java
>      }
이 부분하고 아래의 리뷰 부분은 바꿨었는데 merge하면서 이상하게 바꾼것 같습니다ㅠㅠ
제대로 확인하겠습니다!

2024-07-12 08:33 UTC, LeeTaek2T commented on src/main/java/gift/Repository/WishListRepository.java
> +  List<WishList> findByMemberId(Long memberId);
where문과 @Param을 이용하여 수정해보겠습니다!

2024-07-13 04:51 UTC, ksy90101 approved these changes
고생하셨습니다~
3단계에서 뵈요!!

2024-07-13 04:51 UTC, merged