충남대 BE_신성희 3주차 과제 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #287
Opened 2024-07-12 03:38 UTC by Shsin9797

공부를 좀 하다가 해봤는데 이해가 잘 안되긴해서 
시간관계상 GPT 도움을 받아서 작성했습니다. 
주말동안 공부해서 이해를 좀 더 해보겠습니다.

2024-07-12 19:14 UTC, asebn1 requested changes
2단계는 1단계 코드에서 크게 수정사항이 없어서 코멘트 몇 가지만 작성하였습니다~
PR 충돌이 나고 있는데 이 부분만 확인해주세요 :)
2단계는 충돌해결되면 머지하겠습니다.
3단계 PR에 1, 2단계 코멘트드린 부분 함께 개선해서 리뷰요청주세요!

2024-07-12 19:14 UTC, asebn1 commented on src/main/java/gift/entity/Product.java
> +
`product`에서 wishes를 관리하는 게 어색하다고 느껴지네요

2024-07-12 19:14 UTC, asebn1 commented on src/main/java/gift/entity/User.java
`CascadeType`, `orphanRemoval`를 학습해보고 적용해볼까요?

2024-07-12 19:14 UTC, asebn1 commented on src/main/java/gift/entity/Wish.java
>      private Long userId;
`product`, `user`와 중복되는 것 같아요

2024-07-12 19:14 UTC, asebn1 commented on src/main/java/gift/entity/Wish.java
> +    }
`setter`는 사용하지 않는걸 습관들여봅시다 ㅎㅎ

2024-07-13 06:06 UTC, Shsin9797 commented
넹 !! conflicts 해결 했습니다!! 코드리뷰해주신 부분은 3단계에서 반영해서 올리겠습니다!!

2024-07-14 15:39 UTC, Shsin9797 commented on src/main/java/gift/entity/User.java
Cascade 및 OrphanRemoval

@OneToMany 관계에 cascade = CascadeType.ALL과 orphanRemoval = true를 추가하여 Product 엔티티가 삭제될 때 관련된 Wish 엔티티도 함께 삭제

*  영속성 전이(CASCADE) :부모 엔티티가 영속화될 때 자식 엔티티도 같이 영속화되고, 부모 엔티티가 삭제될 때 자식 엔티티도 삭제되는 등 특정 엔티티를 영속 상태로 만들 때 연관된 엔티티도 함께 영속 상태로 전이되는 것 =특정 엔티티에 대해 특정한 작업을 수행하면 관련된 엔티티에도 동일한 작업을 수행한다는 의미

* CascadeType의 종류 :  PERSIST, MERGE, DETACH, PREFRESH, REMOVE, ALL 

* CascadeType.ALL: 모든 Cascade를 적용
**CascadeType.PERSIST**: 엔티티를 영속화할 때, 연관된 엔티티도 함께 유지
**CascadeType.MERGE:** 엔티티 상태를 병합(Merge)할 때, 연관된 엔티티도 모두 병합
**CascadeType.REMOVE**: 엔티티를 제거할 때, 연관된 엔티티도 모두 제거
**CascadeType.DETACH:** 부모 엔티티를 detach() 수행하면, 연관 엔티티도 detach()상태가 되어 변경 사항 반영 X
**CascadeType.REFRESH:** 상위 엔티티를 새로고침(Refresh)할 때, 연관된 엔티티도 모두 새로고침


* orphanRemoval은 부모 엔티티와의 관계가 제거된 자식 엔티티를 자동으로 삭제하는 기능

2024-07-14 15:53 UTC, Shsin9797 commented on src/main/java/gift/entity/Product.java
> +
비즈니스 로직 관점:

Wish는 일반적으로 특정 사용자(user)가 특정 제품(product)을 원하는 경우를 나타내는 엔티티이다. 따라서 Wish 엔티티는 주로 사용자와 관련이 있다 .
사용자가 특정 제품을 원하는 경우, User 엔티티가 Wish 컬렉션을 가지고 있는 것이 자연스러울 수 있다.

-> product 에서는 wish를 관리하지 않도록한다 .

2024-07-14 16:36 UTC, asebn1 approved these changes
2단계 머지하겠습니다~!

2024-07-14 16:37 UTC, merged