경북대 BE_우현서 3주차 과제 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #290
Opened 2024-07-12 04:39 UTC by wndlthsk

Wish에서 Member, Product로 변경하였더니 현재는 wish 조회시 member와 product의 모든 정보가 다 나옵니다. wish 조회시 어떤 정보를 반환해야하는지 헷갈립니다..!!

2024-07-13 15:38 UTC, leaf-upper requested changes
현서님 3주차 2,3단계 구현 고생하셨습니다~ 👍 👍 
몇가지 코멘트를 남겨드렸는데 수정해주시면 어프로브 및 머지해두겠습니다
질문주신 부분에 대해서 몇가지 답변드릴게요~

1. dto에도 id가 반영되어야할까요?
id는 해당 데이터를 식별할 수 있는 값이기 때문에 dto에 id값이 반영되는경우가 많아요. db에서 만들어주는값이고 애플리케이션에서 이를 잘 활용해야합니다. 이 id값을 통해서 저희는 데이터를 식별하고 사용할수 있어요!

2. wish 조회시 어떤 정보를 담아야할까요?
이부분은 요구사항과 크게 맞닿아 있는 부분일것 같아요. 관리자 화면에서 필요한 데이터는 전부 포함하여 응답으로 넣어주시면 될것 같아요. wish에서 객체매핑으로 member와 product에 접근할 수 있는 만큼, 더 쉽게 데이터를 매핑하실수 있을것 같아요~

2024-07-13 15:38 UTC, leaf-upper commented on src/main/java/gift/controller/ProductAdminController.java
> +        @RequestParam(name = "page", defaultValue = "0") int page,
- page가 -1로 들어오면 어떻게 될까요?
- size가 굉장히 큰 숫자로 들어오면 어떻게 될까요?
- 존재하지 않는 정렬방식으로 값이 들어오면 어떻게 될까요?
Validation 추가해주시면 좋을것 같아요~

2024-07-13 15:38 UTC, leaf-upper commented on src/main/java/gift/controller/ProductAdminController.java
> +        @RequestParam(name = "sortBy", defaultValue = "id") String sortBy) {
정렬기준도 Controller에서 전달받네요~ 👍

2024-07-13 15:38 UTC, leaf-upper commented on src/main/java/gift/service/WishService.java
> +    public Page<Wish> findPagedWishesByMemberId(Long id, Pageable pageable) {
저도 findByMemberId가 좋은것 같아요~ 메서드는 오버로딩이 가능하니, findByMemberId(Long id)는 모든 위시를 반환하고, findByMemberId(Long id, Pageable pageable)은 페이징 결과를 반환하기 때문에 대부분의 경우 코드를 이해할 수 있을것 같아요! 👍  좋은고민이네요~

2024-07-14 12:47 UTC, wndlthsk commented
product와 wish는 responseDto가 필요하다고 판단하여 생성하였습니다! 
wish 조회시 wish id, member_email, product_name, product_price 가 필요할 것 같아 4가지로 WishResponseDto를 구성하였습니다.
pagination은 PageRequestDto를 생성하여 validation을 구현하였습니다. 아직 정렬 방식에서 product와 wish를 분리하진 못하여서 이 부분은 좀 더 생각해보겠습니다!

2024-07-14 14:03 UTC, leaf-upper approved these changes
👍 👍 3주차 고생하셨습니다 현서님
대부분 코드 잘 작성해주셔서 어프로브드릴게요~!

2024-07-14 14:03 UTC, merged