전남대 BE_박민규 3주차 과제 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #291
Opened 2024-07-12 04:48 UTC by ps9319

2024-07-12 18:02 UTC, ps9319 commented on src/main/java/gift/dto/responseDTO/WishResponseDTO.java
> +        return new WishResponseDTO(wish.getId(), wish.getUser().getId(), wish.getProduct().getId(),
제가 생각했을 때 여기서 N+1문제가 발생할 거라고 생각했는데 발생하지 않는 이유를 찾는 데에 시간을 좀 많이 썼습니다.

Lazy 로딩할 때 일단 proxy 객체를 가져온 다음, 관련 객체 정보를 가져올 때 ex) wish.getUser() 이 때 N + 1 문제가 발생할 거라고 생각했는데 발생하지 않아서 의아했습니다. 조금 찾아본 결과 Id값만을 가져올 때는 N + 1문제가 생기지 않는다는데 이게 맞는 건지 궁금합니다 ㅠㅠㅠㅠ.... 이 의문점을 해결하는데에도 오래 걸렸습니다.

2024-07-13 01:00 UTC, dc-choi requested changes
안녕하세요 민규님! 오랜만에 `@OneToMany`를 사용하시느라 정말 고생하셨어요!

질문을 남겨주셨네요! 답변을 드리자면 다음과 같습니다!

> 저는 양방향 연관관계가 좋지 않다고 해서 쓰지 않으려고 하는데, 조회할 때 양방향 연관관계가 필요해서 쓰는 경우가 가끔 있다고 하더라구요. 그래서 멘토님께서는 양방향 연관관계를 쓰시는지 궁금합니다. 만약 쓴다면 어떤 경우에 쓰는게 좋은지도 궁금합니다.

이미 어느정도 아시는거 같지만... 저도 필요한 경우에 추가해서 사용하긴 합니다! `@OneToMany`에서 신경쓰는 부분은 cascade 정도인데 cascade의 경우 잘 사용하지는 않는거 같아요. 데이터가 유실될 가능성이 있어서 잘 안합니다... ㅎㅎ

> 또한 저는 함께 생성되는 객체끼리만 객체 참조로 묶고, 다른 것들은 간접 참조로 id 참조를 하려고 노력하는데, 저는 객체 참조로 모든 것을 묶은 다음에 문제가 생겨서 id참조로 바꾼게 아닌, '그냥 나쁘다고해서, id참조할 것은 id참조해라' 라고 해서 하는 거라서 문제를 겪은 적이 없습니다. 그리고 왜 나쁜지 머릿속으로만 이해가 가는데, 막 와닿지 않는데 혹시 객체 참조로 인해서 문제를 겪은 경험이 있으면 듣고 싶어요!!

이 부분은 양방향 연관관계가 생기면서 나오게 되는 고민이라고 생각이 드는데, 제가 겪었던 문제는 객체 참조를 어디까지 할 것이냐에 대한 것이에요.

이렇게 서로 연결된 상태에서는 거의 무한대로 서로 참조를 할 수 있게 되는데 한 로직 안에서 전부 데이터를 처리할 수 있다는 생각이 들거든요.

그렇게 실제로 그런 방식으로 구현된 코드를 유지보수 하고 있고... 그 코드를 유지보수 해본 입장에서 너무 힘들었습니다...

> service 테스트 코드도 작성했어야하는데 생각보다 2단계가 오래걸려서... 3단계 끝나고 해보겠습니다...

넵 알겠습니다~! 천천히 해주세요~!

> 또 예외를 커스텀해보려고 했는데, NoSuchElement 표준 예외로도 충분히 잘 표현할 수 있을 것 같아서 NoSuchElement로 처리했습니다.

아직 처리해야하는 예외가 많이 없어서 지금 단계에서는 상관없어보입니다. 단, 실무에 들어가면 이렇다 정도로 말씀드린거니 미리 알아두기만 하면 좋을거 같아요!

민규님이 질문주신 내역에 대한 것과 자세한 코멘트는 아래 적었어요! 확인 부탁드려요~!

2024-07-13 01:00 UTC, dc-choi commented on src/main/java/gift/domain/Product.java
> +    @OneToMany(mappedBy = "product")
`mappedBy`라는 옵션을 사용하셨는데 어떤 의미를 가진 옵션인지 궁금합니다!

2024-07-13 01:00 UTC, dc-choi commented on src/main/java/gift/dto/responseDTO/WishResponseDTO.java
> +        return new WishResponseDTO(wish.getId(), wish.getUser().getId(), wish.getProduct().getId(),
제 생각에는 `wish`에서 `user`와 `product`를 바라보는게 `@ManyToOne`이라 이미 해당 테이블에 user_id와 product_id가 있기 때문이라 생각이 들어요!

아마 그 부분 때문에 실제로는 객체에 접근하는게 아니라 해당 id에 직접 접근이 가능해서 그런걸로 예상되네요.

N + 1 문제가 부모 객체에서 자식 객체로 접근할 때 문제가 발생하는거니 `user`와 `product`에서 `wish`의 id를 참조하는 경우에는 N + 1 문제가 발생할 것으로 예상이 되고요.

2024-07-13 03:22 UTC, ps9319 commented on src/main/java/gift/dto/responseDTO/WishResponseDTO.java
> +        return new WishResponseDTO(wish.getId(), wish.getUser().getId(), wish.getProduct().getId(),
아하 알겠습니다! 답변 감사합니다! jpa는 공부해도 어려운 것 같아요

2024-07-13 04:36 UTC, ps9319 commented on src/main/java/gift/domain/Product.java
> +    @OneToMany(mappedBy = "product")
양방향 연관관계에서는 연관관계의 주인을 나타내주려고 씁니다.
mappedBy를 하지 않으면 OneToMany 관계에서는 새로운 테이블을 하나 생성하게 되는데, 이때 '다'쪽에서 '일'을 바꿀 때 그 새로운 테이블에 반영해주지 못하게 됩니다. 예) 일 : Product, 다 : Wish. 따라서 mappedBy를 통해 연관관계의 주인을 정해줘서 "다"쪽에서만 "일"을 변경할 수 있게 하는 옵션입니다.

2024-07-13 15:08 UTC, dc-choi approved these changes
민규님! 코드 확인하였고 문제가 없어보입니다!

E2E Test는 3단계가 끝나고 한번 작성해보시면 더 좋아보입니다!

바로 Merge 하도록 하겠습니다! 수고하셨습니다!

2024-07-13 15:08 UTC, merged