전남대 BE_안재영_3주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #293
Opened 2024-07-12 05:09 UTC by ajy9851

JPA와 User를 Member로 리팩토링 하는 과정에서 많이 꼬인건지 엄청 시간을 잡아먹었습니다ㅠ

2024-07-12 12:55 UTC, gunom requested changes
안녕하세요 재영님! 꼬이셨다고 하셨지만, 결과물은 훌륭합니다! 몇가지 리뷰 남겼으니 반영해주시면 좋을 것 같습니다!

2024-07-12 12:55 UTC, gunom commented on src/main/java/gift/model/Member.java
> +    public Member() {}
실제 비즈니스에서는 초기화시키지 않은 필드가 있는 경우와 같이 실수를 유발할 수 있기에 잘 안쓰이므로 안전하게 protected로 선언하면 좋을 거 같습니다ㅎㅎ
private으로 선언하지 않는 이유는 JPA가 사용하는 Proxy와 Lazy Loading 시 내부에서 해당 엔티티 클래스를 상속받기 때문에 기본 생성자는 private으로 선언하면 안된다는 점도 따로 공부해보시면 좋을 것 같아요:)

2024-07-12 12:55 UTC, gunom commented on src/main/java/gift/service/MemberService.java
> +        return new MemberResponseDTO(member.getId(), member.getEmail());
entity모델에 하나씩 대응되는 Dto를 만들고 ResponseDto와 RequestDto는 Controller에서만 다루면, 각 레이어에 대한 책임이 더 분명해질거 같아요 :)
서비스 레이어에서 Member -> MemberDto로 변환하고 Controller에서는 반환받은 MemberDto로 ResponseEntity<MemberDto> 또는 커스텀한 Response<T>에 MemberDto를 넣는 식으로 말이죠!

2024-07-12 12:55 UTC, gunom commented on src/main/java/gift/service/WishListService.java
> +    private final MemberRepository memberRepository;
하나의 Service는 하나의 Repository만 참조하는 것이 좋습니다. 보통 WishListService는 WishRepository만 참조하게끔이요. 이렇게 하면 좋은 점은 해당 Entity에 책임을 분명하게 가지고 갈 수 있다는 점입니다.

2024-07-12 12:55 UTC, gunom commented on src/main/java/gift/service/WishListService.java
> +        return wishListRepository.findByMember(member);
그렇다면 사용자의 위시 리스트를 조회하기 위한 member는 어디서 가져오느냐
memberService를 WishListService가 참조하면 됩니다. memberService에서 getMember 메소드를 구현하고 해당 메소드를 WishListService에서 호출하면 데이터에 대한 책임이 분명해질 수 있는 것이죠.
단, 이렇게 할 때는 각 서비스가 서로 순환참조되지 않도록 조심해야합니다.

2024-07-12 12:55 UTC, gunom commented on src/main/java/gift/repository/WishListRepository.java
> +    Optional<WishList> findByMemberAndProduct(Member member, Product product);
안쓰이고 있는 거 같네요?

2024-07-14 07:18 UTC, ajy9851 commented on src/main/java/gift/service/WishListService.java
> +        return wishListRepository.findByMember(member);
아 이런 식으로 해야하는거군요...수정해보겠습니다!

2024-07-14 08:56 UTC, gunom approved these changes

2024-07-14 08:56 UTC, merged