경북대 BE_이도훈 3주차 과제 (3단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #294
Opened 2024-07-12 05:17 UTC by 2iedo

위시리스트 조회 시 토큰을 입력받을 때 임시로 admin의 토큰을 받아 admin의 위시리스트를 조회하도록 했습니다!
페이지네이션 구현 시 기존의 list를 page로 변환해서 출력했는데,
1. 처음부터 DTO를 파라미터로 받아서 페이지로 반환하는 메소드
2. 기존의 list를 리턴하는 메소드 -> 리스트를 파라미터로 받아서 페이지로 반환하는 메소드
둘 중 어떤 것이 나은 건지 잘 모르겠습니다.

2024-07-12 10:22 UTC, khj68 commented
처음부터 DTO를 파라미터로 받아서 페이지로 반환하는 메소드
기존의 list를 리턴하는 메소드 -> 리스트를 파라미터로 받아서 페이지로 반환하는 메소드
둘 중 어떤 것이 나은 건지 잘 모르겠습니다.

page로 반환하는 것 까지 Repository의 역할로 맡길 수 있기에 후자를 추천드립니다.
리스트를 받아서 다시 페이지로 변환하는 것은 비즈니스로직을 수행하는 서비스의 역할에서는 잘 어울리지 않습니다.

2024-07-12 16:42 UTC, 2iedo commented
> 처음부터 DTO를 파라미터로 받아서 페이지로 반환하는 메소드 기존의 list를 리턴하는 메소드 -> 리스트를 파라미터로 받아서 페이지로 반환하는 메소드 둘 중 어떤 것이 나은 건지 잘 모르겠습니다.
> 
> page로 반환하는 것 까지 Repository의 역할로 맡길 수 있기에 후자를 추천드립니다. 리스트를 받아서 다시 페이지로 변환하는 것은 비즈니스로직을 수행하는 서비스의 역할에서는 잘 어울리지 않습니다.

수정 완료했습니다!!

2024-07-13 15:28 UTC, khj68 requested changes
도훈님, 고생하셨습니다.
토큰을 서비스 레이어에서 파라미터로 받아 사용하는 것은 레이어 간의 의존성이 생기는 것으로 보입니다.

서비스에서는 토큰에 대한 것을 몰라도 비즈니스 로직이 실행될 수 있게 만들어주시는 것을 추천드립니다.

2024-07-13 15:28 UTC, khj68 commented on src/main/java/gift/Service/WishService.java
> +    public List<String> getAll(String token){
token이 서비스단까지 내려오는 것은 좋지 않아보입니다.
서비스는 컨트롤러 단의 리퀘스트 내용보다 어떤 정보로 자신에게 조회 요청을 하는지에 대한 책임이 있습니다.
따라서 email을 컨트롤러 단에서 꺼내 파라미터로 요청하는 것을 추천드립니다.

2024-07-13 15:28 UTC, khj68 commented on src/main/java/gift/Controller/WishRestController.java
> +        return wishService.getAll(token);
@RequestHeader에서 토큰을 받아 쓰는 것보다,
인터셉터를 이용해 특정 api path를 가진 api에 대해 토큰을 검증하고 유저 정보를 꺼내는 로직을 공통적으로 적용하는,
AOP를 적극 활용하는 것을 추천드립니다.

2024-07-13 15:28 UTC, khj68 commented on src/main/java/gift/Service/WishService.java
> +        List<String> subList = dtoList.subList(start, end);
이 부분 가독성이 아쉽습니다. 
적절한 줄바꿈이나 메소드 분리를 통해 가독성을 챙겨주시는 것을 추천드립니다.

2024-07-14 02:57 UTC, 2iedo commented on src/main/java/gift/Service/WishService.java
> +    public List<String> getAll(String token){
전부 email을 받아 작업을 수행하도록 변경했습니다!

2024-07-14 02:58 UTC, 2iedo commented on src/main/java/gift/Controller/WishRestController.java
> +        return wishService.getAll(token);
interceptor 및 configurator 추가해서 wishlist 및 product 관리할 때 interceptor가 토큰을 확인하도록 변경했습니다!

2024-07-14 02:58 UTC, 2iedo commented on src/main/java/gift/Service/WishService.java
> +        List<String> subList = dtoList.subList(start, end);
수정 완료했습니다!

2024-07-14 03:06 UTC, 2iedo commented on src/test/java/gift/RestControllerTest/ProductRestControllerTest.java
테스트 코드 작성해보려고 만들었는데 커밋을 잘못 했습니다 ㅠㅠ

2024-07-14 14:41 UTC, khj68 approved these changes
리뷰 반영된 부분 확인했습니다.
도훈님 고생 많으셨습니다 :)

2024-07-14 14:41 UTC, khj68 commented on src/main/java/gift/Service/ProductService.java
> +    public void add(String email, ProductDTO productDTO){
피드백 반영된 부분 확인했습니다 :)
이로써 서비스는 토큰과 관계 없이 자신의 역할을 독립적으로 수행할 수 있게 됩니다.
이는 추후 인증 방식이 바뀌거나 할 때 영향도가 훨씬 감소합니다.

2024-07-14 14:41 UTC, khj68 commented on src/main/java/gift/Service/ProductService.java
> +
몇 번의 줄바꿈 만으로 가독성이 좋아졌습니다 :)

2024-07-14 14:41 UTC, merged