경북대 BE_배규민 3주차 과제 (3단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #297
Opened 2024-07-12 05:27 UTC by GyuminBae

* 3주차 3단계 과제입니다!

2024-07-12 10:33 UTC, lsm7179 requested changes
규민님 과제 잘 이행해주셨습니다.💯💯

간단한 코멘트 남겼는데 한번 반영해보세요~

2024-07-12 10:33 UTC, lsm7179 commented on src/main/java/gift/core/PagedDto.java
> +            List<T> contents
제너릭 활용 좋습니다.

2024-07-12 10:33 UTC, lsm7179 commented on src/main/java/gift/wishes/infrastructure/persistence/WishesRepositoryImpl.java
> +        System.out.println(userId);
sysout은 제거해주세요~

2024-07-12 10:33 UTC, lsm7179 commented on src/main/java/gift/wishes/infrastructure/persistence/WishesRepositoryImpl.java
> +                .orElseThrow(UserNotFoundException::new);
user를 조회하는건 wishesRepository의 역할은 아닌거 같아요.
WishesService에서 userRepository를 호출해서 user를 받아온후 넘기는건 어떻게 생각하시나요?

2024-07-12 10:33 UTC, lsm7179 commented on src/main/java/gift/product/restapi/ProductController.java
> +            @RequestParam(required = false, defaultValue = "10") Integer size
`Pageable`을 이용해서 request받아보세요.
https://jaeseo.tistory.com/entry/Pageable-%EC%BB%A4%EC%8A%A4%ED%85%80-%EC%98%88%EC%99%B8-%EC%B2%98%EB%A6%ACfeat-PageableDefault

2024-07-13 07:29 UTC, GyuminBae commented on src/main/java/gift/wishes/infrastructure/persistence/WishesRepositoryImpl.java
> +        System.out.println(userId);
반영했습니다!

2024-07-13 07:29 UTC, GyuminBae commented on src/main/java/gift/wishes/infrastructure/persistence/WishesRepositoryImpl.java
> +                .orElseThrow(UserNotFoundException::new);
말씀해주신 방법이 훨씬 나은 것 같습니다! 반영했습니다!

2024-07-13 07:45 UTC, GyuminBae commented on src/main/java/gift/product/restapi/ProductController.java
> +            @RequestParam(required = false, defaultValue = "10") Integer size
반영했습니다!

2024-07-14 06:26 UTC, lsm7179 approved these changes
규민님 과제 잘 진행해주셨습니다.💯
수고하셨습니다~!

2024-07-14 06:26 UTC, lsm7179 commented on src/main/java/gift/product/restapi/ProductController.java
> +        return PagedProductResponse.from(pagedProducts);
👍

2024-07-14 06:26 UTC, merged