부산대 BE_박수빈 3주차 과제 (3단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #298
Opened 2024-07-12 05:27 UTC by kuma4188

과제요구사항에 정렬은 없어서 구현하지 않고 , 페이지만 구현했다가
제출할떄 확인해보니 정렬기능이 추가돼서 다시 구현했습니다.

그래서 커밋을 보시면 readme 작성이 2번 있습니다 ㅜㅜ

2024-07-12 15:28 UTC, yoo-jaein reviewed
step3 고생하셨어요!
리뷰 코멘트 확인 부탁드립니다~

2024-07-12 15:28 UTC, deactivated-user commented on src/main/java/gift/service/WishlistServiceImpl.java
> +        return wishlistEntities.map(this::convertToDTO);
map 👍

2024-07-12 15:28 UTC, deactivated-user commented on src/main/java/gift/controller/ProductWebController.java
> +        @RequestParam(defaultValue = "3") int size,
기본 페이지 크기가 3으로 되어있는데 일반적으로 10이나 20 정도를 사용합니다

2024-07-12 15:28 UTC, deactivated-user commented on src/main/java/gift/controller/ProductWebController.java
> +        @RequestParam(defaultValue = "0") int page,
required 라는 옵션도 고려해보세요.
required = false 로 지정한 경우 해당 파라미터가 요청에 없어도 됩니다.
만약 파라미터가 없으면 null이 할당되는데, defaultValue 값이 존재하는 경우 해당 값으로 할당됩니다.

2024-07-12 15:28 UTC, deactivated-user commented on src/main/java/gift/service/WishlistServiceImpl.java
> +    public Page<WishlistDTO> getWishlistByUser1(String username, Pageable pageable) {
1은 무슨 뜻인가요??

2024-07-12 15:28 UTC, deactivated-user commented on src/main/java/gift/repository/ProductRepository.java
> +    Page<Product> findAll(Pageable pageable);
JpaRepository 인터페이스는 기본적으로 제공하는 메서드들이 있습니다.
CRUD(Create, Read, Update, Delete) 작업을 위해 만들어 둔 것으로 아래 메서드들은 별도의 구현 없이 바로 사용할 수 있습니다!

### JpaRepository 가 기본적으로 제공하는 메서드들

### 조회
- `findById(ID id)`: 주어진 ID로 엔티티를 찾아 Optional<T>로 반환
- `findAll()`: 모든 엔티티를 List<T>로 반환
- `findAllById(Iterable<ID> ids)`: 주어진 ID 목록에 해당하는 모든 엔티티를 List<T>로 반환
- `getOne(ID id)`: 주어진 ID로 엔티티의 참조를 가져옴 (lazy loading)
- `findAll(Sort sort)`: 정렬된 모든 엔티티를 List<T>로 반환
- `findAll(Pageable pageable)`: 페이징 처리된 엔티티를 Page<T>로 반환

### 생성 & 수정
- `save(S entity)`: 새 엔티티를 저장하거나 기존 엔티티를 업데이트
- `saveAll(Iterable<S> entities)`: 주어진 엔티티들을 모두 저장하거나 업데이트

### 삭제
- `delete(T entity)`: 주어진 엔티티를 삭제
- `deleteById(ID id)`: 주어진 ID의 엔티티를 삭제
- `deleteAll()`: 모든 엔티티를 삭제
- `deleteAll(Iterable<? extends T> entities)`: 주어진 엔티티들을 모두 삭제
- `deleteAllById(Iterable<? extends ID> ids)`: 주어진 ID 목록에 해당하는 모든 엔티티를 삭제

### 존재 확인 
- `existsById(ID id)`: 주어진 ID의 엔티티가 존재하는지 확인

### 개수 
- `count()`: 저장된 엔티티의 총 개수를 반환

이 외에도 여러 메서드들이 있습니다.

2024-07-12 15:32 UTC, yoo-jaein requested changes
step3 고생하셨어요!
리뷰 코멘트 확인 부탁드립니다~

2024-07-13 07:19 UTC, kuma4188 commented
1. 기본 페이지 크기를 10으로 설정했는데 , 제가 집어넣은 데이터가 6개라 페이지 넘어가는걸 직접 눈으로 보고싶어서 3으로 줄였습니다.
2. GetwishlistByUser 이라는 메서드가 List 자료형으로 먼저 선언되었길래 물론 Page자료형으로 다르긴 하지만 혹시나 혼동이 있을까봐 메서드명에 1이라는 숫자를 추가했습니다.

혹시 코드를 수정해야할 부분이 있을까요?
☆이번에도 코드 리뷰 감사합니닷☆

2024-07-14 02:09 UTC, yoo-jaein approved these changes
아하 그렇군요!
다만 단순히 숫자 1을 쓰는 것 보단
메서드 오버로딩을 쓰거나
메서드 이름에 반환 타입을 적어주는 것이 더 명확할 것 같습니다 :) 

3주차 고생 많으셨습니다!
머지하겠습니다.

2024-07-14 02:09 UTC, merged