충남대 BE_이은경 3주차 과제(3단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #301
Opened 2024-07-12 05:46 UTC by pkyung

## 과제 진행 사항
### 페이지네이션
- [x] 로그인 / 회원가입 페이지 생성 및 js
- [x] 위시 리스트 페이지 생성 및 js
- [x] spring data jpa를 이용해서 페이지네이션 추가 
- [x] 상품과 위시리스트에 페이지네이션 적용

2024-07-12 07:00 UTC, ksy90101 requested changes
3단계도 고생 많으셨습니다~
간단한 피드백을 남겼으니 확인해주세요!
언제든 질문이 있다면 DM주세요!

2024-07-12 07:00 UTC, ksy90101 commented on src/main/java/gift/controller/WishController.java
> +    public ResponseEntity<Page<Product>> getAllWishProductsByMember(@LoginMember Member member, Pageable pageable) {
pageable의 default값은 없을까요?

2024-07-12 07:00 UTC, ksy90101 commented on src/main/java/gift/repository/WishRepository.java
> +    Page<Product> findAllByMemberId(@Param("memberId") Long memberId, Pageable pageable);
페이지네이션 방식에서 오프셋방식 vs 커서 방식
두가지가 있습니다.

이경우에는 어떤 방식일까요?

아울러 어떤 방식을 쓰는게 효과적일까요. 현재 상태에서요~

2024-07-12 07:00 UTC, ksy90101 commented on src/main/resources/static/js/wish.js
> +function getAuthToken() {
set도 따로 만들어두면 어떨까 생각이 드네요.
아울러 해당 메서드는 공통으로 쓰일테니 따로 공용 메서드 같은 느낌으로 관리해볼수 있지 않을까요?

2024-07-13 12:06 UTC, pkyung commented on src/main/java/gift/controller/WishController.java
> +    public ResponseEntity<Page<Product>> getAllWishProductsByMember(@LoginMember Member member, Pageable pageable) {
추가해주도로 하겠습니다.

2024-07-13 12:10 UTC, pkyung commented on src/main/resources/static/js/wish.js
> +function getAuthToken() {
set을 따로 만들어두었습니다. 하지만 get을 하는 곳은 wish.js파일이고 set을 하는 곳은 auth.js 파일인데 공용 메서드로 관리할 수 있나요?

2024-07-13 12:15 UTC, pkyung commented on src/main/java/gift/repository/WishRepository.java
> +    Page<Product> findAllByMemberId(@Param("memberId") Long memberId, Pageable pageable);
지금 사용하고 있는 방식은 오프셋 방식입니다. 

현재 상태에서는 오프셋 방식을 사용하는 것이 효과적일 것 같습니다. 오프셋 방식은 커서 방식에 비해서 구현이 쉽고 직관적입니다. 그리고 데이터가 많은 성능이 중요한 프로그램이 아니기 때문입니다. 

데이터의 양이 많아진다면 커서 방식의 구현이 필요할 것 같습니다.

2024-07-14 00:11 UTC, ksy90101 commented on src/main/java/gift/repository/WishRepository.java
> +    Page<Product> findAllByMemberId(@Param("memberId") Long memberId, Pageable pageable);
👍

2024-07-14 00:12 UTC, ksy90101 commented on src/main/resources/static/js/wish.js
> +function getAuthToken() {
Import하면 되죠~

2024-07-14 00:14 UTC, ksy90101 approved these changes
고생하셨습니다~
간단한 피드백을 남기긴했지만 4주차에 진행해주시면 될거 같아요~
3주차도 고생많으셧어요~
궁금하신거나 같이 이야기 해보고 싶은 주제가 있다면 언제든 DM주세요!
홧팅입니다!

2024-07-14 00:14 UTC, ksy90101 commented on src/main/resources/static/js/auth.js
> +function login() {
한번 로그아웃도 만들어 보시면 어때요?

2024-07-14 00:14 UTC, merged

2024-07-16 13:35 UTC, pkyung commented on src/main/resources/static/js/wish.js
> +function getAuthToken() {
4주차에 import 해서 구현완료했습니다!