충남대 BE_박상우 3주차 과제 (3단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #302
Opened 2024-07-12 05:50 UTC by pswaao88

미리 생성했습니다

2024-07-14 12:46 UTC, Hyeon9mak requested changes
안녕하세요 상우님! 우선 2단계 PR 에 맞춰서 아주 간단한 코멘트만 남겼습니다.
궁금하신 점 편하게 질문주세요!

2024-07-14 12:46 UTC, Hyeon9mak commented on src/main/java/gift/Service/ProductService.java
> +        return productRepository.findAll(pageable);
Page 와 Slice 의 차이는 무엇일까요!?

2024-07-14 12:46 UTC, Hyeon9mak commented on src/main/java/gift/Controller/WishListController.java
> +        //model.addAttribute("wishlists", wishlistService.getAllWishlist("1234@google.com", pageable));
불필요해진 주석은 꼭 제거를! 😢

2024-07-14 12:46 UTC, Hyeon9mak commented on src/main/java/gift/Controller/WishListController.java
>      }
출력도 테스트를 위해서 사용해주신 걸까요?
사용자의 개인 정보를 서버에서 계속 출력하면 보안상 큰 위험이 발생할거 같아요.

2024-07-14 13:11 UTC, pswaao88 commented on src/main/java/gift/Controller/WishListController.java
> +        //model.addAttribute("wishlists", wishlistService.getAllWishlist("1234@google.com", pageable));
미처 확인을 못했습니다 지우겠습니다!

2024-07-14 13:12 UTC, pswaao88 commented on src/main/java/gift/Controller/WishListController.java
>      }
기존에 제출하기전에 지운 것을 확인을 했는데 파일이 날아갈까봐 여러군데에 백업을 하여 진행하던중에 파일을 잘못 찾아서 남은것 같습니다 지우겠습니다

2024-07-14 13:25 UTC, pswaao88 commented on src/main/java/gift/Service/ProductService.java
> +        return productRepository.findAll(pageable);
page에 집중을 해서 slice를 알게 되었습니다. 
더 공부를 할테지만 간단하게 정리를 하자면 
page는 조회쿼리 이후에 전체 데이터 갯수를 한번 더 조회하는 쿼리가 실행가 실행됩니다. 
slice같은 경우에는  다음 slice가 존재하는지 여부만 확인을 합니다.
따라서 page는 게시판과 같이 총 데이터 갯수가 필요한 환경에서,
slice는 무한스크롤이 필요한  총 데이터 갯수가 필요없는 환경에서 쓰는게 좋다고 생각합니다!

2024-07-15 13:43 UTC, Hyeon9mak approved these changes
안녕하세요 상우님~ 3단계 피드백 잘 반영해주셨어요!

> 테스트 코드의 경우 WishlistRepository를 기준으로 코드를 짰는데 짠 코드를 보니 Service에 있는 코드를 그대로 쓴거 같습니다. 이경우에는 Service를 가져와 테스트를 하는게 더 좋은지 WishlistRepository에서 쿼리문을 짰으므로 WishlistRepository기준으로 테스트 코드를 짜는 것이 좋은지 궁금합니다.

테스트 코드를 작성하는 이유는 무엇일까요?
결국 상우님이 불안해하시는 포인트에 대해서
꼭 프로그램을 손으로 동작시켜보지 않더라도 자동으로 검증되길 기대하기 때문일거에요.

현재 테스트하고 싶은 내용은 무엇이었나요?
아마도 service 로직의 동작보다는, 쿼리가 잘 동작하는지 확인하고 싶으셨던 것 같아요.
그렇다면 굳이 service 를 테스트하는 것보다 repository 를 테스트하는 것이
테스트 코드를 작성하기도 훨씬 쉽고, 다른 동료가 테스트 코드를 읽을 때
"쿼리를 테스트 하고 싶었나보구나?" 의도를 이해하기 쉽겠죠? 😉 

그 외에도 학습해보실만한 키워드에 대해 코멘트 남겼으니 확인해주세요!
3주차 고생 많으셨어요!

2024-07-15 13:43 UTC, Hyeon9mak commented on src/main/java/gift/Service/ProductService.java
> +        return productRepository.findAll(pageable);
💯 💯 굿굿~!

2024-07-15 13:43 UTC, Hyeon9mak commented on src/main/java/gift/Repository/WishlistRepository.java
> +    Page<Product> getAllWishlist(@Param("email") String email, Pageable pageable);
> 아직 이해도가 부족해서 @transactional를 작성해야 작동을 하는 것 같아서 모든 쿼리에 Transactional 를 명시를 하게 되었습니다. 부족한 공부를 진행해야할것 같습니다.

`@Transactional` 어노테이션이 없어도 실제로는 쿼리가 잘 동작합니다.
특히 조회 쿼리의 경우 `@Transactional` 어노테이션이 꼭 필요하지 않고,
만약 사용하더라도 `@Transactional(readOnly = true)` 옵션을 명세해서 사용할 수 있습니다.

어노테이션을 왜 명세해야하는지는 어렵지 않게 공부해볼 수 있으니 꼭 학습해보시면 좋겠네요!
(힌트: spring aop, transaction roll back)

> wishlist에 product를 저장하는 것으로 바꾸면서 여러가지 테스트를 진행을 할 때 wishlist에서 product를 가져오는 것 같지가 않아서 쿼리문을 직접 작성을 해서 사용했습니다.

`WishList` 에서 즉각적으로 `Product` 를 가져오지 않는 이유는 무엇일까요?
(힌트: `@ManyToOne(fetch = FetchType.LAZY`)

2가지 질문 드린 내용에 대해 4주차 리뷰요청 PR 에 작성해주시면 좋겠어요 😄 👍

2024-07-15 13:43 UTC, merged