강원대 BE_오승환 3주차 과제 (3단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #304
Opened 2024-07-12 05:56 UTC by humpose

주신 리뷰 반영해서 DTO클래스에 validation annotation을 할당했습니다.
그런데 이렇게 하면 entity에서 검사한 것과 중복이 되어 불필요한 부분인지, 아니면 코드 검사를 확실하게 하기 위한 괜찮은 방법인지가 궁금합니다.
그리고 엔티티 클래스 중 하나인 product의 VO인 name도 엔티티 클래스의 일부라고 보고 validation annotation 사용하지 않아야 하는 걸까요? 일단 name에서도 제거하긴 했습니다.

2024-07-12 16:27 UTC, pci2676 commented
> 주신 리뷰 반영해서 DTO클래스에 validation annotation을 할당했습니다.
> 그런데 이렇게 하면 entity에서 검사한 것과 중복이 되어 불필요한 부분인지, 아니면 코드 검사를 확실하게 하기 위한 괜찮은 방법인지가 궁금합니다.

아주 좋은 질문이네요!

말씀해주신 것 처럼 중복되는 검사가 발생할 수 있습니다.

그래서 가장 코어한 곳에 위치한 부분에 검증 로직을 위치시키는것이 좋습니다.

DTO는 여러개가 될 수 있기 때문입니다. 가령 productName 필드를 가진 DTO가 N개 생겨난다면 N개의 동일한 밸리데이션 수행해야할 수 있게 될 수 있습니다.

따라서 DTO에서는 가장 최소한의 검증(null check, blank check 등)을 수행해주는것이 좋고

값객체 혹은 도메인 객체에서 비즈니스적으로 중요한 부분에 대해 검증해주시는 것이 좋습니다. :)

2024-07-12 16:27 UTC, pci2676 commented
> 그리고 엔티티 클래스 중 하나인 product의 VO인 name도 엔티티 클래스의 일부라고 보고 validation annotation 사용하지 않아야 하는 걸까요? 일단 name에서도 제거하긴 했습니다.

말씀하신 이유로 가능하면 저는 사용하지 않는게 좋다고 봅니다.

2024-07-12 16:35 UTC, pci2676 requested changes
아주 조금만 개선해주시면 merge해도 좋을것 같습니다.

리뷰를 확인해주세요

2024-07-12 16:35 UTC, pci2676 commented on src/main/java/gift/controller/ProductController.java
> +        }
controller에서는 가능한 로직이 존재하지 않는것이 좋습니다~!

2024-07-12 16:35 UTC, pci2676 commented on src/main/java/gift/controller/ProductController.java
> +        model.addAttribute("totalPages", productPage.getTotalPages());
👍

2024-07-12 16:35 UTC, pci2676 commented on src/main/java/gift/model/Product.java
> +    @Column(name = "image_url", nullable = false, columnDefinition = "VARCHAR(255)")
👍

2024-07-12 16:35 UTC, pci2676 commented on src/test/java/gift/WishListRepositoryTest.java
> +        }
테스트에서는 반복문이 존재하지 않는것이 좋습니다. 테스트는 한번에 쭉 읽고 파악해야하는데 반복문이 있으면 반복문이 어떠한 행위를 하는지 파악해야하기 때문입니다.

필요한 데이터만 나열해서 생성해주시는 것이 더 좋을것 같습니다.

2024-07-12 16:35 UTC, pci2676 commented on src/test/java/gift/WishListRepositoryTest.java
> +    void findByUserWithPagination() {
테스트는 그 이름 혹은 설명으로 테스트의 목적에 대해 드러낼 수 있는데요.

지금 이름만으로는 그저 페이지네이션을 수행한다는 정보만 노출되는것 같습니다.

페이지네이션으로 어떠한 입력에 어떠한 응답을 줄 수 있는지 조금 더 명확하게 정보를 전달해주신다면 좋을것 같습니다.

2024-07-12 16:35 UTC, pci2676 commented on src/main/java/gift/controller/WishListController.java
> +        @RequestParam(defaultValue = "asc") String direction,
페이징 요청을 할때 최대값에 대한 제한이 없는것 같습니다.

이러한 제한이 없을때 잘못된 요청으로 인해 큰 문제가 발생할 수 있을것 같네요 🤔

2024-07-13 01:53 UTC, humpose commented on src/main/java/gift/controller/WishListController.java
> +        @RequestParam(defaultValue = "asc") String direction,
네. 제한 조건을 거는 대신 controller에 가능한 로직이 존재하지 않는 게 좋다고 조언해주셨으므로 위의 sort부분과 함께 service에서 메서드로 작동하도록 수정하겠습니다.

2024-07-13 01:54 UTC, humpose commented on src/main/java/gift/controller/ProductController.java
> +        }
네 숙지해두겠습니다!

2024-07-13 02:30 UTC, humpose commented on src/test/java/gift/WishListRepositoryTest.java
> +    void findByUserWithPagination() {
given_when_then 방식으로 주석을 추가하고 테스트 메서드 이름도 더 세부적으로 수정하겠습니다!

2024-07-13 02:31 UTC, humpose commented on src/test/java/gift/WishListRepositoryTest.java
> +        }
테스트의 순기능을 잊고 있었군요.. 바로 반영하겠습니다!

2024-07-13 15:15 UTC, pci2676 approved these changes
수고하셨습니다.

2024-07-13 15:15 UTC, pci2676 commented on src/main/java/gift/service/ProductService.java
> +    }
Service가 가지고 있는 repository를 사용하지 않는 별도의 기능으로 보이네요!

지금 이 기능은 PageRequest를 만들기 위한 전처리 단계로 볼 수 있을것 같은데요.

이러한 기능을 위해 dto를 별도로 만들어 사용하는게 더 좋을것 같습니다~

controller -> dto -> service 순으로 데이터를 정제하여 넘기면 좋을것 같네요

2024-07-13 15:15 UTC, pci2676 commented on src/main/java/gift/controller/WishListController.java
> +        @RequestParam(defaultValue = "asc") String direction,
controller에서는 최소한의 검증 자체는 있는것이 괜찮아서

size등의 검증은 여기서 해주어도 됩니다. controller에서는 validate할 수 있는 애터네이션을 사용하면 좋고

service로 값을 넘길때는 별도의 dto를 사용하면 좋습니다!

2024-07-13 15:15 UTC, pci2676 commented on src/main/java/gift/service/ProductService.java
> +    }
추가로 product를 update하는 service 로직에 문제가 있는것 같네요.

전달받은 dto에 있는 id에 해당하는 product가 없는 경우 그냥 새로운 product를 생성하는것 같은데 이게 update가 맞을까요?

2024-07-13 15:15 UTC, merged