경북대 BE_박준석_3주차 과제 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #306
Opened 2024-07-12 06:07 UTC by Lucerna00

2단계 요구 사항을 우선 구현해 보았습니다.
member - wishedProduct는 양방향으로, wishedProduct - product는 단방향으로 매핑하였습니다.

2024-07-12 12:52 UTC, gongdongho12 requested changes
대부분 완벽하게 작업해주셨네요 💯 

요구사항이나 개선포인트 위주로 리뷰드렸습니다
2단계 고생많으셨어요!

2024-07-12 12:52 UTC, gongdongho12 commented on src/main/java/gift/domain/Member.java
> +    private List<WishedProduct> wishList = new ArrayList<>();
벌써부터 사용해주시는군요!

2024-07-12 12:52 UTC, gongdongho12 commented on src/main/java/gift/domain/WishedProduct.java
> +    @JoinColumn(name = "product_id", nullable = false)
나중에 DAO를 출력한다던가, 실수로 접근하게 되면, 값이 불러와지는데요
FetchType을 LAZY로 지정해보는건 어떨까요?

2024-07-12 12:52 UTC, gongdongho12 commented on src/main/java/gift/service/ProductService.java
>      }
예외처리 깔끔 👍🏼

2024-07-12 12:52 UTC, gongdongho12 commented on src/main/java/gift/service/ProductService.java
> +        getProduct(id);
update를 위한 조회용도로 같은 메서드로 사용한 아이디어 좋습니다!

2024-07-12 12:52 UTC, gongdongho12 commented on src/main/java/gift/service/ProductService.java
> +        ProductDTO deletedProductDTO = getProduct(id);
이부분은 위에랑 다르게 삭제를 할때 없으면 예외가 발생하지 않을까요?

2024-07-12 12:52 UTC, gongdongho12 commented on src/test/java/gift/repository/WishedProductRepositoryTest.java
> +    }
Init 좋습니다
그런데 한번 해두면 다른 테스트도 같은 값을 쓸 수 있자나요
BeforeEach 보다는 BeforeAll은 어떠실까요?

2024-07-12 12:52 UTC, gongdongho12 commented on README.md
> +객체에서는 참조를 사용하고 테이블에서는 외래 키를 사용할 수 있도록 수정
join은 걸려있는데 왜래키 설정은 어디에 있을까요?

2024-07-12 13:33 UTC, Lucerna00 commented on src/main/java/gift/domain/WishedProduct.java
> +    @JoinColumn(name = "product_id", nullable = false)
안 그래도 지연 로딩, N+1 문제에 대해 알아보고 있었는데, 말씀해 주셔서 바로 LAZY 적용했습니다!

2024-07-12 13:42 UTC, Lucerna00 commented on src/main/java/gift/service/ProductService.java
> +        ProductDTO deletedProductDTO = getProduct(id);
잘못된 id로 delete 요청할 시 404 Not Found가 반환되도록 하였습니다..!

2024-07-12 13:47 UTC, Lucerna00 commented on src/test/java/gift/repository/WishedProductRepositoryTest.java
> +    }
BeforeAll을 쓰면 제가 작성한 필드와 주입하는 repository를 다 static으로 바꿔야 되던데
어떤 식으로 진행하면 좋을까요?

2024-07-12 13:49 UTC, gongdongho12 commented on src/main/java/gift/service/ProductService.java
> +        ProductDTO deletedProductDTO = getProduct(id);
@Lucerna00 https://hwanchang.tistory.com/7 에 보시면 이미 find하고 예외를 주고 있어서요

2024-07-12 13:51 UTC, Lucerna00 commented on README.md
> +객체에서는 참조를 사용하고 테이블에서는 외래 키를 사용할 수 있도록 수정
연관 관계 매핑에 의해 테이블 생성 시
```
Hibernate: 
    alter table if exists wished_product 
       add constraint FKik0ohdcn00hshodfx8jxh6vmd 
       foreign key (member_email) 
       references member
Hibernate: 
    alter table if exists wished_product 
       add constraint FKjjpa9e15nvcw6687gx8hygqn8 
       foreign key (product_id) 
       references product
```
외래 키가 설정되던데 또 다른 명시적인 방법이 있을까요?

2024-07-12 13:57 UTC, gongdongho12 commented on src/test/java/gift/repository/WishedProductRepositoryTest.java
> +    }
저장만 해두고 비교는 별도로 관리하면 어떨까요?

2024-07-12 13:59 UTC, gongdongho12 commented on README.md
> +객체에서는 참조를 사용하고 테이블에서는 외래 키를 사용할 수 있도록 수정
직접 확인하신 부분 👍🏼
저는 referencedColumnName 지정을 생각했는데 이미 저렇게 처리되겠군요

2024-07-12 14:04 UTC, Lucerna00 commented on src/main/java/gift/service/ProductService.java
> +        ProductDTO deletedProductDTO = getProduct(id);
deleteById에는 어차피 findById가 있으니 id 검사를 두 번 하게 되네요..!

2024-07-12 14:16 UTC, Lucerna00 commented on README.md
> +객체에서는 참조를 사용하고 테이블에서는 외래 키를 사용할 수 있도록 수정
referencedColumnName 속성도 있었네요.. 숙지하겠습니다

2024-07-12 14:51 UTC, Lucerna00 commented on src/test/java/gift/repository/WishedProductRepositoryTest.java
> +    }
BeforeAll에서 필드 값 지정과 함께 repository.save를 해라는 말씀이신가요..!

2024-07-12 15:19 UTC, gongdongho12 commented on src/test/java/gift/repository/WishedProductRepositoryTest.java
> +    }
아 그렇네요!! 저도 생각못했던 부분이 있었군요 ㅎㅎ

2024-07-12 16:11 UTC, Lucerna00 commented on src/test/java/gift/repository/WishedProductRepositoryTest.java
> +    }
그럼 일단 BeforeEach로 두겠습니다!

2024-07-13 08:39 UTC, gongdongho12 approved these changes
3단계 🏃🏼

2024-07-13 08:39 UTC, merged