전남대 BE_나제법_3주차 과제(2단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #310
Opened 2024-07-12 06:30 UTC by nove1080

## 코드 작성하면서 어려웠던 점
본의 아니게 1단계 과제를 건너뛰게 되버렸는데 다음부터는 꼭 단계별 요구사항을 잘 읽고 미션을 진행하도록 하겠습니다. 죄송합니다 ㅜㅜ
## 코드 리뷰 시, 멘토님이 중점적으로 리뷰해주셨으면 하는 부분
### 1. 아래 코드를 개선할 수 있을까요?
```java
@Service
@Transactional(readOnly = true)
public class WishProductService {
    @Transactional
    public CreateWishProductResponse createWishProduct(Long memberId, CreateWishProductRequest request) {

        // 이미 존재하는 WishProduct인 경우 수량만 추가
        Optional<WishProduct> existingWishProduct = wishProductRepository.findByMemberIdAndProductId(
            memberId, request.getProductId());
        if (existingWishProduct.isPresent()) {
            WishProduct wishProduct = existingWishProduct.get();
            wishProduct.addQuantity(request.getQuantity());

            return CreateWishProductResponse.fromEntity(wishProduct);
        }

        WishProduct wishProduct = new Builder()
            .member(memberRepository.findById(memberId)
                .orElseThrow(() -> new NoSuchElementException("Member not found")))
            .product(productRepository.findById(request.getProductId())
                .orElseThrow(() -> new NoSuchElementException("Product not found")))
            .quantity(request.getQuantity()).build();

        return CreateWishProductResponse.fromEntity(wishProductRepository.save(wishProduct));
    }
}
```
위시 상품 등록 시, 

1. 기존에 존재하는 위시 상품인 경우 수량만 추가하도록 하고 
2. 존재하지 않는 상품인 경우에만 새롭게 등록하도록  

코드를 구성하였습니다. 코드를 개선할 수 있을까요?
### 2. DB에 존재하지 않는 상품 삭제 시, 예외를 발생시키는 방법
```java
@Service
@Transactional(readOnly = true)
public class ProductService {
    @Transactional
    public void deleteProduct(Long id) {
        productRepository.deleteById(id);
    }
}
```
기존에는 위와 같은 방식으로 상품 삭제 로직을 만들었습니다. deleteById 시, DB에 존재하지 않는 데이터에 대한 삭제 요청 시 예외가 발생하지 않아서 아래와 같이 코드를 바꾸어서 처리하였는데 적절한 판단이었나요? 어떻게 처리하는 것이 좋은 방법일까요?
(없는 상품에 대한 예외를 발생시키고자 하는 이유는 없는 상품 삭제 시 클라이언트 오류 응답코드를 보내기 위함 이었습니다.)
```java
@Service
@Transactional(readOnly = true)
public class ProductService {
    @Transactional
    public void deleteProduct(Long id) {
        Product product = productRepository.findById(id)
            .orElseThrow(NoSuchElementException::new);
        productRepository.delete(product);
    }
}
```

2024-07-13 08:58 UTC, Hongdonggeon requested changes
안녕하세요 제법님
미션 구현하시느라 수고 많으셨습니다!
jpa 처음 써본다고 들었던 것 같은데 많이 시도해보시고 학습한게 느껴집니다!
제범님이 고민하면 좋을 코멘트들 남겨놓았으니 한번 고민해보면 좋을 것 같아요
수고하셨습니다!

2024-07-13 08:58 UTC, Hongdonggeon commented on src/main/java/gift/authentication/filter/AuthenticationFilter.java
> +        if (ignorePaths.contains(request.getRequestURI())) {
경로를 이렇게 제외시키는것보다 FilterRegistrationBean 을 이용해서 경로들을 제외시키는건 어떨가요?

2024-07-13 08:58 UTC, Hongdonggeon commented on src/main/java/gift/domain/BaseEntity.java
> +        protected abstract T self();
이 메서드는 어떤 용도인가요?

2024-07-13 08:58 UTC, Hongdonggeon commented on src/main/java/gift/domain/Product.java
> +    private URL imageUrl;
이 필드는 디비에 저장하지 않네요 이유가 궁금합니다!

2024-07-13 08:58 UTC, Hongdonggeon commented on src/main/java/gift/domain/Product.java
> +    }
접근지정자를 private 으로 변경해도 되지 않을까요?

2024-07-13 08:58 UTC, Hongdonggeon commented on src/main/java/gift/domain/Product.java
> +    public static class Builder extends BaseEntity.Builder<Builder> {
이 패턴을 사용한 이유가 궁금합니다

2024-07-13 08:58 UTC, Hongdonggeon commented on src/main/java/gift/domain/Product.java
> +        return this;
엔티티에서 dto를 참조하고 있을 때 어떤 영향을 미칠 수 있을까요?

2024-07-13 08:58 UTC, Hongdonggeon commented on src/main/java/gift/web/validation/handler/ApiExceptionHandler.java
> +//        ErrorResponse errorResponse = ErrorResponse.from(bindingResult);
구현 추가하실걸 남겨둔거죠?

2024-07-13 08:58 UTC, Hongdonggeon commented on src/main/java/gift/web/validation/handler/ApiExceptionHandler.java
> +
지금과 같은 구조라면 커스텀 에외 클래스가 생길때마다 이곳에 메서드가 늘어날 것 같은데요
예외 클래스들이 더 좋은 상속구조를 가진다면 더 단순해질 수 있을것 같아요 

예를 들면 
runTimeException 하위에 httpStatusCode 별로 커스텀 익셉션 만들고 
httpStatusCode별 익셉션 아래에 저런 비즈니스 용어가 포함된 커스텀 익셉션을 만드는 방법도 있을 것 같고요
한번 고민해보세요!

2024-07-13 08:58 UTC, Hongdonggeon commented on src/main/java/gift/web/validation/exception/code/ErrorCode.java
> +    INTERNAL_SERVER_ERROR(-50000, Category.COMMON, "서버 내부 오류입니다."),
에러 코드를 카테고리화 하셨네요 카테고리화한 이유가 뭘까요? 
현재 이런 에러코드를 가지게 되면서 어떤 장점이 생긴 것 같아요?

2024-07-13 08:58 UTC, Hongdonggeon commented on src/main/java/gift/web/controller/view/ProductViewController.java
> +    @GetMapping()
소괄호 없애도 될 것 같아요

2024-07-13 08:58 UTC, Hongdonggeon commented on src/main/java/gift/web/controller/api/ProductApiController.java
> +        URI location = new URI("http://localhost:8080/api/products/" + response.getId());
앞에 "http://localhost:8080/api/products/ 붙여줘야 하나요? 안붙여도 브라우저에서 알아서 해줬던 것 같은데.. 아닐수도 잇어요!

2024-07-13 08:58 UTC, Hongdonggeon commented on src/main/java/gift/service/WishProductService.java
> +            .quantity(request.getQuantity()).build();
wishProductRepository 에서 조회해오면 되지 않나요? 새로 객체를 만드는 이유가 뭘까요?

2024-07-13 08:58 UTC, Hongdonggeon commented on src/main/java/gift/service/WishProductService.java
> +        wishProductRepository.delete(wishProduct);
조회 쿼리가 2번 일어나도 1차캐시에서 가져오는거기 때문에 쿼리는 한번 날라갈거예요 
조회하지 않을 때 에러 발생하게 하고 싶으면 지금과 같은 로직 괜찮은 것 같아요

2024-07-13 08:58 UTC, Hongdonggeon commented on src/main/java/gift/domain/Product.java
> +    private List<WishProduct> wishProducts = new ArrayList<>();
product 에서 wishProduct 리스트를 가지고 있게 한 이유가 뭘까요? 
이 리스트를 가지게 되면서 비즈니스 로직이 엔티티에서 많이 생기는 것도 아닌 것 같고요!
양방향 연관관계의 특징, 장단점에 대해 공부해보면 좋을 것 같아요

2024-07-13 08:58 UTC, Hongdonggeon commented on src/main/java/gift/domain/Member.java
> +    private List<WishProduct> wishProducts;
멤버가 장바구니 상품 리스트를 가지고 있는 것은 비즈니스상 어색하진 않아 보이긴하는데요
한편으로는 이렇게 생각할 수 있을 것 같아요. 멤버 객체가 생겨야될때 장바구니 상품 리스트가 필수조건인가? 이렇게 생각하면 조금 어색하다고 생각할 수 있을 것 같아요

이제 코드적으로 생각해봤을 때, 양방향 연관관계를 가지게 하면서 까지, 이 리스트로 엔티티에서 장바구니에 상품을 추가하거나 제거하거나 이런 비즈니스 로직들이 엔티티에 존재하는건 아닌 것 같은데 이렇게 설계하신 이유가 궁금해요

그리고 연관관계는 정말 잘 고려해서 결정해야해요. 
각 연관관계의 장단점에 대해 학습해보시면 좋을 것 같아요

2024-07-13 08:58 UTC, Hongdonggeon commented on src/main/java/gift/repository/mapper/MemberRowMapper.java
> +public class MemberRowMapper implements RowMapper<Member> {
이제 사용하지 않는 클래스죠?

2024-07-13 08:58 UTC, Hongdonggeon commented on src/main/java/gift/domain/WishProduct.java
> +    @ManyToOne(fetch = FetchType.LAZY)
fetch type lazy와 eager의 차이를 알고 계실까요?

2024-07-13 08:58 UTC, Hongdonggeon commented on src/main/java/gift/domain/BaseEntity.java
> +    private Long id;
생성일자, 수정일자, 생성자 수정자 필드를 추가하면 좋을 것 같아요

2024-07-14 12:35 UTC, nove1080 commented on src/main/java/gift/authentication/filter/AuthenticationFilter.java
> +        if (ignorePaths.contains(request.getRequestURI())) {
```java
@Bean
public FilterRegistrationBean authenticationFilter() {
    FilterRegistrationBean filterRegistrationBean = new FilterRegistrationBean();
    filterRegistrationBean.setFilter(new AuthenticationFilter(jwtResolver));
    filterRegistrationBean.addUrlPatterns("/api/*");
    filterRegistrationBean.setOrder(2);
    return filterRegistrationBean;
}
```

위와 같이 설정하고


```java
@Override
protected boolean shouldNotFilter(HttpServletRequest request) throws ServletException {
    return ignorePaths.contains(request.getRequestURI());
}
```
를 오버라이딩하여 경로를 제외하였습니다.

`FilterRegistrationBean` 은 

1. 특정 URL의 요청을 제외시키기 보다는 
2. **어떤 URL에 필터를 적용시킬지에 대해** 보다 적합한 메서드를 제공하는 것 같았습니다.

따라서 특정 URL에 대해 `Filter` 를 적용하지 않는 기능은 제공하지 않는 것 같아서 추가로 조사해보니 `OncePerRequestFilter` 를 확장한 경우 `shouldNotFilter`를 오버라이딩하여 `Filter`를 실행시키지 않을 조건을 만들어 줄 수 있더라구요

`FilterRegistrationBean`으로 "무슨무슨 URL을 제외하고 모두 적용시켜줘" 를 구현하기에는 까다로운 것 같아서 `OncePerRequestFliter.shouldNotFilter()`를 오버라이딩 하도록 리팩토링 하였습니다.

혹시 어떤 방법으로 구현하는 것을 의도 하셨는지 궁금합니다!

2024-07-14 12:58 UTC, nove1080 commented on src/main/java/gift/domain/Product.java
> +    public static class Builder extends BaseEntity.Builder<Builder> {
저는 거의 대부분의 경우에서 Builder 패턴을 사용하고 있습니다.

개인적인 기준으로는 초기화 할 필드가 넷 이상 존재하는 경우, 생성자를 통해 인스턴스화하는 것이 번거롭다고 느꼈고, 꼭 초기화 할 필드가 넷 이상이 아니더라도 추후에 확장을 생각한다면 필드의 개수가 늘어나는 상황이 보편적일 거라 생각하여 항상 적용하고 있습니다.

제가 생각했을 때의 Builder 패턴의 장점은
1. 생성자를 통한 객체 생성 시, 파라미터의 순서를 정확히 맞춰줘야 하는 부분을 해소해줄 수 있습니다.
2. 초기화 할 필드 별로 메서드를 제공할 수 있므로 검증 로직을 분할 해둘 수 있습니다.
```java
Product product = Product.builder()
    .id(1L)             //id 필드에 해당하는 검증 로직 적용
    .name("상품01")      //name 필드에 해당하는 검증 로직 적용
    .price("10000")     //price 필드에 해당하는 검증 로직 적용
    .build();           //복합 검증 로직 적용
```
3. 필수로 초기화 되어야하는 필드와 선택적인 필드에 대해 초기화하는 방법을 제공하는 것이 수월합니다.

단점은 아직 잘 느껴보지 못해서 대부분의 경우 사용 중입니다! 동건님은 어떻게 생각하시나요?

2024-07-14 13:11 UTC, nove1080 commented on src/main/java/gift/domain/Product.java
> +    }
@Entity를 적용하게 되면 기본 생성자의 접근지정을 `protected` 혹은 `public` 으로 선언할 것을 강요하여 그래도 `public` 보다는 `protected` 로 선언하도록 하였습니다.

그래서 궁금한 점이 있는데 스프링이 기본 생성자를 호출하려고 `private`로 접근 제어를 선언하는 것을 막는 것 같았습니다. 그렇다면 `protected`로 접근 제어가 되어있으면 어떻게 스프링이 호출하나요? `public` 으로 선언한다면 외부에서 호출이 가능한데 `protected`의 경우 어떤 방법을 사용하여 호출할 수 있는지 잘 모르겠습니다.

2024-07-14 16:19 UTC, nove1080 commented on src/main/java/gift/domain/WishProduct.java
> +    @ManyToOne(fetch = FetchType.LAZY)
### 지연 로딩(FetchType.LAZY)
* 실제 데이터가 필요한 시점에 조회 쿼리를 전송하여 조회하는 시점을 지연시킵니다
### 즉시 로딩(FetchType.EAGER)
* 엔티티 조회 시 관련된 엔티티를 모두 한 번에 조회합니다.

즉시 로딩의 경우 N + 1 문제를 발생시킬 수 있으며 가급적 지연 로딩을 사용하며 "즉시 로딩과 같이 데이터를 한 번에 가져올 일이 있다면 fetch join을 사용하는 방법을 권장한다" 라고 알고 있습니다 

좀 더 중요한 부분이 있나요? 자세한 부분은 학습이 부족하여 좀 더 알아보겠습니다!

2024-07-14 16:20 UTC, nove1080 commented on src/main/java/gift/domain/Product.java
> +    private URL imageUrl;
이미지 링크 같은 경우에는 필수적이지 않은 옵션으로 생각하고 구현하였습니다. 하지만 이렇게 되면 
DB에 null 값이 존재할 수 있어 문제가 될 수 있을 것 같습니다 수정하도록 하겠습니다

2024-07-14 16:36 UTC, nove1080 commented on src/main/java/gift/domain/BaseEntity.java
> +        protected abstract T self();
아래와 같은 상황이 발생하여 self 라는 메서드를 두는 것 같습니다

```java
//self를 오버라이딩한 경우
new Member.Builder()
    .id(1L) //하위 클래스(Member)의 Builder가 반환되어 계속해서 메서드 체이닝이 가능
    .name("name")
    .build();
```

```java
//self를 정의하지 않은 경우
new Member.Builder()
    .id(1L) //상위 클래스의 빌더가 반환되어 하위 클래스의 필드를 초기화 할 수 없다.
    .build();
```

"하위 클래스의 빌더를 반환하도록 하여 하위클래스의 메소드 체이닝을 지원하기 위함이다" 라고 책에서 보았습니다. 저도 잘 기억이 나질 않아 이 부분은 공부하도록 하겠습니다!

2024-07-14 16:38 UTC, nove1080 commented on src/main/java/gift/web/validation/handler/ApiExceptionHandler.java
> +//        ErrorResponse errorResponse = ErrorResponse.from(bindingResult);
넵 맞습니다 구현하도록 하겠습니다

2024-07-14 16:44 UTC, nove1080 commented on src/main/java/gift/web/validation/exception/code/ErrorCode.java
> +    INTERNAL_SERVER_ERROR(-50000, Category.COMMON, "서버 내부 오류입니다."),
사실 에러 코드를 리팩토링 하기 전에 카카오톡 선물하기 에서는 어떤 에러 응답이 나오는지 확인해보았습니다.

<img width="896" alt="image" src="https://github.com/user-attachments/assets/c5e4fde0-8580-4fa3-881c-2ec831381ef4">

여기서 카테고리를 반환하는 것을 보고 단순히 따라서 만들어 보았는데요
솔직히 저도 장점은 잘 모르겠습니다

동건님은 어떻게 생각하시나요?

2024-07-15 03:58 UTC, nove1080 commented on src/main/java/gift/service/WishProductService.java
> +            .quantity(request.getQuantity()).build();
해당 메서드에서는 새로운 위시 상품 등록에 대한 비즈니스 로직을 담당하는데 

1. 기존에 추가 했던 위시 상품에 대한 등록이 또 발생하는 경우 위시 상품에 대한 수량만 추가합니다.
(쿠팡에서 장바구니에 등록하는 과정을 생각해보면 이미 장바구니에 존재하는 상품인 경우 수량만 추가하도록 동작 하더라구요 좋은 방식인 것 같아 따라해보았습니다)

2. 신규 위시 상품 등록의 경우 위시 상품으로 추가합니다.
현재 코멘트를 남기신 부분은 위시 상품으로 DB에 추가하기 위해 `wishProductRepository.save(Entity)` 를 호출하기 위하여 DTO의 정보를 바탕으로 Entity를 만들어내는 과정이었습니다!

2024-07-15 04:04 UTC, nove1080 commented on src/main/java/gift/domain/Member.java
> +    private List<WishProduct> wishProducts;
양방향 연관관계를 가지도록 한 것은 `Product` 나 `Member`의 삭제가 발생하였을 시, 해당 `Product`, `Member` 가 등록한 혹은 등록된 위시 상품(`WishProduct`)를 같이 삭제하기 위해(삭제 전파) `CascadeType.REMOVE` 라는 옵션을 사용하기 위함이었습니다. 

`CascadeType.REMOVE` 만을 적용하기 위해 양방향 연관관계를 설정하게 되었습니다. 

양방향 연관관계를 피하면서 삭제를 전파할 수 있는 방법을 찾아보고 적용한 것이었는데요

다른 방법으로는 `@OnDeleted` 어노테이션을 적용하는 방법도 있었습니다. 이 경우에는 DB에 `ON DELETED CASCADED` 제약조건을 설정하는 방식으로 동작합니다. 따라서 JPA를 사용하는 경우 영속성 컨텍스트와 동기화 문제가 발생할 수 있어 권장되는 방식은 아니라고 판단되어 `CascadeType.REMOVE` 를 사용하는 방식으로 처리하였습니다.

실무에서는 어떤 방식으로 삭제를 전파하나요?

2024-07-15 04:05 UTC, nove1080 commented on src/main/java/gift/domain/Product.java
> +    private List<WishProduct> wishProducts = new ArrayList<>();
바로 아래 코멘트에 같이 답글을 작성하였습니다!

2024-07-15 04:11 UTC, nove1080 commented on src/main/java/gift/web/controller/api/ProductApiController.java
> +        URI location = new URI("http://localhost:8080/api/products/" + response.getId());
우선 "http://localhost:8080/api/products/" 제거하고 실행해보니 상품의 아이디만 Location 헤더에 들어있어 이 부분은 좀 더 찾아보겠습니다!

2024-07-15 04:14 UTC, nove1080 commented on src/main/java/gift/domain/BaseEntity.java
> +    private Long id;
생성자, 수정자 필드의 경우 Auditing 기능을 사용하기 위해서 `AuditorAware`를 구현하는 방법이 있어 적용해보았습니다.
그래서 `MemberIdAuditorAware` 라는 것을 만들게 되었는데 얘는 어느 패키지에 속하는게 적합할까요?

저는 repository 계층에서 동작한다고 생각해서 우선 repository 패키지에 같이 두었습니다

2024-07-15 04:32 UTC, nove1080 commented on src/main/java/gift/domain/Product.java
> +        return this;
DTO의 변경사항이 엔티티에도 전파될 것 같습니다. 예를 들어 필드 이름이 변경되거나 혹은 필요없는 필드가 제거되는 등의 변경사항에 엔티티도 영향을 받을 것 같습니다.

어떤 방법이 괜찮은지 찾아보니
```java
public Product update(Product product) {
    this.name = product.getName();
    this.price = product.getPrice();
    this.imageUrl = product.getImageUrl();
    return this;
}

product.update(request.toEntity());
```
위와 같은 방식으로 도메인에서 DTO의 참조를 끊고 해당 메서드를 호출하는 외부에서 변환을 수행하여 호출하는 것을 권장하는 것 같았습니다

2024-07-16 15:48 UTC, nove1080 commented on src/main/java/gift/web/validation/handler/ApiExceptionHandler.java
> +
이번 PR에서 코멘트를 남기신 부분들은 모두 step2 브랜치에 반영하였으나 해당 피드백은 step3 브랜치에 반영되어 있습니다! 조금 번거로우시겠지만 확인해주시면 감사하겠습니다

이 부분은 제 스스로 생각해보았을 때 리팩토링을 잘못한 것 같아서 멘토링을 통해 조금 더 조언을 듣고 싶습니다

2024-07-16 16:57 UTC, Hongdonggeon approved these changes
제법님이 코멘트 남긴 부분들에 대해서 저도 코멘트 남겨놓았습니다!
열심히 학습해주시는게 너무나 잘 느껴집니다 👍
이 pr은 머지할게요~ 
남은 이야기들은 step3 pr에서 하시죠!

2024-07-16 16:57 UTC, Hongdonggeon commented on src/main/java/gift/domain/Product.java
> +    private URL imageUrl;
이미지 링크 칼럼을 nullable로 해도 되지 않을까요?

2024-07-16 16:57 UTC, Hongdonggeon commented on src/main/java/gift/domain/Product.java
> +    }
한번 같이 찾아보고 멘토링 시간이 이야기해볼까요~?

2024-07-16 16:57 UTC, Hongdonggeon commented on src/main/java/gift/domain/Product.java
> +    public static class Builder extends BaseEntity.Builder<Builder> {
좋아요 빌더 패턴을 선호하신 것 같아서 한번 여쭤봤습니다! 
이건 그냥 궁금해서 여쭤보는데요~ 빌더 패턴 어노테이션으로도 사용할 수 있지 않나요?

2024-07-16 16:57 UTC, Hongdonggeon commented on src/main/java/gift/domain/Product.java
> +        return this;
맞아요 dto의 변경사항이 엔티티에 전파되서는 안됩니다 
프레젠테이션 계층 (controller와 dto)이 가장 변화가 자주 일어나고 엔티티는 가장 변화가 잘 안 일어나는 계층이라고 할 수 있죠. 또한 엔티티가 변경되면 영향도도 크고요. 
그러기때문에 dto의 변경이 엔티티까지 전파되서는 안됩니다!

2024-07-16 16:57 UTC, Hongdonggeon commented on src/main/java/gift/domain/WishProduct.java
> +    @ManyToOne(fetch = FetchType.LAZY)
지연로딩을 한다고 N+1 문제가 발생하지 않는건 아닙니다 
제법님이 설명하신 것처럼 실제 객체 (데이터) 사용할 때 조회해와서 결국에 n+1 문제가 발생하긴 하죠 
해결책으로 fetch join이나 엔티티 그래프로 많이 해결을 하구요

2024-07-16 16:57 UTC, Hongdonggeon commented on src/main/java/gift/service/WishProductService.java
> +            .quantity(request.getQuantity()).build();
아 신규 위시 상품 등록인 케이스도 있군요~! 설명 감사해요

2024-07-16 17:02 UTC, Hongdonggeon commented on src/main/java/gift/web/validation/exception/code/ErrorCode.java
> +    INTERNAL_SERVER_ERROR(-50000, Category.COMMON, "서버 내부 오류입니다."),
저도 예외 응답으로 카테고리를 추가해서 사용해본적은 없어서 잘 모르겠는데... 흠
예외 케이스가 정말 많아서 카테고리로 분류해서 api 사용하는쪽에서 예외 파악을 쉽게 하기 위함일 수도 있을 것 같고요.
아니면 추적을 용이하기 위해서 추가하지 않았을까 하는 생각입니다

2024-07-16 17:02 UTC, Hongdonggeon commented on src/main/java/gift/web/controller/api/ProductApiController.java
> +        URI location = new URI("http://localhost:8080/api/products/" + response.getId());
아 그렇다면 아닌 것 같습니다... ㅎ

2024-07-16 17:10 UTC, Hongdonggeon commented on src/main/java/gift/domain/Member.java
> +    private List<WishProduct> wishProducts;
cascade 옵션을 사용하기 위해서 연관관계를 맺었다는건 조금 설득하기에 의견이 부족한 것 같아요
오히려 실무에서는 이런 옵션을 지양? 이라고 하기엔 그러는데 정말 조심해서 사용해요. 그래서 연관관계 마저도 잘 사용하지 않기도 해요 
jpa가 이런 옵션들로 간편하게 해주는 것도 맞지만, 그만큼 예상치 못하게 예외도 많이 발생하기도 하고, 데이터가 의도치않게 삭제될수도 있고요. 잘못 사용하면 이런일들이 벌어지기 때문에.. 조심해서 사용해야죠
그리고 또한 실무 운영을 하다보면 데이터 보정하는일도 빈번하게 일어나는데, 외래키가 걸려 있는 테이블을 다룰 때 수작업 시 번거로움도 있죠. 예를들어 a 데이터는 삭제했는데 a데이터를 fk로가지고 있는 b 데이터가 조회에 실패하고 그런? 그래서 외래키때문에 테이블간의 결합도가 강해지면서 고려할게 많아진다는 이런 이유때문에 fk를 설정을 잘 안하는 곳도 있죠

그래서 제 결론은 cascade 옵션을 사용한게 잘못됐다는건 아니고요. 
cascade 옵션을 사용하기 위해서 사용하고 있지 않는 객체를 선언하고 연관관계를 맺는게 조금 아쉽다라는 생각입니다

2024-07-16 17:11 UTC, Hongdonggeon commented on src/main/java/gift/domain/BaseEntity.java
> +    private Long id;
흠... repository 레벨에 있어도 될 것 같아요?!

2024-07-16 17:11 UTC, merged

2024-07-16 17:11 UTC, nove1080 commented on src/main/java/gift/domain/Product.java
> +    public static class Builder extends BaseEntity.Builder<Builder> {
과제를 수행할 때 Lombok을 사용하지 않았으면 좋겠다고 강사님께서 이야기하셔서 직접 코드를 작성했어야 했습니다 ㅜㅜ

2024-07-16 17:17 UTC, nove1080 commented on src/main/java/gift/domain/WishProduct.java
> +    @ManyToOne(fetch = FetchType.LAZY)
아 제가 잘못 알고 있었네요