경북대 BE_한영지 3주차 과제(3단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #311
Opened 2024-07-12 06:39 UTC by yjhannn

**### 3주차 Step3 제출합니다!**
1. 우선 저번 단계 과제의 피드백 반영을 했습니다
- 테스트 코드 수정을 했습니다
- 그리고 Product와 WishList는 원래 DTO 파일에서 Request,Response로 구분하여 변경을 했는데, 아직 User 부분은 변경을 다하지 못하여서 지금과 같은 파일명을 가지고 있습니다ㅠ 주말 내에 마저 변경하도록 하겠습니다
2. 페이지네이션 구현(Product, WishList)을 했습니다!

2024-07-13 05:42 UTC, jadie0319 requested changes
3주차 3단계 미션하시느라 고생하셨습니다!
피드백 확인 부탁드려요! 궁금하신 점 있으시면 DM 주세요!
화이팅 입니다!

2024-07-13 05:42 UTC, jadie0319 commented on src/test/java/gift/repository/ProductRepositoryTest.java
> +        return new Product(name, price, url);
private 메서드는 아래에 위치시키는게 가독성이 더 좋을 것 같아요!

2024-07-13 05:42 UTC, jadie0319 commented on src/main/java/gift/controller/WishListController.java
addProductToWishList, updateQuantityToWishList 메서드는 서비스가 값을 반환하는데 사용하지 않고 있어요.
사용하게 변경해볼까요?

2024-07-13 05:42 UTC, jadie0319 commented on src/main/java/gift/service/ProductService.java
> +        return productRepository.findAll(pageable).map(ProductResponse::from);
조회후 엔티티를 DTO 로 변환해서 반환해줬네요! 👍

2024-07-13 05:42 UTC, jadie0319 commented on src/test/java/gift/repository/WishListRepositoryTest.java
> +        return new WishList(user, product, quantity);
이 메서드도 사용해주시면 좋을 것 같아요!

2024-07-13 05:42 UTC, jadie0319 commented on src/test/java/gift/repository/ProductRepositoryTest.java
Product, User, WishList 공통 피드백 입니다!

이제 DataJpaTest 사용법을 아셨으니 실제 서비스에서 사용중인 메서드에 대한 테스트를 추가하시면 좋을 것 같아요 :)
현재는 WishListRepository.findByIdAndUserId() 와 같이 서비스에서 사용중인 Repository 메서드 테스트가 없네요. 기능에서 사용중인 Repository 메서드를 테스트하는게 DataJpaTest의 주요 목적이기도 합니다~

2024-07-13 05:42 UTC, jadie0319 commented on src/main/java/gift/repository/wish/WishListRepository.java
>      Optional<WishList> findByUserIdAndAndProductId(Long userId, Long ProductId);
미사용 메서드는 삭제해주시는게 좋아요~

2024-07-13 05:42 UTC, jadie0319 commented on src/main/java/gift/controller/ProductController.java
> +        Pageable pageable = PageRequest.of(page, size, Sort.by(direction, sort[0]));
요청객체에 DTO 를 사용하거나 Pageable 을 바로 사용하는건 어떻게 생각하시나요?
만약 Pageable 객체를 요청객체로 받으면 이 로직은 없앨 수 있겠네요!

2024-07-13 16:45 UTC, jadie0319 commented on src/main/java/gift/service/WishListService.java
>      }
페이징 처리 잘하셨습니다!

2024-07-14 10:29 UTC, yjhannn commented
### 피드백 반영하여 다시 제출합니다!
- 안녕하세요! 주말에도 리뷰해주시느라 고생 많으십니다! 피드백 반영하여 코드 변경했습니다. 테스트 코드는 다음 주 과제 진행하면서 더 자세하게 작성해보겠습니다. 감사합니다~!!

2024-07-14 10:41 UTC, jadie0319 approved these changes
3주차 미션하시느라 고생하셨습니다~
피드백 잘 반영해주셔서 좋습니다 👍 
4주차도 화이팅 해봐요!
다음 4주차 미션을 위해 머지하겠습니다!

2024-07-14 10:41 UTC, jadie0319 commented on src/main/java/gift/controller/WishListController.java
> +    @PageableDefault(size = 10, sort =  "name") Pageable pageable) {
좀더 보기 쉬운 코드가 됐네요! 피드백 반영 👍

2024-07-14 10:41 UTC, jadie0319 commented on README.md
피드백 반영 잘해주셨네요 :) 다음주도 화이팅 해봐요!

2024-07-14 10:41 UTC, merged