경북대 BE_김건 3주차 과제(3단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #320
Opened 2024-07-12 07:30 UTC by gunGeongun

## 과제 수행 후 느낀 점
***
일단 3단계까지 과제 요구사항에 나온 기능 구현은 마쳐서 이대로 과제 제출을 하게되지만 이제 남은 시간에 생소한  jpa 개념에 대해 제대로 학습해보는게 좋을 것 같습니다.아직 jpa개념에 대해 잘 모르기도 하고 jpa의 기초 개념을 탄탄히 다져놔야 방대한 jpa 체계의 학습을 무리없이 진행할 수 있을 것 같습니다. 그리고  지금은 그냥 가볍게 과제 요구사항만 충족시킨 정도이지만 추가로 더 넣어볼 기능이나 생각해볼 요소들이 많을 것 이라 생각합니다.코드를 꼼꼼하게 분석해보고 다양한 문제점들을 스스로 생각해보면서 리팩토링을 진행해보겠습니다.

## 과제 수행 후 궁금한 점
***
1. 지금 페이지네이션 방식에서는 PageResponse 객체에 게시물 정보뿐만아니라 totalpage,totalElement 까지 넣어주어 프론트단에서 처리할때 좀 더 많은 정보를 얻을 수 있도록 하였습니다. 원래 페이지네이션 기능을 구현할때에도 이런식으로 프론트단에 정보를 전달해주는 방식으로 하는건지 궁금합니다.

2024-07-13 06:57 UTC, MangKyu requested changes
마지막 단계도 고생많으셨습니다! 이제 핵심을 위해 조금 미뤄뒀던 부분에 대해서 코멘트 및 추가 변경 요청 드리겠습니다 🙇
과제를 하면서 느끼셨겠지만, 요구사항이 계속해서 생김에 따라 리팩터링이 지속적으로 일어나게 됩니다! 따라서 비즈니스 정책들에 대한 테스트가 존재해야 코드 변경이 생겨도 영향이 없음을 보장할 수 있는데요, 예를 들어 Gift의 경우 "카카오" 라는 네이밍 규칙에 대한 부분을 단위 테스트로 작성해둔다면 우리의 비즈니스 정책이 영향없음을 보증받을 수 있을 것 같아요ㅎㅎ 해당 부분을 보완하시면 좋을 것 같습니다!

질문에 대한 답변도 드리도록 하겠습니다!
페이징의 경우 다른 추가적인 정보를 통해 추가적인 페이징 처리가 가능하므로, 전달이 필요합니다! 이때 전달되는 정보는 페이징 전략에 따라 달라질 수 있는데, 이때 또 다른 페이징 전략 중 하나인 cursor 방식을 가져갈 수도 있습니다ㅎㅎ 현재 사용하는 방식은 offset 방식이라고 하는데, 현재는 중요하지 않은 것 같아서 천천히 공부해보시면 좋을 것 같아요

2024-07-13 06:57 UTC, MangKyu commented on src/main/java/gift/config/PageRequestArgumentResolver.java
> +public class PageRequestArgumentResolver implements HandlerMethodArgumentResolver {
ArgumentResolver를 통해 시도한한 부분은 좋은데요! ArgumentResolver 없이도 동일하게 default 값 할당만 처리해주면 구현 가능할 것 같습니다! 정리하면 PagingRequest 객체를 그대로 받고, 내부의 변수에 default 값만 미리 할당해두어도 될 것 같습니다ㅎㅎ

```java
public class PagingRequest {
    private int page = 1;
    private int size = 5;

    ...

}
```

2024-07-13 06:57 UTC, MangKyu commented on src/main/java/gift/controller/WishListController.java
> +        return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body(emptyPagingResponse);
값이 없어도 괜찮을 것 같습니다ㅎㅎ
```suggestion
        return ResponseEntity.status(HttpStatus.UNAUTHORIZED).build()
```

2024-07-13 06:57 UTC, MangKyu commented on src/main/java/gift/dto/PagingRequest.java
> +    int page;
```suggestion
    private int page;
```

2024-07-13 06:57 UTC, MangKyu commented on src/main/java/gift/model/gift/Gift.java
>      public Gift() {
기본생성자 JPA 스펙을 위해 필요한 부분이므로, 사용되지 않는다면 protected로 선언하면 더욱 좋을 것 같습니다ㅎㅎ

2024-07-13 06:57 UTC, MangKyu commented on src/main/java/gift/model/wish/Wish.java
> +    public void modifyQuantity(int quantity) {
도메인을 표현하는 메서드 좋네요! 💯

2024-07-13 06:57 UTC, MangKyu commented on src/test/java/gift/repository/WishRepositoryTest.java
> +//import gift.model.*;
테스트는 우리의 코드가 다른 변경에도 영향받지 않았음을 나타내는 중요한 수단 중 하나인데요, 비활성화 처리하신 이유가 있을까요~?

2024-07-14 05:55 UTC, gunGeongun commented on src/main/java/gift/config/PageRequestArgumentResolver.java
> +public class PageRequestArgumentResolver implements HandlerMethodArgumentResolver {
Resolver라는걸 한번 사용해보자라는 취지로 사용해본거긴한데 객체에 디폴트값을 설정해두고 객체로 받는 방법도 있었네요! 이게 훨씬 깔끔하고 간단한 방법인거 같습니다.

2024-07-14 05:56 UTC, gunGeongun commented on src/main/java/gift/controller/WishListController.java
> +        return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body(emptyPagingResponse);
그냥 build()만 적어주는 방법을 잠시 잊고있었네요. 감사합니다.

2024-07-14 05:58 UTC, gunGeongun commented on src/test/java/gift/repository/WishRepositoryTest.java
> +//import gift.model.*;
오류가 떠서 잠시 주석으로 비활성화 처리해뒀다가 까먹었습니다 ㅜ 테스트  코드 다시 복구했습니다!

2024-07-14 06:04 UTC, gunGeongun commented on src/main/java/gift/model/wish/Wish.java
> +    public void modifyQuantity(int quantity) {
감사합니다!

2024-07-14 06:11 UTC, gunGeongun commented on src/main/java/gift/model/gift/Gift.java
>      public Gift() {
일단 현재는 사용되지 않는 필드라 protected로 선언하겠습니다.

2024-07-14 11:20 UTC, MangKyu approved these changes
수정 사항 열심히 반영해주셔서 감사합니다! 이번 과제도 고생 많으셨습니다ㅎㅎ
학습하시다가 어려운 부분 생기면 편하게 말씀해주세요! 다음주 과제들도 화이팅입니다 🙇

2024-07-14 11:20 UTC, merged