강원대 BE_오승규 3주차 과제 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #321
Opened 2024-07-12 07:33 UTC by 5win

안녕하세요 제이님 2단계 마치고 PR 드립니다!

이번엔 몇가지 질문이 있는데, 구조적인 부분에 의견 주시면 감사하겠습니다 :)

### 1. DTO
이번에 연관관계 매핑으로 변경한 뒤에 순환 참조에 의해서 위시리스트 목록을 가져오는데 오류가 발생했었습니다.
ProductDto를 따로 만들어서 반환하도록 변경하여 해결하였는데요. 
일단 당장의 트러블슈팅을 위해서 ProductDto 만을 생성해서 서비스로 들어오거나 나갈 때 dto와 entity 를 서로 변환하도록 했습니다.
이 부분을 찾아보면서 entity를 클라이언트로 직접 반환하는 것은 지양하라는 의견들이 있던데 당장은 필요하지 않지만 추후를 위해 나머지 entity들도 dto를 생성하는 것이 좋을까요?

### 2. 레거시 코드
JPA로 넘어오면서 아직 JdbcClient를 사용한 코드를 레거시로 남겨놓은 상태입니다.
이번에 Auditing을 통해 생성, 수정 시간을 자동으로 만들어주도록 했는데, 이 기능이 JPA 기능이다보니 기존 JdbcClient의 테스트코드가 모두 통과하지 못하더라구요
보통 이렇게 새로운 기술을 도입하게되면 레거시 코드들은 함께 유지보수하지 않고 제거하는게 좋을까요? 원래 필요하면 바로 갈아끼울수 있도록 함께 유지보수했었는데, 워낙 JPA와 Jdbc쪽의 기술에 차이가 있다보니 이게 맞나 느껴 질문드립니다.

코드에도 몇까지 질문 남겼습니다.
항상 피드백 감사합니다!

2024-07-12 07:39 UTC, 5win commented on src/main/java/gift/controller/MemberController.java
> +        memberService.addWishlist(new WishlistRequest(email, productId));
위시리스트 요청에 대해 DTO 같은 역할로 email, productId를 묶은 WishlistReqeust 를 만들어서 사용했습니다.

형태가 member와 product의 객체를 저장하는 Wishlist 엔티티와는 저장 방식이 좀 다른것 같아 WishlistDto라고 이름 짓지 않고 이렇게 지었는데 괜찮은 네이밍일까요?
혹시 맞다면 패키지를 따로 분리해야 하는 것이 좋은 구조인지 궁금합니다 :)

2024-07-12 07:46 UTC, 5win commented on src/main/java/gift/entity/Product.java
> +@EntityListeners(AuditingEntityListener.class)
제가 1주차 과제에서 Product는 id를 입력받도록 구현한 상태로 여기까지 오게되었습니다.
일단 자동생성이 아닌 입력받는 것이 현재 로직이므로 Product 엔티티에 대해서만 BaseEntity의 상속을 받지 않도록 한 상태인데..

id는 불변해야하는게 좋다고 생각이 바뀌어서 입력받지 않도록 바꿀까 생각중입니다.
그렇게되면 새 상품을 추가할 때 기존에 상품이 이미 존재하는지 확인하는 부분에 findById가 아닌 findByName을 사용해야할 것 같습니다.
당연히 id 보다는 name으로 조회하는게 성능적인 측면에서 느릴 것 같은데, 보통 이런 부분은 감수하고 조회하도록 구현하는 것이 맞을까요? 아니면 최적화하는 방법이 따로 있을까요?

2024-07-12 07:54 UTC, 5win commented on src/main/java/gift/service/MemberService.java
> +    private Wishlist convertWishlistRequestToWishlist(WishlistRequest wish) {
addWishlist 메서드에서 위시리스트 추가하는 과정에서 사용되는 메서드입니다.
연관관계 매핑을 위해서 Member, Product 객체에도 Wishlist 객체를 추가해야한다는 생각에 이렇게 2번의 쿼리를 추가해서 객체를 가져오도록 했었습니다.

지금 생각해보면 내부적으로 email과 productId에 대한 값만 가지고 있으면 wishlist 테이블에 외래키를 충분히 입력이 가능할 것으로 생각이 되긴 합니다. 즉, 2번의 조회 필요없이 가짜 객체를 만들어서 넣어주고 save하면 될 것 같습니다.

어차피 wishlist 테이블에 레코드를 삽입하고 트랜잭션을 종료하기 때문에 Member, Product 객체에 굳이 Wishlist 객체를 저장할 필요가 없는 것 같은데 수정하는 것이 좋을까요?

2024-07-12 14:53 UTC, jaymarystella commented on src/main/java/gift/entity/Product.java
> +    private LocalDateTime modifiedDate;
이 부분은 정의해주신 baseEntity로는 해결이 안될까요?

2024-07-12 14:53 UTC, jaymarystella commented on src/main/java/gift/entity/Wishlist.java
> +    @ManyToOne(fetch = FetchType.LAZY)
Lazy로 설정하신 이유가 어떻게 될까요?

2024-07-12 14:53 UTC, jaymarystella commented on src/main/java/gift/entity/Wishlist.java
> +    }
생성자가 필요한 이유가 어떻게될까요? 제한자는 public만 가능할까요?

2024-07-12 14:53 UTC, jaymarystella commented on src/main/java/gift/service/MemberService.java
> +        wishlistJpaDao.save(wishlist);
연달아있는 get을 없애려면 어떻게하면 좋을까요?

2024-07-12 14:53 UTC, jaymarystella commented on src/main/java/gift/controller/MemberController.java
> +        memberService.addWishlist(new WishlistRequest(email, productId));
내부에서 받자마자 email과 productId를 그대로 꺼내고있는데요, 굳이 불필요한 구조로 보입니다. 애초에 컨트롤러에서 해당 클래스를 이용해서 받는게 아니라면 빼는게 좋을것같습니다.

2024-07-12 14:59 UTC, jaymarystella commented on src/main/java/gift/entity/Product.java
> +@EntityListeners(AuditingEntityListener.class)
특별히 의도가 있지 않으면 id를 입력받는구조는 개선하는게 좋을거같습니다.

그리고 name에 unique index를 설정하실거같은데 둘다 성능이 좋아서 크게 신경안써도 될듯합니다. 그리고 어떤 dbms를 사용하냐에 따라 또 다를거같네요. b-tree구조의 clustered index를 사용하게된다면 id로 조회시 최적화된 조회가 되겠지만 unique index는 인덱스조회후 한번 더 찾아가는 과정이 있을거에요. 대부분의 경우 id조회가 더빠르겠지만 차이는 미미할거같아요. 정확한건 측정을 해봐야알거같고 최적화까지 필요할까 싶네요.

2024-07-12 15:04 UTC, jaymarystella requested changes
안녕하세요 승규님. 
2단계 구현하느라 고생많으셨어요.
몇가지 코멘트남겨두었는데 확인 후 의견부탁드릴게요~

2024-07-12 15:04 UTC, jaymarystella commented on src/main/java/gift/service/MemberService.java
> +    private Wishlist convertWishlistRequestToWishlist(WishlistRequest wish) {
제가 질문을 잘 이해를 못한거일수도있는데요,
member와 product가 유효한지 알려면 조회를 해야되는거 아닌가요?

2024-07-12 15:05 UTC, jaymarystella commented
> 1. DTO
> 이번에 연관관계 매핑으로 변경한 뒤에 순환 참조에 의해서 위시리스트 목록을 가져오는데 오류가 발생했었습니다.
> ProductDto를 따로 만들어서 반환하도록 변경하여 해결하였는데요.
> 일단 당장의 트러블슈팅을 위해서 ProductDto 만을 생성해서 서비스로 들어오거나 나갈 때 dto와 entity 를 서로 변환하도록 했습니다.
> 이 부분을 찾아보면서 entity를 클라이언트로 직접 반환하는 것은 지양하라는 의견들이 있던데 당장은 필요하지 않지만 추후를 위해 나머지 entity들도 dto를 생성하는 것이 좋을까요?

기본적으로 필요할때 만드시는걸 추천드립니다. 필요하지않은데 만들게되면 불필요한 코드들까지 관리를 해야합니다.

2024-07-12 15:07 UTC, jaymarystella commented
> 2. 레거시 코드
> JPA로 넘어오면서 아직 JdbcClient를 사용한 코드를 레거시로 남겨놓은 상태입니다.
> 이번에 Auditing을 통해 생성, 수정 시간을 자동으로 만들어주도록 했는데, 이 기능이 JPA 기능이다보니 기존 JdbcClient의 테스트코드가 모두 통과하지 못하더라구요
> 보통 이렇게 새로운 기술을 도입하게되면 레거시 코드들은 함께 유지보수하지 않고 제거하는게 좋을까요? 원래 필요하면 바로 갈아끼울수 있도록 함께 유지보수했었는데, 워낙 JPA와 Jdbc쪽의 기술에 차이가 있다보니 이게 맞나 느껴 질문드립니다.


일단 동일 dbms에 접근하게되는 기술을 갈아끼우게되면 기존것은 제거하는게 맞습니다. 그리고 쓰이지않는 코드는 특별한 이유가 없는한 제거를 해야합니다. 나중에 원복을 하게되더라도 어차피 형상에 다 남아있기때문에 상관없습니다.

2024-07-12 15:15 UTC, jaymarystella commented
그리고 PR가이드는 제가 링크도 따로 전달드렸는데 다시한번 살펴보시고 브랜치 형상도봐주시면 좋을거같습니다..

2024-07-13 07:51 UTC, 5win commented on src/main/java/gift/entity/Product.java
> +    private LocalDateTime modifiedDate;
> 이 부분은 정의해주신 baseEntity로는 해결이 안될까요?

상속 받은 뒤에 id 값을 직접 넘겨주는 방식으로 하면 될 것 같습니다.
상품 추가시에 id를 입력하지 않도록 수정해서 BaseEntity를 상속 받도록 수정했습니다!

2024-07-13 07:55 UTC, 5win commented on src/main/java/gift/entity/Wishlist.java
> +    @ManyToOne(fetch = FetchType.LAZY)
> Lazy로 설정하신 이유가 어떻게 될까요?

fetch join는 eager 가 기본값이며, eager를 사용하게 되면 member에 대한 조회 쿼리를 날리더라도 wishlist에 대한 쿼리까지 함께 수행되는 것으로 알고 있습니다. 반면에 lazy는 한 번에 쿼리가 실행되지 않고 member 객체의 wishlist에 접근할 때에 실행되는 것으로 알고있습니다.
따라서 사용되지 않을 경우 추가적인 쿼리 실행을 방지하기 위해 사용했습니다.

2024-07-13 07:58 UTC, 5win commented on src/main/java/gift/entity/Wishlist.java
> +    }
> 생성자가 필요한 이유가 어떻게될까요? 제한자는 public만 가능할까요?

https://github.com/kakao-tech-campus-2nd-step2/spring-gift-jpa/pull/145#discussion_r1671713669
step1 PR에서 말씀드린 것처럼 JPA에서 리플렉션을 통해 객체를 생성하기 위해 필요한 것으로 알고있습니다.
그리고 제한자는 public과 protected까지 가능한 것으로 알고있습니다!

2024-07-13 08:02 UTC, 5win commented on src/main/java/gift/service/MemberService.java
> +        wishlistJpaDao.save(wishlist);
> 연달아있는 get을 없애려면 어떻게하면 좋을까요?

피드백 주신 `WishlistRequest`이 단순히 파라미터로 전달만하고 별다른 의미가 없는 것 같아 제거했습니다.
그 후 `convertWishlistRequestToWishlist()` 메서드의 로직을 `addWishlist()` 옮기면서 수정해보았습니다.

member, product 객체를 저장해두고 해당 객체에 바로 `member.getWishlist().add()` 하는 방식으로 줄여보았습니다.

2024-07-13 08:06 UTC, 5win commented on src/main/java/gift/controller/MemberController.java
> +        memberService.addWishlist(new WishlistRequest(email, productId));
> 내부에서 받자마자 email과 productId를 그대로 꺼내고있는데요, 굳이 불필요한 구조로 보입니다. 애초에 컨트롤러에서 해당 클래스를 이용해서 받는게 아니라면 빼는게 좋을것같습니다.

넵 반영하여 WishlistRequest 객체를 제거했습니다.
클론 코딩 강의 내용 중에 "2개 이상의 파라미터를 넘기는 경우엔 객체로 묶어서 하나로 보내는 방법을 생각해볼 수 있다" 라는 말이 있었는데, 해당 내용을 보고 별 생각 없이 썼던 것 같습니다.

아무래도 제이님이 지향하시는 바는 기능적, 역할적으로 의미가 없는 불필요한 것은 지양하는 것이라고 생각이 는데, 저도 항상 왜 사용해야하나 생각해본 뒤에 적용해보도록 노력하겠습니다 🙂

2024-07-13 08:08 UTC, 5win commented on src/main/java/gift/entity/Product.java
> +@EntityListeners(AuditingEntityListener.class)
> 특별히 의도가 있지 않으면 id를 입력받는구조는 개선하는게 좋을거같습니다.
> 
> 그리고 name에 unique index를 설정하실거같은데 둘다 성능이 좋아서 크게 신경안써도 될듯합니다. 그리고 어떤 dbms를 사용하냐에 따라 또 다를거같네요. b-tree구조의 clustered index를 사용하게된다면 id로 조회시 최적화된 조회가 되겠지만 unique index는 인덱스조회후 한번 더 찾아가는 과정이 있을거에요. 대부분의 경우 id조회가 더빠르겠지만 차이는 미미할거같아요. 정확한건 측정을 해봐야알거같고 최적화까지 필요할까 싶네요.

정성스런 답변 감사드립니다 :)
우선 id는 입력받지 않도록 개선했습니다.
말씀해주신 DBMS 구조나 인덱스 같은 경우는 아직 제 지식이 미미해서 이해하진 못했지만 기회가 될 때 한 번 공부해보도록 하겠습니다!

2024-07-13 08:10 UTC, 5win commented on src/main/java/gift/service/MemberService.java
> +    private Wishlist convertWishlistRequestToWishlist(WishlistRequest wish) {
> 제가 질문을 잘 이해를 못한거일수도있는데요, member와 product가 유효한지 알려면 조회를 해야되는거 아닌가요?

지적 감사드립니다. 아직 익숙하지 않아서 착각했던 것 같습니다..
제이님 의견이 맞는 것 같아서 이 부분은 수정하지 않았습니다!

2024-07-13 08:28 UTC, 5win commented
> 그리고 PR가이드는 제가 링크도 따로 전달드렸는데 다시한번 살펴보시고 브랜치 형상도봐주시면 좋을거같습니다..

죄송합니다... 브랜치 형상까지는 생각해보지 못했습니다
지적 감사합니다. 덕분에 rebase와 merge의 차이에 대해 생각해볼 수 있었고 앞으로 주의하도록 하겠습니다.
언제든 답답하시거나 부족해보이는 부분이 있다면 지적해주세요!

아직 미숙해서 잘해보고싶은 마음에 한 가지만 여쭤보고 싶습니다 :)
제가 브랜치 형상을 보며 기억을 더듬어보니 step1에 대한 PR을 한 뒤, step1에서 step2로 브랜칭을 했던 것 같습니다.
리뷰 주시기 전까지 step2 작업을 하다가 이후 피드백을 주신 뒤 반영하고 step1이 머지되었습니다.
그리고는 step2에서 머지된 5win 브랜치를 머지하고 작업한 것 같습니다.

사실 좀 꼬여서 헷갈리는 상태이긴 합니다...
고민해본 결과 앞으로 진행 방식을 이렇게 해야할 것 같은데 피드백 주시면 감사하겠습니다!
1. step1을 수행한 뒤 PR 한다.
2. 리뷰 주시기 전까지 step1 브랜치에서 step2를 브랜칭하고 작업한다. (step1 내용에 이어서 작업해야하므로)
3. 피드백 주시면 step1에 반영한다.
4. step1이 머지되면 upstream/5win에서 fetch하고 local/5win에서 rebase한다.
    1. 이렇게 되면 local/5win에 upstream의 커밋과 내용이 반영된 상태일 것  같습니다.
6. step2 브랜치에서 local/5win 으로 rebase한다.
7. step2 작업을 이어서 진행한다.

이렇게되면 제가 따로 작업하던 step2의 커밋들이 step1 마지막 커밋을 가리키도록? 하여 관리가 될 것으로 생각되는데 잘못된 부분이 있다면 지적해주세요 :)

2024-07-14 11:56 UTC, jaymarystella commented on src/main/java/gift/controller/MemberController.java
> +        memberService.addWishlist(new WishlistRequest(email, productId));
넵 정답은 없고 취향 + 일관된규칙을 지킨다면 그렇게 하셔도 당연히 무방합니다. 
이런부분들은 꼭 저의 피드백대로 하실필요는 없습니다.

2024-07-14 11:58 UTC, jaymarystella commented on src/main/java/gift/service/MemberService.java
> +        wishlistJpaDao.save(wishlist);
넵 혹은 명시적인 메서드를 만드시는것도 방법이 될거같습니다.

2024-07-14 12:01 UTC, jaymarystella commented
넵 말씀주신 방향대로 하셔도되고 step2를 미리진행하고있었다면(브랜치이름은 예를들어 step2-temp) 머지된 remote브랜치로부터 step2브랜치를 새로 만들고 step2-temp의 커밋들을 step2브랜치에 리베이스를 하셔도되고 커밋이 몇개없다면 단순히 특정커밋들만 찍어서 pick해서 올려주셔도 될거같아요.

2024-07-14 12:01 UTC, jaymarystella approved these changes
안녕하세요
리뷰 반영 잘해주셨습니다.
질문주신 내용 코멘트 남겨두었어요. 다음단계에서 뵐게요~

2024-07-14 12:01 UTC, merged

2024-07-15 05:20 UTC, 5win commented on src/main/java/gift/service/MemberService.java
> +        wishlistJpaDao.save(wishlist);
> 넵 혹은 명시적인 메서드를 만드시는것도 방법이 될거같습니다.

wishlist 엔티티에 product, member를 추가하는 메서드를 만들어도 되겠군요 감사합니다!