충남대 BE_박서현 3주차 과제 (3단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #334
Opened 2024-07-12 08:00 UTC by sseooh

2024-07-13 14:41 UTC, jjongwa requested changes
고생 많으셨습니다!

이번에도 구현 잘 해 주셔서 간단한 질문 위주로 리뷰 달았어요!ㅎㅎ 조금 귀찮은 질문일 수도 있지만 잘 정리해서 적어주시면 분명 도움이 될 거라고 생각합니다..!

질문에 대한 답변 주시고 다시 리뷰 요청 주시면 다음번엔 바로 머지하도록 할께요~!

2024-07-13 14:41 UTC, jjongwa commented on src/main/java/gift/controller/ProductController.java
> +//        model.addAttribute("products", products);
page와 size는 각각 어떤 역할을 하나요?
각각 defaulValue을 바꿔주면 어떻게 동작하게 될까요?

+주석은 지워주세요~

2024-07-13 14:41 UTC, jjongwa commented on src/main/java/gift/domain/Wish.java
>      }
이렇게 WIsh가 Member와 Product를 가지게 되면서 어떤 변화가 있었나요?
추가적으로 느낀 장단점은 무엇이었나요?

2024-07-13 14:41 UTC, jjongwa commented on src/main/java/gift/repository/WishRepository.java
> +    Page<Wish> findByMemberId(Long memberId, Pageable pageable);
Repository 단에서 List로 받지 않고 Page로 받게 되면 어떤 장점이 있을까요? 
pageable에는 어떤 설정이 있을까요?

2024-07-13 14:41 UTC, jjongwa commented on src/main/java/gift/repository/WishRepository.java
추가적으로 저번 step에서 물어보지 못했는데, DAO와 Repository의 차이점은 무엇일까요?

2024-07-14 13:03 UTC, sseooh commented on src/main/java/gift/controller/ProductController.java
> +//        model.addAttribute("products", products);
page는 현재 페이지 번호를, size는 하나의 페이지에서 표시할 상품 개수를 의미합니다.
따라서 page의 defaultValue를 1로 바꾸면 1번 페이지부터 시작하게 되고,
size의 defaultValue를 15로 바꿔주면 한 페이지에 15개의 상품을 표시할 수 있게 됩니다!

2024-07-14 13:10 UTC, sseooh commented on src/main/java/gift/repository/WishRepository.java
> +    Page<Wish> findByMemberId(Long memberId, Pageable pageable);
모든 데이터를 한 번에 로드하지 않고, 일부만 로드하기 때문에 메모리 사용량을 줄일 수 있을 것 같습니다.
또, 사용자 입장에서도 항목을 나누어 볼 수 있어서 더 좋을 것 같습니다!

pageable 설정에는 페이지 번호, 페이지 크기, 정렬 기준 등이 있다고 알고 있습니다.

2024-07-14 13:24 UTC, sseooh commented on src/main/java/gift/repository/WishRepository.java
보통 DAO는 데이터베이스에 접근하기 위해서 접근과 관련된 로직을 모아놓고,
Repository는 엔티티 객체를 관리하기 위한 것이라고 알고 있습니다!
DAO -> 직접적인 쿼리 사용, Repository -> 도메인과 데이터베이스 매핑/Spring Data JPA 쓸 때 보통 사용

2024-07-14 13:26 UTC, sseooh commented on src/main/java/gift/domain/Wish.java
>      }
데이터베이스의 외래키 관계를 엔티티 간의 관계로 만들어서 Product와 Member 객체와 관련된 데이터나 메서드를 직접 사용할 수 있는 장점이 있는 것 같습니다!

2024-07-15 14:03 UTC, jjongwa approved these changes
자 이제 4단계로 가봅시다~~ 🚀

2024-07-15 14:03 UTC, merged