경북대 BE_도기헌 3주차 과제 (1단계, 2단계, 3단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #338
Opened 2024-07-12 08:12 UTC by Dockerel

1단계 학습 목표가 JPA의 적용이었고 2단계의 학습목표가 엔티티 간에 연관관계 매핑하기였습니다. 하지만 2단계를 구현하며 전체적으로 굉장히 많이 리팩토링을 하여 1단계, 2단계를 따로 올리는 것 보다 같이 올리는 것이 나을 것 같아 동시에 제출하게 되었습니다.

## 0단계 질문
**1.** JwtFilter를 sut로 등록하여 진행하는 테스트를 언급하셨는데,  이전에 구현한 HTTP 테스트가 아닌 Filter 객체에 대해 직접적으로 수행하는 테스트를 의미하시는 걸까요?
**2.** AOP에 대해 간단히 공부해보면서 시간 체킹 코드를 만들어 보았습니다. 혹시 시간 체킹 혹은 로깅 말고 AOP의 좋은 활용 방법이 있을까요??
## 1단계 질문
~
## 2단계 질문
연관관계에 대해 공부하던 중 manytomany 관계의 경우 기존에 구현되어 있는 어노테이션을 사용하는 것 보다 중간 테이블을 만들어 oneToMany- (manyToOne : manyToOne) - oneToMany 형태로 구현하여야 한다고 들었습니다. 그런데 확실하게 이해가 잘 되지 않습니다. 예를 들어 team - teamAndMember - member 관계에서 team의 id와 member의 id를 저장한 teamAndMember 객체를 중간 테이블에 저장한다음 중간 테이블에서 원하는 데이터를 쿼리를 통해 뽑아내는 방식인가요?
## 3단계 질문
pagination 구현 시 page와 size를 쿼리 스트링으로 넘겨줌으로써 데이터를 받아오는데 요즘 특정 사이트들은 페이지별로 데이터를 나누는게 아닌  계속 내리면서 누적시키면서 데이터를 받아오는 형태가 있는 것 같습니다. 혹시 이런 형태의 사이트들은 처음부터 모든 데이터를 싹다 받아오는 방식인지 궁금합니다.

2024-07-12 13:14 UTC, gongdongho12 requested changes
> 1. JwtFilter를 sut로 등록하여 진행하는 테스트를 언급하셨는데, 이전에 구현한 HTTP 테스트가 아닌 Filter 객체에 대해 직접적으로 수행하는 테스트를 의미하시는 걸까요?

서비스 자체에 테스트를 의미한 것이었습니다
실제로 동작하는 부분중에 DB 접근하지 않더라도 유저 A를 로그인 필터만 통과시켰을 떄의 동작만을 구현하면 DB를 메모리에 올리기까지의 로딩없이 빠르게 비지니스 로직을 테스트 할 수 있으니까요!

> 2. AOP에 대해 간단히 공부해보면서 시간 체킹 코드를 만들어 보았습니다. 혹시 시간 체킹 혹은 로깅 말고 AOP의 좋은 활용 방법이 있을까요??

이부분은 코드에 남겨보겠습니다

> 2단계 질문
연관관계에 대해 공부하던 중 manytomany 관계의 경우 기존에 구현되어 있는 어노테이션을 사용하는 것 보다 중간 테이블을 만들어 oneToMany- (manyToOne : manyToOne) - oneToMany 형태로 구현하여야 한다고 들었습니다. 그런데 확실하게 이해가 잘 되지 않습니다. 예를 들어 team - teamAndMember - member 관계에서 team의 id와 member의 id를 저장한 teamAndMember 객체를 중간 테이블에 저장한다음 중간 테이블에서 원하는 데이터를 쿼리를 통해 뽑아내는 방식인가요?

매번 좋은 질문 주시는군요 😄 

|id|member_id|wishes_id|
|------|---|---|
|1|1|11|
|2|11|12|
|3|12|12|
|4|12|13|

멤버 1명대 위시리스트면 위시리스트에 멤버 하나만 넣어주면 1:N이 가능한데요
멤버 N개고 위시리스트가 있다면 멤버와 위시 각각으로 데이터셋을 구성해줘야 하니까 실제론 물리적인 테이블이 생기므로 관련해서 말씀주신 것 처럼 구성해야 실제 DB와 같다는 이야기를 주신것 같아요!

> 3단계 질문
pagination 구현 시 page와 size를 쿼리 스트링으로 넘겨줌으로써 데이터를 받아오는데 요즘 특정 사이트들은 페이지별로 데이터를 나누는게 아닌 계속 내리면서 누적시키면서 데이터를 받아오는 형태가 있는 것 같습니다. 혹시 이런 형태의 사이트들은 처음부터 모든 데이터를 싹다 받아오는 방식인지 궁금합니다.

이것도 페이지네이션의 일종이라고 생각해주시면 되는데요
대신 차이라고 하면 end가 언제인지 알 필요는 없게 되는게 장점이에요
페이지는 나 10페이지 가고 싶으면 10페이지 가면 되고 최종 몇페이지까지 있는지 한눈에 볼 수 있는데요

말씀주신 내용은 infinite scroll 방식으로 언제가 끝인지 생각하지 않아도 되는 것이죠!

둘다 페이지네이션인데 하나는 뒷 번호가 언제까지일지 몰라도 되는 경우 사용한다 정도 생각해주시면 되구, 지금 페이지네이션 구성해주신 걸로도 무한스크롤 방식의 스크롤로의 사용도 가능합니다
나중에 상품이 엄청 많아져서 매번 카운팅하고 매번 세야하면 그것도 부하자나요
그런 상황일 때 UI를 변경해서 실제 서비스 부하를 줄이는 관점에서 사용하기도 합니다

2024-07-12 13:14 UTC, gongdongho12 commented on README.md
> +위와 같은 방식으로 참조 가능하게...
👍🏼 이번 플젝의 목표 명확하네요

2024-07-12 13:14 UTC, gongdongho12 commented on src/main/java/gift/aop/TimeTraceAop.java
> +    }
이런 시도 좋네요!
AOP로 로깅, 타임 설정 말고도 어떤 걸 해볼 수 있는지 질문주셨자나요
저라면 이번 프로젝트에서 에러로 롤백된 SQL을 쉽게 볼 수 있으면 디버깅할 때 용이할 것 같아요
전부 DB 사용하는 부분이니까요!

2024-07-12 13:14 UTC, gongdongho12 commented on src/main/java/gift/aop/TimeTraceAop.java
> +    }
아니면 아직 계정을 재대로 쓰고있지 않지만 사용자별 주요 참조 상품들을 카운팅해두 되구요!
`A사용자 조회 카운트 3회 이상 -> 구매 1회 등으로요`

2024-07-12 13:14 UTC, gongdongho12 commented on src/main/java/gift/controller/ProductController.java
> +                                        @RequestParam(required = false, defaultValue = "5", value = "size") int size) {
이걸 각각 쿼리로 가져오는것도 좋은데요
PageRequest라는 값으로 한번에 인식하는 방법이 있어요
https://velog.io/@dhk22/Spring-%EC%84%B8%EC%83%81-%EA%B0%84%EB%8B%A8%ED%95%9C-Pagination-Controller%EC%97%90%EC%84%9C-Pageable-%EA%B0%9D%EC%B2%B4-%EB%B0%9B%EC%95%84-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0

이부분 참고해서 한번 개선해보면 어떨까요?

2024-07-12 13:14 UTC, gongdongho12 commented on src/main/java/gift/controller/UserController.java
> +    }
이걸 여기서 관리하는 거랑은 조금 거리가 먼 것 같아요
유저 컨트롤러이니까요
공통 컨트롤러 어드바이스 만들어서 관리하는게 추후 에러가 많아질 때나 유저 컨트롤러를 의미있는 단위로 쪼개는데 더 도움이 되지 않을까요?

2024-07-12 13:14 UTC, gongdongho12 commented on src/main/java/gift/filter/JwtFilter.java
> +        Filter.super.init(filterConfig);
이미 상속받은 상태라서 
```suggestion
        super.init(filterConfig);
```
이렇게 업데이트 하는게 좋지 않을까요?

2024-07-12 13:14 UTC, gongdongho12 commented on src/main/java/gift/model/UserDTO.java
> +    }
여기서 사용한 Length는 하이버네이트 validation이라 DAO가 아니게 되서 정상동작 안하지 않나요?

2024-07-12 13:14 UTC, gongdongho12 commented on src/main/java/gift/util/ProductNameValidator.java
> +    }
이렇게 사용해주신점도 좋네요!

2024-07-12 13:14 UTC, gongdongho12 commented on src/test/java/gift/util/ProductNameValidatorTest.java
> +    }
Validator만 분리하면 확실히 테스트하기 용이하죠?

2024-07-13 03:37 UTC, Dockerel commented on src/main/java/gift/aop/TimeTraceAop.java
> +    }
아하 넵 여러 디버깅 용도로 확장 가능하군요! 추후에 한번 구현해보겠습니다! 👍

2024-07-13 03:38 UTC, Dockerel commented on src/main/java/gift/controller/ProductController.java
> +                                        @RequestParam(required = false, defaultValue = "5", value = "size") int size) {
말씀해주신대로 Pageable pageable로 한번에 받아오는 방식이 있더라구요! 해당 방식으로 개선해보았습니다~!

2024-07-13 03:40 UTC, Dockerel commented on src/main/java/gift/controller/UserController.java
> +    }
그런 것 같습니다 별도 Advice로 빼내어 수정하였습니다! 그리고 util에 너무 많은 파일이 있는 것 같아 utility, validation, constraint, advice 모두 패키지 분리도 해보았습니다!

2024-07-13 03:42 UTC, Dockerel commented on src/main/java/gift/filter/JwtFilter.java
> +        Filter.super.init(filterConfig);
해당 메서드가 디폴트 메서드라 Filter.super.init() 방식으로만 불러올 수 있지 않나요?? super.init() 방식으로는 오류가 발생합니다...

2024-07-13 03:43 UTC, Dockerel commented on src/main/java/gift/model/UserDTO.java
> +    }
아하 넵 자동으로 getter/setter를 만들다 보니 저렇게 만들어진 것 같습니다! 전부 수정 완료하였스빈다!

2024-07-13 03:44 UTC, Dockerel commented on src/main/java/gift/util/ProductNameValidator.java
> +    }
감사합니다 😊

2024-07-13 03:45 UTC, Dockerel commented on src/test/java/gift/util/ProductNameValidatorTest.java
> +    }
넵 확실히 깔끔하게 테스팅 할 수 있었습니다~!

2024-07-13 08:51 UTC, gongdongho12 commented on src/main/java/gift/filter/JwtFilter.java
> +        Filter.super.init(filterConfig);
아하 제가 미처 파악을 못했군요 확인 감사합니다 :)

2024-07-13 08:54 UTC, gongdongho12 commented
@Dockerel conflict 해결도 체크해주세요

2024-07-13 12:41 UTC, Dockerel commented on README.md
> +위와 같은 방식으로 참조 가능하게...
처음에 wishlist - product에 대해 OneToMany로 구현하였으나 이때 다수의 user에 대해 wishlist가 관리가 되지 않는다는 문제점을 발견하였습니다. 이에 product - product_wishlist - wishlist 세 테이블에 대해 ManyToMany 방식으로 구현해보았습니다! 새로운 기능으로는

1. productId 지정해서 wishlist 삭제 가능
2. 여러 user의 wishlist 동시에 관리(저장) 가능
3. 특정 상품을 담은 유저들을 모두 볼 수 있음

이 있습니다!

2024-07-13 13:02 UTC, Dockerel commented
@gongdongho12 코드 리펙터링 및 conflict도 모두 해결했습니다~!

2024-07-13 14:00 UTC, gongdongho12 commented on README.md
> +위와 같은 방식으로 참조 가능하게...
지금의 경우에는 테이블 구조에서 N:M이아니라
member 1 : N wishlist
라서 위시리스트에 member_id가 하나면 되지 않나요?

2024-07-13 14:21 UTC, Dockerel commented on README.md
> +위와 같은 방식으로 참조 가능하게...
아하 넵! 여러 user의 wishlist를 동시에 관리가 되지 않는다는 말의 의미가 잘못 전달된 것 같습니다. 이전 모델에서의 경우 product가 1, 2, 3이 있고 user1의 wishlist1이 있고 user2의 wishlist2가 있다고 가정했을 때 wishlist1에 product 1, 2를 넣고나서 wishlist2에 product 2,3을 넣으면 wishlist1에서 product2가 사라지는 오류가 있었습니다. 이를 위해 product-wishlist간에 manyToMany 관계를 사용하여 wishlist 하나당 1개의 user가 매핑되고 해당 wishlist에 여러 product가 들어가는 구조로 만들었습니다!

2024-07-14 17:35 UTC, gongdongho12 commented on README.md
> +위와 같은 방식으로 참조 가능하게...
아하 wishlist 단위별로 여러 상품 개념을 도입하셨군요
조금 더 복잡하게 트라이해보려는 시도 좋습니다
어려웠을 건데 좋은 반영 👍🏼

2024-07-14 17:36 UTC, merged