전남대 BE_안재영_3주차 과제(2단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #339
Opened 2024-07-12 08:14 UTC by ajy9851

2단계 과제 요구 사항을 제대로 이해한게 맞는지 모르겠습니다. 외래키를 엔티티에 명시적으로 표현했습니다.

2024-07-12 13:21 UTC, gunom requested changes
안녕하세요 재영님! 2단계 수고하셨습니다! 연관관계가 들어가기 시작하면 머리가 바로 아파지죠ㅎㅎ 단방향, 양방향, N + 1 등 고려하고 공부할게 점점 많아지실 겁니다! 포기하지 마시고 어떤 방법이 맞는가보다 어떤 상황에 어떤 방법이 좋을 지 고민해보시면 좋을 거 같습니다! 3단계도 화이팅입니다!

2024-07-12 13:21 UTC, gunom commented on src/main/java/gift/model/WishList.java
> +    @JoinColumn(name = "member_id", foreignKey = @ForeignKey(name = "fk_wish_member_id_ref_member_id"))
연관관계 설정 잘해주셨습니다. JPA는 연관관계가 존재할 시 해당 엔티티를 가져오면서 매핑된 엔티티에 대한 쿼리도 함께 날리므로 불필요한 쿼리가 발생하게 됩니다. 이로 인해 N + 1 문제라 불리는 성능문제가 발생할 수 있으므로 해결방법을 찾아서 적용해 보시면 좋을 거 같습니다 :)

여담으로 foreignKey는 실무에서는 자주 사용하지 않습니다.. 이유는 DBA가 DB를 관리하기 매우 까다로워지기 때문이죠. 또한 락으로 인해 DB 성능 저하의 이슈도 있기에 실무에서는 그리 잘 사용하지 않는다는 어두운 진실,,, 말씀드립니다ㅎㅎ

2024-07-12 13:21 UTC, gunom commented on src/main/java/gift/model/WishList.java
> +        if (this.member == null) {
해당 로직이 들어가는 이유가 있을까요? 기본 생성자를 사용해 생성시키면 다른 필드는 어떻게 될까요?

2024-07-12 13:21 UTC, gunom commented on src/main/java/gift/service/WishListService.java
> +        return wishListRepository.findByMember(member);
현재 Lazy Loading을 하시지 않았고, 양방향 매핑을 하셨다면 member를 꺼내오면서 WishList도 함께 이미 존재할 것입니다. member에서 wishList 필드를 꺼내오는 것도 가능하겠지요? 하지만 그렇게 되었을 때 WishListService에서는 WishListRepository가 아닌 MemberRepository에 의존하게 되는 상황이 생길 수 있습니다. Lazy Loading을 쓰지 않을 때 발생할 수 있는 성능 이슈와, 의존성이 복잡해질 수 있는 상황을 생각해보시면서 양방향 매핑에 대해서도 양방향과 단방향의 선택을 상황에 따라 고민해보면 좋을 거 같아요!

2024-07-14 08:57 UTC, gunom commented
컨플릭 해결 부탁드립니다~

2024-07-14 08:57 UTC, ajy9851 commented on src/main/java/gift/service/WishListService.java
> +        return wishListRepository.findByMember(member);
해당 부분 개념 조금 더 공부해보겠습니다!

2024-07-14 09:00 UTC, ajy9851 commented
> 컨플릭 해결 부탁드립니다~

완료하였습니다!

2024-07-14 09:12 UTC, gunom approved these changes

2024-07-14 09:12 UTC, merged