강원대_BE 안승환 3주차 과제(2, 3단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #340
Opened 2024-07-12 08:15 UTC by Awhn

요구사항을 확인해보니 2단계 내용이 1단계 구현한 것에 반영이 되어 있는 것 같아 부득이하게 3단계에 진행한 내용을 함께 올립니다.
우선 1단계에서의 수정 사항은 다음과 같습니다.
1. wishlist 칼럼 numOfProduct -> count_product
2. MemberService에서 login과 이메일 검증을 분리

또한 3단계에서 요구한 페이지네이션을 Spring Data JPA의 Pageable을 통해서 구현하였습니다. Product, Wishlist, Product에 대한 관리자 페이지에서 페이지네이션을 사용할 수 있습니다.

2024-07-13 01:38 UTC, jaymarystella requested changes
안녕하세요.
구현하느라 고생많으셨어요.
코멘트 몇가지 남겼는데 확인 부탁드립니다.

2024-07-13 01:38 UTC, jaymarystella commented on src/main/java/gift/controller/ProductController.java
> +        headers.add("X-Page-Size", String.valueOf(productPage.getSize()));
페이징 정보를 헤더에 넣어서 내리시는 이유가 있으실까요?

2024-07-13 01:38 UTC, jaymarystella commented on src/main/java/gift/entity/Wishlist.java
> +    private int count_product;
👍🏼

2024-07-13 01:38 UTC, jaymarystella commented on src/main/java/gift/entity/Wishlist.java
> +    private int count_product;
앗 이부분은 db컬럼명을 의도한거고 실제 애플리케이션 코드내에서는 스타일가이드에 따라 camel case로 다시 고쳐주세요.

2024-07-13 01:38 UTC, jaymarystella commented on src/main/java/gift/service/ProductService.java
> +        List<Product> pageContent = allProducts.subList(start, end);
> 또한 3단계에서 요구한 페이지네이션을 Spring Data JPA의 Pageable을 통해서 구현하였습니다. Product, Wishlist, Product에 대한 관리자 페이지에서 페이지네이션을 사용할 수 있습니다.

의도한 페이징이 아닌거같습니다. 테이블을 전부 메모리에 로드하고 코드에서 자르고있는데 이렇게하면 필요한 데이터만 가져오는 의도와는 거리가 있을거같아요. 조회시에도 요청한 페이지만큼 가져오는 방식을 찾아보시면 좋을것같습니다.

2024-07-13 01:38 UTC, jaymarystella commented on src/main/java/gift/service/WishlistService.java
> +        List<Wishlist> allWishlist = wishlistRepository.findByMember_id(member_id);
이 부분도 마찬가지입니다.

2024-07-13 07:04 UTC, Awhn commented on src/main/java/gift/service/ProductService.java
> +        List<Product> pageContent = allProducts.subList(start, end);
넵, 페이지 번호와 크기를 통해 시작과 끝 id를 얻고, id에 대해서 select .. between을 사용하여 필요한 만큼만 수정하도록 변경하였습니다. 오히려 코드가 단순해지네요.

2024-07-13 07:05 UTC, Awhn commented on src/main/java/gift/entity/Wishlist.java
> +    private int count_product;
넵, 수정하였습니다. 필드 변수 명과 칼럼 이름이 일치해야한다고 생각했습니다.

2024-07-13 07:12 UTC, Awhn commented on src/main/java/gift/controller/ProductController.java
> +        headers.add("X-Page-Size", String.valueOf(productPage.getSize()));
일단 다른 자료를 [참고한 내용](https://www.baeldung.com/spring-data-jpa-convert-list-page)이었고, 사용자 입장에서 현재 페이징 정보를 알 필요가 있고, 부가적인 정보기 때문에 헤더에 포함되는 게 맞다고 생각하여 작성하였습니다.

2024-07-14 11:53 UTC, jaymarystella commented on src/main/java/gift/controller/ProductController.java
> +        headers.add("X-Page-Size", String.valueOf(productPage.getSize()));
정의하기 나름이겠지만 페이징결과정보는 부가정보가 아니라 주요정보라고 생각합니다. 보통은 본문에 넣는걸 선호하는데 정답은 없으니 일단 알겠습니다.

2024-07-14 11:55 UTC, jaymarystella approved these changes
안녕하세요 리뷰반영하느라 고생많으셨습니다.
이만 머지할게요. 다음 주차에뵙겠습니다.

2024-07-14 11:55 UTC, merged