부산대 BE_박혜연 3주차 과제 (3단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #344
Opened 2024-07-12 08:25 UTC by hyyyh0x

지금 sorting이 안되는 것 같습니다. 시간이 얼마 남지 않아 일단 제출하지만 추후 이유를 찾아보도록 하겠습니다.

2024-07-12 09:51 UTC, hyyyh0x commented
sort수정 완료했습니다! sortBy와 sortDirection위치가 바꿔져있었습니다.

2024-07-12 14:07 UTC, yoo-jaein requested changes
step3 고생하셨어요!
리뷰 코멘트 확인 부탁드립니다.

2024-07-12 14:07 UTC, deactivated-user commented on src/main/java/gift/product/ProductController.java
> +        @RequestParam(value = "page", required = false, defaultValue = "0") int page,
required, defaultValue 👍

2024-07-12 14:07 UTC, deactivated-user commented on src/main/java/gift/product/ProductController.java
> +        Page<ProductDTO> paging = productService.getAllProducts(page, size, sortBy, sortDirection);
만약 클라이언트가 너무 큰 size로 요청하는 경우를 대비해서 최대 사이즈 제한을 걸어두는 것도 좋겠네요.

2024-07-12 14:07 UTC, deactivated-user commented on src/main/java/gift/product/ProductService.java
> +        List<ProductDTO> products = productPage.stream()
DTO로 반환하는 과정이 좋네요!

2024-07-12 14:07 UTC, deactivated-user commented on src/main/java/gift/product/ProductService.java
> +        List<ProductDTO> products = productPage.stream()
stream 👍

2024-07-12 14:07 UTC, yoo-jaein commented on src/main/java/gift/wishlist/WishListService.java
> +        List<WishListDTO> pageContent = wishLists.subList(start, end);
서비스 로직에서 페이지네이션 로직을 직접 구현하셨네요!
잘 구현하셨지만 이 방식은 모든 데이터를 메모리에 로드한 후 페이징 처리를 하기 때문에 데이터의 양이 매우 많을 때 비효율적입니다.
데이터베이스(repository) 레벨에서 페이징을 수행하도록 변경해주세요!

2024-07-12 14:07 UTC, yoo-jaein commented on src/main/java/gift/wishlist/WishListService.java
> +            sortBy = "id";
상수를 사용하는 것이 좋습니다.
### 예시
```java
private static final String DEFAULT_SORT_BY = "id";
```

2024-07-12 14:07 UTC, yoo-jaein commented on src/main/java/gift/wishlist/WishListService.java
> +        if (sortDirection.equals("desc") || sortDirection.equals("내림차순")) {
sortDirection String 값에 대한 검증은 Request에 대한 검증이니 컨트롤러 레이어에서 수행하고,
서비스 레이어에서는 전달된 값을 받아 바로 사용할 수 있으면 좋겠어요.

sortDirection을 Enum으로 써서 타입 세이프한 코드를 작성할 수도 있을 것 같습니다!
```java
public enum SortDirection {
    ASC, DESC;
    ....
}
```

2024-07-12 14:07 UTC, yoo-jaein commented on src/main/java/gift/wishlist/WishListService.java
> +        List<WishListDTO> pageContent = wishLists.subList(start, end);
### 예시
```java
// WishListRepository
Page<WishList> findByUser(User user, Pageable pageable);
```

2024-07-13 05:10 UTC, hyyyh0x commented
수정 완료했습니다!
enum을 제대로 사용했는지 모르겠네요.
컨트롤러 레이어에서 수행하는 것으로 코드를 수정하니 중복되는 코드가 조금씩 생기는데, 이정도는 괜찮은지 아니면 개선할 좋은 방법이 따로 있는지 궁금합니다!

2024-07-13 05:39 UTC, yoo-jaein requested changes
리뷰 반영된 것 확인했습니다!
컨트롤러 중복 코드는 별도의 유틸 클래스로 빼보면 좋을 것 같습니다 :)

2024-07-13 07:46 UTC, hyyyh0x commented
유틸 클래스로 분리 완료했습니다!

궁금한 점이 몇가지 생겨 질문드립니다.

1. Util class는 static을 사용한다는 말이 있어서 static을 사용하고 바로 접근해서 사용했는데, 이 방법이 맞는지, 맞다면 제가 저번 주차에 작성한 JwtUtil 클래스도 static을 사용해서 메서드들을 바꿔주는 것이 좋을지 궁금합니다.

2. WIshListService에서 다른 서비스들과 달리 ProductService와 UserService에 접근하고 있는데 이렇게 사용해도 괜찮은지 궁금합니다.

3. @Autowired 대신 생성자를 만드는 것을 추천한다고 저번 리뷰에서 말씀해주신 것 같은데, Test코드에서도 사용하지 않는 것을 추천하시는지 궁금합니다! 이유도 궁금합니다.

4. Product와 User 클래스에서 wishes가 

> Field 'wishes' may be 'final'

 라며 노란 줄이 뜨는데, 왜 다른 것들과 달리 이것만 이렇게 뜨는지 궁금합니다! 그리고 final을 사용하는 것이 좋은지, 그대로 두는 것이 나은지 궁금합니다. "수정될 수 없기 때문에 초기화 값은 필수적입니다."라는 글을 봤는데, 이것 때문에 권장하는 걸까요?

5. WishListDTO에서 userId가 

> Private field 'userId' is assigned but never accessed Field can be converted to a local variable

 이라고 뜨면서 경고가 뜨는데, get메시지를 받을 때 같이 출력이 되도록 사용하고 있으면 무시해도 괜찮은 경고인지 궁금합니다.

6. 요구사항에 없어 저는 api화면만 하고 있지만, 1주차에서 

> "실제로 서버 개발자가 관리자 화면을 개발하는 경우도 많다. HTTP API만 개발할 것이라는 고정 관념을 버린다."

 라는 말이 있었습니다. 과제를 진행하며 시간이 나면 화면도 구현하고 싶었는데 조금 어렵다 느꼈습니다. 실제로 근무할 때 api가 아닌 화면을 개발하는 경우가 많은 편인가요?

질문을 너무 한번에 드려서 죄송합니다. 왜 꼭 지나고 나서야 궁금한 점이 생기는지 모르겠습니다. 답변 주시면 감사하겠습니다! 수정사항 중 부족한 부분이 있으면 또 고치겠습니다.

2024-07-14 07:48 UTC, yoo-jaein approved these changes
리뷰 반영된 것 확인했습니다!
3주차 고생 많으셨습니다.
머지하겠습니다 :)

질문에 대한 답변은 길어질 것 같아 별도 코멘트로 남기겠습니다!

2024-07-14 07:48 UTC, merged

2024-07-14 08:23 UTC, yoo-jaein commented
### 질문 1
Util class는 static을 사용한다는 말이 있어서 static을 사용하고 바로 접근해서 사용했는데, 이 방법이 맞는지, 맞다면 제가 저번 주차에 작성한 JwtUtil 클래스도 static을 사용해서 메서드들을 바꿔주는 것이 좋을지 궁금합니다.

### 답변
일반적으로 유틸 클래스에 static을 사용하긴 하지만 모든 상황에 적합한 것은 아닙니다. 

static 유틸 클래스는 주로 이런 상황에서 씁니다.
1. 입력에 대해 단순히 계산하거나 변환하는 작업 (예: 문자열 조작, 날짜 형식 변환, 수식 계산)
2. 애플리케이션 전반에 걸쳐 자주 사용되는 헬퍼 메서드 (예: 파일 입출력, 로깅, 암호화/복호화)
3. 관련된 상수들을 한 곳에 모아 관리 (예: 설정 값, 에러 코드)
4. 상속이나 오버라이딩이 필요 없음
5. 객체 생성 비용을 줄이고 싶음

그렇지만 이런 상황에서는 일반 클래스를 사용하는 것이 더 적합할 수 있습니다.
1. 외부 서비스나 설정값이 필요해서 의존성 주입을 해야하는 경우
2. 인스턴스 별 상태를 관리해야 하는 경우 (static의 필드와 메서드는 모든 인스턴스가 공유합니다)

JwtUtil은 secretKey, expiration 을 설정 파일에서 불러와야 하기 때문에 일반 클래스를 사용하는 것이 적합한 것 같고, PageUtil은 단순 매핑 작업만 있기 때문에 static을 사용하는 것이 적합한 것 같습니다.

2024-07-14 08:23 UTC, yoo-jaein commented
### 질문 2
WIshListService에서 다른 서비스들과 달리 ProductService와 UserService에 접근하고 있는데 이렇게 사용해도 괜찮은지 궁금합니다.

### 답변
네, WishListService가 Product와 User에 관한 로직을 직접 처리하지 않고, 해당 서비스들에 위임하는 것은 관심사가 잘 분리되어있다는 것이기 때문에 자연스럽고 좋은 접근입니다.

다만 WishListService가 ProductService와 UserService를 사용하는 동시에, 이들 서비스가 WishListService를 사용하지 않도록 주의해야 합니다. (순환 의존성은 피해야 합니다.)

2024-07-14 08:23 UTC, yoo-jaein commented
### 질문 3
```@Autowired``` 대신 생성자를 만드는 것을 추천한다고 저번 리뷰에서 말씀해주신 것 같은데, Test코드에서도 사용하지 않는 것을 추천하시는지 궁금합니다! 이유도 궁금합니다.

### 답변
```@Autowired```를 쓰면 빠르게 코드를 작성할 수 있지만, 테스트 코드에서도 ```@Autowired``` 대신 생성자 주입 방식을 사용하는 것이 좋습니다. 
테스트마다 다른 mock 객체나 stub을 주입할 수 있어 다양한 상황을 테스트할 수 있고, 클래스가 필요로 하는 의존성을 명확히 확인할 수 있습니다.

개인적으로 간단한 테스트에는 ```@Autowired```를 작성하게 되는 것 같아요.

2024-07-14 08:23 UTC, yoo-jaein commented
### 질문 4
Product와 User 클래스에서 wishes가 ```Field 'wishes' may be 'final'``` 라며 노란 줄이 뜨는데, 왜 다른 것들과 달리 이것만 이렇게 뜨는지 궁금합니다! 그리고 final을 사용하는 것이 좋은지, 그대로 두는 것이 나은지 궁금합니다. "수정될 수 없기 때문에 초기화 값은 필수적입니다."라는 글을 봤는데, 이것 때문에 권장하는 걸까요?

### 답변
IntelliJ가 wishes 필드가 초기화된 다음 재할당되지 않는 것을 감지하고 불변성을 명시적으로 표현하기 위해 final을 제안하는 것입니다. 
(컬렉션의 내용은 add, remove로 변경 가능하지만 참조가 바뀌지는 않음)

그렇지만 JPA에서 일부 설정에 따라 final 필드에 접근할 때 문제가 발생할 수 있습니다.
final을 붙여 테스트 해보고, 이상이 없다면 final을 붙여 불변성을 표현하는 방법도 괜찮을 것 같습니다. 그대로 두어도 문제는 없습니다.

2024-07-14 08:24 UTC, yoo-jaein commented
### 질문 5
WishListDTO에서 userId가
```Private field 'userId' is assigned but never accessed Field can be converted to a local variable``` 이라고 뜨면서 경고가 뜨는데, get메시지를 받을 때 같이 출력이 되도록 사용하고 있으면 무시해도 괜찮은 경고인지 궁금합니다.

### 답변
userId 필드가 할당은 되지만 직접 접근되지 않고 있다는 의미입니다.
해당 필드가 실제로 필요한지 확인하고 사용되지 않는다면 제거하거나 getter 메서드를 만드는 방법으로 경고를 해결할 수 있습니다.
같이 출력되도록 하고 있다고 하셨는데 println으로 출력하는 것은 필드에 직접 접근하는 것이 아니기 때문에 toString()을 override 하는 방향으로 경고를 해결할 수도 있을 것 같네요.

2024-07-14 08:24 UTC, yoo-jaein commented
### 질문 6
요구사항에 없어 저는 api화면만 하고 있지만, 1주차에서
"실제로 서버 개발자가 관리자 화면을 개발하는 경우도 많다. HTTP API만 개발할 것이라는 고정 관념을 버린다."

라는 말이 있었습니다. 과제를 진행하며 시간이 나면 화면도 구현하고 싶었는데 조금 어렵다 느꼈습니다. 실제로 근무할 때 api가 아닌 화면을 개발하는 경우가 많은 편인가요?

### 답변
부서에 따라 정말 달라요.
대신 타임리프는 거의 사용하지 않고 react나 vue를 사용합니다. 

서버 + 프론트로 완전 풀스택 개발하는 경우가 있고, 서버 위주 + 관리자 페이지 프론트 (9:1 정도로) 약간 풀스택 개발하는 경우가 있어요. 아예 서버 개발만 하는 곳도 있구요.
저는 예전에는 서버 + 프론트 둘다 하다가 지금은 9.5:0.5 로 하고 있습니다.

2024-07-14 08:27 UTC, yoo-jaein commented
혜연님 질문에 여러모로 생각할 거리가 많아서 답변을 오랫동안 작성했네요
좋은 질문들 감사합니다!
앞으로도 질문 많이 많이 해주세요 :D