전남대 BE_모아림 3주차 과제 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #352
Opened 2024-07-12 08:37 UTC by ariimo

2024-07-12 13:49 UTC, dc-choi requested changes
안녕하세요~! 아림님~! step2 과제 확인하였습니다!

혹시 `@OneToMany`에 대해서 어떻게 생각하시는지 궁금합니다!

2024-07-12 18:38 UTC, ariimo commented
> 안녕하세요~! 아림님~! step2 과제 확인하였습니다!
> 
> 혹시 `@OneToMany`에 대해서 어떻게 생각하시는지 궁금합니다!

설계를 진행하며 @OneToMany 를 고려하지 않은 것은 아닙니다. 공부를 진행하며 무조건적인 양방향 관계는 복잡성을 증가시킨다는 것을 알게되었습니다. 또, 저의 코드에선 Product와 Member 객체가 Wish 객체를 참조하지 않기에 @OneToMany 를 굳이 추가할 필요성을 느끼지 못했습니다!

2024-07-12 18:38 UTC, ariimo commented
> > 안녕하세요~! 아림님~! step2 과제 확인하였습니다!
> > 혹시 `@OneToMany`에 대해서 어떻게 생각하시는지 궁금합니다!
> 
안녕하세요 멘토님! 
설계를 진행하며 @OneToMany 를 고려하지 않은 것은 아닙니다. 공부를 진행하며 무조건적인 양방향 관계는 복잡성을 증가시킨다는 것을 알게되었습니다. 또, 저의 코드에선 Product와 Member 객체가 Wish 객체를 참조하지 않기에 @OneToMany 를 굳이 추가할 필요성을 느끼지 못했습니다!

2024-07-12 19:06 UTC, ariimo commented
음.. step1까지만 해도 잘 작동하던 WishControllerTest에서 계속 원인 모를 오류가 발생합니다. 
Postman으로 직접 테스트해 본 결과(상품 추가 > 회원가입 > 로그인 > Wish 추가 > Wish list 확인) Wishlist 관련 로직이 잘 동작한다는 것은 확인할 수 있었습니다. 
따라서 제가 작성한 WishControllerTest가 문제라는 건데, 작성해 둔 테스트를 아무리 뜯어봐도 제 눈에는 논리적 결함이 보이지 않습니다.. 아마 JPA나 Spring 테스트에 대한 충분한 이해 없이 제 머리에서 비롯한 논리를 따라갔기에 보이지 않는 것 같습니다... 멘토님께서 허락해 주신다면 Wish 관련 E2E 테스트는 조금 더 뒤로 미루고 싶습니다.. 호옥시 제가 참고할만한 자료가 있으시다면 리뷰와 함께 첨부해주시면 정말정말 도움이 될 것 같습니다. 항상 감사드립니다..!!

2024-07-13 01:15 UTC, dc-choi approved these changes
안녕하세요 아림님!

> 안녕하세요 멘토님! 설계를 진행하며 `@OneToMany` 를 고려하지 않은 것은 아닙니다. 공부를 진행하며 무조건적인 양방향 관계는 복잡성을 증가시킨다는 것을 알게되었습니다. 또, 저의 코드에선 Product와 Member 객체가 Wish 객체를 참조하지 않기에 `@OneToMany` 를 굳이 추가할 필요성을 느끼지 못했습니다!

이번 과제에서는 연관 관계에 대한 부분을 학습하는 과제여서 질문을 드렸었습니다! 제가 판단하기에는 아림님의 주장을 어느정도 납득할 수 있는 부분이라 생각합니다!

다만, 이번 과제에서 학습해야하는게 연관 관계인 만큼 `@OneToMany`에 대해서는 알고 계셨으면 좋겠습니다!

> 음.. step1까지만 해도 잘 작동하던 WishControllerTest에서 계속 원인 모를 오류가 발생합니다.
Postman으로 직접 테스트해 본 결과(상품 추가 > 회원가입 > 로그인 > Wish 추가 > Wish list 확인) Wishlist 관련 로직이 잘 동작한다는 것은 확인할 수 있었습니다. 따라서 제가 작성한 WishControllerTest가 문제라는 건데, 작성해 둔 테스트를 아무리 뜯어봐도 제 눈에는 논리적 결함이 보이지 않습니다.. 아마 JPA나 Spring 테스트에 대한 충분한 이해 없이 제 머리에서 비롯한 논리를 따라갔기에 보이지 않는 것 같습니다... 멘토님께서 허락해 주신다면 Wish 관련 E2E 테스트는 조금 더 뒤로 미루고 싶습니다.. 호옥시 제가 참고할만한 자료가 있으시다면 리뷰와 함께 첨부해주시면 정말정말 도움이 될 것 같습니다. 항상 감사드립니다..!!

네 뒤로 미루셔도 상관은 없습니다. Test Code에 대한 참고자료는 토스 테크리드인 재민님의 유튜브 영상을 공유드리도록 하겠습니다!

https://youtu.be/txYAmWRnbBg?si=xMHgARv2aMv2XDIv

지금은 승인하도록 하겠습니다! 바로 다음 과제를 진행해주시면 될 거 같습니다!

2024-07-13 01:15 UTC, merged