충남대 BE_정현서 3주차 과제 (3단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #353
Opened 2024-07-12 08:40 UTC by hynseoj

2024-07-14 00:11 UTC, ksy90101 requested changes
간단한 피드백을 남겼습니다~
확인해주세요~

2024-07-14 00:11 UTC, ksy90101 commented on src/main/java/gift/domain/product/controller/ProductRestController.java
> +        @RequestParam(required = false, defaultValue = "10", value = "size") int size
한번 이렇게 말고 DTO를 사용해볼수 있을까요?

2024-07-14 00:11 UTC, ksy90101 commented on src/main/java/gift/domain/wishlist/service/WishlistService.java
> +    }
이 영역이 필요한 이유가 무엇인가요?

2024-07-14 00:11 UTC, ksy90101 commented on src/main/java/gift/domain/wishlist/dao/WishlistJpaRepository.java
> +    void deleteAllByProductId(@Param("productId") Long productId);
이부분은 쿼리 없이도 가능할거 같은데요.
methodNaming으로도 충분히 가능하지 않을까요?

2024-07-15 02:39 UTC, hynseoj commented on src/main/java/gift/domain/product/controller/ProductRestController.java
> +        @RequestParam(required = false, defaultValue = "10", value = "size") int size
네 DTO를 사용하는 게 더 좋을 것 같습니다. 적용하겠습니다!

2024-07-15 02:45 UTC, hynseoj commented on src/main/java/gift/domain/wishlist/service/WishlistService.java
> +    }
User나 Product가 삭제될 때 해당 user와 product의 id를 fk로 가지고 있는 wishlist의 레코드들을 먼저 삭제해주기 위함입니다. UserService나 ProductService에서 WishlistRepository보다는 WsishlistService를 사용하는 게 좋을 것 같아서 Service 영역에 작성했습니다.
해당 기능을 Service에서 제공하지 않고 Repository 메소드를 바로 사용하도록 하는 게 좋을까요?

2024-07-15 03:00 UTC, hynseoj commented on src/main/java/gift/domain/wishlist/dao/WishlistJpaRepository.java
> +    void deleteAllByProductId(@Param("productId") Long productId);
JPA의 쿼리 메서드를 사용하면 지난 주에 말씀하셨던 N+1 문제가 발생한다고 해서 별도로 쿼리를 작성해보았습니다.

2024-07-15 04:35 UTC, ksy90101 commented on src/main/java/gift/domain/wishlist/service/WishlistService.java
> +    }
cascading을 한번 공부해보시면 어떨까요?
그럼 이러한 코드 없이 가능할거 같아요~

2024-07-15 05:50 UTC, hynseoj commented on src/main/java/gift/domain/wishlist/service/WishlistService.java
> +    }
> orphanremoval을 true로 하면 부모와 연관이 끊어진 객체가 자동으로 제거되어서 wishitem의 user를 null로 세팅하지 않고 user의 wishlist에서 wishitem을 remove하는 것만으로도 삭제된다고 하던데 이 방법 역시 이유를 모르겠지만 제대로 동작하지 않았습니다.
> 그래서 Service 계층에서 repository 메서드를 이용해서 확실하게 삭제하는 방식을 택했습니다.
> Product가 삭제될 때 역시 repository 메서드를 이용해 wishitem들을 먼저 삭제하고 product가 삭제되도록 작성해보았습니다.

User의 경우 WishItem과 양방향 연관 관계를 맺고 있고 cascading 옵션과 orphanRemoval 옵션을 설정해줬음에도 setUser를 null로 해주지 않으면 cascading이 잘 동작하지 않아 이렇게 하는 방식을 택했습니다..

그리고 Product의 경우는 WishItem과 단방향 연관 관계를 가지고 있어서 cascading을 사용할 수 없는 걸로 알고 있는데 단방향 연관 관계에서도 cascading할 수 있는 방법이 있나요?

2024-07-15 05:53 UTC, hynseoj commented
추가적으로, 여러 도메인에서 공용으로 사용하는 DTO를 사용해보는게 처음이라 지금 PageRequestDto 클래스의 패키지 경로가 적절한지 여쭤보고 싶습니다!

2024-07-15 05:55 UTC, ksy90101 commented
"Pageable"이걸 쓰면 따로 DTO를 만들지 않아도 됩니다~

2024-07-15 07:03 UTC, ksy90101 commented on src/main/java/gift/domain/wishlist/service/WishlistService.java
> +    }
앗 양방향인줄 알았습니다 ㅠㅠ
그렇다면 지금이 가장 좋은 방안일거 같아요.
혼동을 드려서 죄송해요 ㅠㅠ

2024-07-15 08:30 UTC, hynseoj commented on src/main/java/gift/domain/wishlist/service/WishlistService.java
> +    }
아닙니다! 감사합니다~

2024-07-15 08:49 UTC, ksy90101 approved these changes
고생하셨습니다~
4단계에서 봐요!

2024-07-15 08:49 UTC, merged