경북대 BE_유승욱 3주차(3단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #355
Opened 2024-07-12 08:46 UTC by yso8296

금요일 과제 마감 때문에 pr을 요청했지만 아직 수정해야할 부분이 있는 것 같아 주말동안 보완하도록 하겠습니다.

2024-07-13 15:29 UTC, khj68 commented
페이징 처리를 할 때 프론트쪽에 넘겨줘야 할 기본적인 정보들이 어떤 게 필요한지 궁금합니다.
- 만약 특정 필드로 오름차순 내림차순 정렬을 해야 한다면, 어떤 필드들이 있는지 프론트에 내려주는 것이 필요합니다.
- 정렬을 제외하고는, 총 아이템 개수, 현재 페이지 등을 함께 내려주는 것이 좋습니다
- 정확히는 프론트 개발자의 구현에 맞추어 소통을 하는 것이 필요합니다.
- 보통 총 페이지 개수를 구하기 위해 총 아이템 개수를 함께 내려주는 편입니다.

2024-07-13 15:35 UTC, khj68 requested changes
승욱님 고생 많으셨습니다!

프론트와의 소통을 한다고 생각하고, 어떤 부분이 서로 유지보수에 있어서 유리할지, 효율적일지를 고민해보시는 연습도 좋을 듯 합니다.
코멘트 남긴 page-1 적용하는 부분이 그 예시입니다.

2024-07-13 15:35 UTC, khj68 commented on src/main/java/gift/model/user/User.java
> +    @NotNull
어노테이션을 변경해주니 더 명시적이어서 좋네요 :)

2024-07-13 15:35 UTC, khj68 commented on src/main/java/gift/service/WishService.java
> +        PageRequest pageRequest = PageRequest.of(page - 1, size, Sort.by("id").descending());
page - 1 과 같은 부분은 프론트와 소통하여 값을 맞춰주는 것이 좋습니다.

서버 입장에서 첫번째 페이지가 0인 경우가 많기 때문에
프론트 측에서 요청 시마다 1을 제외하고 요청하는 것이 좀 더 서버의 정합성을 살리는 방향으로 보입니다.

2024-07-13 15:35 UTC, khj68 commented on src/test/java/gift/repository/WishRepositoryTest.java
>          assertThat(wishes).isNotNull();
테스트에서도 적절한 줄바꿈을 통해 가독성을 높여주세요 :)

2024-07-13 15:35 UTC, khj68 commented on src/main/java/gift/common/dto/PageResponse.java
> +    int totalPage
pageResponse라는 템플릿을 적용하여 전체 페이지 개수를 함께 내려주는 형태 좋습니다 :)

2024-07-14 07:00 UTC, yso8296 commented on src/main/java/gift/service/WishService.java
> +        PageRequest pageRequest = PageRequest.of(page - 1, size, Sort.by("id").descending());
백엔드의 입장에서만 생각해서 프론트 측의 입장은 생각을 안해보았던 것 같습니다! 앞으로는 이런것도 생각을 하면서 개발하겠습니다.

2024-07-14 07:00 UTC, yso8296 commented on src/test/java/gift/repository/WishRepositoryTest.java
>          assertThat(wishes).isNotNull();
참고하여 반영하겠습니다.

2024-07-14 07:24 UTC, yso8296 commented on src/main/java/gift/service/WishService.java
> +        PageRequest pageRequest = PageRequest.of(page - 1, size, Sort.by("id").descending());
추가적으로 인터넷에 @PageableDefault를 사용해서 컨트롤러에서 Pageable 객체를 받아오는 경우도 있던데, 제가 구현한 방식인 서비스 클래스에서 pageRequest를 만들어서 사용하는 것이랑 어느 것이 더 나은 방식인지 궁금합니다.

2024-07-14 07:36 UTC, yso8296 commented
피드백 내용 반영하였습니다.

2024-07-14 14:58 UTC, khj68 commented on src/main/java/gift/service/WishService.java
> +        PageRequest pageRequest = PageRequest.of(page - 1, size, Sort.by("id").descending());
일반적으로는 @PageableDefault의 명세를 활용해주시는 것을 추천드립니다.
추후 프론트 개발자와 협업을 할 때에, 서버마다 스펙이 달라지면 프론트에서도 통일성이 깨지기 때문입니다.

좋은 질문 감사합니다 :)

2024-07-14 14:58 UTC, khj68 approved these changes
승욱님, 피드백 반영된 부분 확인하였습니다.
고생 많으셨습니다 :)

2024-07-14 14:58 UTC, merged