충남대 BE_이동현 3주차 과제 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #358
Opened 2024-07-12 08:53 UTC by Thornappl2

- JPA를 적용하며 Entitiy와 DTO를 구분하여 수정하는 작업을 진행했습니다.
- 진행하던 중, convertToDTO와 convertToEntity를 통해 DTO와 Entity간 변환 작업이 필요하다는 것을 알게 되었는데, 이를 Service layer에서 구현하는 것이 맞나 의문이 듭니다.
- 테스트 작성은 아직 에러가 많이 발생하여 원인 파악 중에 있습니다.

2024-07-13 04:56 UTC, ksy90101 requested changes
고생하셨습니다~
간단한 피드백을 남겼으니 참고해주세요~
언제든 질문이 있다면 DM주세요!

2024-07-13 04:56 UTC, ksy90101 commented on src/main/java/gift/dto/ProductDTO.java
> +    private String name;
"카카오"에 대한 validation이 사라졌어요. ㅠ

2024-07-13 04:56 UTC, ksy90101 commented on src/main/java/gift/dto/ProductDTO.java
> +    private int price;
boxedType이 아니기 때문에 null이 들어올 이유가 없지 않을까요?

아울러 음수가 돌아오면 안되니 음수 validation도 처리해봐야 할거 같습니다~

2024-07-13 04:56 UTC, ksy90101 commented on src/main/java/gift/dto/WishDTO.java
> +    private Long productId;
여기도 Validation을 해보면 어떨까요?

2024-07-13 04:56 UTC, ksy90101 commented on src/main/java/gift/model/Wish.java
> -
실제 schema.sql과 여기에 정의내리신 Table name이 안맞아요!

2024-07-13 04:56 UTC, ksy90101 commented on src/main/java/gift/model/Wish.java
>      private Product product;
현재 조회할때 N+1 문제가 발생할거 같습니다.

한번 N+1문제가 무엇인지 찾아보고, N+1 문제를 해결해보면 어떨까요?

2024-07-15 01:03 UTC, Thornappl2 commented on src/main/java/gift/dto/ProductDTO.java
> +    private String name;
수정했습니다.

2024-07-15 01:18 UTC, Thornappl2 commented on src/main/java/gift/dto/ProductDTO.java
> +    private int price;
확인했습니다.

2024-07-15 01:50 UTC, Thornappl2 commented on src/main/java/gift/dto/WishDTO.java
> +    private Long productId;
확인했습니다. NotNull 정도만 처리하면 될까요?

2024-07-15 01:54 UTC, Thornappl2 commented on src/main/java/gift/model/Wish.java
> -
nextstep에 있는대로 table name을 수정하며 schema.sql은 수정하지 않았었네요. 수정했습니다.

2024-07-15 02:22 UTC, Thornappl2 commented on src/main/java/gift/model/Wish.java
>      private Product product;
JPQL 페치 조인을 통해 해결하였습니다.

2024-07-15 04:21 UTC, ksy90101 commented on src/main/java/gift/dto/WishDTO.java
> +    private Long productId;
넹~

2024-07-15 04:21 UTC, ksy90101 approved these changes
고생하셨습니다~
3단계에서 뵐게요~

2024-07-15 04:21 UTC, merged