전남대 BE_이장안_3주차 과제(1단계, 2단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #360
Opened 2024-07-12 08:55 UTC by lja3723

2024-07-13 01:39 UTC, gunom requested changes
안녕하세요 장안님! JPA와 테스트가 어려워 늦어질 수 있다고 생각합니다! 너무 걱정하지 마시고 리뷰 읽어보시고 반영해서 3단계도 화이팅입니다!

2024-07-13 01:39 UTC, gunom commented on src/main/java/gift/domain/entity/Member.java
> +    protected Member() {
👍

2024-07-13 01:39 UTC, gunom commented on src/main/java/gift/domain/repository/ProductRepository.java
> +    Optional<Product> findByContents(ProductRequest request);
쿼리를 안쓰고도 만들 수 JPA 메소드로 만들수 있을 거 같은데 쿼리를 사용하신 이유가 있을까요? 또 이미 등록된 상품인지 체크하는 방법이 이름, 가격, 이미지 링크로 검사하는 것이 실제 비즈니스 환경에서 사용할 일이 많을지도 고민해보면 좋을 거 같아요 :)

2024-07-13 01:39 UTC, gunom commented on src/main/java/gift/domain/repository/old/OldMemberRepository.java
> +@Deprecated
어차피 git으로 버전관리를 하고 있으니 안쓰는건 지워도 될 거 같아요~

2024-07-13 01:39 UTC, gunom commented on src/main/java/gift/global/DataInitializer.java
> +    public void insertInitialData(ProductRepository productRepository, MemberRepository memberRepository, WishRepository wishRepository) {
👍

2024-07-13 01:39 UTC, gunom commented on src/main/java/gift/domain/service/WishService.java
>      private final ProductRepository productRepository;
될 수 있으면 하나의 도메인에서만 사용되는 것을 추천드립니다! WishRepository는 WishService에서만 ProductRepository는 ProductService만 참조하게 만들어서 사용하면, 각각 어떤 데이터가 어디서 변경되는지 추적하기도 용이하고 책임을 명확히 구분할 수 있습니다. 따라서 여기선 ProductService를 참조하여 사용하는 것이 더 좋을 거 같습니다!

2024-07-13 01:39 UTC, gunom commented on src/main/java/gift/domain/service/WishService.java
> +    protected Product getProductByIdOrThrow(Long productId) {
이 메소드가 Product서비스에서 존재해야겠죠?

2024-07-13 01:39 UTC, gunom commented on src/main/java/gift/domain/service/WishService.java
> +    @Transactional(readOnly = true)
트랜잭션 사용 좋습니다! readOnly를 왜 사용하는지까지 공부하고 그게 영속성과 어떤 작용을 하는지도 공부하면 좋을 거 같아요 👍

2024-07-13 07:45 UTC, lja3723 reviewed
리뷰를 반영하여 다시 PR 보내드립니다. 리뷰에 대한 답변 및 질문 드렸는데, 확인해보시고 처리 & 머지해주시면 감사하겠습니다 :)

2024-07-13 07:45 UTC, lja3723 commented on src/main/java/gift/domain/repository/ProductRepository.java
> +    Optional<Product> findByContents(ProductRequest request);
1. 쿼리를 안쓰고도 JPA 메소드로 만들수 있을 거 같은데 쿼리를 사용하신 이유가 있을까요? 
    - 처음에 그렇게 시도했다가 아래의 특징들이 두드러지는 것 같아 지웠는데, 그것들은
        1. 메서드 시그니처가 `Optional<Product> findByNameAndPriceAndImageUrl(String name, Integer price, String imageUrl)`로 너무 길어짐 -> 메서드의 의도를 한눈에 파악하기 어려움
        2. 메서드 시그니처의 파라미터가 3개`(String name, Integer price, String imageUrl)`여서 인터페이스 사용자 입장에서 번거로워짐
            ```java
            //메서드 사용 예시 (너무 길어집니다....)
            //이미 존재하는 상품 등록 시도시 예외 발생
            productRepository.findByNameAndPriceAndImageUrl(requestDto.name(), requestDto.price(), requestDto.imageUrl()).ifPresent((p) -> {
                throw new ProductAlreadyExistsException();});
            ```
        3. `ProductRequest` DTO가 곧 Product의 내용(컨텐츠)과 일치, 즉 내용 그자체로 취급 가능한데, DTO의 필드를 하나하나 풀어서 메서드에 넣어주는 것보다 DTO 그 자체를 넘겨주면 의미도 명확하고 수정(메서드 시그니처 변경)에 닫혀있을 수 있음
    - 하지만 `@Query`를 이용해 SQL을 직접 작성하는 방식은 Product가 변경될 때마다 쿼리를 바꿔줘야 하므로 분명 단점이 있을 것 같습니다. `@Query`의 사용은 무조건 지양해야 하는 걸까요?

---

2. 이미 등록된 상품인지 체크하는 방법이 이름, 가격, 이미지 링크로 검사하는 것이 실제 비즈니스 환경에서 사용할 일이 많을까요?
    - 콘텐츠가 모두 동일하고 id만 다른 경우를 허용하면 시스템 사용에 있어 혼란스러울 수 있을 것 같아 그런 경우가 발생하지 않도록 하는 것이 자연스럽다고 생각했습니다.
    - 그런데 다시 생각해보니 상품 이름 정도만 `unique` 조건을 줘도 괜찮을 것 같다는 생각이 듭니다. 실제 현업에서는 주로 어떤 제약을 채택하는지 궁금합니다!

2024-07-13 07:45 UTC, lja3723 commented on src/main/java/gift/domain/repository/old/OldMemberRepository.java
> +@Deprecated
알겠습니다!

2024-07-13 07:45 UTC, lja3723 commented on src/main/java/gift/domain/service/WishService.java
> +    @Transactional(readOnly = true)
공부해보겠습니다! 감사합니다

2024-07-13 07:45 UTC, lja3723 commented on src/main/java/gift/domain/service/WishService.java
>      private final ProductRepository productRepository;
반영하겠습니다!

2024-07-13 07:45 UTC, lja3723 commented on src/main/java/gift/domain/service/WishService.java
> +    protected Product getProductByIdOrThrow(Long productId) {
반영하겠습니다!

2024-07-14 08:55 UTC, gunom commented
1. 우선 @Query는 무조건 지양대상은 아닙니다. join이 지나치게 많이 필요하거나 fetch join이 필요한 경우, 사용할 수 있습니다. 그러나 String으로 직접 작성하는 한계로 인해 실수와 에러의 원인이 되기도 합니다! 그렇기 때문에 JDSL이라는 쿼리를 만들어주는 다른 도구를 사용하기도 합니다. 제일 유명한건 QueryDSL이겠네요 :)

2. 실무에서는 스트링에 대해서 중복에 대한 검사는 크게 하지 않습니다. 1번과 같은 연유로 스트링은 실수가 발생할 이유가 다분하기 때문입니다. 무조건 코드적으로 해결보다는 운영 측의 꼼꼼함 확인 프로세스를 통해서 해결하는게 오히려 손 쉬울 때도 있습니다

2024-07-14 08:55 UTC, gunom approved these changes

2024-07-14 08:55 UTC, merged