충남대 BE_송민주 3주차 과제 (3단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #368
Opened 2024-07-12 10:09 UTC by mingjuu

요구 기능 사항을 충족하였습니다.
남은 시간동안 setter와 getter를 안쓰는 코드로 바꿔보겠습니다

2024-07-12 15:09 UTC, asebn1 requested changes
민주님 안녕하세요~
3단계까지 빠르게 구현해주셨네요 👍 
setter 부분과 0~2단계 함께 코멘트 드린 부분도 함께 개선해주세요
이번 주차도 달려봅시다! 화이팅 🔥🔥

2024-07-12 15:09 UTC, asebn1 commented on src/main/java/gift/controller/ProductController.java
> +        Pageable pageable = PageRequest.of(page, size, Sort.by(direction, sort[0]));
비즈니스 로직은 서비스에서 수행해볼까요?

2024-07-12 15:09 UTC, asebn1 commented on src/main/java/gift/controller/WishController.java
> +import org.springframework.web.bind.annotation.*;
import가 계속 `*`로 받고있어요

2024-07-12 15:15 UTC, asebn1 requested changes

2024-07-12 15:15 UTC, asebn1 commented on README.md
> +- [x] 상품과 위시 리스트 보기에 페이지네이션을 구현
조금 더 자세하게 작성해보는 연습도 좋을 것 같아요 :)

2024-07-12 15:15 UTC, asebn1 commented on src/main/java/gift/dto/ProductDTO.java
> +    @NotBlank(message = "상품 이름은 필수 입력 사항입니다.")
service, controller를 위한 dto를 따로 관리해볼까요?

- https://umbum.dev/1206/
- https://tecoble.techcourse.co.kr/post/2021-04-25-dto-layer-scope/

2024-07-12 15:15 UTC, asebn1 commented on src/main/java/gift/controller/WishController.java
> +    }
상태코드를 포함해서 반환해볼까요?

2024-07-12 15:15 UTC, asebn1 commented on src/main/java/gift/resolver/LoginMemberArgumentResolver.java
> +    @Autowired
생성자주입 시 `@Autowired`는 명시적으로 작성해주는 것보다 생략하는 것이 자연스럽습니다

2024-07-12 15:15 UTC, asebn1 commented on src/main/java/gift/util/JwtUtil.java
> +    }
현재 사용하는 곳이 있나요?

2024-07-13 04:23 UTC, mingjuu commented on src/main/java/gift/controller/ProductController.java
> +        Pageable pageable = PageRequest.of(page, size, Sort.by(direction, sort[0]));
넵 알겠습니다! service로 해당 로직을 옮겨보겠습니다

2024-07-13 04:26 UTC, mingjuu commented on src/main/java/gift/controller/WishController.java
> +import org.springframework.web.bind.annotation.*;
인텔리제이 단축어로 로드할 때 바뀌는 것 같습니다. 앞으로 더 주의해서 import 하겠습니다!

2024-07-13 04:26 UTC, mingjuu commented on README.md
> +- [x] 상품과 위시 리스트 보기에 페이지네이션을 구현
넵 알겠습니다!

2024-07-13 04:31 UTC, mingjuu commented on src/main/java/gift/controller/WishController.java
> +    }
'@ResponseEntity'를 사용해서 상태코드를 포함하여 반환하도록 수정하겠습니다!

2024-07-13 04:43 UTC, mingjuu commented on src/main/java/gift/dto/ProductDTO.java
> +    @NotBlank(message = "상품 이름은 필수 입력 사항입니다.")
넵 RequestDTO, ResponseDTO를 따로 구현해보겠습니다!

2024-07-13 04:47 UTC, mingjuu commented on src/main/java/gift/resolver/LoginMemberArgumentResolver.java
> +    @Autowired
아하, 감사합니다!

2024-07-13 04:51 UTC, mingjuu commented on src/main/java/gift/util/JwtUtil.java
> +    }
아뇨 없습니다! 삭제하겠습니다

2024-07-14 16:30 UTC, asebn1 requested changes
민주님 안녕하세요~ 
PR 충돌이 나고 있어서 이 부분 확인해주세요!
이후에 머지 진행할게요 :)

2024-07-15 00:57 UTC, mingjuu commented
> 민주님 안녕하세요~ PR 충돌이 나고 있어서 이 부분 확인해주세요!
> 
> 추가로 아래 부분을 개선해볼까요?
> 
> * 도메인 단위 테스트
> * 엔티티 클래스의 기본생성자 구현 및 접근제어자 적용
> * 엔티티의 중복 코드 개선
> * 도메인 setter 우선 제거 (getter는 작성되더라도 사용을 지양합시다)

상위 클래스로 id 필드와 관련된 공통 코드를 상속시키는 방향으로 중복 코드를 개선하였습니다!

2024-07-15 11:41 UTC, asebn1 approved these changes
민주님 안녕하세요~
3단계는 이만 머지하겠습니다 :)

2024-07-15 11:41 UTC, merged