전남대 BE_서지우 3주차 과제(Step3)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #370
Opened 2024-07-12 10:49 UTC by seojiu

페이지네이션 구현 완료해서 pr 먼저 날립니다. 
step1, step2 피드백 반영 후 리뷰 요청 드리겠습니다!

2024-07-12 14:01 UTC, pkeugine requested changes
안녕하세요 지우님,
리뷰 잘 반영하면서 미션 진행해주고 계십니다!
우선 몇 가지 간단한 리뷰 남겨봤어요.
이것들 확인해보고 리뷰를 이어가보면 좋을 것 같아요.
파이팅입니다 :)

2024-07-12 14:01 UTC, pkeugine commented on src/main/java/gift/model/Wishlist.java
> +public class Wishlist {
DB 쪽 테이블명과 클래스명을 맞춰보는건 어떨까요?
좀 사소해보이는 부분이긴한데, 꽤... 중요할 수도 있어요.
이런 이름 관련 실수 또는 오류가 꽤 발생하거든요.

2024-07-12 14:01 UTC, pkeugine commented on src/main/java/gift/service/MemberService.java
> +                });
메서드 추출을 해서 검증한다는 이름을 지어주는건 어떨까요?

2024-07-12 14:01 UTC, pkeugine commented on README.md
> +# spring-gift-jpa
지우님 step 1 리뷰 반영하면서
지우님의 프로젝트를 로컬에서 실행한 화면을 캡쳐해서 이 코멘트에 댓글로 남겨주시면 감사하겠습니다.
전체 기능은 아니고 product 관련 것들만 보여주셔도 괜찮을 것 같아요!

2024-07-12 14:01 UTC, pkeugine commented on src/main/java/gift/controller/MemberController.java
> +@RequestMapping("/members")
members 는 그러고 보니 앞에 `api` 가 안 붙나요?

2024-07-12 14:01 UTC, pkeugine commented on src/main/java/gift/service/MemberService.java
> +    }
```suggestion
    public String register(@Valid MemberDto memberDto) {
        validateNewMember(memberDto);
        String token = JwtUtility.generateToken(memberDto.getEmail());
        Member member = new Member(
                memberDto.getEmail(),
                memberDto.getPassword(),
                token);
        memberRepository.save(member);
        return token;
    }
```

이렇게 로직을 개선해보면 어떨까요?
조금 더 간결해보이지 않나요?
(가장 위에 있는 `validateNewMember` 는 앞서 남긴 메서드 추출 리뷰를 반영한 부분이에요)

뿐만 아니라 위의 로직에서는
`memberRepository.save(member);` 이후
`member.getId()` 를 하면 id 가 제대로 된 값으로 나올거예요. (한 번 해보세요)
어째서 이렇게만 해도 그게 가능할까요?! 🤔

2024-07-12 15:01 UTC, seojiu commented on src/main/java/gift/model/Wishlist.java
> +public class Wishlist {
변경하겠습니다!

2024-07-12 15:04 UTC, seojiu commented on src/main/java/gift/controller/MemberController.java
> +@RequestMapping("/members")
기능 요구 사항 예시에는 없길래 그대로 따라하느라 안 붙였습니다. 수정하겠습니다!

2024-07-12 15:05 UTC, seojiu commented on src/main/java/gift/service/MemberService.java
> +                });
참고하겠습니다!!

2024-07-12 15:09 UTC, seojiu commented on README.md
> +# spring-gift-jpa
![image](https://github.com/user-attachments/assets/57049e27-0419-450e-8e91-b2b6523122be)
![image](https://github.com/user-attachments/assets/9f3d9db5-6131-4c8e-9f90-662d86430074)
![image](https://github.com/user-attachments/assets/c67a2337-79a1-424e-b5bf-a09d90aa711b)

이정도면 될까요?
그런데 혹시 문제가 있어서 보여달라고 하시는 걸까요...?

2024-07-12 15:12 UTC, seojiu commented on src/main/java/gift/service/MemberService.java
> +    }
👍👍👍참고해서 개선하겠습니다!!
어떻게 가능한지는 열심히 공부하고 나서 다시 코멘트 남기겠습니다.

2024-07-16 12:15 UTC, pkeugine commented on README.md
> +# spring-gift-jpa
아 아닙니다!
`/api/` 를 경로로 하셔서 제가 `/web/` 인줄 알고 착각했었어요.
api 가 아닌 페이지는 web 으로 경로를 지정해주는건 어떨까요?

2024-07-16 12:17 UTC, pkeugine approved these changes
안녕하세요 지우님,
미션 진행하느라 고생 많으십니다.
이 미션은 이만 머지하도록 하고,
다음 미션에 집중해보죠!
파이팅입니다 :)

2024-07-16 12:17 UTC, merged

2024-07-16 12:56 UTC, seojiu commented on README.md
> +# spring-gift-jpa
넵 변경하겠습니다!