경북대 BE_권다운 3주차 과제(3단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #373
Opened 2024-07-12 16:22 UTC by momnpa333

체리픽으로 머지 해결후 다시 올립니다!
- @transactional 사용이유 미흡
- Pageable과 Page의 사용법 숙지 미흡
- Lazy로 인한 N+1 문제 해결 미흡
- 페이징 관련 조회에서 정렬 기준에 따라 코드 리팩토링 필요
- 테스트 코드 부실
일단 저녁 6시 까지 pr을 날리고 위의 제가 미흡 하다고 생각하는점은 따로 리팩토링해야 할 것 같습니다 ! 항상 리뷰해주셔서 감사합니다!

2024-07-13 07:45 UTC, MangKyu requested changes
마지막 단계도 고생많으셨습니다! 이제 핵심을 위해 조금 미뤄뒀던 부분에 대해서 코멘트 및 추가 변경 요청 드리겠습니다 🙇

### Product에 대한 단위 테스트
과제를 하면서 느끼셨겠지만, 요구사항이 계속해서 생김에 따라 리팩터링이 지속적으로 일어나게 됩니다! 따라서 비즈니스 정책들에 대한 테스트가 존재해야 코드 변경이 생겨도 영향이 없음을 보장할 수 있는데요, 예를 들어 Product의 경우 "카카오" 라는 네이밍 규칙에 대한 부분을 단위 테스트로 작성해둔다면 우리의 비즈니스 정책이 영향없음을 보증받을 수 있을 것 같아요ㅎㅎ 해당 부분을 보완하시면 좋을 것 같습니다!

### Member에서 Role의 관리
일반적으로 데이터베이스를 관리할 때 Enum 부분은 VARCHAR를 활용하여 저장합니다! 만약 Enum의 번호로 지정을 하게 되면, Enum 클래스에서 새로운 필드를 추가할 때 어려움을 겪을 수 있습니다! 따라서 구체적인 name 값으로 반드시 저장해서 관리할 필요가 있습니다!
예를 들어 ADMIN, USER 만 사용되고 있는데, 새로운 개발자가 와서 GUEST,ADMIN, USER로 추가한다고 하면 관련된 모든 권한 체계가 깨질 수 있기 때문입니다ㅎㅎ
Enum의 경우 `@Enumerated(EnumType.STRING)`을 붙여주지 않으면, 질문에 대한 답변도 드리도록 하겠습니다!
페이징의 경우 다른 추가적인 정보를 통해 추가적인 페이징 처리가 가능하므로, 전달이 필요합니다! 이때 전달되는 정보는 페이징 전략에 따라 달라질 수 있는데, 이때 또 다른 페이징 전략 중 하나인 cursor 방식을 가져갈 수도 있습니다ㅎㅎ 현재 사용하는 방식은 offset 방식이라고 하는데, 현재는 중요하지 않은 것 같아서 천천히 공부해보시면 좋을 것 같아요

### Dao 예외처리
스프링은 데이터 접근 계층을 위해 `@Repository`라는 애노테이션을 제공하는데, 해당 애노테이션이 추가적인 기능을 제공해줍니다! 그 중 하나가 바로 예외 추상화입니다! 자세한 내용은 [다음의 포스팅](https://mangkyu.tistory.com/156) 참고해주세요!
물론 현재 과제에서는 jdbcTemplate과 spring-data-jpa 모두 스프링의 기술을 활용하여 큰 문제가 없지만 추후에 queryDSL이나 다른 접근 도구들을 사용할 때, Repositorty를 활용해야 일관된 에러 핸들링이 가능해집니다ㅎㅎ

2024-07-13 07:45 UTC, MangKyu commented on src/main/java/gift/controller/product/ProductController.java
> +import org.springframework.data.web.PageableDefault;
활용 좋네요! 👍

2024-07-13 07:45 UTC, MangKyu commented on src/main/java/gift/repository/WishJpaRepository.java
> +    @Query("SELECT w FROM Wish w JOIN FETCH w.member JOIN FETCH w.product WHERE w.member.id = :memberId ORDER BY w.id DESC")
이렇게 직접 쿼리를 작성하는 부분에 대해서는 테스트를 통해 검증하는 것이 좋을 것 같아요ㅎㅎ

2024-07-13 16:06 UTC, momnpa333 commented on src/main/java/gift/repository/WishJpaRepository.java
> +    @Query("SELECT w FROM Wish w JOIN FETCH w.member JOIN FETCH w.product WHERE w.member.id = :memberId ORDER BY w.id DESC")
넵 테스트 코드 작성해보겠습니다!

2024-07-14 15:25 UTC, MangKyu commented
혹시 수정사항 전체 반영되면 리뷰 요청 한번만 날려주세요 🙇

2024-07-14 16:10 UTC, momnpa333 commented
## 리팩토링 기능 목록

- [x] createdAt, updatedAt 을 위한 baseEntity 제작
- [x] product에 대한 단위테스트
- [x] Role @Enumerated(EnumType.STRING) 붙이기
- [x] repository 확장성 있게 리팩토링
- [x] repository 테스트코드 작성
- [x] 페이징 옵션 enum 생성
- [ ] n+1 문제 해결
- [ ] controller와 service 분리를 위한 중간 계층 제작

아래 2문제는 다음 과제에서 차차 리팩토링 하겠습니다!
product name 유효성 관련하여 단위 test 구현하였습니다.
### 1..dao 예외처리에서 잘 이해를 못한것 같습니다. 
```
//@Transactional
    public void addWish(Long userId, WishRequest.Register request) {
        Member member = memberRepository.findById(userId)
            .orElseThrow(() -> new NotFoundException("Member not found"));

        Product product = productRepository.findById(request.productId())
            .orElseThrow(() -> new NotFoundException("Product not found"));

        wishRepository.findByMemberAndProduct(member, product)
            .ifPresent(wish -> {
                throw new IllegalArgumentException("Wish already exists");
            });

        wishRepository.save(request.toEntity(member, product));
    }
```
에서 member와 product의 유효성 검사를 service에서 하는 것이 아닌 wishJpaRepository에서 하는 것이 aop 관점에서 더 적절하다는 말씀일까요?

### 2. repository를 확장성을 고려하여 만들어 봤는데 제가 구현한 방식이 맞는지 잘모르겠습니다!

### 3. 정렬의 타입이 많아 지면 controller를 하나씩 만드는 것이 비효율 적이라고 생각하여 SearchType으로 enum을 사용하여 service에서 switch 문으로 반환하여 처리하였는데 이러한 방식이 맞는지 궁금합니다!

### 4. 위시에서 findByMemberAndProduct가 맞는지, 아니면 findByMemberIdAndProductId로 객체로 찾는 것이 아닌 id를 사용하여 찾는 것이 옳바른지 여쭤보고 싶습니다! 

늦은시각까지 저의 질문을 받아주셔서 정말 감사합니다!! ㅜㅜㅜㅜㅜ

2024-07-15 16:29 UTC, MangKyu approved these changes
3주차 과제도 고생 많으셨습니다! 4주차 과제를 진행해야 하여 개선하면 좋을 부분들이 있지만, 어프룹하고 머지하도록 하겠습니다! 가장 어려운 것이 꾸준함이라고 생각하는데, 많은 어려움이 있었을 것임에도 불구하고 지속적으로 리팩토링하고 개선하는 모습이 훌륭하신 것 같습니다ㅎㅎ 남은 과제들도 화이팅해보시죠!
추가적으로 질문 주신 부분들에 대해서도 답변드리겠습니다! 🙇

### Q1 dao 예외처리
앗 아니요! 제가 드리고 싶었던 말씀은 이후에 스프링이 제공하는 jdbcTemplate이나 JpaRepository 외에도 다양한 DB 접근 기술을 사용하실 텐데요~ `@Repository`를 사용하여 스프링이 해주는 데이터베이스에 종속적인 예외들 ex) H2Exception or MySQLException 등을 추상화된 예외 ex) DatabaseException 으로 컨버팅하여 핸들링하라는 얘기였습니다~ `@Repository`를 사용하면 H2Exception or MySQLException 각각의 디비에서 발생하는 에러를 DatabaseException 으로 추상화해줍니다!
참고로 위의 예외 네이밍은 직관을 위해 임의로 작성하였습니다ㅎㅎ


### Q2 Repository 구현
정확하게 OCP를 준수하는 방향으로 코드를 잘 작성해주신 것 같습니다ㅎㅎ 이러한 것이 인터페이스의 장점이며, 추후에 다른 디비 접근 도구를 사용하게 되더라도 비즈니스 정책을 처리하는 Service는 영향없이 DB 접근 계층만 갈아끼울 수 있게 됩니다!


### 정렬 처리
올바르게 처리하고 계신 것 같습니다! 다만 SearchType에 따른 쿼리를 어떤 것을 처리할까를 Service에서 구현할지 아니면 Repository 상세에서 구현할지는 고민이 필요할 것 같네용ㅎㅎ 비즈니스 적으로는 `SearchType으로 조건에 맞는 데이터를 조회한다` 라는 목적의 달성이 중요할 것 같아서요~ 이러한 사고의 확장은 천천히 고민해보시죠


### Q4 Repository 활용
일단 연관관계 관련하여 추가 코멘트 남겨드리겠습니다!
토이 프로젝트임에도 불구하고 느끼셨듯이, 양방향 연관관계는 서비스의 복잡도를 매우 높는 반면에 유지보수성은 매우 떨어뜨립니다. 그래서 가급적 양방향 연관관계를 끊어내고 단방향 연관관계로 유지하는 것이 좋습니다ㅎㅎ
심지어 최근에는 JPA의 연관관계 조차 어렵고 복잡함을 호소하는 분들도 상당히 많고, 저 역시도 그러한 사람 중 한명으로써 연관관계가 아닌 Long과 같은 타입을 지정하여 실무에서 사용하고 있습니다! JPA의 기술적 학습 곡선 뿐만 아니라 놓치는 N+1 문제 등을 겪다 보니 연관관계를 사용하지 않게 되었습니다ㅎㅎ 이러한 추세는 해외에서도 상당히 빈번하게 나오는 모습으로, 최근에 있었던 Spring One 행사에서는 [JPA Complexity](https://www.youtube.com/watch?v=RGz-Vn9fw04)라는 주제를 별도로 다룰 정도였습니다! 또한 [배민 세미나에서 발표](https://www.youtube.com/watch?v=cflK7FTGPlg)하신 정상혁님의 경우 이러한 문제를 개선하고자 jdbc-plus라는 오픈소스를 개발하여 적용하고 계십니다! 물론 연관관계를 맺으면 객체-관계 간 임피던스 불일치를 해결할 수도 있지만 그에 따른 장단점과 기술적 학습 등을 명확히 숙지할 필요가 있다고 생각합니다ㅎㅎ
따라서 실무에서 저는 기본적으로 member와 product의 id를 넘겨주고 있고, 이러한 방식이 훨씬 실용적이라고 생각합니다!

혹여나 추가적으로 궁금한 부분 생기시면 언제든지 편하게 질문 남겨주세요:)

2024-07-15 16:29 UTC, MangKyu commented on src/main/java/gift/model/BaseTimeEntity.java
> +public class BaseTimeEntity {
MappedSuperclass를 활용해 분리하는 부분 💯

2024-07-15 16:29 UTC, MangKyu commented on src/main/java/gift/controller/product/ProductController.java
> +    @DeleteMapping("/products/{id}"
```suggestion
    @DeleteMapping("/products/{id})"
```

2024-07-15 16:29 UTC, MangKyu commented on src/main/java/gift/global/dto/PageResponse.java
> +    public static <T, U> PageResponse<T> from(Page<U> page, Function<U, T> mapper) {
이런식으로 함수형 인터페이스를 넘기게 되면 타입 안정성을 보장받지 못할 뿐만 아니라, 무엇을 처리하는 함수형 인터페이스인지 식별이 어려워 유지보수를 어렵게 만들 수 있습니다ㅎㅎ

2024-07-15 16:29 UTC, MangKyu commented on src/main/java/gift/model/product/SearchType.java
> +public enum SearchType {
꾸준히 기능도 추가하고, 그에 따른 리팩토링을 적용하는 모습이 훌륭하신 것 같습니다!
해당 부분은 Enum으로 처리한 것도 바람직한 선택인 것 같습니다:)

2024-07-15 16:29 UTC, MangKyu commented on src/main/java/gift/repository/member/MemberJdbcRepository.java
> +
인터페이스를 도입함에 따른 부산물(해야하지만 하지 않은 결과물)로 이해하고 넘어갈께용!
딱히 러닝은 없으실 것 같아서 굳이 마무리 안하셔도 될 것 같습니다ㅎㅎ

2024-07-15 16:29 UTC, MangKyu commented on src/main/java/gift/repository/wish/WishJpaRepository.java
> +    @Query("SELECT w FROM Wish w JOIN FETCH w.member JOIN FETCH w.product WHERE w.member.id = :memberId ORDER BY w.id DESC")
Fetch Join 💯

2024-07-15 16:29 UTC, MangKyu commented on src/test/java/gift/controller/ProductControllerTest.java
> +    private ProductRepository productRepository;
이러한 mockito 라이브러리를 사용할 경우에 강결합 구조의 테스트가 작성되었고,
구현이 바뀜에 따라 테스트도 바뀌는 문제가 생겼음을 인지만 해도 좋을 것 같습니다!

2024-07-15 16:29 UTC, MangKyu commented on src/test/java/gift/model/product/ProductTest.java
> +    void product_실패_이름_유효성() {
꼼꼼하게 테스트 작성해주셔서 감사합니다ㅎㅎ
비슷한 파라미터가 반복되는 경우에는 `@ParameterizedTest`를 이용하여 반복할 수 있으니 추후에 [학습](https://www.baeldung.com/parameterized-tests-junit-5)해보시면 좋을 것 같아요~!

2024-07-15 16:29 UTC, merged

2024-07-16 08:12 UTC, momnpa333 commented on src/main/java/gift/controller/product/ProductController.java
> +    @DeleteMapping("/products/{id}"
컨벤션 주의 하겠습니다!

2024-07-16 08:15 UTC, momnpa333 commented on src/main/java/gift/global/dto/PageResponse.java
> +    public static <T, U> PageResponse<T> from(Page<U> page, Function<U, T> mapper) {
타입 안정성에 대해 생각하지 않았는데 그런 단점들이 있었군요 수정하겠습니다!

2024-07-16 08:16 UTC, momnpa333 commented on src/main/java/gift/model/product/SearchType.java
> +public enum SearchType {
요새 코딩에 대한 자존감이 바닥을 치는데 이런 칭찬하나로 하루가 기분이 좋아지네요 감사합니다!

2024-07-16 08:16 UTC, momnpa333 commented on src/main/java/gift/repository/member/MemberJdbcRepository.java
> +
넵 말씀해주신데로 interface에 메서드를 하나 제작할때마다 override해야 하는 코드부산물이 생기네요ㅜㅜ 피드백 감사합니다

2024-07-16 08:17 UTC, momnpa333 commented on src/test/java/gift/controller/ProductControllerTest.java
> +    private ProductRepository productRepository;
넵 감사합니다!

2024-07-16 08:17 UTC, momnpa333 commented on src/test/java/gift/model/product/ProductTest.java
> +    void product_실패_이름_유효성() {
@ParamererizedTest에 대해 공부해봐야겠네요 감사합니다!