강원대 BE_박지희 3주차 과제 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #374
Opened 2024-07-12 19:21 UTC by peacefullyquietly

- step1 코드 리뷰를 반영한 step2 과제 버전으로 수정하였습니다
- step1 코드 수정 중 발견하지 못했던 null을 사용한 부분을 추가로 optional로 변경하였습니다.

2024-07-13 09:00 UTC, jaymarystella requested changes
안녕하세요.
2단계 관련 피드백 몇가지 남겼는데 확인 후 의견 및 반영부탁드릴게요.

2024-07-13 09:00 UTC, jaymarystella commented on src/main/java/gift/controller/ProductController.java
> +        Optional<ProductDTO> productDTO = productService.getProduct(id);
옵셔널 처리로 개선을 잘하셨습니다.

2024-07-13 09:00 UTC, jaymarystella commented on src/main/java/gift/domain/MemberDTO.java
> +public class MemberDTO {
클래스내 코드 정리가 많이 안되어있는것같습니다. 스타일 가이드 참고하셔서 개선해주세요.

2024-07-13 09:00 UTC, jaymarystella commented on src/main/java/gift/entity/ProductEntity.java
> +    }
쓰이지 않는 메서드로 보입니다.

2024-07-13 09:00 UTC, jaymarystella commented on src/main/java/gift/entity/ProductEntity.java
> +    private List<WishListEntity> wishListEntities;
상품으로부터 조회되는 경우가있는건가요?

2024-07-13 09:00 UTC, jaymarystella commented on src/main/java/gift/entity/ProductEntity.java
> +    }
업데이트도 방어적으로 검증이 필요할거같은데 어떻게 생각하실까요?

2024-07-13 09:00 UTC, jaymarystella commented on src/main/java/gift/service/ProductService.java
> +                return ProductServiceStatus.SUCCESS;
optional처리로직을 개선해볼 수 있을것같습니다.

2024-07-14 05:46 UTC, peacefullyquietly commented on src/main/java/gift/domain/MemberDTO.java
> +public class MemberDTO {
넵 수정하겠습니다

2024-07-14 05:47 UTC, peacefullyquietly commented on src/main/java/gift/entity/ProductEntity.java
> +    }
습관적으로 setter를 만들었던 것 같습니다 수정하겠습니다!

2024-07-14 05:50 UTC, peacefullyquietly commented on src/main/java/gift/entity/ProductEntity.java
> +    }
사실 Entity내에 setter를 웬만하면 만들지 않는 것이 좋다하여 생성자로만 값을 주입할 수 있게 두었었습니다. 그런데 코드 작성 중 값을 수정할 일이 생겨 해당 메서드를 두었는데,, 이렇게 하면 setter가 있는 것과 별반 다르지 않아 어떤식으로 작성 하는 것이 좋을지 잘 모르겠습니다

2024-07-14 05:51 UTC, peacefullyquietly commented on src/main/java/gift/service/ProductService.java
> +                return ProductServiceStatus.SUCCESS;
넵 수정해보겠습니다

2024-07-14 06:19 UTC, peacefullyquietly commented on src/main/java/gift/controller/ProductController.java
> +        Optional<ProductDTO> productDTO = productService.getProduct(id);
감사합니다

2024-07-14 06:32 UTC, peacefullyquietly commented on src/main/java/gift/entity/ProductEntity.java
> +    private List<WishListEntity> wishListEntities;
음.. 양방향 매핑이 잘못 설정 된 것 같습니다. 충분히 고민 후 다시 수정해보겠습니다

2024-07-14 12:36 UTC, jaymarystella commented on src/main/java/gift/entity/ProductEntity.java
> +    }
정의하기 나름이겠지만 name의 규칙이라든지 price값이 하한,상한선이라든지 등의 요건이 들어갈수도있겠네요.

2024-07-14 12:49 UTC, jaymarystella approved these changes
2단계 리뷰 반영해주셨네요.
다음 단계 진행해주시면 될것같습니다.

2024-07-14 12:49 UTC, jaymarystella commented on src/main/java/gift/service/ProductService.java
> +            Optional<ProductEntity> existingProductEntityOptional = productRepository.findById(id);
자바버전을 높게 쓰시는거같은데 ifPresentOrElse 같은 것으로 간결화시킬수도있을거같아요.

2024-07-14 12:49 UTC, jaymarystella commented on src/main/java/gift/service/ProductService.java
> +            productRepository.save(updatedProductEntity);
메서드를 최대한 작게 만들어보면 어떨까요?

2024-07-14 12:50 UTC, merged