test
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #376
Opened 2024-07-12 20:28 UTC by donghyuun

test

2024-07-13 06:40 UTC, MangKyu requested changes
마지막 단계도 고생많으셨습니다! 이제 핵심을 위해 조금 미뤄뒀던 부분에 대해서 코멘트 및 추가 변경 요청 드리겠습니다 🙇 
과제를 하면서 느끼셨겠지만, 요구사항이 계속해서 생김에 따라 리팩터링이 지속적으로 일어나게 됩니다! 따라서 비즈니스 정책들에 대한 테스트가 존재해야 코드 변경이 생겨도 영향이 없음을 보장할 수 있는데요, 예를 들어 Prodocut의 경우 "카카오" 라는 네이밍 규칙에 대한 부분을 단위 테스트로 작성해둔다면 우리의 비즈니스 정책이 영향없음을 보증받을 수 있을 것 같아요ㅎㅎ 해당 부분을 보완하시면 좋을 것 같습니다!

질문에 대한 답변도 드리도록 하겠습니다!
페이징의 경우 다른 엔티티 정보를 필요로 하는 경우가 있을 수 있습니다. 이러한 경우에는 작성하신대로 2번 repository를 활용하거나 조인을 활용하는 방법이 있습니다. 또는 또 다른 페이징 전략 중 하나인 cursor 방식을 가져갈 수도 있습니다ㅎㅎ 현재 사용하는 방식은 offset 방식이라고 하는데, 현재는 중요하지 않은 것 같아서 천천히 공부해보시면 좋을 것 같아요

2024-07-13 06:40 UTC, MangKyu commented on src/main/java/gift/domain/cart/CartItemService.java
> +            .collect(Collectors.toList());
```suggestion
            .toList();
```

2024-07-13 06:40 UTC, MangKyu commented on src/main/java/gift/domain/product/Product.java
>      public Product() {
기본생성자 JPA 스펙을 위해 필요한 부분이므로, 사용되지 않는다면 protected로 선언하면 더욱 좋을 것 같습니다ㅎㅎ

2024-07-13 06:40 UTC, MangKyu commented on src/main/java/gift/domain/product/Product.java
> +    public void proxyInitialize(String name, int price, String imageUrl) {
요것은 무슨 용도로 추가된 메서드일까요~?

2024-07-14 13:21 UTC, donghyuun commented on src/main/java/gift/domain/product/Product.java
> +    public void proxyInitialize(String name, int price, String imageUrl) {
```
public static Product createProductFromProxy(Product proxyProduct) {
        return new Product(
            proxyProduct.getId(),
            proxyProduct.getName(),
            proxyProduct.getPrice(),
            proxyProduct.getImageUrl());
    }
``` 프록시 객체를 실제 객체로 변환하는 코드인데, 아래 코드와 기능이 중복되어 삭제하였습니다!

2024-07-14 13:23 UTC, donghyuun commented on src/main/java/gift/domain/cart/CartItemService.java
> +            .collect(Collectors.toList());
감사합니다 수정하였습니다!

2024-07-14 13:26 UTC, donghyuun commented on src/main/java/gift/domain/product/Product.java
>      public Product() {
생각해보니, 기본 생성자를 직접 사용할 일이 아예 없네요 수정하겠습니다!

2024-07-14 14:03 UTC, donghyuun commented
```
@Test
    @Description("카카오 문구 포함 상품 저장 실패")
    void kakaoPersistFailed() {
        // given
        Product product = new Product("아이스 카카오 라떼 T", 4500, "https://example.com/image.jpg");

        // when, then
        assertThrows(ConstraintViolationException.class, () -> productRepository.saveAndFlush(product));
    }

    @Test
    @Description("카카오 문구 포함 상품 검증 메서드")
    void kakaoValidation() {
        // given
        Product product = new Product("아이스 카카오 라떼 T", 4500, "https://example.com/image.jpg");

        // when, then
        assertThrows(BusinessException.class, () -> productService.validateProduct(product));
    }
```
카카오 관련 테스트는 작성되어있습니다!. 페이징 포함해서 기타 테스트 마저 작성한 후 리뷰 요청드리겠습니다!

2024-07-15 14:06 UTC, donghyuun commented
**구현 사항**
- 저번 주 요구사항에서 장바구니 상품 수량 기능을 빠트려서 구현했습니다
- 타임리프를 통해 브라우저에서 로그인/로그아웃을 사용할 수 있도록 했습니다.
- 페이징 관련 테스트를 작성했습니다.

**기타**
양방향 관계 + orphanRemoval = true 를 적용했었는데, 양방향 연관관계를 설정할 경우에 연관관계의 주인이 아닌 쪽에서 주인에 대한 값을 입력하면 값은 입력되지만, 실제 db에 들어가지 않는다고 알고 있습니다. 그래서 연관관계 편의 메서드?(출처: 영한님 강의) 라는 것을 통해 db 에 반영되도록 할 수 있다고 배웠는데, 지금의 경우 해당 기능이 필수도 아니고, 복잡하기도 해서 단방향으로 설정했습니다. 

**질문**
**Q1**
양방향 연관관계를 설정하는 순간부터 복잡해지는 것(양쪽에 모두 값 입력해줘야 함) 같은데, 실무에서 양방향 연관관계를 사용하는 일이 많은지 궁금합니다. 아니면 혹시 양방향 연관관계를 설정하지만, 주인이 아닌쪽에서는 당연히 조회만 가능하다고 이해하고 연관관계 편의메서드를 구현하지 않는 경우도 있을까요?

**Q2**
Cascade.REMOVE 를 사용하는것에 대해 멘토님의 의견이 궁금합니다. 이번 장바구니 상품 관련해서, 유저or상품이 삭제되면 장바구니 상품 정보도 따라서 삭제되는게 당연하다고 생각되어 REMOVE 속성을 사용하였는데, 이런 당연한 경우들에 대해서도 REMOVE 를 사용하지 말아야 할까요? 

감사합니다!

2024-07-15 16:09 UTC, MangKyu approved these changes
3주차 과제도 고생 많으셨습니다! 4주차 과제를 진행해야 하여 개선하면 좋을 부분들이 있지만, 어프룹하고 머지하도록 하겠습니다! 저는 꾸준히 리팩토링하고 개선하는 자세가 개발자에게 필요하다고 생각하는데, 동현님께서 이러한 모습을 너무 잘 보여주고 계신 것 같습니다ㅎㅎ 남은 과제들도 화이팅해보시죠!
추가적으로 질문 주신 부분들에 대해서도 답변드리겠습니다! 🙇 

### Q1 연관관계 설정
토이 프로젝트임에도 불구하고 느끼셨듯이, 양방향 연관관계는 서비스의 복잡도를 매우 높는 반면에 유지보수성은 매우 떨어뜨립니다. 그래서 가급적 양방향 연관관계를 끊어내고 단방향 연관관계로 유지하는 것이 좋습니다ㅎㅎ
심지어 최근에는 JPA의 연관관계 조차 어렵고 복잡함을 호소하는 분들도 상당히 많고, 저 역시도 그러한 사람 중 한명으로써 연관관계가 아닌 Long과 같은 타입을 지정하여 실무에서 사용하고 있습니다! JPA의 기술적 학습 곡선 뿐만 아니라 놓치는 N+1 문제 등을 겪다 보니 연관관계를 사용하지 않게 되었습니다ㅎㅎ 이러한 추세는 해외에서도 상당히 빈번하게 나오는 모습으로, 최근에 있었던 Spring One 행사에서는 [JPA Complexity](https://www.youtube.com/watch?v=RGz-Vn9fw04)라는 주제를 별도로 다룰 정도였습니다! 또한 [배민 세미나에서 발표](https://www.youtube.com/watch?v=cflK7FTGPlg)하신 정상혁님의 경우 이러한 문제를 개선하고자 jdbc-plus라는 오픈소스를 개발하여 적용하고 계십니다! 물론 연관관계를 맺으면 객체-관계 간 임피던스 불일치를 해결할 수도 있지만 그에 따른 장단점과 기술적 학습 등을 명확히 숙지할 필요가 있다고 생각합니다ㅎㅎ


### Q2 Cascade.REMOVE 
위에 설명드렸듯이 제 개인적으로는 ORM의 연관관계 자체를 사용하지 않는 것을 선호합니다! 따라서 함께 지워줘야 하는 데이터가 있다면 직접 함께 지워주는 편입니다ㅎㅎ 그 외에 연관관계를 맺어주는 상황이라면 사용해도 크게 문제는 없다고 생각합니다!


혹여나 추가적으로 궁금한 부분 생기시면 언제든지 편하게 질문 남겨주세요:)

2024-07-15 16:09 UTC, MangKyu commented on src/main/java/gift/domain/cart/CartItem.java
> +    protected CartItem() {
protected로 생성해주시는 부분 💯

2024-07-15 16:09 UTC, MangKyu commented on src/main/java/gift/domain/cart/CartItem.java
> +               Objects.equals(user, cartItem.user) &&
이렇게 하면 equals 비교 시에 불필요하게 lazy-loading이 발생할 수도 있을 것 같네요~

2024-07-15 16:09 UTC, MangKyu commented on src/main/java/gift/domain/cart/CartItemController.java
>          @LoginInfo UserInfo userInfo) {
취향 문제일 수 있어서 따로 코멘트는 안남겼는데, 이미 수정하셨으니 적어보면
저는 실무에서 이러한 방식으로 개행합니다ㅎㅎ

```suggestion
        @LoginInfo UserInfo userInfo
    ) {
```

2024-07-15 16:09 UTC, MangKyu commented on src/main/java/gift/domain/cart/CartItemRestController.java
> +    public CartItemRestController(CartItemService cartItemService, JdbcTemplate jdbcTemplate) {
```suggestion
    public CartItemRestController(CartItemService cartItemService) {
```

2024-07-15 16:09 UTC, MangKyu commented on src/main/java/gift/domain/cart/CartItemService.java
> +                return Product.createProductFromProxy(product);
Product는 비즈니스 정책을 다루는 클래스인데, createProductFromProxy라는 부분은 비즈니스 정책이라기 보다는 구현 기술에 가까운 느낌이 드네요ㅎㅎ 이 부분도 어떻게 해결할 수 있을지 고민해보면 좋을 것 같습니다!

2024-07-15 16:09 UTC, MangKyu commented on src/main/java/gift/domain/cart/CartItemService.java
>          if (cartItemRepository.existsByUserAndProduct(user, product)) {
이렇게 하면 쿼리가 2번 발생하니까 cartItemRepository.findByUserIdAndProductId가 null인 경우와 그렇지 않은 경우를 비교하는 것이 더 좋을 것 같네요!

2024-07-15 16:09 UTC, MangKyu commented on src/main/java/gift/domain/cart/CartItemController.java
> +    private Sort getSortObject(String sort) {
저는 사실 이렇게 타입 구체화되는 부분은 enum으로 관리하는 편입니다ㅎㅎ
처음에 남길까 말까 고민하다가 자주 고치시는 것 같아서 코멘트 남겨용!

2024-07-15 16:09 UTC, MangKyu commented on src/main/java/gift/global/config/WebConfig.java
> +            .addPathPatterns("/users/cart/**"); // Controller
꾸준히 리팩토링하시고 고치시는 모습이 너무 훌륭하십니다!
계속해서 연습하고 학습하다 보면 더 멋진 개발자가 되실 것 같습니다ㅎㅎ 🙇

2024-07-15 16:09 UTC, MangKyu commented on src/main/java/gift/global/handler/GlobalExceptionHandler.java
> +        e.getBindingResult().getAllErrors().forEach(error -> {
포매팅 정리 💯

2024-07-15 16:09 UTC, MangKyu commented on src/test/java/gift/JpaDataTest/ProductRepositoryTest.java
> +        assertThat(findProduct.isEmpty()).isEqualTo(true);
```suggestion
        assertThat(findProduct).isEmpty();
```

2024-07-15 16:09 UTC, merged

2024-07-16 11:06 UTC, donghyuun commented on src/main/java/gift/domain/cart/CartItemController.java
>          @LoginInfo UserInfo userInfo) {
수정하니 더욱 깔끔한 것 같습니다. 공유 감사합니다!

2024-07-16 11:06 UTC, donghyuun commented on src/main/java/gift/domain/cart/CartItemRestController.java
> +    public CartItemRestController(CartItemService cartItemService, JdbcTemplate jdbcTemplate) {
수정하겠습니다!

2024-07-16 11:08 UTC, donghyuun commented on src/main/java/gift/global/config/WebConfig.java
> +            .addPathPatterns("/users/cart/**"); // Controller
감사합니다 ㅎㅎ
카테캠 조원들과 얘기를 나누다보니 더 나은 코드에 대해 생각할 수 있어서 좋은 것 같습니다.

2024-07-16 11:36 UTC, donghyuun commented on src/main/java/gift/domain/cart/CartItemService.java
> +                return Product.createProductFromProxy(product);
비즈니스 정책과 구현 기술에 대해 조금 혼동이 오는데, 날 잡고 곰곰히 생각해봐야겠습니다..!

2024-07-16 11:36 UTC, donghyuun commented on src/main/java/gift/domain/cart/CartItemService.java
> +                return Product.createProductFromProxy(product);
리뷰 감사합니다!

2024-07-17 10:25 UTC, donghyuun commented on src/main/java/gift/domain/cart/CartItemService.java
>          if (cartItemRepository.existsByUserAndProduct(user, product)) {
수정했습니다!!

2024-07-17 10:39 UTC, donghyuun commented on src/main/java/gift/domain/cart/CartItem.java
> +               Objects.equals(user, cartItem.user) &&
프록시 객체를 초기화시키는 것보다 id 값만을 사용하는 것이 나을 것 같아 getId() 로 해결하였습니다!

2024-07-17 10:42 UTC, donghyuun commented on src/main/java/gift/domain/cart/CartItemController.java
> +    private Sort getSortObject(String sort) {
혹시 타입 구체화되는 부분이 HttpStatus.OK 와 같은 응답 코드를 말씀하시는 건가요?!
아니면 Sort.by(Sort.Direction.ASC, "price") <- 이러한 값들을 enum 으로 관리하신다는 말씀이신가요??