전남대 BE_박준형 3주차 과제(step3)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #377
Opened 2024-07-13 02:27 UTC by cliant

### 코드를 작성하면서 어려웠던 점 

1. 페이지네이션이라는 개념 자체가 추상적이라는 느낌이 들어 좀 어려웠습니다.

2. WishListRepository에 
`
Page<WishList> findByMemberId()
`
를 선언하며 기존의 List를 반환하던 메서드랑 이름이 중복되었습니다. 다만 JpaRepository는 메서드명으로 쿼리를 만들기에 이름을 변경하면 안된다는 생각이 들었습니다. 또한 위시리스트 삭제기능에서 List를 반환하는 메서드도 필요하기에 삭제할 수도 없었습니다. 다만 중복된 이름의 메서드가 존재한다는 이질감이 들어 이에 대해 리턴 값이 다르면 중복된 이름으로 놔두는 지 아니면 차별성을 두는 다른 방법이 있는지 궁금합니다. 

### 코드 리뷰시 중점적으로 봐주셨으면 하는 부분

1.불필요하게 구현되거나 필요한데 구현하지 않은 부분이 있을 것이라 생각합니다. 그 부분을 지적해주셨으면 합니다.

2024-07-13 15:06 UTC, dc-choi requested changes
안녕하세요 준형님! step3 확인하였습니다!

자세한 내용은 코멘트에 적어두었습니다! 확인 부탁드립니다!

몇가지 질문을 주셨는데 그에 대한 답도 같이 드려보도록 하겠습니다!

> 페이지네이션이라는 개념 자체가 추상적이라는 느낌이 들어 좀 어려웠습니다.

이 부분이 왜 필요한지에 대한 이유에 대해 고민해볼 필요가 있겠다는 생각을 하게 되었네요.

실제 프로젝트에서는 모든 데이터를 전부 가져오지 않고 여러번 나누어서 가져오게 됩니다.

그에 대한 부분이라고 생각하시면 될 거 같아요!

> WishListRepository에 Page<WishList> findByMemberId()를 선언하며 기존의 List를 반환하던 메서드랑 이름이 중복되었습니다. 다만 JpaRepository는 메서드명으로 쿼리를 만들기에 이름을 변경하면 안된다는 생각이 들었습니다. 또한 위시리스트 삭제기능에서 List를 반환하는 메서드도 필요하기에 삭제할 수도 없었습니다. 다만 중복된 이름의 메서드가 존재한다는 이질감이 들어 이에 대해 리턴 값이 다르면 중복된 이름으로 놔두는 지 아니면 차별성을 두는 다른 방법이 있는지 궁금합니다.

이런 경우 오버로딩으로 처리할 수 있다고 생각합니다. 매개변수의 타입이나 갯수가 다르면 메서드의 다형성을 보장해주니깐요. 제 생각에는 상호간 협의만 잘 된다면 문제가 없어보인다고 생각합니다.

이상입니다! 확인 부탁드려요~!

2024-07-13 15:06 UTC, dc-choi commented on src/main/java/gift/controller/ProductController.java
> +    public String getProducts(Model model, @RequestParam(value = "page", defaultValue = "0")int page) {
페이징을 하는 경우 offset을 구하기 위한 page size를 가져오는 부분이 누락된 것으로 보입니다.

혹시 왜 누락되었는지 설명해주실 수 있나요?

2024-07-13 15:06 UTC, dc-choi commented on src/main/java/gift/controller/ProductController.java
> +        Page<ProductDto> paging = productService.getPage(page);
`Page` 객체의 모든 정보를 전부 다 내려주는 것은 불필요해보입니다.

필요한 정보만을 남은 Response 객체를 다시 반환해주는건 어떨까요?

2024-07-13 15:06 UTC, dc-choi commented on src/main/java/gift/controller/WishListController.java
> +        Page<WishListDto> wishListPage = wishListService.findWishListById(jwtUtil.extractToken(authorizationHeader), page);
`Page` 객체의 모든 정보를 전부 다 내려주게 되는 경우 warn log가 발생합니다.

필요한 정보만을 남은 Response 객체를 다시 반환해주는건 어떨까요?

2024-07-13 15:06 UTC, dc-choi commented on src/main/java/gift/controller/WishListController.java
> +    public ResponseEntity<Page<WishListDto>> getWishList(@RequestHeader("Authorization") String authorizationHeader, MemberDto memberDto, @RequestParam(defaultValue = "0") int page){
마찬가지로 페이징을 하는 경우 offset을 구하기 위한 page size를 가져오는 부분이 누락된 것으로 보입니다.

혹시 왜 누락되었는지 설명해주실 수 있나요?

2024-07-13 15:06 UTC, dc-choi commented on src/main/java/gift/repository/ProductRepository.java
> +    Page<Product> findAll(Pageable pageable);
저는 이 부분에서 컴파일 경고가 발생하더라고요. 기존 `findAll()`이 동작할 수 있도록 다른 이름으로 바꾸는게 좋아보입니다.

마침 로직에서 Order By를 진행하니 Pageable 객체에서 정렬하는게 아니라 `ByOrderByNameDesc`를 사용하는건 어떨까요?

2024-07-13 15:06 UTC, dc-choi commented on src/main/java/gift/service/ProductService.java
> +        List<Sort.Order> sorts = new ArrayList<>();
`Repository` 영역에서 쿼리로 Order By를 하게 되면 이 로직은 필요가 없어질 것으로 보입니다!

2024-07-13 15:06 UTC, dc-choi commented on src/main/java/gift/service/ProductService.java
> +        Pageable pageable = PageRequest.of(page, 10, Sort.by(sorts));
page size에 대한 부분도 클라이언트에서 받아오면 어떨까요?

요구사항이 변경된다면 유지보수하기 어려워 보일 것으로 예상됩니다.

2024-07-13 15:06 UTC, dc-choi commented on src/main/java/gift/repository/WishListRepository.java
> +    Page<WishList> findByMemberId(Pageable pageable, Long memberId);
로직안에서 Pageable 객체를 생성할 때 정렬하는게 아니라 `ByMemberIdByProductIdDesc`를 사용하는건 어떨까요?

2024-07-13 15:06 UTC, dc-choi commented on src/main/java/gift/service/WishListService.java
> +        List<Sort.Order> sorts = new ArrayList<>();
`Repository` 영역에서 쿼리로 Order By를 하게 되면 이 로직은 필요가 없어질 것으로 보입니다!

2024-07-14 05:26 UTC, cliant commented on src/main/java/gift/controller/ProductController.java
> +    public String getProducts(Model model, @RequestParam(value = "page", defaultValue = "0")int page) {
Pagable에 대한 학습이 부족하여 size는 별도의 기본 값 설정 없이도 10으로 설정되는 줄 알았습니다ㅠ 사이즈를 클라이언트에게 받아오도록 변경하였습니다!

2024-07-14 05:27 UTC, cliant commented on src/main/java/gift/controller/ProductController.java
> +        Page<ProductDto> paging = productService.getPage(page);
ProductPageResponse라는 dto를 만들어 해결하였습니다.

2024-07-14 05:27 UTC, cliant commented on src/main/java/gift/repository/ProductRepository.java
> +    Page<Product> findAll(Pageable pageable);
Repository에서 정렬된 채로 데이터를 가져올 수 있는 것을 리뷰를 통해 알게 되었습니다. 조언해주신 대로 프로그램을 변경해보았습니다!

2024-07-14 05:27 UTC, cliant commented on src/main/java/gift/service/ProductService.java
> +        List<Sort.Order> sorts = new ArrayList<>();
넵 삭제하였습니다!

2024-07-14 05:27 UTC, cliant commented on src/main/java/gift/service/ProductService.java
> +        Pageable pageable = PageRequest.of(page, 10, Sort.by(sorts));
넵 반영하였습니다!

2024-07-14 05:39 UTC, cliant commented on src/main/java/gift/controller/WishListController.java
> +        Page<WishListDto> wishListPage = wishListService.findWishListById(jwtUtil.extractToken(authorizationHeader), page);
넵 WishListPageResponse dto를 만들어 해결했습니다!

2024-07-14 05:39 UTC, cliant commented on src/main/java/gift/controller/WishListController.java
> +    public ResponseEntity<Page<WishListDto>> getWishList(@RequestHeader("Authorization") String authorizationHeader, MemberDto memberDto, @RequestParam(defaultValue = "0") int page){
위와 같은 이유입니다ㅠ 수정하였습니다!

2024-07-14 05:39 UTC, cliant commented on src/main/java/gift/repository/WishListRepository.java
> +    Page<WishList> findByMemberId(Pageable pageable, Long memberId);
넵 반영하였습니다!

2024-07-14 05:39 UTC, cliant commented on src/main/java/gift/service/WishListService.java
> +        List<Sort.Order> sorts = new ArrayList<>();
넵 반영하였습니다!

2024-07-14 06:38 UTC, dc-choi approved these changes
준형님~! 피드백 주신대로 잘 수정해주셨네요!

step3까지 진행하시느라 고생하셨습니다!

추가적으로 E2E Test까지 진행하시면 더 좋을거 같습니다!

2024-07-14 06:38 UTC, merged