경북대 BE_김은선 (1단계, 2단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #378
Opened 2024-07-13 05:35 UTC by eunsoni

안녕하세요 멘토님,

리뷰요청드립니다!

기존에 wish 테이블을 인식하지 못해서 생긴 오류는 MemberDao, ProductDao를 모두 Repository로 변경하고 jpa를 적용하니 해결되었습니다.

중점적으로 리뷰 받고 싶은 내용은 최종 서비스를 위해서 현재 구조에서 개선되어야 하는 점이 궁금합니다. 

그리고 RepositoryTest는 정상적으로 작동하는데, ApplicationTest는 오류가 나고있어서 이 부분도 원인이나 해결방법이 궁금합니다.

2024-07-14 17:14 UTC, gongdongho12 requested changes
아직 3단계 PR은 작성 전이신거죠?

> 그리고 RepositoryTest는 정상적으로 작동하는데, ApplicationTest는 오류가 나고있어서 이 부분도 원인이나 해결방법이 궁금합니다.

![image](https://github.com/user-attachments/assets/eaf406ab-7728-45c9-a2ad-bf7f8989ccb4)
자체를 쓸 수 없는데 빈을 가져오려고 하는 문제입니다
저게 아니라 다른 빈을 가져오거나 사용하는 부분은 문제 없습니다
![image](https://github.com/user-attachments/assets/a1e158ed-6b66-4725-808c-bc53e0af0277)

막혔던 부분도 있었고 어려운 부분도 있었겠지만 잘 따라오느라 고생 많으셨습니다
3단계두 화이팅입니다

2024-07-14 17:14 UTC, gongdongho12 commented on src/main/java/gift/config/WebConfig.java
> +
kk의 용도가 궁금합니다
api를 잘못 수정하셨을까요?

2024-07-14 17:14 UTC, gongdongho12 commented on src/main/java/gift/dao/MemberDao.java
> +
JPA를 사용중이신데 아직 JDBCTemplate를 사용하면 DB접근 포인트가 두개가 되서요
하나로 공통화 주시는게 맞지 않을까요?

2024-07-14 17:14 UTC, gongdongho12 commented on src/main/java/gift/model/Product.java
> +    }
Product 클래스만 사용하는 곳이 없는 것 같은데 생성된 미사용 생성자이지 않을까요?

2024-07-14 17:14 UTC, gongdongho12 commented on src/main/java/gift/service/MemberService.java
> +
레포지토리의 findByEmail은 nullable인데 메서드 명을 getMember라고 하고 findByEmail 메서드에서 null이 나오면 exception 처리하면 사용처에서 간편하게 사용할 수 있지 않을까요?

2024-07-14 17:14 UTC, gongdongho12 commented on src/main/java/gift/service/ProductService.java
> +        return productRepository.findById(id).orElse(null);
null일때 exception 해두는게 용이하게 처리할 수 있지 않을까요?

2024-07-14 17:14 UTC, gongdongho12 commented on src/main/java/gift/service/MemberService.java
> +    private final BCryptPasswordEncoder passwordEncoder = new BCryptPasswordEncoder();
이런 부분은 이 부분에만 쓰는건 아닌 것 같은데 Component 등으로 빈으로 등록해두면 레이어 구분도 되고 추후 멤버가 아니라도 인코더를 사용할 수 있지 않을까요?

2024-07-14 17:14 UTC, gongdongho12 commented on src/test/java/gift/ApplicationTest.java
> +    }
테스트 부분은 전체 코멘트로 드렸습니다

그런데 실제 코드에 대한 테스트는 올려주셔야 할 것 같습니다

2024-07-14 20:15 UTC, eunsoni commented
> 아직 3단계 PR은 작성 전이신거죠?
> 
> > 그리고 RepositoryTest는 정상적으로 작동하는데, ApplicationTest는 오류가 나고있어서 이 부분도 원인이나 해결방법이 궁금합니다.
> 
> ![image](https://private-user-images.githubusercontent.com/1717874/348559195-eaf406ab-7728-45c9-a2ad-bf7f8989ccb4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5ODgxMjQsIm5iZiI6MTcyMDk4NzgyNCwicGF0aCI6Ii8xNzE3ODc0LzM0ODU1OTE5NS1lYWY0MDZhYi03NzI4LTQ1YzktYTJhZC1iZjdmODk4OWNjYjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTRUMjAxMDI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzA2NTdjOGM2MjMzYmM2YzA1NDRhYTJlYzNhM2RlMjZjMDk0YWQ1YmMzOGY5ZmY2ODU0OGI4NzBiNzRhNjJiYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.YjpsOFonwj4qrGjpb7U_P9uo4PFa2lqgh6ZtEQW_PMg) 자체를 쓸 수 없는데 빈을 가져오려고 하는 문제입니다 저게 아니라 다른 빈을 가져오거나 사용하는 부분은 문제 없습니다 ![image](https://private-user-images.githubusercontent.com/1717874/348559306-a1e158ed-6b66-4725-808c-bc53e0af0277.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5ODgxMjQsIm5iZiI6MTcyMDk4NzgyNCwicGF0aCI6Ii8xNzE3ODc0LzM0ODU1OTMwNi1hMWUxNThlZC02YjY2LTQ3MjUtODA4Yy1iYzUzZTBhZjAyNzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTRUMjAxMDI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTIxZTZhZGU2OTY2NGE3NzZlZDc2Yjk2NWJkM2IzOTgwZWRmZGMxOTlkOThkYmRkNTgwNWNkNjIzZDVjYzhlZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jZwIm0XJC-Mx9gFj2Y4vDMjxLe2qatymFB8HIlXZ2hs)
> 
> 막혔던 부분도 있었고 어려운 부분도 있었겠지만 잘 따라오느라 고생 많으셨습니다 3단계두 화이팅입니다

2단계까지 머지가 되면 그 프로젝트를 클론 받아서 3단계를 수행해야하는 것으로 알고있습니다!

2024-07-14 20:20 UTC, eunsoni commented on src/main/java/gift/dao/MemberDao.java
> +
dao는 사용되고 있는 곳이 없어서 삭제만 하면 되는 상태입니다! 수정해놓겠습니다

2024-07-14 20:23 UTC, eunsoni commented on src/main/java/gift/model/Product.java
> +    }
JPA의 Entity는 기본 생성자를 가져야 한다고 배워서 붙이게 되었는데, 지워도 되는 부분일까요?

2024-07-14 23:38 UTC, gongdongho12 commented on src/main/java/gift/model/Product.java
> +    }
이부분 관련해서 있을때와 없을때를 구분해서 테스트 해보시면 정확하게 알 수 있을것 같은데
한번 시도해보시겠어요?

2024-07-14 23:39 UTC, gongdongho12 commented on src/main/java/gift/dao/MemberDao.java
> +
DAO라는 명칭때문에 타 작업자가 있는 상황이라면 이걸로 해봐야겠다 등의 생각이 들 것 같아서 미사용이라면 혼동스러운 여지는 제거해주는게 좋을 것 같아요

2024-07-15 02:02 UTC, eunsoni commented on src/main/java/gift/service/MemberService.java
> +
이 부분은 설명을 조금 더 들을 수 있을까요?
음 어떤 메서드의 이름을 getMember로 하면 되는걸까요

2024-07-15 02:14 UTC, eunsoni commented on src/test/java/gift/ApplicationTest.java
> +    }
혹시 실제 코드에 대한 테스트가 어떤 것인지 조금 더 설명해주실 수 있을까요?

2024-07-15 02:14 UTC, eunsoni commented on src/main/java/gift/service/MemberService.java
> +    private final BCryptPasswordEncoder passwordEncoder = new BCryptPasswordEncoder();
저번에 실습코치님께 우리 미션에서는 인코딩까지는 필요없다라고 조언을 받고 이번에 인코딩 부분을 뺐습니다!

2024-07-15 02:14 UTC, eunsoni commented on src/main/java/gift/service/ProductService.java
> +        return productRepository.findById(id).orElse(null);
넵 반영하겠습니다!

2024-07-15 02:15 UTC, eunsoni commented on src/main/java/gift/model/Product.java
> +    }
넵!

2024-07-15 02:49 UTC, eunsoni commented on src/main/java/gift/config/WebConfig.java
> +
넵 그런데 인증부분에 다시 에러가 나서ㅜ 이 부분은 이번주 과제 해결 후에 따로 해결해도 될까요?

2024-07-15 12:29 UTC, gongdongho12 commented on src/main/java/gift/config/WebConfig.java
> +
넵 알겠습니다
리뷰에 언급드린 resolver가 실제론 적용안되고 있던데 시간날때 한번 파고들어보면 좋을 것 같습니다

2024-07-15 12:31 UTC, gongdongho12 commented on src/main/java/gift/service/MemberService.java
> +
findByEmail 이 nullable 이자나요
그 상태를 미리 체크해서 null이면 exception, 아니면 널 아닌 값으로 그대로 리턴할 수 있으니까 서비스 단에 그 내용까지 포함해서 메서드 명을 getMember로 하게되면 멤버를 가져와서 쓰는 부분에서 null 인경우에 별도 처리없이 자동으로 exception으로 동작하게 만들 수 있지 않을까요 라는 이야기였어요

2024-07-15 12:32 UTC, gongdongho12 commented on src/main/java/gift/service/MemberService.java
> +
https://github.com/kakao-tech-campus-2nd-step2/spring-gift-jpa/pull/378#discussion_r1677170972 이 부분과 연관지어서요

2024-07-15 12:32 UTC, gongdongho12 commented on src/main/java/gift/service/MemberService.java
> +    private final BCryptPasswordEncoder passwordEncoder = new BCryptPasswordEncoder();
우선 적용이 우선이구 이후 하나씩 개선이긴 합니다!

2024-07-15 12:33 UTC, gongdongho12 commented on src/test/java/gift/ApplicationTest.java
> +    }
샘플로 1번 멤버를 넣고
1번 멤버를 조회하면 A가 나온다와 같이

실제 서비스 로직을 테스트 하는 프로세스에 대한 테스트가 작성되면 좋겠다는 내용이에요

그러면 2번 멤버는 없는 상태일 때 2번 멤버를 조회하면 exception이 발생한다와 같이 테스트도 가능하겠죠?

2024-07-15 13:14 UTC, gongdongho12 approved these changes
타 주차 프로젝트와 이어지는 부분이라 3단계 마무리 진행이 필요해서
작업 진행을 위해 머지 진행합니다

2024-07-15 13:14 UTC, merged