경북대 BE_김민주 3주차 과제 제출(3단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #382
Opened 2024-07-13 08:53 UTC by minju26

- `상품 목록 조회`와 `위시 리스트 조회`에 pagination 적용했습니다.
- `상품 목록 조회`는 관리자 페이지도 수정하여 보일 수 있도록 했습니다.

2024-07-14 16:48 UTC, gongdongho12 requested changes
작업을 진행하실 때는 항상 이전 PR에 사용된 커밋 이후에서 작업이 진행되어야 합니다
Step1 브랜치를 베이스로 하면 안되구요 이전 작업물인 Step2 브랜치의 마지막 커밋으로 베이스로 두고 Step3를 만드셔야 이와 같이 conflict가 일어나지 않을 것 같아요

그리고 테스트 건에 대해서 JPA말고도 비지니스 로직 (서비스단) 테스트가 있어야 정확한 테스트가 가능할 것 같은데 한번 반영해주시면 좋을 것 같습니다

JPA에 생각보다 많은 기능이 있는데요 생성일 추가 등이나, Enum을 문자열로 쓴다던가 등의 기능을 한번 활용해보았으면 좋았을 것 같습니다

이번 주차에 진행한 과정이 꽤 되었는데 고생 많으셨습니다 💯

2024-07-14 16:48 UTC, gongdongho12 commented on README.md
> +  3. WishRepositoryTest - `findWishByMemberId`
테스트를 만드셔 보셨으면 JPA 테스트 말고도 일반 로직 테스트도 한번 시도해보실 수 있지 않을까요?

2024-07-14 16:48 UTC, gongdongho12 commented on README.md
> +  > 이메일은 **변경/삭제될 수 있는 속성**이므로 `고유한 값의 역할`을 하는 id로 변경
이유랑 같이 정리하면 타인이 이 코드를 보더라도 깔끔하게 이해할 수 있네요 👍🏼

2024-07-14 16:48 UTC, gongdongho12 commented on src/main/java/gift/controller/ProductController.java
> +        return ResponseEntity.ok(products);
갯수 없이 페이지만 처리하는 방식인데 갯수나 소팅까지 처리 가능한 PageRequest를 사용해보면 어떨까요?
[[참고]](https://velog.io/@dhk22/Spring-%EC%84%B8%EC%83%81-%EA%B0%84%EB%8B%A8%ED%95%9C-Pagination-Controller%EC%97%90%EC%84%9C-Pageable-%EA%B0%9D%EC%B2%B4-%EB%B0%9B%EC%95%84-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0) 해보시면 좋을 것 같습니다

2024-07-14 16:48 UTC, gongdongho12 commented on src/main/java/gift/domain/Product.java
> +    @NotBlank(message = REQUIRED_FIELD_MSG)
Null에서 Blank로 구체화 👍🏼

2024-07-14 16:48 UTC, gongdongho12 commented on src/main/java/gift/domain/Product.java
> +    }
밸리데이션이랑 실제 값 주입을 생성자로 깔끔하게 처리할 수 있게 되었네요 👍🏼

2024-07-14 16:48 UTC, gongdongho12 commented on src/main/java/gift/domain/Wish.java
> +    private Product product;
Lazy 설정 👍🏼

2024-07-14 16:48 UTC, gongdongho12 commented on src/main/java/gift/dto/response/WishProductsResponse.java
> +    }
생성자를 정말 잘 활용해 주시는군요

2024-07-14 16:48 UTC, gongdongho12 commented on src/main/java/gift/service/AuthService.java
>          return storedMember.map(member -> new AuthResponse(jwtUtil.createJWT(member.getId()))).orElse(null);
이것도 null이 될 수 있는 객체인데 AuthResponse도 Optional로 봐야하지 않을까요?

조금 의견을 보태면 null 이 되는 케이스는 exception을 주게 하면 어떨까요?

2024-07-14 16:48 UTC, gongdongho12 commented on src/main/java/gift/service/ProductService.java
> +        productRepository.save(productToUpdate);
UpdateProductRequest 안이나 Product 객체 안에 UpdateProductRequest 타입이 들어오는 메서드를 만들어 처리하면 서비스로직에 밸리데이션을 넣어주지 않아도 깔끔해지지 않을까요?

2024-07-14 16:48 UTC, gongdongho12 commented on src/main/java/gift/domain/Member.java
> +    private List<Wish> wishes;
cascade 옵션도 사용해주셨군요 👍🏼 
개발에는 용이하지만 실제 운영에서는 기록을 체크해야 할 수도 있어서 나중에 한번 고민해보면 좋을 것 같습니다

2024-07-15 05:16 UTC, minju26 commented on README.md
> +  3. WishRepositoryTest - `findWishByMemberId`
매 주차 시작에 마음은 먹는데 우선순위에서 자꾸 밀리네요🥹
이번엔 꼭 한번 시도해보도록 하겠습니다!

2024-07-15 05:17 UTC, minju26 commented on README.md
> +  > 이메일은 **변경/삭제될 수 있는 속성**이므로 `고유한 값의 역할`을 하는 id로 변경
잘 설명해주셔서 깔끔하게 정리할 수 있었습니다 :)

2024-07-15 05:17 UTC, minju26 commented on src/main/java/gift/controller/ProductController.java
> +        return ResponseEntity.ok(products);
오호 알겠습니다! 참고해보도록 하겠습니다

2024-07-15 05:20 UTC, minju26 commented on src/main/java/gift/service/AuthService.java
>          return storedMember.map(member -> new AuthResponse(jwtUtil.createJWT(member.getId()))).orElse(null);
넵 optional에 대해 다시 생각해보고, exception도 추가하도록 하겠습니다!

2024-07-15 05:23 UTC, minju26 commented on src/main/java/gift/service/ProductService.java
> +        productRepository.save(productToUpdate);
아하 그렇네요! 수정해보도록 하겠습니다

2024-07-15 05:23 UTC, minju26 commented on src/main/java/gift/domain/Member.java
> +    private List<Wish> wishes;
으음 기록을 체크해야 하는 경우도 있을 수 있군요..! 고민해 보겠습니다

2024-07-15 05:44 UTC, minju26 commented
> 작업을 진행하실 때는 항상 이전 PR에 사용된 커밋 이후에서 작업이 진행되어야 합니다 Step1 브랜치를 베이스로 하면 안되구요 이전 작업물인 Step2 브랜치의 마지막 커밋으로 베이스로 두고 Step3를 만드셔야 이와 같이 conflict가 일어나지 않을 것 같아요
> 
> 그리고 테스트 건에 대해서 JPA말고도 비지니스 로직 (서비스단) 테스트가 있어야 정확한 테스트가 가능할 것 같은데 한번 반영해주시면 좋을 것 같습니다
> 
> JPA에 생각보다 많은 기능이 있는데요 생성일 추가 등이나, Enum을 문자열로 쓴다던가 등의 기능을 한번 활용해보았으면 좋았을 것 같습니다
> 
> > 이전 피드백에서 상품 이름의 유효성을 검사하는 ProductNameValidationUtil에 대해서 객체를 직접 참조하는 것에 대한 단점을 언급해주셨습니다.
> > 해당 부분을 공부하다가, Util 클래스는 전역에서 사용될 수 있는 기능을 담고
> > 특정 부분에 집중된 기능을 담고 있다면 Util 인지 다시 생각해보아야 한다는 글을 보았습니다.
> > 그리고 ProductNameValidationUtil 을 보니, 너무 특정 부분(상품 이름 유효성)에 집중된 것 같다는 생각을 했습니다.
> > Util 클래스로 두지 않는다면, ProductNameValidationUtil에 있는 로직을 Product Entity 클래스와 상품 이름과 과련된 Dto에 넣을지 고민이 됩니다!
> 
> 이부분은 DTO나 DAO 등에서 생성자 등으로 미리 검증할 수 있는데 분리한 감이 있어서 의견드린 거였습니다! 특정 DTO 옆에 있거나 하면 실제로 연관 대상이니까 참조하기도 용이하기도 하고, 아에 DTO안에 있어도 코드가 크게 길어지지 않다면 그렇게 적용되도 효율적이니까요! (`@Valid`로 미리 처리할 수 있으면 객체안에서 처리하기도 좋은데) 한곳에서 쓸 유틸을 공통 패키지 단위인 util로 빠져있는 느낌이 커서 드린 의견이었습니다!
> 
> 이번 주차에 진행한 과정이 꽤 되었는데 고생 많으셨습니다 💯


@gongdongho12 
충돌 해결해 둔 상태입니다!

이번 주차 부터는 branch관리에 조금 더 신경써보도록 하겠습니다..!
그리고 로직 테스트, JPA 기능, 유틸에 대한 것도 고민하고 적용해볼게요! 
디테일한 피드백 감사합니다👍

2024-07-15 05:44 UTC, minju26 commented
@gongdongho12
충돌 해결해 둔 상태입니다!

이번 주차 부터는 branch관리에 조금 더 신경써보도록 하겠습니다..!
그리고 로직 테스트, JPA 기능, 유틸에 대한 것도 고민하고 적용해볼게요!
디테일한 피드백 감사합니다👍

2024-07-15 12:54 UTC, merged