부산대 BE_김동현 3주차 과제 (3단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #386
Opened 2024-07-13 12:13 UTC by donghyun5434

3주차 과제 완료하였습니다

2024-07-13 14:58 UTC, jadie0319 requested changes
안녕하세요 동현님! 
3주차 미션하시느라 고생하셨습니다! :) 
피드백 남겨놨으니 확인 부탁드려요!
궁금하신점 있으시면 DM 주세요~

2024-07-13 14:58 UTC, jadie0319 commented on src/main/java/gift/controller/WishController.java
> +        @RequestParam(defaultValue = "10") int size) {
요청객체에 DTO 를 사용하거나 Pageable 을  사용하는건 어떻게 생각하시나요?
만약 Pageable 객체를 요청객체로 받으면 Pageable 생성 로직을 없앨 수 있겠네요!

그리고 기존의 목록 조회 api 를 페이징 api 로 대체하는 것이니 기존 api 는 삭제하고
해당 api 의 url 에서 page 를 삭제해주시면 될 것 같아요~

2024-07-13 14:58 UTC, jadie0319 commented on src/main/java/gift/domain/Wish.java
> +    private LocalDateTime createdAt;
`@CreatedDate` 라는 것도 있으니 참고하시면 좋을 것 같아요~

2024-07-13 14:58 UTC, jadie0319 commented on src/main/java/gift/repository/WishRepository.java
>      Optional<List<Wish>> findByMemberId(Long memberId);
목록 조회시 대상이 없으면 빈 리스트를 반환할거에요.
Optional 이 필요할까요?

2024-07-13 14:58 UTC, jadie0319 commented on src/main/java/gift/service/WishService.java
>      private final String NOT_FOUND_WISH_MESSAGE = "해당 wish가 존재하지 않습니다.";
에러 메시지가 많아질수록 변수가 많이 생길 것 같아요!
다른 클래스로 분리하면 어떨까요?

2024-07-13 14:58 UTC, jadie0319 commented on src/main/java/gift/service/WishService.java
>      }
비즈니스 로직과 무관한 로직은 아래에 위치 시켜두는게 좋아요.
비즈니스 로직을 위에 위치 시켜놓으면 코드를 읽는 사람이 기능을 파악하기 더 쉬울 것 같아요~

2024-07-13 14:58 UTC, jadie0319 commented on src/main/java/gift/service/WishService.java
> +    public void deleteWish(String memberEmail, Long productId) {
미사용 파라미터는 제거 해주셔도 될것 같아요 :)

2024-07-13 14:58 UTC, jadie0319 commented on src/main/java/gift/service/WishService.java
service 로직이  깔끔해진것 같아요! 👍

2024-07-13 14:58 UTC, jadie0319 commented on src/test/java/gift/repository/MemberRepositoryTest.java
entityManager 는 제거해주셔도 될 것 같아요~
그리고 테스트 코드가 깔끔해졌졌어요 👍

2024-07-13 14:58 UTC, jadie0319 commented on src/test/java/gift/repository/ProductRepositoryTest.java
미사용 코드인 EntityManager 는 제거해주세요!

2024-07-13 14:58 UTC, jadie0319 commented on src/test/java/gift/repository/WishRepositoryTest.java
service 에서 사용중인 Repository 메서드중 테스트 되고 있지 않은 메서드가 몇개 있어요!
DataJpaTest 의 목적은 비즈니스 로직에서 사용되는 메서드들을 테스트하는데 있어요~ 테스트 케이스 추가해주시면 될 것 같습니다!

2024-07-13 14:58 UTC, jadie0319 commented on src/test/java/gift/repository/fixture/MemberFixture.java
Fixture 생성 좋습니다! :)

2024-07-13 14:58 UTC, jadie0319 commented on src/main/java/gift/repository/WishRepository.java
> +    List<Wish> findAllByMemberIdOrderByCreatedAt(Long memberId, Pageable pageable);
Pageable 파라미터로 조회를 하면 Page<Wish> 로 반환값을 받을 수 있어요.
페이징 처리를 하기 위해 Page 를 반환받아야 합니다~
Page 인터페이스에 대해 알아보시면 좋을 것 같아요! :)

2024-07-13 16:21 UTC, jadie0319 commented on src/main/java/gift/service/WishService.java
> +        List<Wish> wishes = wishRepository.findAllByMemberIdOrderByCreatedAt(member.getId(), pageable);
respository 응답으로 Page 를 받아보면 어떨까요?
그리고 Paging 처리 요청에 대한 응답을 어떻게 반환해야 할지도 고민해보시면 좋을 것 같아요!

2024-07-15 05:38 UTC, donghyun5434 commented on src/main/java/gift/service/WishService.java
>      private final String NOT_FOUND_WISH_MESSAGE = "해당 wish가 존재하지 않습니다.";
constants 디렉토리에 에러메세지를 포함하는 클래스를 생성하였습니다

2024-07-15 05:38 UTC, donghyun5434 commented on src/main/java/gift/domain/Wish.java
> +    private LocalDateTime createdAt;
넵

2024-07-15 05:38 UTC, donghyun5434 commented on src/main/java/gift/controller/WishController.java
> +        @RequestParam(defaultValue = "10") int size) {
넵

2024-07-15 05:39 UTC, donghyun5434 commented on src/main/java/gift/service/WishService.java
>      }
넵!

2024-07-15 06:24 UTC, donghyun5434 commented on src/main/java/gift/repository/WishRepository.java
> +    List<Wish> findAllByMemberIdOrderByCreatedAt(Long memberId, Pageable pageable);
List가 아닌 Page로 반환받도록 수정하였습니다

2024-07-15 07:08 UTC, donghyun5434 commented on src/test/java/gift/repository/WishRepositoryTest.java
누락된 메서드에 대한 테스트를 추가하였습니다.

2024-07-15 07:36 UTC, jadie0319 approved these changes
4주차 미션을 위해 머지하겠습니다.
피드백 반영하신건 4주차 미션때 함께 확인해볼게요!
4주차 화이팅 하세요!

2024-07-15 07:36 UTC, merged