전남대 BE_모아림 3주차 과제(3단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #392
Opened 2024-07-13 13:58 UTC by ariimo

2024-07-13 15:31 UTC, dc-choi requested changes
아림님 안녕하세요!

위시 리스트 보기에 대한 부분에도 페이징을 적용해주시면 감사하겠습니다!

해당 부분이 처리가 되면 다시 리뷰 요청 주세요!

2024-07-13 18:46 UTC, ariimo commented
안녕하세요 멘토님!
WishList 페이징을 적용하였습니다. 

음 구현을 진행하며 궁금한 점이 생겨 질문을 남깁니다. JPA나 Pageable 등 점점 spring에서 다루는 영역이 확장되고 있는데, 코드를 짜며 '이런 것도 미리 구현된 메소드가 있을까?'와 비슷한 류의 생각을 하곤 합니다. 앞서 step 2에서도 아래와 같은 comment를 남긴 기억이 있는데요... 

> JPA에 ID가 아닌 특정 칼럼을 기준으로 Wish 를 찾는 메서드가 없는 줄 알고 선택했던 방법입니다. 멘토님의 리뷰를 보고 다시 찾아보니 있더군요...하하 이 부분도 수정했습니다!

spring 자체가 거대하다보니(특히 입문자에게), 이걸 하나하나 외우는 건 말이 안 되는 것 같아서요. 사실, 이런 의문조차 남기지 않고 spring이 제공하는 부분을 직접 구현하며 넘긴 적도 꽤 있지 않을까 싶습니다. 적으며 생각해 보니, 개발 공부에 대한 꽤 거시적인 질문이 되었네요.. 멘토님께서는 이런 부분에 있어 어떻게 공부를 진행하셨나요??

2024-07-14 06:18 UTC, dc-choi requested changes
안녕하세요! step3 과제를 확인하였습니다~!

자세한 내용은 코멘트를 남겨두었으니 확인 바랍니다.

질문을 주셨군요! 제가 아는 선에서 말씀을 드려보겠습니다.

> spring 자체가 거대하다보니(특히 입문자에게), 이걸 하나하나 외우는 건 말이 안 되는 것 같아서요. 사실, 이런 의문조차 남기지 않고 spring이 제공하는 부분을 직접 구현하며 넘긴 적도 꽤 있지 않을까 싶습니다. 적으며 생각해 보니, 개발 공부에 대한 꽤 거시적인 질문이 되었네요.. 멘토님께서는 이런 부분에 있어 어떻게 공부를 진행하셨나요??

어려운 질문이네요... 저도 입문할 때 spring을 학습하는게 너무 어려웠어요...

저 같은 경우 왜? 라는 질문을 던지면서 깊이 공부하려고 했었던거 같아요.

요즘은 IDE나 ChatGPT, GitHub Copilot 같은 툴이 많이 좋아져서 그런 도구들을 사용해서 더 빠르게 학습도 가능하니...

이 부분은 도구를 잘 사용해서 학습하시면 될 거 같습니다!

뭔가 도움이 못되어 드린거 같아서 죄송하네요...

2024-07-14 06:18 UTC, dc-choi commented on src/main/java/gift/controller/PageController.java
> +    public String indexPageGet(Model model, @PageableDefault(page = 0, size = 10, sort = "id", direction = Direction.DESC) Pageable pageable) {
`@PageableDefault` 는 어떤 어노테이션인가요?

2024-07-14 06:18 UTC, dc-choi commented on src/main/java/gift/controller/WishController.java
> +    public ResponseEntity<WishListRequestStateDTO> getWishlistById(@LoginMember MemberDto memberDto, @RequestParam int page, @RequestParam int size) {
값이 누락되는 경우 어떻게 처리되는지 궁금합니다!

이 부분에 대한 예외처리가 필요해보여요!

2024-07-14 13:45 UTC, ariimo commented on src/main/java/gift/controller/PageController.java
> +    public String indexPageGet(Model model, @PageableDefault(page = 0, size = 10, sort = "id", direction = Direction.DESC) Pageable pageable) {
@PageableDefault 는 페이징 요청의 기본값을 설정하는 어노테이션입니다! URL 쿼리 파라미터에서 값을 받아옵니다.

2024-07-14 13:46 UTC, ariimo commented on src/main/java/gift/controller/WishController.java
> +    public ResponseEntity<WishListRequestStateDTO> getWishlistById(@LoginMember MemberDto memberDto, @RequestParam int page, @RequestParam int size) {
값이 누락되는 경우를 고려한 디폴트값 처리와 예외처리를 추가하였습니다!

2024-07-14 13:50 UTC, ariimo commented
> 요즘은 IDE나 ChatGPT, GitHub Copilot 같은 툴이 많이 좋아져서 그런 도구들을 사용해서 더 빠르게 학습도 가능하니...
이 부분은 도구를 잘 사용해서 학습하시면 될 거 같습니다!

멘토님께서 죄송할 부분은 정말정말 아닌 것 같습니다! 이런저런 도구를 이용하며 경험이 쌓여야 하나 보군요...! 답변 감사드립니다!!

2024-07-15 01:20 UTC, dc-choi approved these changes
아림님~ step3까지 하시느라 고생하셨습니다!

이번주도 파이팅~!

2024-07-15 01:20 UTC, merged