전남대 BE_박규현 3주차 과제 (step3)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #393
Opened 2024-07-13 14:02 UTC by pinkbeenyeti

3주차 페이지네이션을 진행하였습니다!

과제하면서 궁금한 사항은 아래와 같습니다.

N+1 문제를 잘 해결하였는가?

다른 학생들의 코드 리뷰도 보면서 멘토님들이 N+1 문제에 대해 언급하시는 것을 보았습니다.
이 N+1 문제가 무엇인지 궁금하여 조사해 보니 연관 관계가 설정된 엔티티를 조회 시 조회된 데이터 갯수만큼 조회 쿼리가 추가로 발생하는 문제라는 것을 알았습니다.
혹시 이 문제가 발생할 까 싶어 애플리케이션을 실행 후 페이지를 왔다갔다 하며 콘솔을 확인 해 보았을 때 제가 보기에는 N+1 문제가 발생하지 않은 듯 했습니다.
하지만 아직 공부하는 입장에서 발견하지 못한 부분이 있을 수 있겠다고 생각하여 이 부분을 잘 해결했는 지 궁금합니다!

2024-07-13 15:27 UTC, dc-choi requested changes
안녕하세요 규현님! step3 과제 내역 확인하였습니다!

자세한 코멘트를 작성하였습니다! 확인 부탁드려요~!

질문에 대한 답도 드리도록 하겠습니다!

> N+1 문제를 잘 해결하였는가?

현재 코드에서는 없어보여서 딱히 멘트를 남기지는 않았습니다.

다만, 이 부분에 대한 것을 학습하고 싶으시다면 직접 해당 문제가 발생할 수 있는 코드를 작성해보시고 해결해보시는 것도 방법이라고 생각합니다!

2024-07-13 15:27 UTC, dc-choi commented on src/main/java/gift/controller/ProductController.java
> +    public String getAllProducts(Model model, @PageableDefault(size = 3, sort = "id") Pageable pageable) {
`@PageableDefault`을 사용하신 것은 너무 훌륭합니다.

다만, query 상으로 이미 오름차순 정렬이 되어오기 때문에 어떤 부분으로 정렬할 지에 대한 로직이 의미가 없어보입니다.

2024-07-13 15:27 UTC, dc-choi commented on src/main/java/gift/controller/WishListController.java
> +    public String getWishlist(@LoginUser User user, Model model, @PageableDefault(size = 3, sort = "id") Pageable pageable) {
마찬가지로 `@PageableDefault`을 사용하신 것은 너무 훌륭합니다.

다만, query 상으로 이미 오름차순 정렬이 되어오기 때문에 어떤 부분으로 정렬할 지에 대한 로직이 의미가 없어보입니다.

2024-07-13 15:27 UTC, dc-choi commented on src/main/java/gift/controller/WishListController.java
> +    public String addWishProductPage(@LoginUser User user, Model model, Pageable pageable) {
이 부분에서는 `@PageableDefault`가 적용되지 않은 이유를 알 수 있을까요?

2024-07-13 15:27 UTC, dc-choi commented on src/main/java/gift/controller/WishListController.java
> +    public String deleteWishProduct(@LoginUser User user, @RequestBody WishRequestDTO wishRequestDTO, Model model, @PageableDefault(size = 3, sort = "id") Pageable pageable) {
마찬가지로 `@PageableDefault`을 사용하신 것은 너무 훌륭합니다.

다만, query 상으로 이미 오름차순 정렬이 되어오기 때문에 어떤 부분으로 정렬할 지에 대한 로직이 의미가 없어보입니다.

2024-07-13 15:27 UTC, dc-choi commented on src/main/java/gift/repository/ProductRepository.java
> +    Page<Product> findAllById(@Param("ids") List<Long> productsId, Pageable pageable);
이 부분에서는 `pageable` 매개변수를 사용하지 않아보이는데 혹시 매개변수로 받아오는 이유가 있을 까요?

2024-07-13 15:30 UTC, dc-choi commented on src/main/java/gift/repository/ProductRepository.java
> +    Page<Product> findAll(Pageable pageable);
추가적으로 이 부분은 이미 `JpaRepository`에 정의되어 있는 부분입니다.

다시 구현하실 필요가 없습니다.

2024-07-13 15:45 UTC, pinkbeenyeti commented on src/main/java/gift/repository/ProductRepository.java
> +    Page<Product> findAllById(@Param("ids") List<Long> productsId, Pageable pageable);
이 부분에서 pageable 매개 변수를 받지 않으니 오류가 발생하였기 때문입니다!

오류 내용
`Could not create query for public abstract org.springframework.data.domain.Page gift.repository.ProductRepository.findAllById(java.util.List); Reason: Paging query needs to have a Pageable parameter; Offending method: public abstract org.springframework.data.domain.Page gift.repository.ProductRepository.findAllById(java.util.List)`

이러한 오류가 발생했었습니다. 오류 내용을 잘 살펴보니 Page를 반환하기 위해 사용했었던 findAllById 함수에서 Paging 쿼리를 사용하는데 Pageable 파라미터를 받지 못해 오류가 발생했다는 사실을 알았습니다. 이를 해결하기 위해 Pageabel pageable 매개 변수를 추가하였고 오류를 해결할 수 있었습니다!

2024-07-13 15:46 UTC, pinkbeenyeti commented on src/main/java/gift/repository/ProductRepository.java
> +    Page<Product> findAll(Pageable pageable);
피드백 감사드립니다! 삭제하고 실행해 보았더니 실제로 작동하는 것까지 확인하였습니다. 더 열심히 공부하겠습니다!

2024-07-13 15:48 UTC, pinkbeenyeti commented on src/main/java/gift/controller/ProductController.java
> +    public String getAllProducts(Model model, @PageableDefault(size = 3, sort = "id") Pageable pageable) {
아하 이런 부분은 체크하지 못했던 것 같습니다. 피드백 감사드립니다. 수정하였습니다!

2024-07-13 15:48 UTC, pinkbeenyeti commented on src/main/java/gift/controller/WishListController.java
> +    public String getWishlist(@LoginUser User user, Model model, @PageableDefault(size = 3, sort = "id") Pageable pageable) {
피드백 감사드립니다. 수정하였습니다!

2024-07-13 15:48 UTC, pinkbeenyeti commented on src/main/java/gift/controller/WishListController.java
> +    public String deleteWishProduct(@LoginUser User user, @RequestBody WishRequestDTO wishRequestDTO, Model model, @PageableDefault(size = 3, sort = "id") Pageable pageable) {
피드백 감사드립니다. 수정하였습니다!

2024-07-13 16:01 UTC, pinkbeenyeti commented on src/main/java/gift/controller/WishListController.java
> +    public String addWishProductPage(@LoginUser User user, Model model, Pageable pageable) {
앗.. 솔직히 말씀드리면 이 부분은 제가 꼼꼼하게 확인하지 못하고 넘어갔던 것 같습니다..

사실 계속 애를 먹었던 부분이 wishlist 페이지에서 다음 페이지를 클릭하여도 넘어가지 않던 문제를 겪고 있었고, addWishProduct 페이지에서도 페이지네이션을 구현할 때 같은 로직을 사용하려고 하였기 때문에 wishlist의 문제를 해결하기 위해 넘어 갔었습니다.

이후 다음 페이지로 넘어가지 않는 이유를 발견 하였고 해결하였다는 기쁨에 얼른 PR을 하다 보니 이 부분도 똑같이 적용만 하면 되는 부분인데 제가 체크하지 못하고 넘어간 것 같습니다...

앞으로는 더 꼼꼼하게 코드를 체크하여 이런 일이 없도록 주의하겠습니다! 죄송합니다!!

2024-07-14 06:29 UTC, dc-choi approved these changes
규현님! 더 코멘트 해드릴 부분은 없어보이네요.

이번주도 step3까지 진행하시느라 고생하셨어요~!

시간이 되신다면 E2E Test도 같이 하셨으면 좋겠습니다!

2024-07-14 06:29 UTC, merged

2024-07-14 08:13 UTC, pinkbeenyeti commented
항상 감사합니다~!