충남대 BE_이택 3주차 과제 step3
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #396
Opened 2024-07-13 14:20 UTC by LeeTaek2T

2024-07-13 19:52 UTC, LeeTaek2T commented
[이번 pr에서는 총 3가지를 구현하였습니다.]
 1)step3
 2)wishList test
 3)member test

**궁금한점**
1. 하나의 Service 클래스에 다른 Service클래스, Repository들을 이용해도 되는지 궁금합니다.
 -ex) WishListService에서 WishListRepository, MemberRepository 사용
 -ex) MemberService에서 JwtService이용

2. postman을 쓰다보니 어떤 것이 잘못 되었는지 파악이 가능하며, 다양한 예제를 사용하여 혼자서 test를 하다보니 굳이 Test 코드를 짜야하는 건가? 의문이 생겼습니다. Test코드를 꼭 짜야하는 걸까요?

2024-07-16 06:24 UTC, ksy90101 requested changes
고생하셨습니다!

2024-07-16 06:24 UTC, ksy90101 commented on src/main/java/gift/Controller/MemberController.java
> +  public ResponseEntity<MemberDto> memberSignUp(@Valid @RequestBody MemberDto memberDtoInfo) {
memberController가 명시되어 있고, 동사로 쓰는게 메서드 명은 좋습니다.

signUp으로만 써도 무관할거 같아요.
아래도 동일합니다.

2024-07-16 06:24 UTC, ksy90101 commented on src/main/java/gift/Controller/ProductController.java
> +  public ResponseEntity<Page<ProductDto>> getAllProducts(Pageable pageable) {
page에 대한 default값은 필요 없을까요?

2024-07-16 06:24 UTC, ksy90101 commented on src/main/java/gift/DTO/ProductDto.java
> +  public void setId(Long id) {
setter를 제거해도 될거 같아요!

2024-07-16 06:24 UTC, ksy90101 commented on src/main/java/gift/DTO/WishList.java
> +  @ManyToOne
cascade를 제거하신 이유가 있나요?

2024-07-16 06:29 UTC, LeeTaek2T commented on src/main/java/gift/Controller/MemberController.java
> +  public ResponseEntity<MemberDto> memberSignUp(@Valid @RequestBody MemberDto memberDtoInfo) {
네! 알겠습니다

2024-07-16 06:39 UTC, LeeTaek2T commented on src/main/java/gift/Controller/ProductController.java
> +  public ResponseEntity<Page<ProductDto>> getAllProducts(Pageable pageable) {
필요한 거 같습니다! 추가하겠습니다

2024-07-16 06:44 UTC, LeeTaek2T commented on src/main/java/gift/DTO/ProductDto.java
> +  public void setId(Long id) {
id는 자동으로 생성되게 했으니 id에 대한 setter는 필요없는거 같습니다!
제거하겠습니다

2024-07-16 07:01 UTC, LeeTaek2T commented on src/main/java/gift/DTO/WishList.java
> +  @ManyToOne
wishList를 먼저 추가하고, product를 추가하면 중복 오류가 일어날 것이라 생각해서 지웠습니다.
그런데 애초에 wishList를 추가하고 product를 추가하는 과정을 못하므로, 다시 해당 cascade를 추가하여 관련 entity 업데이트나 삭제 시 WishList에도 반영이 되게 하겠습니다!

2024-07-16 07:18 UTC, ksy90101 approved these changes
고생하셨습니다!!
4주차에서 뵐게요~
홧팅입니다!

2024-07-16 07:19 UTC, ksy90101 commented on src/main/java/gift/DTO/ProductDto.java
> +  public void setId(Long id) {
id뿐만 아니라 다른 것들도 setter가 다 필요 없는거 아닌가요?
DTO는 생성자의 리플렉션으로 인자를 넣을수 있으니깐요!

2024-07-16 07:19 UTC, merged