경북대 BE_박준석_3주차 과제 (3단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #398
Opened 2024-07-13 15:32 UTC by Lucerna00

상품과 위시 리스트에 페이지네이션을 적용하였습니다.
그리고 mock에 대해 알아보고자 간단하게 product 서비스 테스트를 해보았습니다.

Q. step2 피드백을 반영하고자 product 삭제 메서드를 수정하였습니다. 하지만 삭제가 실제로  이루어지지 않았고, 이 원인에 대해 생각해 보았습니다.
문제의 코드는 다음과 같습니다.
```
ProductDTO deletedProductDTO = getProduct(id);
productRepository.delete(deletedProductDTO.toEntity());
```
이때 DTO의 `toEntity()`에 의해 `new Product()`가 delete로 넘어갑니다.
여기서 저는 `new Product()`가 비영속 상태로 취급되기 때문에 삭제되지 않는다고 생각하였는데 맞는지 궁금합니다.

Q. 상품 수정 메서드에서 저는 업데이트 내용이 담긴 DTO로 새로운 엔티티를 생성하여 save(merge)하는 식으로 만들었습니다.
```
Product product = new Product(id, productDTO.name(), productDTO.price(), productDTO.imageUrl());
return productRepository.save(product).toDTO();
```
그런데 테스트 코드를 작성하는 과정에서 findById로 찾은 상품에 setter로 업데이트 내용을 반영하고 save하는 식이 더 낫겠다고 생각이 들었습니다. 하지만 엔티티는 setter를 지양해야 한다는 말도 있는데, 어떤 방법이 더 나은지 궁금합니다.

2024-07-14 17:29 UTC, gongdongho12 requested changes
테스트를 해보려고 노력하신 점 너무 좋네요 👍🏼 

### 질문에 대해서 정리하자면

> Q. step2 피드백을 반영하고자 product 삭제 메서드를 수정하였습니다. 하지만 삭제가 실제로 이루어지지 않았고, 이 원인에 대해 생각해 보았습니다.
문제의 코드는 다음과 같습니다.
```ProductDTO deletedProductDTO = getProduct(id);
productRepository.delete(deletedProductDTO.toEntity());
이때 DTO의 toEntity()에 의해 new Product()가 delete로 넘어갑니다.
```
> 여기서 저는 new Product()가 비영속 상태로 취급되기 때문에 삭제되지 않는다고 생각하였는데 맞는지 궁금합니다.

실제 delete 쿼리가 발생했을때의 id가 쿼리로 찍힐 거자나요
그 값을 확인해보시면서 디버깅하는게 가장 정확하긴 한데 말씀주신 내용이 가장 합리적인 의견입니다!
이런 경우에 저는 deleteById를 주로 사용하는데 delete는 DAO를 지울때 사용하는 메서드인데 toEntity는 준영속도 이루어지지 않아 삭제가 당연히 일어나게 되지 않습니다

> Q. 상품 수정 메서드에서 저는 업데이트 내용이 담긴 DTO로 새로운 엔티티를 생성하여 save(merge)하는 식으로 만들었습니다.
```
Product product = new Product(id, productDTO.name(), productDTO.price(), productDTO.imageUrl());
return productRepository.save(product).toDTO();
```
> 그런데 테스트 코드를 작성하면서 findById로 찾은 상품에 setter로 업데이트 내용을 반영하고 save하는 식이 더 나을 것 같다는 생각이 들었습니다. 하지만 엔티티는 setter를 지양해야 한다는 말도 있는데, 어떤 방법이 더 나은지 궁금합니다.

지금은 배우지 않았지만 영속된 상태에서 @Transactional을 걸어두고 각 엔티티를 업데이트 하면 트랜잭션으로 감싼 메서드가 끝날때 commit이 일어나게 됩니다
그러면 DAO의 수정 사항이 반영되게 되는데 제가 만약 업데이트 해야 한다면 이렇게 작업할 것 같습니다

2024-07-14 17:29 UTC, gongdongho12 commented on src/main/java/gift/controller/AdminController.java
> +        model.addAttribute("pages", productService.getProducts(page));
page만 처리하면 나중에 갯수를 조절하기 어려워서 Pageable 객체를 사용하는데요
관련해서 [[참고]](https://velog.io/@dhk22/Spring-%EC%84%B8%EC%83%81-%EA%B0%84%EB%8B%A8%ED%95%9C-Pagination-Controller%EC%97%90%EC%84%9C-Pageable-%EA%B0%9D%EC%B2%B4-%EB%B0%9B%EC%95%84-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0)해보시면 좋을 것 같습니다

2024-07-14 17:29 UTC, gongdongho12 commented on src/main/java/gift/controller/ProductController.java
> +        System.out.println("controller: " + id);
이런 로깅을 sysout으로 할 수 있는데 Logger 같은 객체로 에러 로그나 인포성 로그등을 구분해서 적용해보면 추후 디버깅 관점에서 도움이 되지 않을까요?

2024-07-14 17:29 UTC, gongdongho12 commented on src/test/java/gift/service/ProductServiceTest.java
> +    }
mockk을 사용한 테스트 👍🏼

2024-07-14 17:31 UTC, gongdongho12 approved these changes
2단계 리뷰에서 대부분을 수정해 주셔서 3단계는 테스트 위주였네요

리뷰 남긴 부분한번 참고만 해주시면 좋을 것 같습니다

고생 많으셨습니다

2024-07-14 17:31 UTC, merged

2024-07-15 05:43 UTC, Lucerna00 commented on src/main/java/gift/controller/AdminController.java
> +        model.addAttribute("pages", productService.getProducts(page));
말씀대로 controller에서 pageable을 사용하니 size와 sort를 다루기 쉬워졌습니다!

2024-07-15 05:43 UTC, Lucerna00 commented on src/main/java/gift/controller/ProductController.java
> +        System.out.println("controller: " + id);
지금까진 간단히 sysout을 사용하였는데, Logger도 사용해 보겠습니다.