경북대 BE_김영인 3주차 과제(3단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #399
Opened 2024-07-13 15:34 UTC by Youngini

2단계에서 받은 피드백과 합쳐서 3단계를 진행하였습니다.

2024-07-14 10:40 UTC, Youngini commented
어제 과제를 제출했는데, 리뷰 요청 버튼이 제대로 안눌렸었던거 같습니다,,ㅜㅜ 다음엔 2번 확인하겠습니다,,!

2024-07-14 15:44 UTC, gongdongho12 requested changes
기존 1, 2주차에 JPA를 더하는 과정인데도 잘 따라오시느라 고생많으셨습니다 💯

2024-07-14 15:44 UTC, gongdongho12 commented on README.md
> +    - [ ] WishRepositoryTest 작성
작성된 부분 구분 감사합니다 👍🏼

2024-07-14 15:44 UTC, gongdongho12 commented on build.gradle
> +    //implementation 'org.springframework.security:spring-security-test'
시큐리티 제외 👍🏼

2024-07-14 15:44 UTC, gongdongho12 commented on src/main/java/gift/config/JwtConfig.java
> +    }
단순 빈만 등록하는 경우엔 JwtTokenProvider 코드를 분리하기 보다는 메서드로 호출하는게 어떠실까요?

아니면 JwtTokenProvider를 Component로 분리해서 빈으로 주입하는 방법도 있을 것 같습니다

2024-07-14 15:44 UTC, gongdongho12 commented on src/main/java/gift/config/WebConfig.java
> +    }
addArgumentResolvers는 WebConfig에서 override도 아닌데 실제로 쓰여지는 코드인지 한번 디버깅 해보시면 좋을 것 같아요
아마 WebMvcConfigurationSupport를 상속받아서 override 설정을 해줬어야 할 것 같은데 이런 부분도 테스트 코드에서 검증될 수 있도록 작업이 필요하겠죠?

2024-07-14 15:44 UTC, gongdongho12 commented on src/main/java/gift/controller/MemberController.java
> +    private static final String AUTHENTICATE_HEADER = "Authenticate";
이 설정값은 여기에만 쓰기 보다는 Constants 등으로 한곳에 모아두면 어떨까요?
아래 Bearer 두 같이요

2024-07-14 15:44 UTC, gongdongho12 commented on src/main/java/gift/controller/ProductController.java
> +            @RequestParam(defaultValue = "asc") String direction) {
페이징 처리에 많은 파라미터를 지정하기 힘들다보니 편하게 사용할 수 있는 파라미터 옵션이 있는데요
[[참고]](https://velog.io/@dhk22/Spring-%EC%84%B8%EC%83%81-%EA%B0%84%EB%8B%A8%ED%95%9C-Pagination-Controller%EC%97%90%EC%84%9C-Pageable-%EA%B0%9D%EC%B2%B4-%EB%B0%9B%EC%95%84-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0) 해서 작업해보시면 더 깔끔해질 것 같아요!

2024-07-14 15:44 UTC, gongdongho12 commented on src/main/java/gift/domain/Product.java
> +    private List<Wish> wishes = new ArrayList<>();
casecade 옵션도 적용해주셨군요
간단하게 적용되는 로직에선 편하게 사용할 수 있지만 쿼리가 여러번 동작하는 형태로 바뀌기에 실제 사용에는 고민해보면 좋을 것 같습니다 👍🏼 

그리고 join해서 사용하는 부분에는 fetchType을 lazy로 적용하는게 좋은데요
관련해서 N+1 문제에 대해서 한번 찾아보시면 좋을 것 같습니다

2024-07-14 15:44 UTC, gongdongho12 commented on src/main/java/gift/domain/Product.java
> +    Long product_id;
이부분은 id로 사용안하고 product_id로 한 이유가 궁금합니다 특히 다른 곳은 camelcase 사용해주셨는데 이곳만 snakecase라서 컨벤션도 어긋나니까요 👀

2024-07-14 15:44 UTC, gongdongho12 commented on src/main/java/gift/domain/Wish.java
> +    private Product product;
이부분은 위와 다르게 Lazy 👍🏼

2024-07-14 15:44 UTC, gongdongho12 commented on src/main/java/gift/service/MemberService.java
> +        return memberRepository.findById(memberId)
이부분은 테스트 하시다가 다시 반영이 안된 부분일까요?
아니면 유저가 정상적으로 잡히지 않아서 임시로 멤버아이디는 1로 정의해둔 부분인지 궁금합니다 ❓

2024-07-14 15:44 UTC, gongdongho12 commented on src/main/java/gift/service/ProductService.java
> +        Product product = new Product(productDto.getName(), productDto.getPrice(), productDto.getImageUrl());
CreateProductDto -> Product로 만들기 위해 쓰는 부분인데 CreateProductDto에 toProduct 같은 메서드가 있으면 깔끔하게 정의할 수 있지 않을까요?

DTO와 Entity (DAO) 간 메서드도 클래스 내부에 넣으면 관련해서 찾을 수 있는 부분 참고해주시면 좋을 것 같습니다

2024-07-14 15:44 UTC, gongdongho12 commented on src/main/java/gift/service/ProductService.java
> +        product.setImageUrl(productDto.getImageUrl());
이부분도 같은 관점이겠죠?

2024-07-14 15:44 UTC, gongdongho12 commented on src/main/resources/application.properties
> +spring.jpa.show-sql=true
주석이 자주 ??로 올라오는데 파일 저장이 UTF-8로 되어있지 않는지 의심이 드네요 🤔

2024-07-14 15:44 UTC, gongdongho12 commented on src/test/java/gift/MemberRepositoryTest.java
> +    }
테스트 주석으로 깔끔한 구분이 👍🏼 

`Member member = new Member("test@example.com", "password");` 이런 값들은 같이 사용하고 있는데 fixture나 상단 변수로 등록해두면 좋지 않을까요?

2024-07-14 17:19 UTC, gongdongho12 commented
PR 올리실 때 커밋 올리는 방법에 대해 숙지가 필요할 것 같아요
Step 0 PR은 base
Step 1은 Step 0 커밋 위의 내용부터 등록
Step 2는 Step 1 커밋 위의 내용부터
Step 3는 Step 2
근데 매번 처음부터 끝까지 포함된 내용으로 Step이 들어가는 것 같아요

2024-07-15 05:11 UTC, Youngini commented
요번주차 과제부터는 그렇게 하도록 하겠습니다!
번거롭게 해드려 죄송합니다 🥲

2024-07-15 05:49 UTC, Youngini commented on src/main/java/gift/config/JwtConfig.java
> +    }
config로 분리를 많이 하길래 한번해봤던 것인데 메서드로 호출하는 방식이 JWT 토큰 생성과 검증 기능만 볼 땐 코드 이해가 더 용이할것 같아서 그러면 멘토님 말씀대로  JwtProvider에서 메서드로 호출하는 방식으로 수정하도록 하겠습니다.

2024-07-15 06:53 UTC, Youngini commented on src/main/java/gift/controller/MemberController.java
> +    private static final String AUTHENTICATE_HEADER = "Authenticate";
Constants라는 class를 만들어서 따로 다 모았습니다! 다음부턴 설정값을 한곳에 모으도록 구현해보겠습니다.

2024-07-15 12:58 UTC, gongdongho12 commented on src/main/java/gift/config/JwtConfig.java
> +    }
크게 구분지어 보자면 `@Configuration`은 특정 주입된 빈을 상속받아서 거기에서 객체를 수정해서 넣는 경우에 사용하구요
`@Component`는 단순 Bean만 등록하는 경우에 사용하는 방식이라
위와 같이 jwtProvider만 쓰는 경우엔 Component가 맞지 않을까 싶습니다!
아마 기존엔 SpringSecurity의 설정값을 상속받아서 그걸 빈으로 객체 변환해서 주입하기 위해서 Configuration을 사용했다고 생각해주시면 이해하시는데 용이하실 거에요!

2024-07-15 12:58 UTC, gongdongho12 commented on src/main/java/gift/config/WebConfig.java
> +    }
@Youngini 이부분 중요한 부분인데 한번 체크하구 넘어가주세요 🙏🏼

2024-07-15 13:00 UTC, gongdongho12 approved these changes
고생하셨습니다 💪🏼 
그래도 리뷰 드린 내용중에 잘 모르고 지나갔던 부분은 한번 다시 체크해주세요

2024-07-15 13:00 UTC, merged