강원대 BE_김송목 3주차과제 (Step 3)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #408
Opened 2024-07-13 19:25 UTC by kimsongmok

Step2 피드백 반영, Step3의 페이지네이션을 구현해봤습니다.

1. id를 세팅할 일이 어떤게 있을까요? (Product.java 중)
  public void setId(Long id) {
    this.id = id;
  }
이 부분을 제거해서 해결했습니다!
JPA @Id 어노테이션을 사용하고 있으므로 setter를 사용할 일이 없을 것 같습니다.

2.좀 더 나아가서 update메서드안에 넘어온값들이 유효한 값인지에 대한 검증도 있으면 더 좋을거같습니다.(ProductService.java 중)
product.update(productDetails.getName(), productDetails.getPrice(), productDetails.getImageUrl());

  public boolean updateProduct(Long id, ProductDto productDetails) {
    productDetails.validate();
    return productRepository.findById(id).map(product -> {
      product.update(productDetails.getName(), productDetails.getPrice(), productDetails.getImageUrl());
      productRepository.save(product);
      return true;
    }).orElse(false);
  }
  이렇게 validate 메서드로 검증하는 것으로 해결했습니다!
  
3. 이 클래스에 `@Size` 애노테이션, `@column` 애노테이션 등 다양한 애노테이션들이 붙어있어요. 전 계층에서 사용하기에는 특정 계층에 의존적인 부분들이 많은것 같은데요, 어떻게 개선해볼 수 있을까요?(Product.java 중)

일단 저는 어떻게 개선할 수 있을까에 대한 생각을 해봤습니다.
계속해서 찾아보니 계층을 나누는 방식이 있었습니다. 그래서 Product의 엔티티 클래스(Product.java) 그리고 DTO클래스(ProductDto.java)를 만들어 책임을 나누는 것으로 해결해보았습니다.
엔티티 클래스는
1) 데이터베이스와 직접적으로 상호작용
2) 데이터베이스 테이블과 매핑되는 필드들 포함
3) 데이터베이스의 데이터를 관리하는 비즈니스 로직 포함
DTO클래스
1) 데이터 전송, 검증 담당
2) 서비스와 컨트롤러 간의 데이터 전달을 위한 구조체 역할

과연 멘토님이 의도한것이 맞는지 궁금합니다!

또, 페이지네이션을 부족하게나마 구현해보았습니다. 리뷰 잘 부탁드립니다.

2024-07-14 12:28 UTC, jaymarystella requested changes
안녕하세요
3단계 구현하느라 고생많으셨어요. 
몇가지 코멘트 남겼으니 확인부탁드릴게요

2024-07-14 12:28 UTC, jaymarystella commented on src/main/java/gift/model/ProductDto.java
> +    }
validate메서드를 외부에서 호출할일이 있을까요?

2024-07-14 12:28 UTC, jaymarystella commented on src/main/java/gift/model/ProductDto.java
> +    }
else문을 사용하지 않고 구현해보면 어떨까요?

2024-07-14 12:28 UTC, jaymarystella commented on src/main/java/gift/model/ProductDto.java
> +  }
이것도 필요한 부분일까요?

2024-07-14 12:28 UTC, jaymarystella commented on src/main/java/gift/controller/WishlistController.java
>  public class WishlistController {
```
@PostMapping
   public ResponseEntity<Wishlist> addWishlistItem(@RequestBody Wishlist wishlist, @LoginMember Member member) {
     wishlist.setMember(member);
     Wishlist savedWishlist = wishlistService.addWishlistItem(wishlist);
     return ResponseEntity.ok(savedWishlist);
   }
```

이거 wishlist에 member를 바로 세팅해버리면 본인정보가 아닌데 수정을 해버리는 문제가 발생할거같은데요 로직 한번 확인부탁드립니다.
그리고 로직은 최대한 컨트롤러에서 작성하지 않으시는걸 추천드립니다.

2024-07-14 12:28 UTC, jaymarystella commented on src/main/java/gift/service/WishlistService.java
> +    Pageable pageable = PageRequest.of(page, size);
Pageable을 만들어보셨네요~
인자값에 대한 검증은 필요없을까요?

2024-07-15 07:14 UTC, kimsongmok commented
최대한 피드백을 반영해보았습니다!

1. validate메서드를 외부에서 호출할일이 있을까요?
-> service에서 직접 구현하는걸로 바꾸었습니다
2. else문을 사용하지 않고 구현해보면 어떨까요?
-> if로 바꾸었습니다!
3. 이것도 필요한 부분일까요? (ProductDto.java 중 기본 생성자)
-> 없애보았습니다!
4. 이거 wishlist에 member를 바로 세팅해버리면 본인정보가 아닌데 수정을 해버리는 문제가 발생할거같은데요 로직 한번 확인부탁드립니다.
그리고 로직은 최대한 컨트롤러에서 작성하지 않으시는걸 추천드립니다.
-> service로 옮겨서 로직 재구성했습니다!
5. Pageable을 만들어보셨네요~
인자값에 대한 검증은 필요없을까요?
-> 인자값 검증 로직을 일단 써봤습니다!

2024-07-15 13:58 UTC, jaymarystella approved these changes
안녕하세요.
리뷰 반영주신것 확인했습니다. 어려운점있으시면 말씀주시구 이번주차도 화이팅입니다!

2024-07-15 13:58 UTC, jaymarystella commented
제가 남겨드린 피드백을 수동적으로 모두 반영했다라고만 남겨주셨는데요, 물론 공감하셔서 하신걸수도있겠지만 조금의 공부흔적을 남겨주신다든지, 반론이라든지 이런것들을 같이 해주셔야 조금이라도 더 얻어가시는게 있을거에요.

2024-07-15 13:58 UTC, merged