전남대 BE_김보민_3주차 과제(2단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #416
Opened 2024-07-14 06:14 UTC by KBM05haruin30

### 1단계 리뷰 수정
1. 기본 생성자를 private로 해도 되는가?
   - JPA가 매핑한 Entity를 조회할 때 hibernate가 생성한 proxy 객체를 사용하여 연관된 데이터를 실제 사용하는 시점에서 조회 가능합니다. proxy 객체는 직접 만든 객체 class를 상속하기 때문에 private로 기본 생성자를 선언하면 파생 클래스로부터의 상속 형태가 접근 불가가 되어버립니다. 그래서 private로 선언하면 안된다고 생각합니다.
2. 조회 쿼리의 `@Transactional`
   - 조회 쿼리에는 성능 최적화와 안정성을 위해서 `@Transactional(readOnly=true)`를 사용할 수 있습니다. 데이터 일관성을 위해 삭제, 추가, 업데이트에만 붙이는 것인 줄 알았는데 readOnly라는 옵션을 새로 알게 되었습니다. 감사합니다!
3. `@BeforeEach` 관련 질문
   - `private Product invalidProduct;`로 선언하고 각 테스트마다 `invalidProduct = new Product(...)를 사용해 테스트별로 다른 예외가 발생하도록 작성했습니다. 수정한 것은 예외가 발생할 수 있는 객체들을 `@BeforeEach`에 작성해 두었습니다. 이 객체들은 각 테스트 코드에서 한 번만 수행되는데 이렇게 작성하게 되면 코드가 길어지는 것 아닌가 라는 생각이 들었습니다. 
# 2단계
### 코드 작성하면서 어려웠던 점
상품 목록에 있는 상품을 위시 리스트에 추가한 뒤 상품 목록에서 삭제를 해버리면 에러가 발생했습니다. 이를 해결하고자 찾은 것이 CASCADE입니다. cascade의 타입 중 remove를 사용해서 해결은 했습니다. cascade와 함께 '고아 객체', 'orphanRemoval'도 찾게 되었습니다. 이 둘의 관계가 아직 무엇인지 잘 모르겠습니다...
일대다, 다대일 개념이 처음에 헷갈려서 반대로 작성을 했었습니다. 하지만 강의 자료를 보고 검색도 하며 수정을 했습니다.

### 중점적으로 봐주셨으면 하는 점
검증 메소드를 분리했는데 이렇게 분리하는 것인지 봐주셨으면 합니다. 테스트 코드도 잘 작성되었는지 봐주셨으면 합니다. 추가로 관계 매핑이 잘 되었는지도 봐주셨으면 합니다.

2024-07-14 12:54 UTC, Hongdonggeon requested changes
안녕하세요 보민님 
미션 수행하느라 수고많으셨어요~~
코멘트 남겨놓으니 확인해주세요!

2024-07-14 12:54 UTC, Hongdonggeon commented on src/main/java/gift/model/Member.java
> +    private void validateInvalidEmail() {
validateEmail라는 한 메서드로 3가지 케이스에 대해거 검증해도 될 것 같아요

2024-07-14 12:54 UTC, Hongdonggeon commented on src/main/java/gift/model/Member.java
> +    private List<Wishlist> wishlistList;
wishListList 보다 wishLists가 더 자연스럽지 않나요?

2024-07-14 12:54 UTC, Hongdonggeon commented on src/main/java/gift/model/Product.java
>          }
이것도 name 묶어서 같이 검증하고 price 묶어서 같이 검증하고 하는게 좋을 것 같아요

2024-07-14 12:54 UTC, Hongdonggeon commented on src/main/java/gift/service/ProductService.java
>  @Service
보통 클래스 레벨이 `@Transactional(readOnly=true) ` 로 선언하고 생성, 삭제, 수정 하는 메서드위에 `@Transactional`을 붙이긴하죠 ㅎ

2024-07-14 12:54 UTC, Hongdonggeon commented on src/test/java/gift/repository/MemberRepositoryTest.java
> +        emptyPasswordMember = new Member(1L, "kbm", "kbm@kbm.com", "", "user");
객체 생성을 beforeEach안에서 한 이유가 뭘까요? 
조회나 수정, 삭제 테스트를 하기위해서 db에 데이터를 저장하는 로직이 beforeEach에 있는게 좋을 것 같아요

2024-07-14 12:54 UTC, Hongdonggeon commented on src/test/java/gift/repository/ProductRepositoryTest.java
> +        invalidImageUrlProduct = new Product(1L, "상품", "100", "kbm");
이곳도요!

2024-07-14 12:54 UTC, Hongdonggeon commented on src/test/java/gift/repository/MemberRepositoryTest.java
> +        emptyPasswordMember = new Member(1L, "kbm", "kbm@kbm.com", "", "user");
beforeEach에서는 반복되는 로직을 추가시키는 거예요 
예를 들어 

- 조회 테스트 
  - 저장
  - 조회 검증

- 수정 테스트 
  - 저장
  - 수정 검증

- 삭제 테스트
  - 저장
  - 삭제 검증

저장 로직이 반복되니까 beforeEach에 저장로직을 작성하는거죠~

2024-07-14 12:54 UTC, Hongdonggeon commented on src/main/java/gift/model/Product.java
> +    private List<Wishlist> wishlists;
이 연관관계가 있어야할까요?
연관관계를 무조건 양방향 연관관계로 설정할 필요가 없어요! 
제 생각엔 wishProduct : product N:1 단방향 연관관계만 가지고 있어도 될 것 같은데요 어떻게 생각하세요!? 한번 고민해보시죠!

2024-07-14 12:54 UTC, Hongdonggeon commented on src/main/java/gift/model/Member.java
> +    private List<Wishlist> wishlistList;
cascade = CascadeType.REMOVE) 로 하시면 member 데이터가 삭제될때 멤버 객체에 연관된 wishList 데이터들도 함께 삭제된다는 옵션입니다 이 상황에 어울리는 것 같아요

2024-07-14 12:54 UTC, Hongdonggeon commented
생성자는 제가 잠깐 착각한 것 같네요.. 죄송해요 
protected 유지해주시면 될 것 같아요

2024-07-14 12:58 UTC, Hongdonggeon commented
고아 객체란 부모 엔티티와 연관관계가 끊어진 자식 엔티티를 의미하는데요. orphanRemoval = true 이란 옵션을 설정하게 되면, 부모와 연관관계가 끊어진 자식 엔티티를 자동으로 삭제되게 됩니다 (약간 cascade remove) 와 비슷하게 동작하죠
@OneToOne, @OneToMany 에서만 가능하고 default 값은 false 입니다!

2024-07-14 13:45 UTC, KBM05haruin30 commented on src/main/java/gift/model/Member.java
> +    private void validateInvalidEmail() {
넵 알겠습니다!

2024-07-14 13:52 UTC, KBM05haruin30 commented on src/main/java/gift/model/Member.java
> +    private List<Wishlist> wishlistList;
인텔리제이에서 자동으로 생성되는 Tab을 누르다가 변수명이 이렇게 나온 것 같습니다. 다음부터는 꼼꼼히 확인하도록 하겠습니다!

2024-07-14 13:59 UTC, KBM05haruin30 commented on src/main/java/gift/model/Product.java
>          }
넵 알겠습니다!

2024-07-14 14:06 UTC, KBM05haruin30 commented on src/main/java/gift/service/ProductService.java
>  @Service
자료를 찾아보았을 때 메서드 위에 작성을 해둔 자료가 많아서 클래스 레벨로 생각하지 못했습니다...
클래스 레벨로 `@Transactional(readOnly=true)`로 작성하면 조회 메서드가 여러 개일 때 개별로 지정해주지 않아도 되는 장점이 있을 것 같습니다.

2024-07-14 14:25 UTC, KBM05haruin30 commented on src/main/java/gift/model/Product.java
> +    private List<Wishlist> wishlists;
이 연관 관계가 없다면 cascade를 사용할 수 없어 product 데이터가 삭제될 때 product 객체에 연관된 wishlist 데이터도 함께 삭제될 수 없을 것 같습니다. 따로 삭제하려면 로직을 새로 만들어주어야 하는데 양방향 연관 관계를 하면 더 쉽게 할 수 있을 것이라 생각해서 꼭 있어야 할 것 같습니다!

2024-07-14 14:32 UTC, KBM05haruin30 commented on src/test/java/gift/repository/MemberRepositoryTest.java
> +        emptyPasswordMember = new Member(1L, "kbm", "kbm@kbm.com", "", "user");
제가 잘못 이해했었던 것 같습니다. 저장 로직이 반복되므로 beforeEach 안에 넣어보도록 하겠습니다!

2024-07-14 15:26 UTC, KBM05haruin30 commented on src/test/java/gift/repository/MemberRepositoryTest.java
> +        emptyPasswordMember = new Member(1L, "kbm", "kbm@kbm.com", "", "user");
정상 테스트에 관한 저장은 beforeEach에 작성을 했습니다. 하지만 예외 테스트에 관한 저장은 어떻게 beforeEach에 작성을 해야하는지 감이 안잡힙니다...

2024-07-15 15:04 UTC, Hongdonggeon commented on src/test/java/gift/repository/MemberRepositoryTest.java
> +        emptyPasswordMember = new Member(1L, "kbm", "kbm@kbm.com", "", "user");
예외 테스트도 동일하게 하면 되지 않을까요? 어떤점이 어려웠나요?

2024-07-15 15:11 UTC, Hongdonggeon commented on src/main/java/gift/model/Product.java
> +    private List<Wishlist> wishlists;
cascade 없이도, 삭제한 prodcut에 맵핑된 wishList를 쿼리로 삭제할 수 있을 것 같아요
보민님이 이야기하신 것 처럼 cascade 옵션을 통해서 편하게 삭제할 수 있는 장점도 맞지만, 잘못 설정한다면 예기치 못하게 데이터가 삭제되거나 할 수 있거든요. 그래서 이런 옵션들은 잘 생각해서 사용해야 됩니다. 

그리고 cascade 별개로 product 객체가 wishList를 리스트로 가지고 있는게 어색하다고 느껴지는데요.
product 객체가 존재하기 위해서 wishList가 꼭 필수는 아니잖아요? (반대로, wishList가 있기 위해서는 product가 존재해아한다 라고 생각하면 더 와닿을수도 있을 것 같아요) 그래서 저는 product에 필드로 wishList를 리스트로 가지고 있는게 불필요하다고 느꼈는데 어떻게 생각하세요?

2024-07-15 15:12 UTC, Hongdonggeon requested changes
보민님 추가로 코멘트들 남겨놓았습니다! 확인한번해주세요
반영하느라 수고많으셨습니다!

2024-07-16 16:29 UTC, Hongdonggeon approved these changes
남은 코멘트들은 step3 pr에서 이야기 나누도록할게요!

2024-07-16 16:30 UTC, merged