경북대 BE_권도윤 3주차 과제 (3단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #427
Opened 2024-07-14 12:58 UTC by doyooon

2024-07-14 13:22 UTC, MangKyu requested changes
마지막 단계도 고생많으셨습니다! 이제 핵심을 위해 조금 미뤄뒀던 부분에 대해서 코멘트 및 추가 변경 요청 드리겠습니다 🙇

### Product에 대한 단위 테스트
과제를 하면서 느끼셨겠지만, 요구사항이 계속해서 생김에 따라 리팩터링이 지속적으로 일어나게 됩니다! 따라서 비즈니스 정책들에 대한 테스트가 존재해야 코드 변경이 생겨도 영향이 없음을 보장할 수 있는데요, 예를 들어 Product의 경우 "카카오" 라는 네이밍 규칙에 대한 부분을 단위 테스트로 작성해둔다면 우리의 비즈니스 정책이 영향없음을 보증받을 수 있을 것 같아요ㅎㅎ 해당 부분을 보완하시면 좋을 것 같습니다!


### Entity의 기본 생성자
기본생성자 JPA 스펙을 위해 필요한 부분입니다! 따라서 외부에서 사용될 수 있으므로, 사용되지 않는다면 protected로 선언하면 더욱 좋을 것 같습니다ㅎㅎ


### 유효성 검사
현재 Product 클래스 내부의 `@Kakao` 기능은 동작하고 있지 않을 것 같아요! 그 이유는 유효성 검사와 관련된 부분을 Service 계층에 적용하려면 `@Validated`와 함께 사용되어야 하기 때문입니다ㅎㅎ [다음의 포스팅](https://mangkyu.tistory.com/174)을 참고하여 유효성 검사가 동작하게 반영 부탁드려요!
참고로 비즈니스 정책에 대한 유효성 검사는 해당 클래스 내부에서 하는 것이 바람직하지만, 현재는 별도의 Validator로 생성된 부분 넘어가도록 하겠습니다~

2024-07-14 13:22 UTC, MangKyu commented on src/main/java/gift/wishes/WishService.java
> +    public Page<Wish> getAllWishPage(Long memberId){
요것은 항상 사용되지 않고, 처음 페이지만 반환되는 것 같은데요~
사용되는 곳이 있을까요? 없으면 지워도 될 것 같습니다!

2024-07-14 13:22 UTC, MangKyu commented on src/main/java/gift/wishes/WishService.java
> +        Pageable pageable = PageRequest.of(page,10);
IntelliJ 코드(라인) 자동 정렬 Command + Option + L 단축키 사용하시면 편리하게 자동적용 할 수 있습니다.
```suggestion
        Pageable pageable = PageRequest.of(page, 10);
```

2024-07-14 14:20 UTC, doyooon commented on src/main/java/gift/wishes/WishService.java
> +    public Page<Wish> getAllWishPage(Long memberId){
테스트에서만 사용하고 컨트롤러에서는 사용을 하지 않았었습니다! 삭제하였습니다!

2024-07-14 15:20 UTC, MangKyu approved these changes
이번 과제들도 고생 많으셨습니다ㅎㅎ 몇 가지 개선이 필요한 부분들은 코멘트 남겨드렸는데, 필수적이지는 않은 부분인 것 같아서 추후에 개선 부탁드릴께요! 고생 많으셨습니다ㅎㅎ

2024-07-14 15:20 UTC, MangKyu commented on build.gradle
> +    testImplementation("org.assertj:assertj-core:3.25.1")
assertj는 `org.springframework.boot:spring-boot-starter-test`에 포함되어 있어 굳이 의존성 추가 안하셔도 됩니다! merge 해둘테니 제거 부탁드릴께요ㅎㅎ

2024-07-14 15:20 UTC, MangKyu commented on src/main/java/gift/member/Member.java
> +    protected Member() {
protected 변경 👍

2024-07-14 15:20 UTC, MangKyu commented on src/main/java/gift/wishes/WishController.java
> +    public ResponseEntity<?> getWishListPage(@Login UserDTO userDTO, @RequestParam(value="page", defaultValue="0")int page){
타입은 구체적으로 작성해주는 편이 좋습니다! 그래야 잘못된 타입이 반환되는 경우에 컴파일러로부터 검사를 받을 수 있습니다 🙇

2024-07-14 15:20 UTC, MangKyu commented on src/test/java/gift/ProductTest.java
> +@SpringBootTest
제가 의도했던 부분은 `단위 테스트로` 스프링 컨테이너가 띄워지지 않는 환경이였습니다만ㅎㅎ
지금으로도 크게 문제는 없을 것 같으니 천천히 수정해주세요!

2024-07-14 15:20 UTC, merged

2024-07-15 06:20 UTC, doyooon commented on build.gradle
> +    testImplementation("org.assertj:assertj-core:3.25.1")
넵! 제거하겠습니다! 혹시 중복되는 의존성을 판단할 수 있는 방법이 있을까요?

2024-07-15 15:40 UTC, MangKyu commented on build.gradle
> +    testImplementation("org.assertj:assertj-core:3.25.1")
제 개인적으로는 gradle에서 의존성 관리를 확인하는 편입니다!
assertJ처럼 자주 사용되는 부분은 도윤님께서도 숙련도가 높아지면 자연스럽게 알게되시지 않을까 싶습니다ㅎㅎ
![image](https://github.com/user-attachments/assets/4ccd432d-ed8c-4c5c-b4f1-2185d551ad20)