전남대 BE_김보민_3주차 과제(3단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #436
Opened 2024-07-15 04:38 UTC by KBM05haruin30

# 3단계
### 코드 작성하면서 어려웠던 점
`@PageableDefault`를 사용했습니다. `Pageable pageable = PageRequest.of(page, size);`를 사용하는 것보다 PageableDefault를 사용하는 것이 더 간편하게 코드를 짤 수 있을 것이라 생각했습니다. 
상품 목록에서는 페이지 이동이 되는 것을 확인했습니다. 위시 리스트에서의 페이지 이동을 하면 로그인 화면으로 돌아가서 이 부분을 해결하는데 어려웠습니다.

### 중점적으로 봐주셨으면 하는 점
변경된 코드가 잘 작성한 것인지 봐주셨으면 합니다!

2024-07-15 15:22 UTC, Hongdonggeon commented on src/main/java/gift/model/Wishlist.java
> +    @JoinColumn(name = "member_email", nullable = false)
member_id로 하지 않고 member_email로 한이유가 뭘까요?

2024-07-15 15:54 UTC, Hongdonggeon requested changes
보민님 미션 구현하느라 수고많으셨습니다!
코멘트들 남겨놓았으니 확인해주세요

2024-07-15 15:54 UTC, Hongdonggeon commented on src/main/java/gift/model/Member.java
>      public void validate() {
검증을 member 생성자안에서 해주는게 좋지 않을까요?
그렇게 된다면 검증에 실패할 필드에 대해서 객체가 만들어질일도 없어질 것 같아요~

2024-07-15 15:54 UTC, Hongdonggeon commented on src/main/java/gift/model/Member.java
>      public void validate() {
```
   public Member(Long id, String name, String email, String password, String role) {
validateName();
xxxx ....
        this.id = id;
        this.name = name;
        this.email = email;
        this.password = password;
        this.role = role;
    }

2024-07-15 15:54 UTC, Hongdonggeon commented on src/main/java/gift/model/Product.java
> +    private List<Wishlist> wishlists;
이전 pr에 코멘트를 남겨놓았는데요. 이 연관관계에 대해서 필요한지 고민해봐주세요~

2024-07-15 15:54 UTC, Hongdonggeon commented on src/main/java/gift/model/Product.java
>      public void validate() {
이곳도 생성자에서 검증해주는게 좋을 것 같아요

2024-07-15 15:54 UTC, Hongdonggeon commented on src/main/java/gift/repository/WishlistRepository.java
> +    Page<Wishlist> findByMember(Member member, Pageable pageable);
entityGraph로 n+1 문제를 방지하는건 좋은데요!, N+1 이 왜 일어나는지에 대해서 학습해보면 좋을 것 같아요

2024-07-15 15:54 UTC, Hongdonggeon commented on src/main/java/gift/model/Product.java
> +    private List<Wishlist> wishlists;
그리고 지금 wishLIsts들을 사용하지도 않고 있는데요 사용하지 않은 객체들을 선언할 필요가 있을까요?

2024-07-15 23:30 UTC, KBM05haruin30 commented on src/main/java/gift/model/Wishlist.java
> +    @JoinColumn(name = "member_email", nullable = false)
Product는 findById 처럼 id를 통해서 찾고 Member는 findMemberByEmail 처럼 email을 통해서 찾기 때문에 member_email로 작성했었습니다. 하지만 실제로 작동을 해보면 나오는 결과는 id가 나오기 member_id로 변경해주고 schema도 변경해주겠습니다!

2024-07-15 23:31 UTC, KBM05haruin30 commented on src/main/java/gift/model/Member.java
>      public void validate() {
넵 알겠습니다!

2024-07-15 23:36 UTC, KBM05haruin30 commented on src/main/java/gift/model/Product.java
>      public void validate() {
넵 알겠습니다!

2024-07-16 01:09 UTC, KBM05haruin30 commented
### STEP 2 리뷰
#### 예외 테스트에 관한 저장이 어려습니다..
- beforeEach에 반복 로직만 추가하고 싶은데 저장하기 위해서는 객체를 먼저 만들어주어야 하는 것 같습니다.
- beforeEach에 예외를 발생시키는 객체를 넣고 저장하면 예외 발생하여 testSave()부터 통과가 안됩니다.
   - 밑의 코드처럼 작성하려고 했었습니다.
```
@BeforeEach
    public void setUp() {
        member = new Member(1L, "kbm", "kbm@kbm.com", "mbk", "user");
        savedMember = memberRepository.save(member);
        nullNameMember = new Member(1L, null, "kbm@kbm.com", "mbk", "user");
        memberRepository.save(nullNameMember);
    }
```

### STEP 2 + STEP 3 리뷰
#### 연관 관계
- 멘토님 리뷰 중 product 객체가 존재하기 위해서 wishlist가 꼭 필수는 아니라는 것과 wishlist가 있기 위해서는 product가 존재해야 한다는 것을 보고 다시 생각해보게 되었습니다. 꼭 필수가 아니라면 사용하지 않아도 되고 지금 사용하고 있지도 않은데 선언할 필요가 없는 것 같습니다. member도 마찬가지라고 생각합니다. member 객체가 존재하기 위해서 wishlist가 필수는 아니지만, wishlist가 존재하기 위해서는 member가 존재해야 합니다. 그래서 member에서도 선언할 필요가 없는 것 같습니다.
- Product에 맵핑된 wishlist를 지우기 위해서 WishlistRepository에 Product로 지우는 메서드를 생성했습니다. 그리고 deleteProduct 메서드를 deleteProductAndWishlist로 변경하여 id를 통해 product를 찾고 그 product를 wishlist에서 지운 후 product에서 지우도록 하였습니다.

### STEP 3 리뷰
#### N + 1 문제
- N + 1 문제는 요청이 1개의 쿼리로 처리 되길 기대했는데 N개의 추가 쿼리가 발생되는 문제입니다.
- 이러한 문제가 일어나는 이유는 조회할 때 한쪽 테이블만 조회하고 연결된 다른 테이블은 따로 조회하기 때문입니다. 즉, 첫 쿼리에서 하위 엔티티까지 한 번에 가져오지 않고, 하위 엔티티를 사용할 때 추가로 조회하기 때문에 추가 쿼리가 발생하는 것입니다.
- 해결 방법으로는 조회할 때 처음부터 연관된 데이터까지 같이 가져오게 하면 됩니다.

2024-07-16 16:34 UTC, Hongdonggeon commented on src/main/java/gift/model/Member.java
>      public void validate() {
validate 하는 부분을 생성자 최상단에서 하는게 좋지 않을가요?  또한 validate() 메서드 없애고 생성자안에서 validatename, validateEmail, validatePassword를 호출해주는게 더 좋을 것 같아요
그리고 현재 생성자에 들어오는 인자를 검증하는게 아니라 객체의 필드를 검증하고 있는 부분이 이상한 것 같아요
아래와 같이 변경되는게 좋을 것 같은데 어떻게 생각하세요?
생성자에 들어온 인자값 검증 -> 검증 통과 -> 객체 생성 

```java

    public Member(Long id, String name, String email, String password, String role) {
        validateName(name);
        validateEmail(email);
        validatePassword(password);
        this.id = id;
        this.name = name;
        this.email = email;
        this.password = password;
        this.role = role;
    }

```

2024-07-16 16:44 UTC, Hongdonggeon commented
현재 예외 케이스로 테스트 작성해주신 메서드들을 확인해보니, 아래와 같은 케이스인 것 같아요
- member 객체 생성 전 검증 실패 (validate에서 예외날것들) 
- product 객체 생성 전 검증 실패 (validate에서 예외 날것 들)
이 예외 상황을 repositoryTest에서 작성한게 조금 잘못 된 것 같아요.
위와 같은 예외 상황들은 보민님이 추가한 요구사항이잖아요 
보민님이 정한 규칙에서 어긋나면 비즈니스 로직상 예외지만, db 입장에서는 예외 상황이 아니니까 repository 레벨에서 검증할 필요도 없고 검증하기가 힘들었던 것 같아요
repositoryTest에서는 db 저장, 조회, 삭제 이런 행위들이 잘 수행되는기 검증해주는게 좋을 것 같다는 생각이 들고요
위와 같은 상황은 단위 테스트로 작성해주는게 좋을 것 같습니다

2024-07-16 16:45 UTC, Hongdonggeon requested changes
보민님 코멘트들 확인했고요! 
생성자 검증 부분이랑 테스트 코드 예외 상황만 수정해주시면 될 것 같습니다~

2024-07-16 23:36 UTC, KBM05haruin30 commented on src/main/java/gift/model/Member.java
>      public void validate() {
단순하게 validate()가 생성자 안에 있으면 해결될 것이라 생각했었습니다. 다시 보니 생성자에 들어오는 인자를 검증해야 하는데 제가 작성한 코드는 인자가 아닌 객체의 필드를 검증하고 있다는 것을 알게 되었습니다. 검증 메서드를 최상단에 두고 검증을 통과하지 않으면 밑의 코드를 실행할 필요가 없어 불필요하게 낭비되는 것을 막을 수 있을 것 같습니다. validate()를 지우고 validateName처럼 작성하는 것이 직관적이라 더 좋다고 생각합니다!

2024-07-17 16:05 UTC, Hongdonggeon approved these changes
보민님 리뷰 반영하시느라 수고많으셨습니다! 
이번주 미션도 화이팅입니다! 
머지할게요

2024-07-17 16:05 UTC, merged