전남대 BE_나제법_3주차 과제(3단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #443
Opened 2024-07-15 08:31 UTC by nove1080

## 코드 작성하면서 어려웠던 점
## 코드 리뷰 시, 멘토님이 중점적으로 리뷰해주셨으면 하는 부분
### 1. 페이징 기능을 제공할 때 URL은 어떻게 설계하나요?

저는 http://localhost:8080/api/members/wishlist?page=0&size=10&sort=id,desc 이런 식으로 URL이 구성되는데 

네이버에서는 어떻게 사용하는지 궁금하여

<img width="732" alt="image" src="https://github.com/user-attachments/assets/0c811c1b-e3dd-4acf-89b2-e723d7f2f81c">

https://search.naver.com/search.naver

?nso=&query=foo&sm=tab_pge&where=nexearch
?nso=&page=2&query=foo&sm=tab_pge&start=1&where=web
?nso=&page=3&query=foo&sm=tab_pge&start=16&where=web

위에서부터 차례대로 네이버에서 foo 라는 검색어를 입력하고 첫번째 페이지, 두번째 페이지, 세번째 페이지에 대한 쿼리 스트링의 변화입니다.

뭔가 제 코드의 구성과 다른 것 같은데 현업에서는 어떤 식으로 페이징 기능을 제공하는지 궁금합니다!

2024-07-15 16:12 UTC, Hongdonggeon requested changes
제법님 미션 구현하느라 수고많으셨습니다!
잘 구현해주셔서 리뷰를 드릴 내용이 딱히 없네요!! 👍
점점 성장하는 모습이 보기 좋습니다! 
간단한 코멘트들 남겨놓았어요! (wishProduct와 product 의 연관관계에 대해서 고민만 해주시면 좋을 것 같아요)
수고하셨습니다~

2024-07-15 16:12 UTC, Hongdonggeon commented on src/main/java/gift/domain/BaseTimeEntity.java
> +    private LocalDateTime modifiedAt;
크게 상관없긴 한데 보통 updatedAt이라는 표현을 많이 사용하긴 하죠

2024-07-15 16:12 UTC, Hongdonggeon commented on src/main/java/gift/domain/Product.java
> +    private List<WishProduct> wishProducts = new ArrayList<>();
wishLists는 사용하지 않고 있는데요. 연관관계로 설정한 이유가 뭘까요? 
wishProduct와 product 가 N대 1 단방향 연관관계로 가지고 있어도 되지 않나요

2024-07-15 16:12 UTC, Hongdonggeon commented on src/main/java/gift/web/controller/api/MemberApiController.java
> +    public ResponseEntity<ReadAllWishProductsResponse> readWishProduct(@LoginMember MemberDetails memberDetails, @PageableDefault Pageable pageable) {
default 값을 따로 지정하지 않았네요. pageAble의 default 값을 사용하지 않은 이유가 뭘까요

2024-07-15 16:12 UTC, Hongdonggeon commented on src/main/java/gift/domain/Product.java
> +    @ColumnDefault("'https://gift-s3.s3.ap-northeast-2.amazonaws.com/default-image.png'")
디폴트값을 추가해준 이유가 뭐예요?

2024-07-15 16:43 UTC, nove1080 commented on src/main/java/gift/web/controller/api/MemberApiController.java
> +    public ResponseEntity<ReadAllWishProductsResponse> readWishProduct(@LoginMember MemberDetails memberDetails, @PageableDefault Pageable pageable) {
@PageableDefault로 기본값을 지정하였습니다

```java
public @interface PageableDefault {

	@AliasFor("size")
	int value() default 10;

	@AliasFor("value")
	int size() default 10;

	int page() default 0;

	String[] sort() default {};

	Direction direction() default Direction.ASC;
}
```
위와 같은 값이 디폴트로 적용이 되어 제공하는 값이 다른 웹 사이트에서도 주로 사용되는 값인 것 같아 별도로 사이즈 기본값이나 페이지의 기본값을 정의하지 않고 그대로 사용하였습니다!

2024-07-15 16:46 UTC, nove1080 commented on src/main/java/gift/domain/Product.java
> +    @ColumnDefault("'https://gift-s3.s3.ap-northeast-2.amazonaws.com/default-image.png'")
상품 이미지의 경우, 사용자가 제공하지 않더라도 기본값을 적용하여야 한다. 라는 저만의 요구사항을 만들어보았습니다!

2024-07-15 16:48 UTC, nove1080 commented on src/main/java/gift/domain/Product.java
> +    private List<WishProduct> wishProducts = new ArrayList<>();
이 부분은 https://github.com/kakao-tech-campus-2nd-step2/spring-gift-jpa/pull/310#discussion_r1676789512 에서 제 생각을 적어보았습니다. 아래는 해당 디스커션에서 남긴 제 답글입니다

***

양방향 연관관계를 가지도록 한 것은 `Product` 나 `Member`의 삭제가 발생하였을 시, 해당 `Product`, `Member` 가 등록한 혹은 등록된 위시 상품(`WishProduct`)를 같이 삭제하기 위해(삭제 전파) `CascadeType.REMOVE` 라는 옵션을 사용하기 위함이었습니다. 

`CascadeType.REMOVE` 만을 적용하기 위해 양방향 연관관계를 설정하게 되었습니다. 

양방향 연관관계를 피하면서 삭제를 전파할 수 있는 방법을 찾아보고 적용한 것이었는데요

다른 방법으로는 `@OnDeleted` 어노테이션을 적용하는 방법도 있었습니다. 이 경우에는 DB에 `ON DELETED CASCADED` 제약조건을 설정하는 방식으로 동작합니다. 따라서 JPA를 사용하는 경우 영속성 컨텍스트와 동기화 문제가 발생할 수 있어 권장되는 방식은 아니라고 판단되어 `CascadeType.REMOVE` 를 사용하는 방식으로 처리하였습니다.

실무에서는 어떤 방식으로 삭제를 전파하나요?

2024-07-15 16:49 UTC, nove1080 commented on src/main/java/gift/domain/BaseTimeEntity.java
> +    private LocalDateTime modifiedAt;
넵! 이 부분은 관례 따르도록 수정하겠습니다

2024-07-15 17:01 UTC, nove1080 commented
> 제법님 미션 구현하느라 수고많으셨습니다! 잘 구현해주셔서 리뷰를 드릴 내용이 딱히 없네요!! 👍 점점 성장하는 모습이 보기 좋습니다! 간단한 코멘트들 남겨놓았어요! (wishProduct와 product 의 연관관계에 대해서 고민만 해주시면 좋을 것 같아요) 수고하셨습니다~

늦은시간임에도 빠르게 피드백을 남겨주셔서 감사합니다! 동건님 덕분에 많이 배우고 있습니다

2024-07-16 16:22 UTC, Hongdonggeon commented on src/main/java/gift/domain/BaseTimeEntity.java
> +    private LocalDateTime modifiedAt;
넵 보통은 그런것 같아요

2024-07-17 16:10 UTC, Hongdonggeon commented on src/main/java/gift/domain/Product.java
> +    private List<WishProduct> wishProducts = new ArrayList<>();
https://github.com/kakao-tech-campus-2nd-step2/spring-gift-jpa/pull/310#discussion_r1679776632 
여기에 답변 달았습니다!

2024-07-17 16:11 UTC, Hongdonggeon approved these changes
제법님 미션 너무 구현잘해주셨습니다!
리뷰 반영하시느라 수고도 많았고요!
머지할게요!

2024-07-17 16:11 UTC, merged