경북대 BE_주보경 3주차 과제 (3단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #449
Opened 2024-07-15 18:01 UTC by jupyter471

이전 코드는 Member가 WIsh를 리스트로 가지는 양방향 매핑 구조였습니다. 그렇다보니 Member를 통해 위시 조회는 빠르지만 삭제와 수정의 경우 멤버 도메인 내부 뿐만 아니라 wish 도메인에서도 반영을 해주어야해서 코드가 깔끔하지 않았습니다. 그래서 3단계에서 단방향 1:N 관계로 모두 수정하였습니다.  

멘토님께서 피드백 해주신 대로 wish 수량 업데이트 로직을 추가하였습니다. 또한 저는 wish가 add될 때 데이터 중복을 방지하기 위해 해당 member와 product에 대한 wish가 있는지 확인하고 없다면 새로운 로직을 생성하고, 있다면 기존 wish의 quantity 수량을 기존 수량 + 추가하는 수량으로 update하였습니다.

이전 pr이 merge 되어 여기서 멘토님 질문에 답변하겠습니다!
JPA를 사용함으로써 동적으로 객체 생성 시 Reflection API를 활용하기 때문에 파라미터가 없는 기본 생성자가 비록 코드에서는 사용되지 않지만 필요했습니다. 기존에는 public으로 선언하였지만 protected로 모두 변경하였습니다.
또한 DTO에서도 JSON과 객체의 매핑을 위해 각 필드에 대한 getter가 필요하다고 생각되어 DTO에 getter를 추가하였습니다.

기존에 사용되었던 setter 대신 메서드의 역할을 알 수 있게 네이밍을 하였습니다. 
```
wish.updateQuantity(quantity);
```
(코드 파일에 comment 달아두겠습니다!)
이렇게 메서드명만 바꾸고 하는 일은 동일한데 이런 경우도 괜찮은가요?

2024-07-16 11:43 UTC, sang5c requested changes
3단계 요구사항은 `상품과 위시 리스트 보기에 페이지네이션을 구현한다.`입니다. : ) 
상품이 빠져있으니 확인해주세요!

---


간단히 의견남기면,  
단방향 매핑으로 수정해야지만 리뷰를 반영할 수 있었던 것은 아닙니다.  
양방향인 경우에도 문제를 해결할 수 있었고, 나쁘지 않은 시도였으니 시간이 남을 때 다시 수정해보시면 좋겠네요 :)  

아직 배울게 많으니 우선 진도를 따라가기 위해 노력하구요.

> 이렇게 메서드명만 바꾸고 하는 일은 동일한데 이런 경우도 괜찮은가요?

이름을 바꾸는 것(리팩터링)은 단순하지만 굉장히 중요한 작업이니 변경으로 어떤 이점을 얻을 수 있었는지도 고민해보시면 좋겠네요!

2024-07-16 11:43 UTC, sang5c commented on src/main/java/gift/controller/MemberController.java
>      @GetMapping("/wishes")
`/members/wishes` 형태의 URL이 규칙에 맞게 설계되었고, 이해하기 쉬운지도 고민해보면 좋겠네요!  
https://mannhowie.com/rest-api

2024-07-17 03:34 UTC, jupyter471 commented
상품 페이지네이션 구현해두었습니다 감사합니다!
 
> 이름을 바꾸는 것(리팩터링)은 단순하지만 굉장히 중요한 작업이니 변경으로 어떤 이점을 얻을 수 있었는지도 고민해보시면 좋겠네요!
setQuantity() 보다는 updateQuantity()라고 이름을 바꿈으로써 해당 메서드가 어떤 일을 수행 하는지 알 수 있다는 장점이 있는 것 같습니다!

2024-07-17 03:51 UTC, sang5c approved these changes
4주차도 파이팅입니다~!

2024-07-17 03:51 UTC, merged