충남대 BE_이은경 3주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #55
Opened 2024-07-08 07:24 UTC by pkyung

## 과제 진행 사항
### 엔티티 매핑
- [x] jdbc template 기반 코드 jpa 로 리펙토링
- [x] 멤버 클래스 엔티티 매핑
- [x] 상품 클래스 엔티티 매핑
- [x] 위시 클래스 엔티티 매핑

2024-07-08 07:58 UTC, ksy90101 requested changes
안녕하세요. 벌써 1단계를 진행하셨군요 ㅎㅎ
빠르시네요.
간단한 피드백을 남겼으니 한번 확인해주세요!

2024-07-08 07:58 UTC, ksy90101 commented on src/main/java/gift/dto/MemberRequest.java
> +public record MemberRequest(@Email(message = "이메일 형식의 입력이어야 합니다.") String email, String password) {
```suggestion
public record MemberRequest(
@Email(message = "이메일 형식의 입력이어야 합니다.") String email, 
String password
) {
```

한줄로 적기보단 개행을 두면 훨씬 더 가독성이 높아질거 같습니다.

2024-07-08 07:58 UTC, ksy90101 commented on src/main/java/gift/controller/MemberController.java
> +public class MemberController {
이 부분은 요구사항에 있지 않은데, 혹시

"(선택) 회원을 조회, 추가, 수정, 삭제할 수 있는 관리자 화면을 구현한다."
해당 부분으로 인해 있는걸까요?

2024-07-08 07:58 UTC, ksy90101 commented on src/main/java/gift/model/Member.java
> +@Entity
기존에 테이블 이름은 복수형이였는데요.
지금 테이블명을 따로 지정하지 않으면 단수형이 될거 같은데 의도하신걸까요?

2024-07-08 07:58 UTC, ksy90101 commented on src/main/java/gift/repository/WishRepository.java
> +    List<Product> findAllByUserId(@Param("memberId") Long memberId);
```suggestion
    List<Product> findAllByMemberId(@Param("memberId") Long memberId);
```

2024-07-08 07:58 UTC, ksy90101 commented on src/test/java/gift/JpaRepositoryTest.java
> +    @Test
여긴 DisplayName이 없네요 ㅠㅠ

2024-07-08 07:58 UTC, ksy90101 commented on src/test/java/gift/JpaRepositoryTest.java
> +    @Autowired
이부분을 각 Repository에 맞게 테스트 케이스를 분리하면 어떨까요?

아울러 직접 쿼리를 발생시키는 메서드인 "findAllByUserId" 이 메서드의 테스트 코드를 추가해보면 어떨까요?

2024-07-09 04:56 UTC, pkyung commented on src/main/java/gift/dto/MemberRequest.java
> +public record MemberRequest(@Email(message = "이메일 형식의 입력이어야 합니다.") String email, String password) {
저도 가독성이 부족한 것 같다는 생각을 했는데, 개행을 넣으면 되는군요! 수정하겠습니다.

2024-07-09 04:59 UTC, pkyung commented on src/main/java/gift/controller/MemberController.java
> +public class MemberController {
회원 가입, 로그인 api를 만들면서 습관적으로 만들었던 것 같습니다.

2024-07-09 04:59 UTC, pkyung commented on src/main/java/gift/model/Member.java
> +@Entity
수정하도록 하겠습니다.

2024-07-09 05:02 UTC, pkyung commented on src/main/java/gift/repository/WishRepository.java
> +    List<Product> findAllByUserId(@Param("memberId") Long memberId);
수정하겠습니다.

2024-07-09 05:12 UTC, pkyung commented on src/test/java/gift/JpaRepositoryTest.java
> +    @Autowired
테스트 케이스를 클래스 단위로 분리하라는 말씀이신건가요?? 
wish는 product와 member 모두 연관이 되어 있어서 repository를 결국 세 개 다 불러와야 테스트 가능할 것 같은데 이런 경우여도 분리하는 게 좋을까요?

2024-07-09 05:20 UTC, pkyung commented on src/main/java/gift/controller/MemberController.java
> +public class MemberController {
수정하도록 하겠습니다.

2024-07-09 05:20 UTC, pkyung commented on src/test/java/gift/JpaRepositoryTest.java
> +    @Test
추가했습니다!

2024-07-09 14:54 UTC, ksy90101 commented on src/test/java/gift/JpaRepositoryTest.java
> +    @Autowired
네 각 클래스의 맞은 테스트 클래스가 1:1로 최대한 매칭되는게 좋을거 같습니다.

2024-07-09 14:54 UTC, ksy90101 commented on src/test/java/gift/JpaRepositoryTest.java
> +    @Autowired
지금이야 몇개 없지만 서비스가 거대해지면 거대해질수록 테스트 케이스가 계속 늘어나거든요.
객체지향에서 객체를 분리하는것처럼 테스트 케이스도 동일하다고 생각해주시면 좋을거 같아요

2024-07-09 14:59 UTC, ksy90101 approved these changes
1단계 고생 많으셧어요~
간단한 피드백을 남기긴 햇지만 2단계에서 하셔도 무관하기 때문에 머지할게요!
언제든 질문이 있다면 DM주세요!
홧팅입니다!

아울러 시간이 남으신다고 생각하시면,

1주차, 2주차 선택 미션을 한번 같이 진행해봐도 좋을거 같아요~
다른분들과 다르게 빠르신거 같아서 추천드려요!

2024-07-09 14:59 UTC, ksy90101 commented on build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-data-jpa:'
```suggestion
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
```

2024-07-09 14:59 UTC, ksy90101 commented on src/main/java/gift/dto/LoginRequest.java
> +        @Email(message = "이메일 형식의 입력이어야 합니다.") String email,
```suggestion
        @Email(message = "이메일 형식의 입력이어야 합니다.") 
        String email,
```
여기도 개행두면 좋을거 같네요!

2024-07-09 14:59 UTC, ksy90101 commented on src/main/java/gift/dto/LoginRequest.java
> +        @Email(message = "이메일 형식의 입력이어야 합니다.") String email,
NotEmpty, NotNull같은건 필요 없을까요?
아래 password도 포함입니다.

2024-07-09 14:59 UTC, ksy90101 commented on src/main/java/gift/dto/WishRequest.java
> +        @Min(value = 1, message = "상품 id는 1 이상이어야 합니다.") Long productId
여기도 Null이 들어와도 될까요?

2024-07-09 14:59 UTC, ksy90101 commented on src/main/java/gift/repository/WishRepository.java
> +    @Query("SELECT new gift.model.Product(p.id, p.name, p.price, p.imageUrl) " +
Java17을 쓰니 `"""` 이걸 쓰면 더 깔끔하게 쓸수 있을거 같기도 하네요!

2024-07-09 14:59 UTC, merged

2024-07-10 05:24 UTC, pkyung commented on build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-data-jpa:'
수정하겠습니다.

2024-07-10 05:24 UTC, pkyung commented on src/test/java/gift/JpaRepositoryTest.java
> +    @Autowired
네! 클래스 단위로 1:1 매칭되도록 수정하겠습니다.

2024-07-10 05:27 UTC, pkyung commented on src/main/java/gift/dto/WishRequest.java
> +        @Min(value = 1, message = "상품 id는 1 이상이어야 합니다.") Long productId
안됩니다. 수정하겠습니다.

2024-07-10 05:32 UTC, pkyung commented on src/main/java/gift/dto/LoginRequest.java
> +        @Email(message = "이메일 형식의 입력이어야 합니다.") String email,
네 수정하겠습니다.

2024-07-10 05:40 UTC, pkyung commented on src/main/java/gift/repository/WishRepository.java
> +    @Query("SELECT new gift.model.Product(p.id, p.name, p.price, p.imageUrl) " +
수정해보겠습니다.