경북대 BE_배준호 3주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #72
Opened 2024-07-08 13:29 UTC by BaeJunH0

피드백 내용 반영 및 step 1 부분 구현하였습니다.
기존에 피드백 받은 위시 리스트 조회와 수량 표기 및 수정 기능에 대한 부분도 적용하였습니다
그런데 DTO가 Request와 Response로 나뉘어야 하는지는 잘 모르겠습니다.
물론 책임을 여러 개 갖는 객체가 만들어지면 객체 지향적으로는 좋지 않겠지만, DTO는 말 그대로 "데이터를 옮기는" 객체라고 생각하기 때문에, 저는 요청과 응답 모두에서 사용해도 괜찮지 않나... 하는 생각입니다
이외에 멘토님이 피드백 해주신 위시 리스트 조회 과정은 제가 너무 프론트 친화적? 으로 생각한 결과였던 것 같습니다
그래서, 위시 리스트 조회는 wishProduct 객체 내용만 반환하는 것으로 하였습니다. wishProduct의 ProducctId 필드를 이용해서 Front에서 처리하는 것이 서버에 부하가 덜 걸릴 것이라고 생각했습니다!

2024-07-09 12:07 UTC, lsm7179 commented
> 피드백 내용 반영 및 step 1 부분 구현하였습니다. 기존에 피드백 받은 위시 리스트 조회와 수량 표기 및 수정 기능에 대한 부분도 적용하였습니다 그런데 DTO가 Request와 Response로 나뉘어야 하는지는 잘 모르겠습니다. 물론 책임을 여러 개 갖는 객체가 만들어지면 객체 지향적으로는 좋지 않겠지만, DTO는 말 그대로 "데이터를 옮기는" 객체라고 생각하기 때문에, 저는 요청과 응답 모두에서 사용해도 괜찮지 않나... 하는 생각입니다 이외에 멘토님이 피드백 해주신 위시 리스트 조회 과정은 제가 너무 프론트 친화적? 으로 생각한 결과였던 것 같습니다 그래서, 위시 리스트 조회는 wishProduct 객체 내용만 반환하는 것으로 하였습니다. wishProduct의 ProducctId 필드를 이용해서 Front에서 처리하는 것이 서버에 부하가 덜 걸릴 것이라고 생각했습니다!

request, response의 역할이 다르면 srp를 따라서 나누는게 좋다고 생각합니다.
같은 멤버변수를 쓴다고 하더라도 결국엔 고도화 될수록 달라지기 때문에 나눠놓는게 어떠한가 제안해본 것이죠.
미션하시다가 필요할때 나누면 좋을거 같네요.

2024-07-09 12:47 UTC, lsm7179 requested changes
준호님 1단계 수고하셨습니다.😁
간단한 코멘트들 있으니 확인해주세요.
이해 안가시는 부분 있으면 편하게 DM주세요~

2024-07-09 12:47 UTC, lsm7179 commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=create
spring.jpa.hibernate.ddl-auto 옵션에 대해 잘 알고 계시겠지만
create는 주의해서 사용해야 합니다.

2024-07-09 12:47 UTC, lsm7179 commented on src/main/java/gift/domain/Product.java
>      public Product(){
jpa entity를 사용하므로 setter와 프로퍼티 접근 방하기 위해 생성자는 protected로 수정해주세요.
다른 엔티티도 같이 확인해주세요.

2024-07-09 12:47 UTC, lsm7179 commented on src/main/java/gift/domain/WishProduct.java
> +    }
set 을 사용하지 말아보세요.
set을 쓰지않고 메서드명을 수정하고 수량이 음수인 경우 처리도 해주세요.

메서드명으로 의미를 알 수 있고 단위테스트도 진행 할 수있기 때문에 큰 장점이 됩니다.
도메인이 비즈니스 로직을 가지게 됩니다.

2024-07-09 12:47 UTC, lsm7179 commented on src/main/java/gift/service/ProductService.java
> +        if(byId.isPresent()) {
orElse를 사용해볼까요?
https://dev-coco.tistory.com/178

2024-07-09 12:47 UTC, lsm7179 commented on src/main/java/gift/service/ProductService.java
>      public void createProduct(ProductDTO product){
cud하는곳에 @transactional를 붙여주세요.

저는 조회하는쪽에도 @transactional(readOnly = true)를 붙이는 편입니다.
클래스단위로  @transactional(readOnly = true) 붙이고 cud하는 메서드만 @transactional를 붙입니다.
조회메서드를 가지고 트랜잭션 없이 수정을 진행할때 에러를 발생시켜 transactional작업을 강제하기 위해서 입니다.
커넥션 관리나 여러 관리측면에서 조회 쪽에 transactional이 없어도 된다는 의견도 있습니다.

2024-07-09 12:47 UTC, lsm7179 commented on src/main/java/gift/repository/ProductRepository.java
> +public interface ProductRepository extends JpaRepository<Product, Long> {
`import gift.domain.Product;` 가 없어서 컴파일 에러가 뜨네요.

2024-07-09 12:47 UTC, lsm7179 commented on src/main/java/gift/domain/User.java
> +    @Column(nullable = false, unique = true)
id가 이미 있는데 userId는 필요한가요?

2024-07-09 12:47 UTC, lsm7179 commented on src/test/java/gift/ProductRepositoryTest.java
> +        Product expected = new Product(100L, "name", 4500, "none");
id값을 jpa에서 자동생성해주므로 id없는 생성자를 만들어 보세요~

2024-07-10 05:48 UTC, BaeJunH0 commented on src/main/java/gift/repository/ProductRepository.java
> +public interface ProductRepository extends JpaRepository<Product, Long> {
Confilict 해결 과정에서 해당 부분을 지운 것 같네요! 로컬 환경에서는 있습니다 ㅠㅠ

2024-07-10 06:37 UTC, BaeJunH0 commented on src/main/java/gift/service/ProductService.java
>      public void createProduct(ProductDTO product){
더 공부한 이후에 적용해보겠습니다!

2024-07-10 06:56 UTC, BaeJunH0 commented on src/main/java/gift/domain/User.java
> +    @Column(nullable = false, unique = true)
Email에는 변경 가능성이 있다고 말씀하신 부분에서 처음 생각한 필드입니다, 
아무래도 일반적인 웹 서비스들을 생각해보면, 비밀번호 변경은 있고, 아이디를 변경하는 기능은 없습니다.
그렇다면 사용자가 사용하는 UserId는 변경 가능성이 없는, 어쩌면 Long 타입의 id와 동등한 수준의 key 라고 생각해서 UserId 필드를 만들었습니다, 
그래도 굳이 Primary Key로 String을 사용할 필요까지는 없을 것 같아서 Long 타입 id 필드도 만들었습니다!

2024-07-11 12:51 UTC, lsm7179 approved these changes
준호님 
1단계 수고하셨습니다.
요구사항을 충족하여 머지하겠습니다.
피드백 드린거 있는데 확인해보시고 다음단계에서 반영해주세요~

2024-07-11 12:51 UTC, lsm7179 commented on src/main/java/gift/domain/User.java
> +    Boolean admin;
접근제어자를 private으로 만들어서 객체지향적인 도메인객체로 만들어주세요.

2024-07-11 12:51 UTC, lsm7179 commented on src/main/java/gift/service/ProductService.java
>      public void createProduct(ProductDTO product){
https://jaehhh.tistory.com/61 를 한번 보고 고민해보세요.😁
서비스계층의 public method는 작업의 단위가 됩니다. 그럼 작업의 단위로 트랜잭션을 처리하는게 어떨까요?

2024-07-11 12:51 UTC, lsm7179 commented on src/main/java/gift/service/ProductService.java
> +        product1.setImageUrl(product.getImageUrl());
orElseThrow 를 사용하고
set프로퍼티를 없애고 도메인객체에 수정메서드로 작성해보세요~
지난번에도 같은 피드백을 드린거 같은데요~
어떤 이유로 set을 사용하고 orElseThrow를 사용하지 않나요?🤔😨

2024-07-11 12:51 UTC, merged

2024-07-12 04:44 UTC, BaeJunH0 commented on src/main/java/gift/service/ProductService.java
> +        product1.setImageUrl(product.getImageUrl());
이것도 로컬에서 반영했는데, 아직 깃 사용이 미숙한 것 같습니다... 깃 PR 과정에 좀 더 집중하겠습니다 😢

2024-07-12 04:56 UTC, BaeJunH0 commented on src/main/java/gift/domain/User.java
> +    Boolean admin;
수정 완료했습니다