강원대 BE_전혜지 3주차 과제 (0단계)
kakao-tech-campus-2nd-step2/spring-gift-jpa pull request #86
Opened 2024-07-08 18:27 UTC by HyeJiJUN11

**코드 옮기고, 1주차, 2주차 피드백 내용 수정했습니다.**
1. 2주차 2,3단계 PR 피드백에 코멘트로 추가 질문 작성했습니다! 한 번 살펴주시면 감사하겠습니다🙏
2. setter를 사용하는 코드를 모두 수정했습니다. Member와 Wishlist의 경우 setter삭제후에도 잘 작동 되지만 Product의 경우 setter를 삭제하면 `@ModelAttribute Product product` 에서 product를 가져오지 못하는 오류가 발생합니다... 왜인지 이유를 찾지 못해 일단 product의 setter만 남겨두었습니다.

2024-07-08 22:20 UTC, pci2676 requested changes
리뷰를 확인해주시고 다시 PR 부탁드려요!

2024-07-08 22:20 UTC, pci2676 commented on src/main/java/gift/controller/CatchError.java
> +}
https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/pull/427#discussion_r1668279953

값 객체를 어떻게 만들어주신건지 이번 pr에서 보이지 않는것 같습니다. 😢

2024-07-08 22:20 UTC, pci2676 commented on src/main/java/gift/controller/Interceptor.java
> +public class Interceptor {
Interceptor라는 이름은 너무 추상적입니다. 조금 더 구체적인 이름을 작성해주세요.

2024-07-08 22:20 UTC, pci2676 commented on src/main/java/gift/domain/MemberDomain.java
> +    }
계층 구분이 전혀되지 않고 있는것 같습니다.

controller와 같은 요청/응답을 다루는 클래스인지

비즈니스 로직의 흐름을 담당하는 service인지

명확하게 클래스의 역할과 책임을 나누어주세요.

지금 상태로는 step1을 진행하기에 무리가 있어보입니다.

2024-07-08 22:20 UTC, pci2676 commented on src/main/java/gift/domain/MemberDomain.java
> +    }
domain 패키지에 있는 클래스가 전부 해당됩니다.

2024-07-08 22:20 UTC, pci2676 commented on src/main/java/gift/model/JwtUtil.java
> +//    private String secretKey;
https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/pull/427/files#r1668280520

value를 사용해서 key를 주입할때 jwtUtil이라는 클래스는 spring bean으로 선언하셨을까요?

2024-07-08 22:20 UTC, pci2676 commented on src/main/java/gift/model/JwtUtil.java
> +public class JwtUtil {
JwtUtil이라는 이름또한 너무 추상적입니다.

util이라는 네이밍은 가급적 사용하지 말고 다른 이름으로 작명해주시면 좋을것 같습니다. 😄

2024-07-08 22:20 UTC, pci2676 commented on src/main/java/gift/model/Product.java
> +    }
product 클래스의 역할과 책임에 대해 적어주시겠어요?

해당 객체가 setter가 필요한지 아닌지 확인할 수 있는 내용이 될 것 같습니다.

2024-07-08 22:20 UTC, pci2676 commented on src/main/java/gift/controller/ProductController.java
> +    }
https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/pull/427/files#r1668281167

DeleteMapping을 사용하면서 redirect를 활용하지 않고 해당 api 호출후 front 영역에서 필요한 api를 별도로 호출해도 될 것 같습니다.

2024-07-08 22:20 UTC, pci2676 commented on src/main/java/gift/domain/MemberDomain.java
> +        if (memberDao.selectMember(member.getEmail()) == null){
nullable한 객체를 다룰때는 optional을 사용해주세요.

2024-07-09 06:10 UTC, HyeJiJUN11 commented on src/main/java/gift/controller/CatchError.java
> +}
product객체 내부에서 name에 대해 equals() and hashCode()를 오버라이드 해주었는데, name객체를 아예 새로 만들어야 하는 걸까요?

2024-07-09 06:11 UTC, HyeJiJUN11 commented on src/main/java/gift/controller/Interceptor.java
> +public class Interceptor {
TokenInterceptor로 수정했습니다.!

2024-07-09 06:12 UTC, HyeJiJUN11 commented on src/main/java/gift/domain/MemberDomain.java
> +    }
controller, dao, model, service로 다시 나누었습니다. PR할테니 확인해주세요!

2024-07-09 06:12 UTC, HyeJiJUN11 commented on src/main/java/gift/model/JwtUtil.java
> +//    private String secretKey;
@Component 로 선언 해주었는데도 해결되지 않습니다....

2024-07-09 06:13 UTC, HyeJiJUN11 commented on src/main/java/gift/model/JwtUtil.java
> +public class JwtUtil {
CreateJwtToken으로 수정했습니다!

2024-07-09 06:14 UTC, HyeJiJUN11 commented on src/main/java/gift/model/Product.java
> +    }
product는 product를 생성하고, 필요한 필드를 받아오는 역할로 생각하고 있습니다. 다만 log을 찍어본 결과 @ModelAttribute Product product 에서 html에서 받아오지 못하는 것 같습니다.

2024-07-09 06:15 UTC, HyeJiJUN11 commented on src/main/java/gift/domain/MemberDomain.java
> +        if (memberDao.selectMember(member.getEmail()) == null){
수정했습니다!

2024-07-09 08:50 UTC, pci2676 commented on src/main/java/gift/model/JwtUtil.java
> +//    private String secretKey;
지금 올려주신 코드에서 주석처리하신 `@Value`를 주석해제 하시면 정상적으로 주입되는것으로 보이네요!

2024-07-09 08:52 UTC, pci2676 commented on src/main/java/gift/model/JwtUtil.java
> +public class JwtUtil {
다른 클래스들의 이름과 조금 달라보이는데 클래스 이름을 짓는 규칙을 가지고 계실까요?

2024-07-09 09:00 UTC, pci2676 approved these changes
다음 단계를 진행하면서 이번단계에 리뷰한 내용을 개선해주세요.

2024-07-09 09:00 UTC, pci2676 commented on src/main/java/gift/model/Product.java
> +@Component
spring bean으로 사용하기에 적절치 않아보입니다. 

component로 왜 선언하신 이유가 있으신가요?

2024-07-09 09:00 UTC, pci2676 commented on src/main/java/gift/model/Member.java
> +public class Member {
모든 모델 클래스가 request/response로도 사용되고

dao에서 database에 저장되기도 하는것 같습니다.

이렇게 두가지 용도로 사용하시면 안됩니다.

역할에 맞게 서로 다른 클래스와 객체를 생성해주셔야 합니다.

2024-07-09 09:00 UTC, pci2676 commented on src/main/java/gift/service/MemberService.java
> +    public MemberService(MemberDao memberDao) {
autowired가 필요한가요?

2024-07-09 09:00 UTC, pci2676 commented on src/main/java/gift/service/MemberService.java
> +    CreatJwtToken jwtUtil = new CreatJwtToken();
왜 이 객체들은 bean으로 사용하지 않으셨나요?

2024-07-09 09:00 UTC, pci2676 commented on src/main/java/gift/service/MemberService.java
> +    TokenInterceptor interceptor = new TokenInterceptor();
token interceptor는 web요청을 받는 layer에서 사용하시는게 좋을것 같습니다.

service에서 직접 사용하지 말고 configuration을 통해 bean으로 등록하여 사용할 수 있도록 해주세요.

2024-07-09 09:00 UTC, pci2676 commented on src/main/java/gift/service/MemberService.java
> +    }
mvc패턴에서는 service에서 web레이어에 대해 알고 있으면 안됩니다. 계층간 침범을 하지 않도록 해주세요.

2024-07-09 09:00 UTC, pci2676 commented on src/main/java/gift/service/MemberService.java
> +        if(Objects.equals(member.getPassword(), loginMember.getPassword())){
이 부분을 비롯해 전체적으로 객체지향적으로 작성해주시면 좋을것 같은데 아래 동영상을 참고해주세요.

https://www.youtube.com/watch?v=3etKkkna-f0&ab_channel=%EC%9A%B0%EC%95%84%ED%95%9C%ED%85%8C%ED%81%AC

2024-07-09 09:00 UTC, pci2676 commented on src/main/java/gift/service/ProductService.java
> +                newProduct.getImageUrl() != null && !newProduct.getImageUrl().isEmpty() ? newProduct.getImageUrl() : oldProduct.getImageUrl()
삼항연산자는 사용하지 말아주세요.

무분별한 getter도 사용하지 말아주세요.

2024-07-09 09:00 UTC, pci2676 commented on src/main/java/gift/service/ProductService.java
> +    private final CatchError catchError = new CatchError();
CatchError객체는 멤버변수로 관리할 필요가 있나요?

2024-07-09 09:01 UTC, pci2676 commented
지난 단계서부터 계속해서 동일한 리뷰를 하게 되는것 같습니다.

개선해주시고 잘 이해가 되지 않고 모르는 부분이 있으면 정리하여 멘토링 신청을해주세요!

2024-07-09 09:01 UTC, merged